### ISSUE TITLE
Edit Person details - edit name

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#1002]
Currently, if a name is misspelled you have to either create a new Person with the corrected name or manually edit the database.

Adding an "edit" button in the "faces" view would allow this simple change and could potentially be useful for other scenarios (like thumbnail editing, manually adding cluster relationships etc)

**Comment by derneuere** [comment]
There is an edit button in /people, but adding it to the faces view makes sense too :)

**Comment by derneuere** [comment]
Added this to the face dashboard :)
