### ISSUE TITLE
Issue with import folder

### ISSUE THREAD

**Issue by GuillaumeFX** [LibrePhotos/librephotos#1007]
Hi, i have plugged and mounted my save external disk to my ubuntu server but when i write the path and click save i have this error

<img width="577" alt="image" src="https://github.com/LibrePhotos/librephotos/assets/77529874/feb8fe17-a32f-4fed-82cc-700d37f9fca7">

**Comment by GuillaumeFX** [comment]
Oh okay i understand but why there is only data folder there is pictures folder too

**Comment by derneuere** [comment]
I think you have to learn a bit more docker, as this has nothing to do with LibrePhotos 😅 

In docker land, the container does not have access to the file system. Instead, you map folders or volumes into the containers. In LibrePhotos this means that the scanDirectory you defined in you .env is the same as the data folder in the container.
