### ISSUE TITLE
Same face detected twice in the same photo.

### ISSUE THREAD

**Issue by scepterus** [LibrePhotos/librephotos#1008]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ ] ❌ I have looked for similar issues (including closed ones)
* [X] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Faces are detected twice in the same photo, moved a few pixels.

## 🔁 How can we reproduce it:
Scan photos with the following config:
<img width="1240" alt="image" src="https://github.com/LibrePhotos/librephotos/assets/56637330/63cce842-0973-4175-8711-f66decfd7934">
some photos will have the same face detected twice.

## Please provide additional information:
- 💻 Operating system: Debian
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Direct Mount

<img width="218" alt="image" src="https://github.com/LibrePhotos/librephotos/assets/56637330/60fb027c-fa73-4da6-87e7-809bb38ea91c">

**Comment by mxm199** [comment]
You may have run face recognition in two ways at different times, both HOG and СNN. They create different previews just differing by a few pixels.

**Comment by scepterus** [comment]
Oh, in that case, we need some sort of failsafe for such a case to not have 2 methods colliding.

**Comment by derneuere** [comment]
Changed up the margin calculation to be relative and to be +-5% of the size of the face. This should prevent wrongly duplicates.

**Comment by scepterus** [comment]
OK cool, will this also check retro results, or will this only be from this point forward?

**Comment by derneuere** [comment]
There is a deduplication action in the django admin photo view, where you can resolve the issue :)
