### ISSUE TITLE
Exception/Crash: Face Extraction fails on Lightroom based face regions

### ISSUE THREAD

**Issue by Scott8586** [LibrePhotos/librephotos#1011]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x ] ❌ I have looked for similar issues (including closed ones)
* [x ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue: exiftools info

## 📝 Description of issue:

Extraction of face information fails due to software exception:

```
backend_1   | Traceback (most recent call last):
backend_1   |   File "/code/api/directory_watcher.py", line 203, in handle_new_image
backend_1   |     photo._extract_faces()
backend_1   |   File "/code/api/models/photo.py", line 636, in _extract_faces
backend_1   |     if region["Area"]["Unit"] == "normalized":
backend_1   |        ~~~~~~~~~~~~~~^^^^^^^^
backend_1   | KeyError: 'Unit'
```

Regions generated by Adobe Lightroom do not contain the key 'Unit', but they do have 'Region Applied To Dimensions Unit'.
Example photo, exiftools output:

```
Region Applied To Dimensions W  : 2832
Region Applied To Dimensions H  : 3540
Region Applied To Dimensions Unit: pixel
Region Rotation                 : -1.67268, -1.62436, -1.67089
Region Name                     : Person1, Person2, Person3
Region Type                     : Face, Face, Face
Region Area H                   : 0.12878, 0.11261, 0.14894
Region Area W                   : 0.16107, 0.14084, 0.18628
Region Area X                   : 0.36254, 0.54666, 0.63764
Region Area Y                   : 0.38770, 0.57477, 0.17045
```

## 🔁 How can we reproduce it:

Try to scan photos containing Adobe Lightroom written face regions

## Please provide additional information:
- 💻 Operating system: Synology DSM7
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: (docker, dev, not sure of the number, cannot find it)
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local file system
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): none

**Comment by derneuere** [comment]
I think I handled that case now correctly. I can check it myself, if you provide an example xmp file, but you can also update the dev image and report back to me :)

**Comment by Scott8586** [comment]
Thank you for taking a look so quickly.  But no, now I'm getting the following:

```
backend_1   | ERROR:ownphotos:job 0998e55a-c37f-494f-9f46-ec42a7f945ac: could not load image XXX. reason: cannot access local variable 'top' where it is not associated with a value
backend_1   | Traceback (most recent call last):
backend_1   |   File "/code/api/directory_watcher.py", line 203, in handle_new_image
backend_1   |     photo._extract_faces()
backend_1   |   File "/code/api/models/photo.py", line 699, in _extract_faces
backend_1   |     face_image = image[top:bottom, left:right]
backend_1   |                  ^^^^^
```

I've attached an xmp sidecar for you to work with

[DSF_4259_xmp.txt](https://github.com/LibrePhotos/librephotos/files/12566053/DSF_4259_xmp.txt)

**Comment by derneuere** [comment]
Pushed another fix, should work now :)
