### ISSUE TITLE
502 when attempting to complete upload

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#1015]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

Making some changes to the upload functonality in UhuruPhotos, I keep bumping across this issue.

Performing the /complete operation after uploading all chunks results in a 502 which internally looks to be a worker timeout which causes the service to restart.

I believe i made a mistake in the chunking of the new process, perhaps causing wrong chunks to be uploaded (missing a byte perhaps) so the complete operation can't process the item.

If that's what's happening. I feel the error in that scenario should be something meaningful and not a 5xx

## Please provide additional information:
- 💻 Operating system:  docker running on Ubuntu
- ⚙ Architecture (x86 or ARM):  x86
- 🔢 Librephotos version: latest dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.):  docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local file system
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by savvasdalkitsis** [comment]
[log.zip](https://github.com/LibrePhotos/librephotos/files/12609149/log.zip)

**Comment by derneuere** [comment]
502 errors and restarting of workers usually indicates either a time out issue or it got killed by an OOM killer. 
I don't think it's an issue with the uploading component itself, but something is overloading your system from time to time. 

It sounds like it could be a slow endpoint, which blocks all the API workers. Could you look into http://localhost:3000/api/silk/ if there is any endpoint which takes a long time to execute?

**Comment by derneuere** [comment]
I link this issue here, for the other 502 error you encountered: https://github.com/LibrePhotos/librephotos-docker/issues/104
