### ISSUE TITLE
dependency failed to start: container db is unhealthy 

### ISSUE THREAD

**Issue by kornelia82** [LibrePhotos/librephotos#1017]
I installed librephotos on two different systems (both windows) but this same error appears. i dont even know where to look for logs...
![grafik](https://github.com/LibrePhotos/librephotos/assets/145105744/0a72d7ff-6c41-4a04-b6fd-514cc9254ed2)

**Comment by compbl** [comment]
Getting the same error, Docker installed on Ubuntu

**Comment by sickelap** [comment]
to see logs of failed db container run `docker logs db`

**Comment by compbl** [comment]
![image](https://github.com/LibrePhotos/librephotos/assets/37711686/96f08433-2d93-4400-a5bb-468c6cb060c4)

![image](https://github.com/LibrePhotos/librephotos/assets/37711686/adad335f-673d-4a18-83e3-6c92295d79d8)

**Comment by sickelap** [comment]
Looks like there is no disk space available for the DB. Check your setup and available resources.
