### ISSUE TITLE
Remove requests for small thumbnails in the frontend

### ISSUE THREAD

**Issue by robertcontois** [LibrePhotos/librephotos#102]
The frontend has GET requests for for "/media/thumbnails_small/" but those images aren't generated in the backend so it gets 404 responses. Even if the thumbnails did exist in the requested path they aren't currently being displayed on the front end. 

To reproduce the issue open the developer console on your web browser and navigate to recent photos, click on a photo to view it. You'll be able to successfully view the photo but it will generate 404 errors for thumbnails associated with each previous and next image.

**Comment by derneuere** [comment]
Do you know in which view the small thumbnails are used?

**Comment by robertcontois** [comment]
They are defined in _src/components/lightBox.js_. I've modified the code on my end, by removing the code for the thumbnails since they aren't required by lightbox and that solved the problem. It could also be accomplished by setting all the thumbnails to a transparent png, keeps more of the code if they are going to be set later but does a lot of unnecessary gets. 

Let me know if you want either of those done and I can make the change.

**Comment by robertcontois** [comment]
I created a PR for this but I couldn't figure out how to link it to this issue (or I messed up linking it).
