### ISSUE TITLE
Variables in .env

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#1020]
Good day
Tell me what is the maximum value supported by the HEAVYWEIGHT_PROCESS variable (in the .env file)? In the web interface, in the administrator settings, this value can be set from 1 to 3. Or are these other settings?

The gunniWorkers variable (in the .env file). If I have 4 cores and a lot of RAM, can I specify the value 16 in this variable (2-4 х $(NUM_CORES)), will this give an increase in processing speed?

How much does it make sense to set the maximum values of these variables?

**Comment by derneuere** [comment]
I think there is no upper bound. The limitation is just in the frontend to prevent users to make the system to resource heavy.

gunicorn handles the the regular api calls. Set it as high as you need for a responsive experience.

increasing the number of heavyweight workers will increase the speed of processing the images.

#904
