### ISSUE TITLE
Missing photo

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#1023]
Tell me how to remove the "Missing photo". I deleted the photo myself, which is not needed, and when re-scanning in the Library indicates the missing photo, and the total number of photos is more than one (which I deleted). How to get the real number of photos and remove the mention of the missing photo?

**Comment by derneuere** [comment]
Missing photos mean, that the file attached to the photo got removed in a subsequent scan. We do a hash comparison, so as long as you moved it within the visible folders it's fine.

If you want to remove the metadata and the thumbnails of the missing photos. Click on the "Missing Photos Found" text :)
