### ISSUE TITLE
Double /api/ prefix on rqavailable request

### ISSUE THREAD

**Issue by robertcontois** [LibrePhotos/librephotos#103]
After the frontend access token expires a HTTP 401 response is received and the front end makes a call to _/api/auth/token/refresh/_ to refresh the token. 

Once the token is refreshed the original request is sent again but it appends an extra "/api/" to the beginning of the request and it fails as "/api/api/rqavailable". Subsequent calls succeed with the correct url, just not the first one after a token refresh.

**Comment by robertcontois** [comment]
I've added in a check if the request url already has the base of "/api/" in it and I've created a PR for this issues.

**Comment by SchoofsEbert** [comment]
Just a small heads-up. You've created a branch on your fork. Now you should still create a PR for it. For this, you need to click on Pull Requests in this repo, click new pull request and select the branches you want to merge (the left one should be librephotos/dev and the right side your modified branch).

You should provide a meaning full description, e.g. a small repeat of what you've solved. Linking an issue is as simple as just referencing the issue in your description: e.g. #102 Links to you're other issue.

Good luck!

**Comment by SchoofsEbert** [comment]
Woops, they are PR for the frontend of course 😅  
I didn't say anything 😅

**Comment by robertcontois** [comment]
Thanks, yeah I wasn't sure if I did something wrong in linking because the PR was in the frontend repository.

**Comment by derneuere** [comment]
Fixed, but no yet done see: #122
