### ISSUE TITLE
Document Docker setup without Docker Compose

### ISSUE THREAD

**Issue by sdebruyn** [LibrePhotos/librephotos#104]
If you want to run and manage this on Synology DSM via the web interface, then you can't easily use Docker Compose. It would be helpful to document the ports and network settings needed for each of the containers.

Not a duplicate of #57 since I still prefer Docker, just without the Compose part.

**Comment by travisfont** [comment]
This is huge! I refuse to use Docker, and many other developers do too.

**Comment by guystreeter** [comment]
I have it running as a rootless `podman` pod, in case you find that any more palatable.

**Comment by ohthehugemanatee** [comment]
In case it helps someone understand the containers and their requirements, here is my working kubernetes configuration for librephotos. Should work for you too with some modification.

https://github.com/ohthehugemanatee/homenet-documentation/tree/b30c4ac/cluster/services/librephotos

- Each component can scale independently of the others. 
- Photos are mounted from NFS (PV/C are included)
- includes an external ingress with letsencrypt TLS configuration
- `.vert` is my internal TLD, please ignore. :) 
- you need to create secrets before deploying, something like
```
kubectl create secret generic librephotos -n librephotos \n
--from-literal=admin-email='info@example.com' \n 
--from-literal=admin-username='some-username' \n
--from-literal=admin-password='some-password' \n
--from-literal=db-username='db-username' \n
--from-literal=db-password='another-password' \n
--from-literal=secret-key='secret-key' \n
--from-literal=mapbox='mapbox-api-key'
```
See the `.env` file provided in this repo for description of requirements on those vars.

**Comment by rkoshak** [comment]
For another example I've an Ansible role that spins up the three Librephotos containers (PostgreSQL and Redis are already running for Nextcloud and other services). It's just that though, no reverse proxy or LetsEncrypt or anything like that. It does create the database and database user on PostgreSQL though if needed. 

https://gist.github.com/rkoshak/f0b12590d24421e36ee521f5994b8ce0

Even if you don't know or use Ansible it should be pretty easy to map the arguments to `docker_container` to the arguments you'd pass to a `docker run` command. Stuff in `{{ }}` are variables you'd need to create or replace with your values.

**Comment by derneuere** [comment]
There is now some documentation on how to use the singleton image.
