### ISSUE TITLE
Details section on public page

### ISSUE THREAD

**Issue by tobiasff3200** [LibrePhotos/librephotos#1046]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I marked a picture as public and visited the public pictures page in a browser where I was not logged in. The details section shows the form to edit the timestamp of a picture. Luckily, it doesn't work, but I think it should be disabled if not hidden completely.

Moreover, the full internal file path is shown, which is also not a good idea on a public page.

## 🔁 How can we reproduce it:
Visit the public images page while not being logged in. Open a picture and click on the 'i' symbol.

## Please provide additional information:
- 🔢 Librephotos version: latest (15.10.2023)
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker (reallibrephotos/librephotos-frontend:latest)

**Comment by derneuere** [comment]
Removed all edit icons, buttons which change the state and the file path, if it is a public image :)
