### ISSUE TITLE
Adding a second scan directory

### ISSUE THREAD

**Issue by Absinthze** [LibrePhotos/librephotos#1047]
How can I add a second scan directory to my Windows through Docker setup?  
For example I want to add this path to my scan search.
Q:\PROJECTS COMPLETE
Thank you,

# Location of your photos.
scanDirectory=P:\Rendering Materials\Renderings Reference

# Internal data of LibrePhotos
data=C:\librephotos-docker\librephotos\data

**Comment by derneuere** [comment]
To do that you have to change up the docker-compose.yml file. Everything in /data inside of the docker container will be shown in the selection dialog. The idea is to mount P:\Rendering Materials\Renderings Reference to /data/folder1 and Q:\PROJECTS COMPLETE to /data/folder2. Then both should show up :)
