### ISSUE TITLE
API Calls Unauthorized (Images Not Loading)

### ISSUE THREAD

**Issue by rephormat** [LibrePhotos/librephotos#105]
## Expected Behavior

View full-size images with frontend ui.

## Actual Behavior

Thumbnails are created and present, but clicking on the thumbnail does not display a full-size image as expected.  Instead it acts as though it's perpetually loading with loading circles on some of the top-right icons.

## Additional Details

I've set this up on two different installs (CentOS 7 & Ubuntu 18.04).  I've restarted with clean containers on each with no success.  The only indication that something is wrong is in the file gunicorn_django.log below:

Unauthorized: /api/persons/
Unauthorized: /api/albums/place/list/
Unauthorized: /api/albums/date/photohash/list/
Unauthorized: /api/albums/thing/list/
Unauthorized: /api/albums/user/list/
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/stats/
Unauthorized: /api/rqavailable/
Unauthorized: /api/rqavailable/
Unauthorized: /api/rqavailable/
Unauthorized: /api/rqavailable/

**Comment by derneuere** [comment]
Related to #26

Did you scan finish? What does your web console say?

**Comment by rephormat** [comment]
@derneuere Yes.  Scan completed.

**Comment by Rihcus** [comment]
I made a duplicate issue #107 just found this one 

![image](https://user-images.githubusercontent.com/30292597/103737844-040a5300-4fc1-11eb-8995-ac28d1105cfb.png)

**Comment by derneuere** [comment]
Fixed the issue. Please do a docker-compose down, docker-compose pull and docker-compose up -d

**Comment by niko** [comment]
Amazing! Just had the same issue on a fresh install … 12 hours later it's fixed! Thanks!

**Comment by rephormat** [comment]
@derneuere Thank you!!  Issue is resolved now.
