### ISSUE TITLE
Public photos with no timestamp breaks settings (null exif_timestamp in public_photo_samples)

### ISSUE THREAD

**Issue by ledlamp** [LibrePhotos/librephotos#1054]
(from new install with no public photos) make a photo with no timestamp public and you will find error like this in console:

```
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      "public_photo_samples",
      0,
      "exif_timestamp"
    ],
    "message": "Expected string, received null"
  }
]
```

And settings page will not load values. Because settings are in that /api/user/1.

![2023-10-23_13-50-10-384 DevTools_-_photos owo69 mesettings](https://github.com/LibrePhotos/librephotos/assets/103386533/e5ca5414-8b4f-48b2-9ed1-72f91193a725)

**Comment by derneuere** [comment]
Pushed a fix. Will be available on dev or in the next release in a week :)
