### ISSUE TITLE
cuda initialization error in latest GPU backend

### ISSUE THREAD

**Issue by guystreeter** [LibrePhotos/librephotos#1056]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I am trying to use the latest gpu variant of the backend container. For every image it tries to process it gets this error:
```
ERROR:ownphotos:job 44ba2b87-c55f-4ba7-9c28-05b1368f596c: could not load image /data/DSC00414.JPG. reason: Error while calling cudaGetDevice(&the_device_id) in file /tmp/builds/dlib/dlib/cuda/gpu_data.cpp:204. code: 3, reason: initialization error
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 203, in handle_new_image
    photo._extract_faces()
  File "/code/api/models/photo.py", line 732, in _extract_faces
    import face_recognition
  File "/usr/local/lib/python3.10/dist-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/local/lib/python3.10/dist-packages/face_recognition/api.py", line 26, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/builds/dlib/dlib/cuda/gpu_data.cpp:204. code: 3, reason: initialization error
```

I can exec into the backend container and verify GPU access:
```
# nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4070 Ti (UUID: GPU-a04e1dbc-1bb8-bf05-04df-4e47a3430096)
```

In the container, simply importing face_recognition is successful:
```
# python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
>>> 
```

## 🔁 How can we reproduce it:
I spun up a new librephotos instance using the librephotos-gpu container and started a scan.

## Please provide additional information:
- 💻 Operating system: Fedora 38, with Cuda 12.2
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): podman/docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): N/A

**Comment by guystreeter** [comment]
I have searched the internet for information about this CUDA initialization error, and the only suggestions I found say it is caused by trying to initialize CUDA multiple times. Some of them suggest that CUDA multiprocessing must be done with `spawn` instead of `fork`.

**Comment by derneuere** [comment]
This issue is that PyTorch ships a different version than face_recognition at the moment. I think that this is the error. I tried to change the version already, but the build takes too long and gets canceled constantly. Will try again and if it than still not works, I will have to find a workaround.

**Comment by guystreeter** [comment]
If you can show me the change you made, I can try to build and test it locally.

**Comment by derneuere** [comment]
You have to rebuild first this base image: https://github.com/LibrePhotos/librephotos-docker/blob/main/backend-gpu/base/Dockerfile

Then you have to rebuild the general image: https://github.com/LibrePhotos/librephotos-docker/blob/main/backend-gpu/Dockerfile

**Comment by guystreeter** [comment]
Those just need to be rebuilt without any changes? I tried that but got the same error.

**Comment by derneuere** [comment]
It's a slightly different error on my system. I think it has something to do with pytorch and dlib being active in the same environment. I will extract it into it's own service and will see if that fixes things.

**Comment by derneuere** [comment]
Alright I pushed a fix. Should be available in half an hour. Let me know if that fixes the issue for you :)

**Comment by guystreeter** [comment]
You might be a step close, I can't tell:
```
ERROR:ownphotos:Error in calculating clip embeddings: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Comment by derneuere** [comment]
Hmm, the only reason I can think of, why it works on my system is, that I only have one heavyweight worker. I will link this issue here and will try to resolve it: https://github.com/pytorch/pytorch/issues/40403

**Comment by derneuere** [comment]
I think I found the issue and pushed a fix for it :) Seems to work on my system with multiple background workers.

**Comment by guystreeter** [comment]
If your intention is to limit threads to 1 when using CUDA, you'll need an `else` to explicitly set it. The default on my system is 8.

**Comment by derneuere** [comment]
I extracted the clip embedding logic into its own service. It should work better now.
