### ISSUE TITLE
Possible issue while Scanning with Network Mount?

### ISSUE THREAD

**Issue by vr6syncro** [LibrePhotos/librephotos#1058]
Hey i added a cifs mount as scan folder and after that it stopped working...
The scan was stuck i think it was yellow for over 30min and do nothing. CPU and RAM also did nothing much.

Removed Jobs and restarted the Docker compose but nothing helped.

What i have done when it started working was: removed a thumbs.db that windows create in one folder and after klick scan it scans.
maybe thats a issue? because i did nothing else this time.

i also get often Unauthorized: messages from api.

**Comment by ggennrich** [comment]
I have the exact same issue. I also tried to upload and logs show a critical failure in the worker along with unauthorized messages via API. I followed the instructions from Docker about how to set up a network mount and it did create them all successfully. The uid and gid are the same as the photos folder

**Comment by vr6syncro** [comment]
hey after some weeks of testing i were not able to reproduce the failure again. i dont know what happend. i only had deleated the thumbs.db (hidden file) ... so far it is working for me
