### ISSUE TITLE
User name can not contain capitol letters. 

### ISSUE THREAD

**Issue by DigitalWarrior** [LibrePhotos/librephotos#106]
If you set up though the .env a user name that has a capitol letter you can not log in and will receive a user not found. This should not be the case User names should be allowed to have uppercase letters.

**Comment by robertcontois** [comment]
This is a deeper issue than just fixing one field. Every time _username_ is used in the frontend code it's converted to a lowercase string. We could change one field to fix it for the login form but that leaves a lot of other places to change and test. 

I would say that we should update the backend instead to have all users created be lowercase, it's standard practice to have usernames be case insensitive.
