### ISSUE TITLE
"unkown - others" not automaticaly refreshed

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#1067]
with today release (23/11/05) (maybe was existing before...) I get the following problem when allocating a face to a person:
I select a face in "unknown - others" cluster and add it to an existing person. Then the "unknown - others" cluster becomes blank and is not updated. Previous clusters are displayed but from "unknown- others" they are blank.
Need a manual refresh to see them correctly.
[serverstats (1).json](https://github.com/LibrePhotos/librephotos/files/13260678/serverstats.1.json)

**Comment by loulou91** [comment]
Well, not sure issue is really closed... Could you retest on your side? (I made a pull this morning).
Should be reopen ;-)

**Comment by derneuere** [comment]
I can't reproduce it on the demo server. Could you maybe more specific on how I can reproduce it?
