### ISSUE TITLE
Unable to open scanned photos

### ISSUE THREAD

**Issue by Rihcus** [LibrePhotos/librephotos#107]
thumbnails show up and the scan runs without issue, however after scan I am unable to click and view photo. Zoom and make photo public buttons infinitly load.

Platform
- Windows 10 Docker Desktop

Attempted solutions:
- running a new scan
- restarting docker containers (when no scan is running and workers are available)
![unknown](https://user-images.githubusercontent.com/30292597/103736625-9b21db80-4fbe-11eb-98ca-7dcba463d2c1.png)

**Comment by derneuere** [comment]
Fixed the issue. Please do a docker-compose down, docker-compose pull and docker-compose up -d
