### ISSUE TITLE
unable to select photos directory in admin pannel on large photo library and high memory usage

### ISSUE THREAD

**Issue by Rihcus** [LibrePhotos/librephotos#108]
When setting the scan directory to a 400gb photo library it failed to show the library in admin:
![image](https://user-images.githubusercontent.com/30292597/103736897-2307e580-4fbf-11eb-9da7-502a7c6a5e23.png)

Platforms:
-- MacOS
-- Windows 10

I also observed high ram usage on both platforms

[gunicorn_django.log](https://github.com/LibrePhotos/librephotos/files/5774198/gunicorn_django.log)

log from windows 10

**Comment by derneuere** [comment]
This is also related to the api issues.

**Comment by derneuere** [comment]
https://stackoverflow.com/questions/24828541/why-is-os-listdir-causing-excessive-memory-usage

**Comment by derneuere** [comment]
https://github.com/LibrePhotos/librephotos/blob/850e42d36483a410510b585717ab62a39002393f/api/api_util.py#L42-L48

**Comment by derneuere** [comment]
Related to #97

**Comment by derneuere** [comment]
Created a new image. Would be great if you could test if your issue still persists or if it is solved 👍

**Comment by derneuere** [comment]
Maybe it has something to do with the recursion. We could optionally change the way it is called to only get one folder structure at a time. If you clicked on a folder you could then load the next folder structure.

**Comment by rafntor** [comment]
I dont do python , but ; the `path_to_dict` function appears to in one sweep build a dictionary of all files in all subfolders and return the dict for further prosessing. That does not scale well with large libraries , tens of thousands of files .. each with potentially long path-names (?)
Would it not make more sense to do the scan while crawling the filesystem, as opposed to first crawl the filesystem and then process that (huge) list?
Or am I misreading this (as I said python is not my thing :-) )

**Comment by rafntor** [comment]
When looking a little closer I realize the function is only used to populate the directory-tree presented in the gui so I definitely think it should be changed as you indicate to only recurse-on-demand when user navigates the folders.

Also it seems that [`os.scandir()`](https://www.simplifiedpython.net/python-get-files-in-directory/#osscandir) is much better to build on than [`os.listdir()`](https://www.simplifiedpython.net/python-get-files-in-directory/#oslistdir) to support large and deep folder structures.
And the `scan_photos()` [loop](https://github.com/LibrePhotos/librephotos/blob/dev/api/directory_watcher.py#L142) also must be refactored to have sane memory usage. Perhaps a generic folder-walking function with a function callback argument for each found file would be a clean approach?

**Comment by derneuere** [comment]
@Rihcus There is now a new image which should resolve your issue. Could you test it and report if it works?
