### ISSUE TITLE
feeback on new caption model: strange result

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#1086]
The result from log and caption result are different... "a stream in the middle of a field" on one side "a white and blue boat traveling down a mountain" on the other side...
![image](https://github.com/LibrePhotos/librephotos/assets/51127123/b0704295-ffd6-4846-a636-1e824cf939a7)

`2023-12-02 12:31:13,666 : api_util.py : get_search_term_examples : 186 : INFO : 100 possible ids
2023-12-02 12:31:13,667 : api_util.py : get_search_term_examples : 201 : INFO : Getting search terms for user 1
2023-12-02 12:31:14,306 : api_util.py : get_search_term_examples : 202 : INFO : Found 93 photos
2023-12-02 12:32:32,031 : photo.py : _generate_captions_im2txt : 189 : INFO : generated im2txt captions for image /protected_media/thumbnails_big/16dd51def768c326e131d5b70bbe51a51.webp with SiteConfig blip_base_capfilt_large with Blip: True and Onnx: False caption: a stream in the middle of a field`

![image](https://github.com/LibrePhotos/librephotos/assets/51127123/6e67bfb7-5f99-4f8f-b7e4-1396f1e0eeac)

**Comment by derneuere** [comment]
The suggestion will now be displayed above the caption. This should make it clearer, what the description is and what the suggestion is :)

**Comment by loulou91** [comment]
Well... not so sure it's clearer for me... ;-)
![image](https://github.com/LibrePhotos/librephotos/assets/51127123/ac24364b-c7d5-41af-b0bc-7b3fb4279bbf) ![image](https://github.com/LibrePhotos/librephotos/assets/51127123/77b4182d-b017-4df6-b772-b11f252edf5c)
where is "generate" button for image without caption? what means the icon?

sorry to be boring with all that stuff  😅 in addition doc will have to be updated accordingly ;-)

**Comment by derneuere** [comment]
The wand button is now the generating button. You can click on the suggestion, which will add it to the caption field. You can then save it by clicking on submit.

This makes it clear, what the suggestion is, what you description is and when it gets saved!
