### ISSUE TITLE
feeback on new caption model: screen refresh needed

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#1087]
When caption "generate" is pressed, "generate" becomes grey for a while, then goes back to blue. Nevertheless caption field is still blank.
Text may appear after a browser refresh request.

**Comment by loulou91** [comment]
It looks now working.
However I noted strange behaviour.
When I enter a manual caption, if I press right arrow (next picture) the manually entered caption is still visible.
it is the same by pressing 2 or 3 time then it disappears and pressing again left arrow looks correct.

**Comment by derneuere** [comment]
This is was fixed in a previous release :)
