### ISSUE TITLE
Can't Label faces

### ISSUE THREAD

**Issue by roha62** [LibrePhotos/librephotos#1092]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x ] ❌ I have looked for similar issues (including closed ones)
* [x ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
![image](https://github.com/LibrePhotos/librephotos/assets/114854786/02f59eaa-f747-4720-adcc-0612574b69d0)
I can't label faces by clicking on the list of existing, named faces. The list appears non-responsive. I could add a name by entering in the "New person" field, but this is not what I want.

## 🔁 How can we reproduce it:
1.) Follow the standard install procedure:
https://docs.librephotos.com/docs/installation/standard-install/
2.) Create user, login
3.) Upload some photos
4.) After scanning, label some faces (give them a name)
5.) Select one of the "People" list, click on the "pencil" icon
6.) Try to Label the face by clicking on the list

## Please provide additional information:
- 💻 Operating system: ubuntu 23.10
- ⚙ Architecture x86 
- 🔢 Librephotos version: latest pull as of today 
- 📸 Librephotos installation method Docker 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted Local file system (ext4) 
- ☁ If you are virtualizing librephotos No

**Comment by derneuere** [comment]
Pushed a fix :) This will land in the next latest release in the beginning of january or now on the dev tag.

You have to click on the title to assign it to a person. I switched it to a button, so that you can click on whitespace and still assign it to a person.
