### ISSUE TITLE
Change dependency to DeepFace

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#11]
[DeepFace](https://github.com/serengil/deepface) has an ensemble model which should lead to better results than our current model.

**Comment by sysoppl** [comment]
Confirm, a lot of faces that are clearly visible was skipped

**Comment by derneuere** [comment]
I found a bug in the current implementation. Should work way better now.

**Comment by sysoppl** [comment]
There is a lot of new faces, also more false positives (a fish and penguin got in too ;), but overall it works now way better. Before this, there was ~1900 faces, we'll see in some time

- - - - 
After this fix I have ~3800 faces

**Comment by derneuere** [comment]
I do not think, that we have to switch any longer :)
