### ISSUE TITLE
Geotag in the video file

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#1105]
Tell me, where does librephotos get the location in the video files? From photos adjacent by date and time?

**Comment by derneuere** [comment]
Usually this is EXIF data within the file, which gives us the coordinate. For reverse geocoding aka coordinates to place names we use a reverse geocoding provider, which can be selected in the admin panel.

**Comment by mxm199** [comment]
But video files (mp4) don’t contain a geotag?

**Comment by derneuere** [comment]
They can contain geotags, like any other media file :)
