### ISSUE TITLE
HEIC selfie images face recondition positions are off

### ISSUE THREAD

**Issue by sefininio** [LibrePhotos/librephotos#1107]
After #1103 was fixed, we noticed that selfie HEIC image files face recognition position calculation is off.

**Comment by derneuere** [comment]
Implemented the selfies / mirroring of coordinates. You can also search for selfies by typing in the lens, which in that case is "front camera". There is no option yet in the light box to delete a face though.

**Comment by sefininio** [comment]
Cool, will this also be part of the upcoming release?

**Comment by derneuere** [comment]
Yes :)
