### ISSUE TITLE
Slideshow from album on a digital picture frame

### ISSUE THREAD

**Issue by Jcros214** [LibrePhotos/librephotos#1110]
I'm new to this project. I want to make a feature request (which I hope to develop myself once I understand react a little better), but I'm not sure where to put it. 

I'm trying to create a digital picture frame using a LibrePhotos album since I already have most of my pictures scanned into my library and organized, and it dosen't seem _too_ complicated.

This repo seems like it's the main one, and librephotos-frontend doesn't have a way to submit issues, so I guess it belongs here?

**Comment by derneuere** [comment]
All the feature request are in the "librephotos" repository, which contains the backend code :) This request seems similar to this issue here: #294

How does your digital picture frame work? Is it an android based device or is it more like a desktop setup? Do we need a new app for that or can we use the regular frontend for it?

If you need help with setting up the dev environment or on how to implement it, I am happy to help :)

**Comment by Jcros214** [comment]
Thanks! This is the same as that issue. The picture frame is just a Raspberry Pi plugged into a display, so regular frontend should work.

How would you recommend setting it up?

Slightly off topic, when I setup the dev environment on my laptop, the instructions say to `git clone` all the files into the `$codedir` directory, but it looks like you have to move the other two repos into librephotos-docker/librephotos/code for the containers to start. Is that a documentation issue, or something else?

**Comment by derneuere** [comment]
No, all folders should be in one parent folder, like this:

![image](https://github.com/LibrePhotos/librephotos/assets/6658807/b44cef2b-b61c-4ab6-b2bf-402530c417e8)

Where did you get the information, that it should be in librephotos-docker/librephotos/code? :sweat_smile:

**Comment by Jcros214** [comment]
Well, nowhere, but when I started the container, the backend kept restarting because Django couldn't access code files, and it looked like the other repos had those files. 

What should the value of code dir be in .env? ../ ?

**Comment by derneuere** [comment]
The value of code dir should be the path of parent folder where all the code folders are. In my case it is /home/librephotos :)

**Comment by Jcros214** [comment]
Ok, I'll come back to the codedir thing in another issue later. I assume it was an issue with the way I set it up or something.

For the slide show, I think the easier implementation in my case (because there is some more custom stuff I want to do with the same app instance) is to just use a light flask server to actually run the slide show.

I see that the /api/ is available on the production server, so that should be pretty straightforward. 

Can you point me to a way to get an album's photos given it's ID? 

I found `/api/albums/user/shared/tome/`, which gives me the ID I need, but I don't see any endpoints that give a list of pictures. If one does not exist, how does the frontend display them?

**Comment by Jcros214** [comment]
Ok, I think I found what i need.

I generate a token, get the id of the album I want, and hit `/api/albums/user/<id>`, and response['grouped_photos'] has all the pictures grouped by date.

Awesome project! I look forward to using it, and hopefully contributing to it in the future!
