### ISSUE TITLE
Picture details allows to edit a person tag or untag, but not to delete the face

### ISSUE THREAD

**Issue by sefininio** [LibrePhotos/librephotos#1127]
When going over photos - sometimes it is easier to go over the photos and not the inferred faces and tag. 
For this scenario, the photo details has the options to change the person associated with a face or move the face back to unknown - other. But there's no way to delete the face, so the user must go look for it in the unknown-others section and delete if from there.

Suggestion - add another icon button that allows to delete entirely.

**Comment by derneuere** [comment]
This is now implemented! :)
