### ISSUE TITLE
Return if photo was uploaded but not yet processed

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#1142]
**Describe the enhancement you'd like**
As a app developer I want to know if an image successfully uploaded, but is still being processed.

The endpoint "api/exists/hash" should return exist true or false, but also report if an image was successfully uploaded, but is still being processed. The condition is, if the photo exists with the hash, but thumbnails are missing.

**Associated view**
https://github.com/LibrePhotos/librephotos/blob/9caa501643527af7be7e99ce9e9813623634a056/api/views/upload.py#L26

**Implementation**
https://github.com/LibrePhotos/librephotos/blob/9caa501643527af7be7e99ce9e9813623634a056/api/views/upload.py#L71

Add in the on_complete function a creation of a new photo entity associated with the user who uploaded it. The photo does not have associated thumbnails or machine learning information and only a path to the file.

Instead of using the handle_new_image, we should use rescan_image instead:
https://github.com/LibrePhotos/librephotos/blob/9caa501643527af7be7e99ce9e9813623634a056/api/directory_watcher.py#L240

**Test scenarios**

At the moment we assume that photos are completely processed. 
- check if the photo gets processed after creating a partial entity
- check if the views for displaying break or if they are suppressed successfully

**Describe why this will benefit the LibrePhotos**
Allows for smoother uploading in low end systems, where a processing may or may not finish.

**Additional context**
https://github.com/savvasdalkitsis/uhuruphotos-android/issues/454

**Comment by savvasdalkitsis** [comment]
Will thumbnail existence be enough of a proof the item is ready to be fetched by the /api/photos/{id}/summary/ endpoint?

That is the thing that is ultimately needed by clients like UhuruPhotos to mark the uploaded item as synced and display the remote data for it on the item details page.

**Comment by savvasdalkitsis** [comment]
An alternative would be to get the api/photos/{id}/summary/ endpoint itself return some pending status so there is no need for multiple api calls but the /exists endpoint would work too

**Comment by derneuere** [comment]
There is now a new field called "processing" in the response of the api/photos/{id}/summary/. If it is true, the file was successfully uploaded, but has not finished processing yet.

Currently we only check for the existence of the thumbnails, testing if that is enough would be great :)

**Comment by savvasdalkitsis** [comment]
Hm so this is interesting. In the latest dev, after uploading a rather large video, right after the complete call is made, so before the video has finished processing, calling the above api returns a 200 with the following body:

```
{
    "photo_summary": {
        "id": "1cb3322d5f9e38f03080e3a6c5b0bc2c1",
        "dominantColor": "",
        "url": "1cb3322d5f9e38f03080e3a6c5b0bc2c1",
        "location": "",
        "date": "",
        "birthTime": "",
        "aspectRatio": null,
        "type": "video",
        "video_length": "",
        "rating": 0,
        "owner": {
            "id": 1,
            "username": "kurosavvas",
            "first_name": "Savvas",
            "last_name": "Dalkitsis"
        }
    },
    "album_date_id": null,
    "processing": false
}
```

Notice that processing is false, there is a body for the photo_summary but things like album date, aspect ratio, etc is missing. The client would not be able to process this response properly :/

Calling the api again after a while returns the full response:

```
{
    "photo_summary": {
        "id": "1cb3322d5f9e38f03080e3a6c5b0bc2c1",
        "dominantColor": "#ccb69f",
        "url": "1cb3322d5f9e38f03080e3a6c5b0bc2c1",
        "location": "",
        "date": "2024-01-28T22:51:47+00:00",
        "birthTime": "2024-01-28T22:51:47Z",
        "aspectRatio": 0.56,
        "type": "video",
        "video_length": "19.8198",
        "rating": 0,
        "owner": {
            "id": 1,
            "username": "kurosavvas",
            "first_name": "Savvas",
            "last_name": "Dalkitsis"
        }
    },
    "album_date_id": 1633,
    "processing": false
}
```

**Comment by savvasdalkitsis** [comment]
Also note that calling the api with a completely made up hash returns a 404 with an empty body, not a response with 'processing = false` as i would expect if my assumption was correct that for a processing item we'd get a 404 with the field true but for a truly missing item, we'd get a 404 with the processing field = false

**Comment by derneuere** [comment]
I am not sure why the check is not working for videos. I use now aspect_ratio instead, which is calculated after creating thumbnails, which should also work.

Not sure if I agree, that an photo, that does exist should return 404.

My mental model is that 404 means the image does not exist at all and should be uploaded, 200 with processing = true means, it was uploaded but not yet processed, 200 with processing=false means was uploaded and processed.

**Comment by savvasdalkitsis** [comment]
Hm it seems I am getting the same behaviour unless the dev image hasn't updated yet?
```
{
    "photo_summary": {
        "id": "4521bdd19748a9b63786a95916c3792a1",
        "dominantColor": "",
        "url": "4521bdd19748a9b63786a95916c3792a1",
        "location": "",
        "date": "",
        "birthTime": "",
        "aspectRatio": null,
        "type": "video",
        "video_length": "",
        "rating": 0,
        "owner": {
            "id": 1,
            "username": "kurosavvas",
            "first_name": "Savvas",
            "last_name": "Dalkitsis"
        }
    },
    "album_date_id": null,
    "processing": false
}
```

As far as the code goes, I don't have strong feelings either way tbh. I only assumed a 404 cause, semantically, until the media has finished processing, the **summary** of the media is not found so 404 🤷 But like i said, don't mind either way

**Comment by derneuere** [comment]
According to docker hub the new image was uploaded and should be available. I uploaded a couple of videos, while preventing them from getting processed and it returned this, which looks correct.

```
{
  "photo_summary": {
    "id": "7c2b8fab486bfcebd2dd9355c72ae3101",
    "dominantColor": "",
    "url": "7c2b8fab486bfcebd2dd9355c72ae3101",
    "location": "",
    "date": "",
    "birthTime": "",
    "aspectRatio": null,
    "type": "video",
    "video_length": "",
    "rating": 0,
    "owner": {
      "id": 1,
      "username": "admin",
      "first_name": "Niaz",
      "last_name": "Faridani-Rad"
    }
  },
  "album_date_id": null,
  "processing": true
}
```

**Comment by savvasdalkitsis** [comment]
Very weird. I still cannot get this to report processing true. I guess I could just use the album_date_id being not null as an indicator as that is the main key the app is using to assing the media into the user's feed as well as the processing field and it should cover all cases

**Comment by derneuere** [comment]
I added some automated testing in this class here and all the tests pass and return true or false based on the aspect ratio property:

https://github.com/LibrePhotos/librephotos/blob/dev/api/tests/test_photo_summary.py

I found a bug, where non admin users e.g. a second user could not reach the summary endpoint and would get a 403 error instead. Could that explain, why it did continuously upload for some users?

**Comment by savvasdalkitsis** [comment]
Hm that could perhaps also be contributing. Would be nice to fix that alongside with this

**Comment by derneuere** [comment]
Alright, added a fix for the 403 error too :)

**Comment by savvasdalkitsis** [comment]
I closed the accompanying UhuruPhotos ticket. Happy with this as is so feel free to close it unless you feel there should be more work done
