### ISSUE TITLE
Docker - On first boot LibrePhotos does not load setup | Cannot sign in at logon screen

### ISSUE THREAD

**Issue by alternativesurfer** [LibrePhotos/librephotos#1156]
# 🛑 Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.
- You have asked for help on our Discord server [LibrePhotos](https://discord.gg/xwRvtSDGWb) if your issue involves general "how to" questions

**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

Install via docker instructions:
https://docs.librephotos.com/docs/installation/standard-install

on first boot, load the page http://localhost:3000
Page redirects to http://localhost:3000/login
![image](https://github.com/LibrePhotos/librephotos/assets/10135929/9fe54389-5387-4a3b-ae97-141d60904aaf)

There is no way to log into the app.

## Please provide additional information:
- 💻 Operating system: Ubuntu server 22
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: 2024 January
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: image tag(s) are the default:
    * https://github.com/LibrePhotos/librephotos-docker/blob/main/docker-compose.yml
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): hyperV

**Comment by derneuere** [comment]
You probably did not rename librephotos.env to .env

If it is not the issue, please look into ownphotos.log and look for an error and post it here.

**Comment by brice-t** [comment]
I have a similar issue.
It seems related to https://github.com/LibrePhotos/librephotos/issues/1097 (as seen in my gunicorn_django.log)
Would it be possible ?
What is the easiest way to revert to a previous librephotos version using the docker install ?

**Comment by brice-t** [comment]
After a few more investigations, I realized that playing with the "tag" of docker image does not have any positive effect.
But as far as I understand, I would need to have the latest RC of pytorch, which even the "dev" tag does not have (which makes sense).
Is there a way to force the latest RC og pytorch using the docker install ?

**Comment by derneuere** [comment]
I think the October release is the one you have to go back to ([2023w43](https://github.com/LibrePhotos/librephotos-docker/tree/2023w43))  Are you sure, that you run a CPU, which is older like 10 years and probably something like a Core Duo?

If you want to install it, it would make sense to download the entrypoint.sh file, add the download for pytorch nightly to it and then mount it into the docker container.

**Comment by brice-t** [comment]
Thanks for your answer.
Unfortunately, yes : I am trying to make it run on a low-end dedicated server having an Atom N2800 (no SSE4)
I tried with 2023w43 but had no better luck.
I will try with the entrypoint.sh whenever I get time for it (I am not that confortable with Docker but will manage to find out how to do it)

**Comment by derneuere** [comment]
@brice-t There is a new pytorch release, which should include the fix. If everything goes well, it should work again in a couple of days with the latest release :)
