### ISSUE TITLE
Faces tagging in Firefox: Detail: Invalid Page when tagging faces

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#1165]
Latest docker dev image (frontend image: d0d98006d62c)

Firefox debug log:

[content.js:8:1240](moz-extension://c018d7df-250a-4fb1-a995-fddd8ed95101/content.js)
Error in parsing value for ‘image-rendering’.  Declaration dropped. [leaflet.css:34:19](https://unpkg.com/leaflet@1.7.1/dist/leaflet.css)
Unknown property ‘behavior’.  Declaration dropped. [leaflet.css:114:11](https://unpkg.com/leaflet@1.7.1/dist/leaflet.css)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [leaflet.css:542:10](https://unpkg.com/leaflet@1.7.1/dist/leaflet.css)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. [index-3-CbAyEn.css:4:673](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Unrecognized at-rule or error parsing at-rule ‘@-ms-keyframes’. [index-3-CbAyEn.css:4:34417](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. [index-3-CbAyEn.css:4:34466](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Unrecognized at-rule or error parsing at-rule ‘@-ms-keyframes’. [index-3-CbAyEn.css:4:34664](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. [index-3-CbAyEn.css:4:34712](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Error in parsing value for ‘background’.  Declaration dropped. [index-3-CbAyEn.css:4:35579](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Error in parsing value for ‘width’.  Declaration dropped. [index-3-CbAyEn.css:4:35614](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Error in parsing value for ‘letter-spacing’.  Declaration dropped. [index-3-CbAyEn.css:4:43320](https://libre.skadaha.dk/assets/index-3-CbAyEn.css)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.

**Comment by derneuere** [comment]
Should be fixed
