### ISSUE TITLE
Crash when requesting summary of hidden photo

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#1173]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

When requesting the summary of a hidden photo, there is a crash on the backend (logs attached)

## 🔁 How can we reproduce it:

Request the `/api/photos/{HASH}/summary/` endpoint for an image that is previouslyu hidden.

## Please provide additional information:
- 💻 Operating system:  docker on ubuntu
- ⚙ Architecture (x86 or ARM):  x86
- 🔢 Librephotos version: dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.):  local file systen
- 
[log.txt](https://github.com/LibrePhotos/librephotos/files/14565724/log.txt)

**Comment by derneuere** [comment]
Your are calling /api/albums/date/hiddenPhoto/, which is creating the subsequent error. This is not the correct format, when using this API. If you want to filter, for only hidden photos, use /api/albums/date/list/?hidden=true for getting all relevant album dates and /api/albums/date/67/?page=1&hidden=true for requesting a page with only hidden images. If you need additional information let me know :)
