### ISSUE TITLE
scanning photos numbers always centered

### ISSUE THREAD

**Issue by ololax123** [LibrePhotos/librephotos#119]
Hi, on the admin area page when a scan is running, it centers the "photos scanned / photos to scan" on the "done part" of the progressbar, should be centered on the progressbar as whole, so you can always see the numbers.

**Comment by robertcontois** [comment]
adding in your screenshot from discord for clarity.

![Screenshot_2021-01-09_151137](https://user-images.githubusercontent.com/6868371/104108290-51bcdf00-5291-11eb-85cf-1cda161100d3.png)

**Comment by tomamplius** [comment]
duplicate #149?

**Comment by derneuere** [comment]
This is now fixed.
