### ISSUE TITLE
Modify frontend calls for rebuildfaissindex

### ISSUE THREAD

**Issue by robertcontois** [LibrePhotos/librephotos#121]
Currently, after scanning for photos the front end makes a call to _/api/rebuildfaissindex/_ on the backend, but that endpoint doesn't exist. This throws a message on the backend "Not Found: /api/rebuildfaissindex/"

_librephotos-frontend/src/actions/utilActions.js_

<img width="616" alt="Screen Shot 2021-01-09 at 3 33 16 PM" src="https://user-images.githubusercontent.com/6868371/104108257-16baab80-5291-11eb-9218-a69c1f2368e5.png">

<img width="708" alt="Screen Shot 2021-01-09 at 3 25 24 PM" src="https://user-images.githubusercontent.com/6868371/104108254-14585180-5291-11eb-81d3-853c71c1c307.png">

We should either remove the call from the frontend or add it to the backend. It looks like the similarity index is already being built after the scan on the backend already.

**Comment by derneuere** [comment]
That is correct. Currently, the function call to rebuild the similarity index is after a scan but in the backend only. Should be save to delete.
https://github.com/LibrePhotos/librephotos/blob/2e3c4669650b8e3fe8fce59bfbaac871d834671f/api/directory_watcher.py#L179-L189
