### ISSUE TITLE
Places on map in wrong location

### ISSUE THREAD

**Issue by HMKnapp** [LibrePhotos/librephotos#1272]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Coordinates are off to east and south. Looks like a constant offset.

These are in Central Europe:
![image](https://github.com/LibrePhotos/librephotos/assets/42992894/fda3ff24-370b-45f0-8ec0-ad50221e837f)

Distance between places seems to be correct. Location information of images in image details is correct, coordinates as well as street name, etc.
Only the display on the map is wrong.

I have tried
- rescan
- removed the DB
- removed protected_media

I use Mapbox now but it's the same with Photon 

## 🔁 How can we reproduce it:
I can reproduce it, but don't know how you could.

## Please provide additional information:
- 💻 Operating system: librephotos-gpu Docker image
- ⚙ Architecture (x86 or ARM): x86_64
- 🔢 Librephotos version: 2024w05
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: librephotos-gpu:latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
This was definitely fixed in a newer release :)
