### ISSUE TITLE
Use original filename when saving photos or videos

### ISSUE THREAD

**Issue by HMKnapp** [LibrePhotos/librephotos#1273]
**Describe the enhancement you'd like**
Saving a file should give it its original filename instead of the hash

**Describe why this will benefit the LibrePhotos**
Being able to save an image with its original filename is better in every way.

Saving e.g. `http://localhost:3000/media/photos/316f2524acd7f5841c924fe4f1a422641` should use `IMG_2024_0101_1234.jpg` instead of `316f2524acd7f5841c924fe4f1a422641.jpg`

All that is needed is an additional HTTP header:
`Content-Disposition: inline; filename="IMG_2024_0101_1234.jpg"`
**inline** so it preserves the possibility to view the image in the browser, and at the same time you can save it with its real filename.

**Comment by derneuere** [comment]
Implemented, is now available on dev or in the next release :)
