### ISSUE TITLE
Faces page improvement suggestions

### ISSUE THREAD

**Issue by ololax123** [LibrePhotos/librephotos#128]
Ability to press the name of a person in order to get to an edit page, maybe the person have changed his/her last name. A name has been misspelled etc.

Go into a view of photos of a person with the ability to retag it if there has been an error and a face has been assigned to the wrong person.

A page to make changes to the tagged person and the photos assigned to a name would be good I think.

Not really an issue, more of an improvement suggestion

**Comment by guystreeter** [comment]
I would like to be able to move incorrectly-inferred faces back to "unknown". I don't want to delete them.

**Comment by guystreeter** [comment]
Not being able to edit a name is a big problem. People get offended, and I'm a terrible typist anyway.

**Comment by ChrisFab16** [comment]
> I would like to be able to move incorrectly-inferred faces back to "unknown". I don't want to delete them.

Exactly this. I have wrongly inferred faces w 100% confidence  levels. I need an explicit way to train these as a "Wrong match". and I don't want to create multiple Person albums of people
