### ISSUE TITLE
High CPU load all the time, especially from DB

### ISSUE THREAD

**Issue by BorisBrock** [LibrePhotos/librephotos#1281]
# 🐛 Bug Report

* [ x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ x] ❌ I have looked for similar issues (including closed ones)
* [ x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I have installed LibrePhotos via Docker a few days ago. On day one I added ~300 photos. The photos were imported successfully, and everything looked fine.
But after several hours without any operations (no more imports, not opening the Web UI), the CPU load of the the backend and the db is very high:
- Backend: 1-2%
- **DB: 7-12% (yikes!)**
In the Web UI no running operations are shown.
Even after restarting the docker container (or the whole machine), the CPU load remains high.
IMHO LibrePhotos should be idle with close to 0% CPU load.

![Screenshot from 2024-05-28 08-36-52](https://github.com/LibrePhotos/librephotos/assets/5222025/79f90d5d-3323-44b4-bd9b-be962baa4e71)

Logs:
[logs.zip](https://github.com/LibrePhotos/librephotos/files/15465100/logs.zip)

## 🔁 How can we reproduce it:
- Fresh installation via Docker Compose
- Add a few photos
- Wait 24 hours
- Check CPU usage with `docker stats`

## Please provide additional information:
- 💻 Operating system: Ubuntu Server 22.04
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: 2024w18
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local file system (SSD)
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): Proxmox

**Comment by derneuere** [comment]
The database is just a PostgreSQL system. I cant change anything about this :)
