### ISSUE TITLE
The difficulties with installing librephoto on UNraid

### ISSUE THREAD

**Issue by EWEDLCM** [LibrePhotos/librephotos#1302]
Hello, please take a look at the picture. 
When I installed librephoto on Unraid, it successfully ran the program automatically.  But I did not enter the normal registration interface, but directly into the login interface！I rebooted it a few times, but it didn't work., so I tried to use the address bar to let him enter the registration interface, but it could not register normally. 
Is there any other way to solve this problem？ Thanks very much.
![log](https://github.com/LibrePhotos/librephotos/assets/168160898/327e9cc1-d551-431a-81b6-b2fd931dc27a)
![微信截图_20240703184617](https://github.com/LibrePhotos/librephotos/assets/168160898/f1bb7bdc-2c9d-4a7a-a2bc-c9c11359b18c)
![微信图片_20240703184550](https://github.com/LibrePhotos/librephotos/assets/168160898/9adcb060-b455-4415-8ccf-05af0193551b)

**Comment by pnaskardev** [comment]
it seems like the database migrations has not completed can you please elaborate more on how you installed?

**Comment by derneuere** [comment]
The local install and singleton docker image option is no longer maintained and deprecated. Please use docker-compose instead.
