### ISSUE TITLE
Cannot install dependency matplotlib

### ISSUE THREAD

**Issue by Chewie9999** [LibrePhotos/librephotos#1312]
# 🐛 Bug Report

* [N/A - didn't get that far ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

Installation fails with missing dependencies:

```
ERROR: Could not find a version that satisfies the requirement matplotlib==3.9.0 (from -r requirements.txt (line 23)) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0rc1, 3.4.0rc2, 3.4.0rc3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0b1, 3.5.0rc1, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.6.0rc1, 3.6.0rc2, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.7.0rc1, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5)
ERROR: No matching distribution found for matplotlib==3.9.0 (from -r requirements.txt 
```
It seems that only v3.1.2 is available in the ubuntu repository.
I tried using the instructions here: https://matplotlib.org/stable/install/index.html for a nightly build, but that only installed v3.7.5

## 🔁 How can we reproduce it:

```
git clone https://github.com/LibrePhotos/librephotos-linux.git
cd librephotos-linux
./install-librephotos.sh
```

## Please provide additional information:
- 💻 Operating system: Ubuntu 20.04.6 LTS
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: Downloaded using git 12 hours ago
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): "./install-librephotos.sh"

How can I get the right version for my OS?

**Comment by derneuere** [comment]
The local install option is no longer maintained and deprecated. Please use docker-compose instead.
