### ISSUE TITLE
Persist thumbnail setting

### ISSUE THREAD

**Issue by turnbeutelvergesser** [LibrePhotos/librephotos#132]
I can switch to small thumbnails and it takes effect when I display photos, but immediately after reloading the page in the browser (F5 in Firefox), they are big again and the setting in the settings panel also is back to "big".

**Comment by derneuere** [comment]
We do not have a field for that in the database, and we also need an API interface for that.

**Comment by derneuere** [comment]
This setting does not exist anymore.
