### ISSUE TITLE
Cannot create album

### ISSUE THREAD

**Issue by 1michaelbrown** [LibrePhotos/librephotos#1323]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 
[log-files.zip](https://github.com/user-attachments/files/16238010/log-files.zip)

<img width="1851" alt="Screenshot 2024-07-15 at 10 35 35 AM" src="https://github.com/user-attachments/assets/79c01030-85b7-41d5-922a-bead7e247efe">

## Please provide additional information:
- 💻 Operating system: Debian GNU/Linux 12 (bookworm)
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: 2024w28
- 📸 Librephotos installation method: Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: reallibrephotos/librephotos:latest
- 📁 How is you picture library mounted: USB to Sabrent SATA Hard Drive docking station so I presume that is Local file system
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): VMware

**Comment by 1michaelbrown** [comment]
Another note if it matters I use casaos then portainer to manage docker containers.

**Comment by derneuere** [comment]
Select images in photos, click on the plus and click "add to album". You have there the option to add a new album too.

We can keep this issue open, if you change it to an enhancement and change the title :)
