### ISSUE TITLE
Buttons in library are grayed out

### ISSUE THREAD

**Issue by WASDetchan** [LibrePhotos/librephotos#1340]
# 🐛 Bug Report

* [✓] 📁 I've Included a ZIP file containing my librephotos `log` files 
* [✓ ] ❌ I have looked for similar issues (including closed ones)
* [✓ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

On fresh installation buttons in the "Library" (including Scan Library) are grayed out. The "Rescan" button works. Rescan is able to find all my photos.

## 🔁 How can we reproduce it:

Install librephotos via docker compose (docker-compose-v2) on local machine with Ubuntu 24.04 LTS using [this guide](https://docs.librephotos.com/docs/installation/standard-install). Go to http://localhost:3000/library. Almost all the buttons are grayed out and are not clickable
![image](https://github.com/user-attachments/assets/cf2ff41e-cd38-46c9-920e-cc998261ff00).

The same issue is present with a fresh installation via docker-compose on Ubuntu 20.04 LTS.

An archive with logs, console output during reinstallation process, configuration files and videos demonstrating the problem:
[issue.zip](https://github.com/user-attachments/files/16411840/issue.zip).

## Similar issues:

#1269 has similar error messages, no answers

https://www.reddit.com/r/librephotos/comments/sit3jz/help_configuring_and_starting/
Similar symptoms, but I can't understand what "myPhotos" is. And there are no answers.

## Please provide additional information:
- 💻 Operating system: Ubuntu 24.04 LTS
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: Version: 2024w28
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker compose (docker-compose-v2)
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: reallibrephotos/librephotos:latest 
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local file system

**Comment by derneuere** [comment]
There is probably a long-running job that seems to be running in the admin dashboard. If it is actually finished, because it crashed or is stuck, then just remove it from the list, and then you can start another one

**Comment by WASDetchan** [comment]
Thank you!
