### ISSUE TITLE
Cannot remove missing photos from db

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#1341]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

Pressing on the missing photos label asks to confirm removal of missing photos but nothing happens

![image](https://github.com/user-attachments/assets/3512629b-6d6d-4619-be3d-cc9bc6a4fec7)

![image](https://github.com/user-attachments/assets/b5487afd-41e4-4583-a418-afd2a5fadfb8)

The following shows up in my firefox console

```
TypeError: Request constructor: HEAD or GET Request cannot have a body.
    R3t https://DOMAIN/assets/index-BEl6n31b.js:708
    a6t https://DOMAIN/assets/index-BEl6n31b.js:708
    u https://DOMAIN/assets/index-BEl6n31b.js:708
    v https://DOMAIN/assets/index-BEl6n31b.js:708
    nbe https://DOMAIN/assets/index-BEl6n31b.js:708
    kFe https://DOMAIN/assets/index-BEl6n31b.js:708
    dispatch https://DOMAIN/assets/index-BEl6n31b.js:708
    m https://DOMAIN/assets/index-BEl6n31b.js:708
    kFe https://DOMAIN/assets/index-BEl6n31b.js:708
    P https://DOMAIN/assets/index-BEl6n31b.js:708
    q https://DOMAIN/assets/index-BEl6n31b.js:1220
    wdt https://DOMAIN/assets/index-BEl6n31b.js:82
    Odt https://DOMAIN/assets/index-BEl6n31b.js:82
    Pdt https://DOMAIN/assets/index-BEl6n31b.js:82
    afe https://DOMAIN/assets/index-BEl6n31b.js:82
    tRe https://DOMAIN/assets/index-BEl6n31b.js:82
    tH https://DOMAIN/assets/index-BEl6n31b.js:82
    Fte https://DOMAIN/assets/index-BEl6n31b.js:85
    PIe https://DOMAIN/assets/index-BEl6n31b.js:82
    tH https://DOMAIN/assets/index-BEl6n31b.js:82
    hte https://DOMAIN/assets/index-BEl6n31b.js:82
    Bdt https://DOMAIN/assets/index-BEl6n31b.js:82
[library:13851:25](https://DOMAIN/library)
Uncaught (in promise) 
Object { error: {…}, isUnhandledError: true, meta: undefined }
[index-BEl6n31b.js:856:106934](https://DOMAIN/assets/index-BEl6n31b.js)
Source map error: Error: request failed with status 404
Resource URL: null

```

## 🔁 How can we reproduce it:

Have missing photos in the library. Press the label and accept. Notice that nothing happens

## Please provide additional information:
- 💻 Operating system: Ubuntu 20.4
- ⚙ Architecture (x86 or ARM):  x86
- 🔢 Librephotos version: reallibrephotos/librephotos-gpu:dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.):  docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.):  local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by nagarrido** [comment]
This is also happening to me

**Comment by derneuere** [comment]
Pushed a fix :)
