### ISSUE TITLE
Open with direct link (or in new tab) does not work due to session storage not shared

### ISSUE THREAD

**Issue by johanatandromeda** [LibrePhotos/librephotos#1343]
# 🛑 Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.
- You have asked for help on our Discord server [LibrePhotos](https://discord.gg/xwRvtSDGWb) if your issue involves general "how to" questions

**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X ] ❌ I have looked for similar issues (including closed ones)
* [X] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

If I open librephotos from a link, the user is logged in via the jwt HTTP cookie, but API calls will not work due to the API keys that are located in the session storage is not included.

## 🔁 How can we reproduce it:

1. Log in to librephotos
2. Copy the URL
3. Open the URL in a new tab
4. "authorization: Bearer ..." is missing in the REST calls
5. The user gets an notification "Authentication credentials were not provided."

## Please provide additional information:
- 💻 Operating system:  Docker (Ubuntu 22.04 LTS + HAproxy (reproducible with direct connection to 3000)
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: 2024w28
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.):  local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):  Proxmox 8

**Comment by johanatandromeda** [comment]
2024w09 works

**Comment by derneuere** [comment]
Switched to saving it in the cookies instead :)
