### ISSUE TITLE
Refactor api/dirtree

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#136]
We currently have a workaround to use only two recursions when determining the directory tree. This will lead to an incorrect directory tree when it is deeply nested. 

We should fix that by an on-demand-lookup when the user clicks the tree. We need to rewrite the path_to_dict function:
https://github.com/LibrePhotos/librephotos/blob/a388d0c6f914be127e51a6e4d0790877f77fd23f/api/api_util.py#L42-L51
It should not do recursion but should only determine the children in the directory and if they have also folders.

We also need to refactor the frontend to call the function every time a node is clicked and update the directory tree accordingly.
https://github.com/LibrePhotos/librephotos-frontend/blob/3220b25ec92e942d030503ea699fc6e6db83fda0/src/layouts/AdminPage.js#L36-L44

https://github.com/LibrePhotos/librephotos-frontend/blob/3220b25ec92e942d030503ea699fc6e6db83fda0/src/layouts/AdminPage.js#L377-L381

https://github.com/LibrePhotos/librephotos-frontend/blob/3220b25ec92e942d030503ea699fc6e6db83fda0/src/layouts/AdminPage.js#L459-L475

**Comment by 2andgi** [comment]
![Знімок екрана 2021-09-09 110013](https://user-images.githubusercontent.com/89306827/132648481-5a1aa087-3417-487d-8127-2cfdafdde56a.jpg)

More levels deeper will be very useful to connect NextCloud users Pictures folders directly in case of two instances LP&NC at same server

**Comment by derneuere** [comment]
There is also another issue with this function. It does return the folders in a random order. It should be ordered by name instead.

**Comment by derneuere** [comment]
This is now implemented :)
