### ISSUE TITLE
Docker image reallibrephotos/singleton not updated for a while

### ISSUE THREAD

**Issue by apavelm** [LibrePhotos/librephotos#1389]
Please update the docker image "reallibrephotos/singleton" to correspond to the latest versions. 
Last time it was updated more than a year ago.
Thanks

**Comment by derneuere** [comment]
Yes, it's archived and will not be updated going forward. It was no longer maintainable with the current approach and I do not have the time to find a better solution for it.

**Comment by apavelm** [comment]
@derneuere OK, got it. Maybe be you (or anybody else) can please update the LibrePhotos App in unRAID repository? Thanks
I found a thread here: https://forums.unraid.net/topic/126943-support-librephoto
I know you mentioned that you have no time for that, but I guess only you have an access to replace the "unRAID App" in repository.
It would be very appreciated if you could update it. I mean the template may use another docker image

Thanks

**Comment by apavelm** [comment]
Apparently, according to the unRAID rules - only you can update the App template.
@derneuere please let me know if I can help you with that.

**Comment by derneuere** [comment]
Sure, I talked to the admin of unraid to take the app down and archived the librephotos-unraid repository :) Should now not appear in the community apps section anymore.

We do not have a single docker image setup for this application, so there will be no unraid app anymore. Please use docker compose instead.
