### ISSUE TITLE
Photos not loading (403) after browser restart

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#14]
I got an 403 error, when I close and open again chrome. To fix this I need to logout and login again, or it just randomly start woking after a while.

![image](https://user-images.githubusercontent.com/30871217/101013963-5fca6200-3565-11eb-9fab-42ac269b3819.png)

**Comment by DigitalWarrior** [comment]
@sysoppl I have been trying to recreate this issue. 
Do you have any logs? 
What is the back end of the url you are experiencing this issue with i.e. /people or /notimestamp? 
What version of Chrome are you using and OS?
If you do a fresh pull from Docker Hub is this issue still persisting?

Thank you - DW

**Comment by sysoppl** [comment]
This is not anymore an issue. I haven't seen this bug since some update. Sorry that I didn't close this earlier.
