### ISSUE TITLE
Predefine old name when renaming persons

### ISSUE THREAD

**Issue by BrewGnu** [LibrePhotos/librephotos#1414]
**Describe the enhancement you'd like**
When renaming a person, it would be great to have the old name in the renaming field.

**Describe why this will benefit the LibrePhotos**
 I am at the beginning of naming all my faces and had to rename them quite many times. For example adding the prefix "Work - " or "Teachers -" would be much easier that way.

**Additional context**

**Comment by derneuere** [comment]
This is now implemented :)
