### ISSUE TITLE
cannot connect to backend server with Synology

### ISSUE THREAD

**Issue by gpopesc** [LibrePhotos/librephotos#144]
Hello

I get an error when I try to install it on synology. There was a similar post few weeks ago, but I think the error is different ( 
https://github.com/LibrePhotos/librephotos/issues/27 ). I have the latest container downloaded today.

I can connect to frontend and get the folowing error:

![image](https://user-images.githubusercontent.com/11590919/105409218-cc461100-5c38-11eb-8f34-992cfd35fcde.png)

The database is ok I can connect . Redis is also ok.. Only backend container I have errors and it is restarting every 10-15 minutes.
[_librephotos-backend_logs.txt](https://github.com/LibrePhotos/librephotos/files/5851952/_librephotos-backend_logs.txt)
[_librephotos-redis_logs.txt](https://github.com/LibrePhotos/librephotos/files/5851953/_librephotos-redis_logs.txt)
[_librephotos-db_logs.txt](https://github.com/LibrePhotos/librephotos/files/5851954/_librephotos-db_logs.txt)

I try to connect to database in many ways : inside container, external and I tried to connect other postgres database where I created first the database, but I get always those errors from backend container. 

Any ideas what I can try?

**Comment by derneuere** [comment]
You somehow managed to get an older docker image of the backend. No idea how you did that 😅 It is at least 18 days old. Do you have steps to reproduce that error?

**Comment by gpopesc** [comment]
screen capture took from portainer. I will delete all and redownload. I have all images with dev as ${tag} in compose.

![image](https://user-images.githubusercontent.com/11590919/105419329-35348580-5c47-11eb-8b2f-8ecae14afdf4.png)

**Comment by gpopesc** [comment]
now it is ok, thank you very much. I think the image was changed today in the meantime ;)
![image](https://user-images.githubusercontent.com/11590919/105487335-8df03680-5cb8-11eb-98a3-3a248ce4c118.png)
