### ISSUE TITLE
Android / iOS app

### ISSUE THREAD

**Issue by TAW-V** [LibrePhotos/librephotos#145]
I'v tried many different self hosted alternatives to Google Photos.
Librephotos is one of the best.

What i'm missing is an android app. For most use cases a web page is sufficient.
But being able to view non-uploaded photos and already uploaded photos in the same place in a gallery app would be nice.

Is this something that is planned for the future?

Thanks

**Comment by Rijul-A** [comment]
I can take a look at the Android app, but can you recommend any starting points to look at, and if you have any spec for the app already? For example, first we need to answer questions like if we want it to be structured in a web view (a la Jellyfin), or native?

**Comment by derneuere** [comment]
I think we need to go in the direction of a native app. We need access to the memory to sync pictures with the server and to display them in one view together with the pictures from the server. But I think we can use something like React Native, because the frontend codebase is in React.

**Comment by mind-overflow** [comment]
I totally agree and would love to have a native android app. It should be kind of a replacement for your gallery imho, like Google Photos does. I hate having to constantly switch between my stock gallery and another page or app to see my pics. Seeing all of them in the same place would be awesome!

**Comment by Norien** [comment]
An android app for uploading and viewing photos is basically required for me. I would love to migrate out of Google photos but without the app my wife will never get on board

**Comment by mike-lloyd03** [comment]
React-Native is an excellent approach and it allows the mobile codebase to be used on both Android and iOS. It could even by implemented in a desktop app using something like Electron. 

And I agree that LibrePhotos is far ahead of the pack when it comes to a suitable Google Photos replacement.

**Comment by darrepac** [comment]
Really looking for an iOS app...

**Comment by VirtualGit** [comment]
+1 for a native app. Don't really know how good is react native, but web-based apps are often much less responsive.
I'm looking for a google photo replacement solution (self hosted) and definitevely, the Android app quality and reactivity is a major criteria.

**Comment by gomme600** [comment]
Hi, any updates on this ?

**Comment by cbh2000** [comment]
I agree that React Native would be a good fit here. Especially considering that LibrePhotos' frontend is implemented in React.

I'd be interested in possibly starting a simple React Native app. I'm skeptical I'd find the time to do it, but I could maybe spend a day or two on it. Are there docs for the backend's API? Or is there a file I can reference in the frontend for auth?

**Comment by derneuere** [comment]
You can find some documentation after you startup LibrePhotos in the latest version: https://docs.librephotos.com/4/dev_frontend/

**Comment by nagarrido** [comment]
This would be greatly appreciated @cbh2000

**Comment by akshay9** [comment]
Native Mobile app is something I'll really love to use!!

I am a React Native Developer myself, would love to contribute!
@cbh2000 count me in :)

**Comment by cbh2000** [comment]
I'm finding that I don't realistically have time to work on the mobile app, even for just a few days. Life got busier shortly after I made that comment. Sorry, guys. 😢

**Comment by mind-overflow** [comment]
@cbh2000 don't worry! You never signed any contract, and you even said you probably wouldn't have had time for it. I'd be happy to give it a try too, but I'm in your same situation.  
Who knows what the future holds! Maybe we'll find someone who can work on this. Meanwhile, good luck with everything!

**Comment by derneuere** [comment]
We now have an app in beta here: https://github.com/akshay9/librephotos-mobile 🥳

**Comment by Atemu** [comment]
FYI: https://github.com/savvasdalkitsis/uhuruphotos-android
