### ISSUE TITLE
Visual bug when scanning

### ISSUE THREAD

**Issue by FunDeckHermit** [LibrePhotos/librephotos#149]
![image](https://user-images.githubusercontent.com/5075692/105688004-663be100-5ef9-11eb-893c-b47688fdc650.png)
The text is not left aligned with the start of the progress bar. As a result some of the text is cut-off. 
Tested in Opera and Edge browser.

![image](https://user-images.githubusercontent.com/5075692/105688091-7a7fde00-5ef9-11eb-9b2b-345f51a7ea8a.png)
![image](https://user-images.githubusercontent.com/5075692/105688480-ef531800-5ef9-11eb-9fa4-2fc45c53c4a8.png)
Removing the `right: .5em` seems to fix it.

**Comment by derneuere** [comment]
Related to #119

**Comment by FunDeckHermit** [comment]
![image](https://user-images.githubusercontent.com/5075692/105730893-1d068400-5f2f-11eb-967c-ca99ca82c2f9.png)
I just found the same bug in the navigation bar.

**Comment by tomamplius** [comment]
It's seems the normal work of the progressbar
https://react.semantic-ui.com/modules/progress/#content-progress
