### ISSUE TITLE
How to end a scan in progress?

### ISSUE THREAD

**Issue by ajquick** [LibrePhotos/librephotos#1496]
I am working on a project that involves face tagging tens of thousands of faces. All my images are already in Librephotos. I found there was a large number of photos that were included that did not need to be, so I move the files out of Librephotos and initiated a rescan to find the missing images so I could delete them.

The scan found the missing photos right away, however the scan is now going through the full rescan process with no ability to stop it. This scan is going to take 2-4 days to complete. How do I end the scan? I have killed processes, restarted, terminated the backend container and done a lot to try to get it to stop. I believe there are actually two scan processes running now.

I'd like to run the delete pictures task so that I can go back to face tagging. 

There has to be somewhere where the task to saved to get it to run the next time the container starts? (It has been deleted from the processes in the admin panel.)

**Comment by derneuere** [comment]
We use Django Q2 as our queuing solution, with all tasks for a given job persisted in the database. For development purposes, you can access the backend at /api/django-admin to view all database entries and manually delete tasks from the queue.

Each image processing request generates an individual task, which might make bulk deletion somewhat cumbersome.

Currently, there is no straightforward way to stop tasks directly from the regular frontend.

**Comment by ajquick** [comment]
I can't access due to CSRF errors. I added my local host IP to the ENV, but it still isn't working.

Would a database command like this work?

````DELETE FROM `django_q_task` WHERE `func` = 'XXX' ````

Where XXX is the name of the new images process? (Can't remember off hand.)

**Comment by ajquick** [comment]
After clearing all the tasks and everything, the delete images / metadata task did nothing. It just kept postponing out 12 hours to be run again later.

I ended up just deleting my missing faces with the following SQL:

````
DELETE FROM api_face
USING api_photo, api_file
WHERE api_face.photo_id = api_photo.main_file_id
  AND api_file.hash = api_photo.main_file_id
  AND api_file.missing = TRUE;
````
