### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by tarmacalastair** [LibrePhotos/librephotos#1497]
# 🐛 Bug Report
* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files

* [y] ❌ I have looked for similar issues (including closed ones)
* [y] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Hello,

I'm trying to install and falling at the first hurdle. I've now tried on 2 x different PCs running Ubuntu 24.04 and one other machine using dietpi (based on Debian 12). One installation of Ubuntu and the dietpi installation are both fresh installs.

I might be doing something wrong so please advise if that's the case. Thanks.

Following the first step in the documentation to install on Docker, I have copied the _librephotos.env_ to _.env_ and created the directories needed. Next, I try running 

> docker-compose up -d

These are the messages I get back:
**Ubuntu:**
`ERROR: A service can not depend on itself: db`

**Dietpi (Debian 12):**
`dependency cycle detected: db -> db`

## 🔁 How can we reproduce it:
Attempt to install on Ubuntu or Debian.

## Please provide additional information:
- 💻 Operating system: Ubuntu 24.04
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: current
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: n/a
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
This was introduced by recent changes, and I just reverted them. Please pull this librephotos-docker with git again and try again :)

**Comment by tarmacalastair** [comment]
Thanks. All working now.
