### ISSUE TITLE
Refactor geocoding to use geopy instead

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#150]
[Geopy ](https://github.com/geopy/geopy) is a libary which has multiple reverse geocoding apis implemented. This could make our code simpler and more robust.

**Comment by derneuere** [comment]
Related to #143 and #9

**Comment by derneuere** [comment]
I think this is the way to go. I will close the other tickets.

**Comment by derneuere** [comment]
location.raw should have all the data we need:
https://towardsdatascience.com/things-to-do-with-latitude-longitude-data-using-geopy-python-1d356ed1ae30

**Comment by derneuere** [comment]
This here looks also promising: https://photon.komoot.io/

**Comment by derneuere** [comment]
This is now implemented, thanks to @sickelap :)

**Comment by NachtigallersLehrling** [comment]
@derneuere Does this mean Mapbox is no longer required?
My Places are empty and the [Docs](https://docs.librephotos.com/docs/user-guide/places) still refer to Mapbox as only solution. I am on 2025w35-amd64.

**Comment by derneuere** [comment]
The default is now photon and should work without any api keys :)

**Comment by NachtigallersLehrling** [comment]
Ah, thanks.
I now found the menu to select this. Since i switched from Photon to OSM it works as expected :)
The Docs still claim Mapbox is the only option, which caused some confusion
