### ISSUE TITLE
Images still leaking between users (see also issue #453)

### ISSUE THREAD

**Issue by tarmacalastair** [LibrePhotos/librephotos#1501]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I have created the fist-time user, logged in, and created an additional user but then the two users can both see each other's photos. 
In the documentation, the description for managing multiple users is unclear. It mentions changing the scan path but not how to do this. So, on first use, if you log in immediately after creating the first-time user and create user number 2 and then try to modify this user's path, there are no other paths available, nor is there any option within the admin area to create a new path.

Please can you advise on the best way to keep each other's photos private? Is it possible to add multiple picture locations in the _.env_ file? Or should I manually create additional subfolders in the filesystem before launching the docker container? Or is this something that I have missed with the user interface? If not, could it be added at some point?

At the moment, I'm really not sure how I can set up Librephotos so that more than one user can use the same server but keep their photos private.
Thanks and apologies if I've missed something.

## 🔁 How can we reproduce it:
Install using _git clone_ as per documentation for docker
Copy _librephotos.env_ to _.env_
Do not modify _.env_ at all (leave _scanDirectory=./librephotos/pictures_ and _data=./librephotos/data_ as per defaults)
Issue _docker-compose up_
Create user1, set directory to _/data_ (the only option available)
Create user2, set directory to _/data_ (the only option available)
(Still logged in as user1) Upload 1 photo
Switch to a different browser and log in as user2
Upload 1 photo
On both browsers while logged in to each browser as a different user, rescan the folder
Both photos are visible to each user

## Please provide additional information:
- 💻 Operating system: Ubuntu 24.04
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):  n/a

**Comment by derneuere** [comment]
In LibrePhotos, the file system acts as the definitive source of photo organization. This means that folder structure dictate how photos are grouped and accessed within the application.

To isolate users and their photo collections, create separate subfolders for each user on your host system (e.g., /data/user1, /data/user2, etc.). Then assign each user their respective subfolder as their scan directory in LibrePhotos. This ensures that users only see and interact with the photos in their designated directories.

If multiple users are assigned the same scan directory (e.g., /data), all photos within that directory will be accessible to all users. LibrePhotos treats the directory as a global source of photos, meaning that every user linked to the directory will see all its contents.

While the application saves metadata (e.g., tags, albums, facial recognition data) on a per-user basis in its database, it doesn’t inherently restrict access to the photos themselves. Access permissions must be managed through the file system / paths.

EDIT: The separation will also not keep the photos "private" as the admin of the host system can see all the images.

**Comment by tarmacalastair** [comment]
Thanks, that's a useful and comprehensive explanation. However, none of this is mentioned in the docs. Would it be possible to update the page? In fact, I've just tried to update it with your wording. I've never attempted this so please let me know if it's OK with you.

Also, do the file permissions of the manually created folders need to be the same as those created by the application, ie _drwxr-xr-x root root_ ?
Thanks

**Comment by derneuere** [comment]
Any contributions to improving the documentation would be greatly appreciated! Due to juggling multiple tasks on this project, I’ve had limited time to focus on documenting everything thoroughly.

The current documentation regarding file and folder access can be found here: [FAQ](https://docs.librephotos.com/docs/user-guide/faq#videos-are-not-playing-and-showing-a-404-error). However, please note that it might be outdated. Testing may be required to confirm the accuracy of the information provided.
