### ISSUE TITLE
Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by M4RC02U1F4A4** [LibrePhotos/librephotos#152]
```
Invalid HTTP_HOST header: '172.18.10.40'. You may need to add '172.18.10.40' to ALLOWED_HOSTS.
Bad Request: /api/sitesettings/
```
How can i had this host to the ALLOWED_HOSTS list?

**Comment by derneuere** [comment]
What os are you using? Did you use the sample docker-compose.yml or do you have a custom setup? 

It sounds like something you have to set in your system.

**Comment by M4RC02U1F4A4** [comment]
I'm using Unraid
The only difference with the default setup was to modify the hostname, with the IP, in the `nginx.conf` in the proxy container

**Comment by M4RC02U1F4A4** [comment]
My strange setup is connected to #61

**Comment by derneuere** [comment]
We now provide an Unraid Template see #276 
This should simplify your custom setup and remove this issue :)
