### ISSUE TITLE
I think LibrePhotos just crashed my server

### ISSUE THREAD

**Issue by FunDeckHermit** [LibrePhotos/librephotos#153]
I have LibrePhotos running in a docker container and while connected to the box by SSH suddenly got disconnected. The machine has 8GBs of RAM and running an i5-8250u. 

The box had to be rebooted by holding the power-on button. Checking journalctl -r -b -1 determined this:

```
jan 28 20:24:57 roy-SERVER kernel: oom_reaper: reaped process 474878 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
jan 28 20:24:57 roy-SERVER kernel: Out of memory: Killed process 474878 (python) total-vm:6544688kB, anon-rss:3913448kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:9392kB oom_score_adj:0
jan 28 20:24:57 roy-SERVER kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/d3e31e594b63d9b5fc939dd42cd3864ff90c03726f11f58>
```

Do you have a memory leak somewhere? I was scanning photos.

**Comment by derneuere** [comment]
How many workers do you have? Do you have a very large picture? Both could cause a spike in ram usage.

**Comment by FunDeckHermit** [comment]
Just the default of 2 workers. 
My pictures are not massive, all below 10MB. 

I just installed librephotos and am still scanning them all for the first time. It has taken me about four days to scan all 50000 photos. The task seems to stall after a couple of hours so I stopped the scanning an restarted it. 

It might be that some resources are not being releases/destroyed after I stop the scan.

**Comment by jcobreros** [comment]
You know what? I think it did the same to my unRaid server.
8GB of RAM
2 workers

Lost all remote access and services. Will check when I get home

Update: Never mind. My modem crashed.

**Comment by derneuere** [comment]
If this error occurs again and when you have some steps on how to reproduce the error, then please reopen the ticket.
