### ISSUE TITLE
Setting for timestamp parsing

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#154]
Some people only want to use EXIF Metadata to set the date and others want it to be parsed from the timestamp. Others also want [EXIF GPS date/time to be used](https://github.com/hooram/ownphotos/issues/35)

The easiest way forward to handle this is to add a setting on a per-user basis to decide which ones to use.

**Comment by darrepac** [comment]
Just a use case I am seeing right now:
A picture has no EXIF but  "file created" and "file modified" time stamp that are correct (or approximately correct, it was in 2006 so I don't remember precisely).
Google Photo place it in my time at the right time which seem to come from file modified/created timestamp
In LP, I don't have the photo in "timestamp" view :(

**Comment by derneuere** [comment]
https://github.com/LibrePhotos/librephotos/pull/413

**Comment by derneuere** [comment]
It's now implemented!
