### ISSUE TITLE
Nextcloud Linking - Unable to add directory

### ISSUE THREAD

**Issue by cohenchris** [LibrePhotos/librephotos#155]
I am hosting LibrePhotos using the recommended docker-compose method. I have added a new app password, entered NextCloud credentials, and it says that I am logged into NextCloud. However, when I attempt to change the NextCloud scan directory, I cannot get it to save the directory. A notification pops up saying "admin's information was successfully updated". When I reload the page, though, it resets itself. I have looked through other issues, and find nothing similar.

[ownphotos.log](https://github.com/LibrePhotos/librephotos/files/5898642/ownphotos.log)

**Comment by derneuere** [comment]
Found the error. Fixed it. Please do a docker-compose down and a docker-compose pull and then a docker-compose up.

After you added your credentials, wait for a view seconds. The red circle should switch to green like here:
![image](https://user-images.githubusercontent.com/6658807/106380094-5700db80-63b0-11eb-9824-1d2f6cd980db.png)
Click on change, then select a directory:
![image](https://user-images.githubusercontent.com/6658807/106380114-6f70f600-63b0-11eb-8128-02026a441ce2.png)

Reminder: It will download your pictures from your nextcloud instance. If you use the same server to host librephotos and nextcloud, it makes more sense to point librephotos at the directory than link nextcloud.

**Comment by ImmortalScientist** [comment]
Yep, I had the same issue - did a down->pull->up and it went away :) Thanks @derneuere
