### ISSUE TITLE
Can't select multiple images via holding shift 

### ISSUE THREAD

**Issue by Linda-uwu** [LibrePhotos/librephotos#156]
When trying to select multiple images via holding shift, only the starting pic is actually being selected.

**Comment by derneuere** [comment]
This is currently only implemented in the faces view. Where did you want to select multiple images?

**Comment by Linda-uwu** [comment]
I wanted to select multiple pictures from "Photos" to add them to an album.

**Comment by nothing2obvi** [comment]
Same here, please :)

**Comment by derneuere** [comment]
This is now possible in the latest build :)
