### ISSUE TITLE
Add a function to save captions when they are submitted by the user

### ISSUE THREAD

**Issue by tbrtje** [LibrePhotos/librephotos#159]
When trying to edit the caption of a picture, the submit button doesnt do anything. The captions are not saved and no confirmation is shown. When the generate button is used, a caption is successfully generated and automatically saved. But this caption can not be edited nor removed.
Logs dont show any activity besides caption generation.
This happens on the newest docker-compose examples.

**Comment by asenov** [comment]
I can confirm the same issue here

**Comment by chrisbeckstrom** [comment]
This still seems to be an issue. I'm running version 3.8 (at least that's what docker-compose.yml says). Entering text in the text field and clicking "submit" doesn't seem to do anything.
This seems like a pretty basic functionality for a photo management software - is there still no way to caption images? Thank you!

**Comment by meichthys** [comment]
I'm looking into this on https://github.com/meichthys/librephotos/tree/lihtbox_sidebar
I'm not familiar with react, so i need to play around with the front end a bit more to get things working.

**Comment by derneuere** [comment]
I think you can look at this file here to get a good idea on what to do: https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/components/lightbox/TimestampItem.tsx

**Comment by meichthys** [comment]
@derneuere , If we add a user-generated caption, we will have multiple caption types:

-  User generated
- Auto-generated via im2txt
 
My thoughts are to display the user-supplied caption on the Lightbox sidebar, and if a user caption doesn't exist, then display the auto-generated `im2txt` caption. This seems logical, but has a side-effect that the user would not be aware of the auto-generated caption that still exists after they supply their own caption. I suppose the user could re-click the "Generate" button which would re-generate the caption, at which point, we could clear the user caption so the auto-generated caption is displayed again?

**Comment by abdulasiraj** [comment]
start working.
