### ISSUE TITLE
Map is shifted

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#16]
This is probably frontend bug

Map is loading shifted:
![image](https://user-images.githubusercontent.com/30871217/101016321-e6347300-3568-11eb-93fd-d9ed82dd43a2.png)
Marker is in upper left corner:
![image](https://user-images.githubusercontent.com/30871217/101016379-ffd5ba80-3568-11eb-8a97-fad28d45c921.png)

**Comment by derneuere** [comment]
Comment by sim4city:

As for the map generated by Leaflet, the map view still loads at an offset (loading is still not centered) for me. It seems the map size and positions needs to be "invalidated" after the photo info panel is un-hidden.

Something like this should exist in the code after the panel is made visible: map.invalidateSize(true);

**Comment by derneuere** [comment]
as for map: https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/components/maps.js#L184

append the following to line 185:
const map = this.mapRef.current.leafletElement;
map.invalidateSize(true);

**Comment by derneuere** [comment]
Maybe the default zoom level for this component could be an adjustable setting under the "Appearance" section of the settings page: https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/components/lightBox.js#L483
