### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Outlet2048** [LibrePhotos/librephotos#165]
I can see that the Docker image is getting frequent updates which is great!
But is there a way to see some sort of changelog to see what exactly has been updated / changed / fixed?

Cheers!

**Comment by alexislefebvre** [comment]
It's not a changelog but you can view the list of commits: https://github.com/LibrePhotos/librephotos/commits/dev

**Comment by Outlet2048** [comment]
Thanks for the suggestion!
Sadly im not able to understand much but its definitely better than not knowing at all
