### ISSUE TITLE
Generate Event Albums fails on latest version

### ISSUE THREAD

**Issue by jcobreros** [LibrePhotos/librephotos#176]
ownphotos.log shows:
views.py : get : 1536 : ERROR : name 'generate_event_albums' is not defined

Running using docker-compose on a unraid system

**Comment by derneuere** [comment]
I pushed a new image, which should resolve this problem.

**Comment by Linecutterx** [comment]
Using the new image still results in "2021-02-28 16:03:41,154 : views.py : get : 1536 : ERROR : name 'generate_event_albums' is not defined"
The generate event button does bring up the "started" & "finished" notifications, but nothing is shown in the admin area logs.
