### ISSUE TITLE
Unable to set custom scan directory

### ISSUE THREAD

**Issue by thelittlefireman** [LibrePhotos/librephotos#18]
Hi,
First, a huge thanks you for saving this repo :) 

I don't find a way to change the "local scan directory" of users : 
log as admin, when I click on the edit icon it's just showing this message :

![](https://i.ibb.co/tDsnV6k/screen3.jpg)
Thanks

**Comment by sysoppl** [comment]
It works for me with the latest docker image
![image](https://user-images.githubusercontent.com/30871217/101277582-b9c16680-37b5-11eb-8f96-63cd7def270d.png)


Sometimes I have problem with showing pages like this when I left my adblock and popup blocker enabled. Maybe try other browser, or disable adblock or popup blocker If you have one

**Comment by thelittlefireman** [comment]
Thanks you're right :) disable adblock fix the pb
