### ISSUE TITLE
Feature request: Delete person

### ISSUE THREAD

**Issue by ishults** [LibrePhotos/librephotos#182]
Hi! Just started using the project, and I love the features available so far. One that would be helpful is the ability to delete/forget a person, so that any labeled or inferred images with that person are unlearned. 

I got carried away tagging people to train the face algorithm, but there are only a few photos of some people, yet now the algorithm keeps incorrectly tagging other photos as those people, and it's kind of annoying.

Thanks for the hard work, please let me know if there's anywhere to donate, too.

**Comment by tomamplius** [comment]
I means there don't need backend update
On backend side url  "api/labelfaces can be use with {"person_name":"unkown","face_ids":[<faceid>]}
Right?
In this case, remove button must be added on Frontend side in the labeled faces view to call.
Confirmation popup will be welcome

**Comment by tomamplius** [comment]
there is two ways :
 - Add unknow person on the popup where the person mae is select after click on the green + button
 - Add new button between + and trash to set selected faces to unknow
What is the good way?
