### ISSUE TITLE
Event albums are created & displayed, but only open a blank page

### ISSUE THREAD

**Issue by Linecutterx** [LibrePhotos/librephotos#184]
Latest version of the docker backend.
Creating auto albums succeeds, & titles + thumbnails are created.
Clicking on an album opens a page at domain/event/{event number} which shows a white screen.
Source is:
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/><style>.leaflet-container{height:250px;width:100%;z-index:2;position:relative}</style><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" href="/favicon.ico"><title>LibrePhotos</title><link href="/static/css/main.4af8163c.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="/static/js/main.18ad4de3.js"></script></body></html>

Logs don't seem to show anything at the point of opening the album & album creation/recreation logging looks OK to me.

**Comment by JoshLoecker** [comment]
I am also having these issues

**Comment by sushshring** [comment]
Any update on this?

**Comment by nowheretobefound** [comment]
I also have this issue. Any workaround ?

**Comment by derneuere** [comment]
It broke as soon as one person was in the event album. The reason was that the link was actually a router. But multiple nested Routers are not allowed. But anyway I fixed it!

**Comment by MurrayGroves** [comment]
> It broke as soon as one person was in the event album. The reason was that the link was actually a router. But multiple nested Routers are not allowed. But anyway I fixed it!

Could you elaborate on how you fixed it? I have the same problem.

**Comment by derneuere** [comment]
@MurrayGroves Here is the commit if you want to take a look https://github.com/LibrePhotos/librephotos-frontend/commit/b186d05ba918161b86fcefdc08504b2c8dd65b93

**Comment by MurrayGroves** [comment]
@derneuere thanks! If I pull the frontend container again will it be updated?

**Comment by derneuere** [comment]
Yes!
