### ISSUE TITLE
Unique key on albumthing need to be update to add thing_type

### ISSUE THREAD

**Issue by tomamplius** [LibrePhotos/librephotos#187]
Currently, the unique key on albumthing is based on title and owner_id.

        migrations.AlterUniqueTogether(
            name='albumthing',
            unique_together={('title', 'owner')},
        ),

but some title can be the same for different thing_type values 

Example : ocean can be "places365_attribute" or "places365_category"

**Comment by derneuere** [comment]
I agree. This will also become an issue if we also add other neural networks to LibrePhotos which could use similar names.
