### ISSUE TITLE
Add confirmation popup before delete face

### ISSUE THREAD

**Issue by tomamplius** [LibrePhotos/librephotos#194]
Add confirmation popup on inferred face on red been near the green +
Because some time i click on the bad button and face a deleted

**Comment by not-senate** [comment]
With this a deleted faces page that stores them for a few hours before deleting forever, or a undo button in the little message that pops up in the bottom right.

**Comment by tomamplius** [comment]
Sorry i don't understand?

**Comment by not-senate** [comment]
Oh I was just agreeing with you idea.

**Comment by derneuere** [comment]
This is now added :)
