### ISSUE TITLE
Live demo unavailable

### ISSUE THREAD

**Issue by fallingcats** [LibrePhotos/librephotos#196]
I case this isn't already known: The live demo seems to be unavailable, I am getting a `502 Bad Gateway` response from the webserver at `https://demo2.librephotos.com/`

**Comment by tomamplius** [comment]
I can hosting demo site if needed

**Comment by DigitalWarrior** [comment]
The demo server is currently hosted off the dev branch. It is currently undergoing maintenance / enhancements to allow auto building & deployment from dev code. Also enhanced logging that is held over across docker builds to help trouble shoot issues. Unfortunately real life work got in my way. I expect to have it back up as soon as possible.

**Comment by DigitalWarrior** [comment]
Demo is back up and running. If you notice that it is down just hit me up on our discord server [LibrePhotos Discord ](https://discord.gg/xwRvtSDGWb)
