### ISSUE TITLE
Why is the scan directoy not mounted read-only?

### ISSUE THREAD

**Issue by fallingcats** [LibrePhotos/librephotos#197]
I have tried to find out if librephotos will touch my scan directory in any way that is not reading, but I have not found an answer to that.
I assume from what I've read that the directory is not modified which begs the question why it is mounted as writable in the docker-compose file. Sorry if this is specified somewhere, buy I could not find anything definitive on this topic.

**Comment by tomamplius** [comment]
Maybe to allow upload in the future?

**Comment by fallingcats** [comment]
@tomamplius Do you know if I can be sure that existing files are not modified in any way, including modified or creation time?

**Comment by tomamplius** [comment]
@fallingcats : I have not check all the source code. But i can confirm that, there is not write on /data.
I don't know docker but i think you can change the read/write to read. And you can validated that application work without write on /data?

**Comment by fallingcats** [comment]
Thanks for the answer, I've made it read-only in my docker-compose file and everything seems fine.
I think I'll leave this open so somebody with knowledge of the inner workings of librephotos can add this to the docs.

**Comment by derneuere** [comment]
We currently only have one feature that writes to the scan directory or how it's internally called "data". When you download pictures from an Nextcloud instance the pictures will be download to your scan directory into the folder nextcloud_media/<username>/
