### ISSUE TITLE
Add "Download selected photos" button to frontend

### ISSUE THREAD

**Issue by JonathanBrose** [LibrePhotos/librephotos#198]
As a user i want to be able to export Photos from LibrePhotos. So i would suggest a download button on the right to download the selected photos.

**Comment by tomamplius** [comment]
Backend side : https://github.com/LibrePhotos/librephotos/pull/215
If someone can add Front-end function like that ( i think is copy paste and change url)
![image](https://user-images.githubusercontent.com/6951820/112725414-6ae03e00-8f18-11eb-8d38-45ff23783055.png)

**Comment by tomamplius** [comment]
@derneuere Frontend side on https://github.com/LibrePhotos/librephotos-frontend/pull/11

**Comment by derneuere** [comment]
This is implemented now thanks to @tomamplius :)
