### ISSUE TITLE
Publicly sharing pictures isn't working

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#20]
If you publicy share a photo it is not giving you a full link only something like "/media/thumbnails_big/a9c11224d9c4885c3eb04192ce4ba2d31.jpg"

If you try to open the url with the added baseurl you get an error in the frontend part:
![image](https://user-images.githubusercontent.com/6658807/101366249-05067280-38a5-11eb-8145-98816caed9f2.png)

Just sharing the link as a picture works.

**Comment by DigitalWarrior** [comment]
Possible fix in lightbox.js change row 270 serverAddress.replace('//','') + "/media/thumbnails_big/" + image_hash + ".jpg"  
to 
serverAddress+"/media/thumbnails_big/" + image_hash + ".jpg"

**Comment by DigitalWarrior** [comment]
Potential fix pushed to front end. @derneuere please update docker hub for widespread testing.

**Comment by derneuere** [comment]
Uploaded the docker image. lgtm

**Comment by ghost** [comment]
That fixed it on my end. lgtm

**Comment by DigitalWarrior** [comment]
Closed as Fixed
