### ISSUE TITLE
Is there a (minimal) doc somewhere on how to use?

### ISSUE THREAD

**Issue by darrepac** [LibrePhotos/librephotos#200]
Hello

Setup went smooth but I am not able to use it as I don't even understand the logic :)
Is there a minimal doc explaining how to scan the photo (it is written in the setup doc so I guess I did it well but nothing is really happening), what to expect, where can we see the progess (I see something on top but not sure if it is real as I still have 0 photos) etc

thx

**Comment by alexislefebvre** [comment]
Did you see that? https://github.com/LibrePhotos/librephotos#first-steps-after-setting-up

**Comment by darrepac** [comment]
> Did you see that? https://github.com/LibrePhotos/librephotos#first-steps-after-setting-up

yes but then I did not see anything for the rest.
Where can I see the progress?.... I end-up finding something but that doesn't move that much
Where are logs? (the logs folder is empty)
Is it normal that no photos is displayed after some minutes? (= does it wait to scan all the files before to display anything?)

Scanning but not progressing (the numbers do not move)
![image](https://user-images.githubusercontent.com/7128994/110829285-3a51a080-8298-11eb-9399-5750e13a2a01.png)

**Comment by derneuere** [comment]
It seems like it got stuck. Usually you should see the pictures after scanning. Does it show pictures when you click on "Photos -> No Timestamp"? Do you use a special directory like an network attached drive? We have some issues with these: https://github.com/LibrePhotos/librephotos/issues/167

**Comment by darrepac** [comment]
yes I do use a NAS (nfs mount)... I got no issue when I tried it with Photoprism... Will look into the other issue thread
