### ISSUE TITLE
Worker UI improvment

### ISSUE THREAD

**Issue by darrepac** [LibrePhotos/librephotos#201]
Hi,

It is may-be due to my screen resolution (1366x768) but worker UI is not lisible at all:
![image](https://user-images.githubusercontent.com/7128994/110930218-21dd9680-8329-11eb-8862-b890a10b369d.png)

**Comment by darrepac** [comment]
in my full HD screen, the same happen

**Comment by tomamplius** [comment]
duplicate with  #149?

**Comment by darrepac** [comment]
I think yes! did not see it before

**Comment by derneuere** [comment]
I will close this issue, because it is a duplicate :)
