### ISSUE TITLE
Scanning speed

### ISSUE THREAD

**Issue by darrepac** [LibrePhotos/librephotos#203]
Hi

After seeing the #167 , I put some of my photos in local in order to evaluate correctly Librephotos (same for media /thumbnails).
The scanner is now working since 6hours and it still has scanned less than 100 photos (77 to be exact!)
I am running it with ubuntu 20.04, i5 (@1.2GHz, need to solve it), 8GB Ram but the cpu is in average much below 50% on all the 4 cores... so it is very slow and not using full cpu, is it normal?
At this speed, it would take >5 months to scan all my photos!

**Comment by darrepac** [comment]
I cannot find a proper place to look at logs to see the progress of the scan.
Following command
```
docker-compose logs
docker-compose logs frontend
docker-compose logs backend
```
do not give info about the scan progress or I miss it

**Comment by tomamplius** [comment]
link with #17 and #151

**Comment by darrepac** [comment]
In fact my question behind is: where is the bottleneck
Scan is really slow
My photos are in local so I don’t think disk read/write is a limiting factor
My CPU is far from being at 100% (much less than 50% on each core)
So wondering where is the bottleneck...

**Comment by tomamplius** [comment]
@darrepac Can you add worker paramerter to test difference?

~~~
gunicorn --workers=4 --worker-class=gevent --timeout 3600 --bind localhost:8001 --log-level=info ownphotos.wsgi

**Comment by darrepac** [comment]
Sure, how?

**Comment by tomamplius** [comment]
You use docker? in this case i mean that you need to update the entrypoint.sh in the backend.
I sorry but i don't know docker

**Comment by darrepac** [comment]
Yes I am using docker... 
The purpose of my bugs entry is to make thing progressing positively. So for sure I am ready to test some things.

**Comment by darrepac** [comment]
If you know what to test within docker, tell me.
I have changed the scan folder (choose an upper level), hope it will not rescan pictures already scanned (should not happen with the hash system isn't it?)

**Comment by tomamplius** [comment]
You can use the pull request https://github.com/LibrePhotos/librephotos/pull/206
![image](https://user-images.githubusercontent.com/6951820/111825643-fdb12500-88e7-11eb-8c5c-f2909361f903.png)

**Comment by tomamplius** [comment]
@darrepac With last version you can test to add HEAVYWEIGHT_PROCESS=3 in https://github.com/LibrePhotos/librephotos-docker/blob/main/docker-compose.arm.yml ?
And inform us how time you win?

**Comment by darrepac** [comment]
> @darrepac With last version you can test to add HEAVYWEIGHT_PROCESS=3 in https://github.com/LibrePhotos/librephotos-docker/blob/main/docker-compose.arm.yml ?
> And inform us how time you win?

well I am a bit stuck with #167
and where do I add this parameter exactly?

**Comment by derneuere** [comment]
You have to add it to your .env file like in the example: https://github.com/LibrePhotos/librephotos-docker/blob/main/librephotos.env

**Comment by darrepac** [comment]
I add already `gunniWorkers=4`
What's the difference?

**Comment by derneuere** [comment]
The discussion now moved to #255
