### ISSUE TITLE
Can I view animated gifs?

### ISSUE THREAD

**Issue by CptanPanic** [LibrePhotos/librephotos#205]
Anyway to have animated gifs, or some other type of animated image show up in LP? I tried some animated gifs, and they are static.

**Comment by tomamplius** [comment]
Currently, all resize picture are store un jpeg.

**Comment by CptanPanic** [comment]
> Currently, all resize picture are store un jpeg.

Can you disable the resize feature?

**Comment by derneuere** [comment]
This should work now :)
