### ISSUE TITLE
Timeline view: add the date on the side

### ISSUE THREAD

**Issue by darrepac** [LibrePhotos/librephotos#207]
Hi

I am surprised to not find this request already so I may missed it.
As quite some people, I am looking for a google photo replacement, and a feature I miss in current LP version is to have a date timeline on the side in order to pick quickly an approximative date when I look for a photo.
![image](https://user-images.githubusercontent.com/7128994/111078785-7e8eac00-84f7-11eb-9634-75e6a5613367.png)

**Comment by 5m4u66y** [comment]
This is implemented in LibrePhotos/librephotos-frontend#133
This issue can be closed.
