### ISSUE TITLE
RAW-images are transferred with image/jpeg MIME type.

### ISSUE THREAD

**Issue by SolAstrius** [LibrePhotos/librephotos#226]
### What Operating system and version is LibrePhotos running on:
Debian

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### How is your picture library mounted on the host (or in the virtual machine):
Local file system (ext4)

### Description of issue:
RAW-images are transferred with image/jpeg MIME type, so it's impossible to directly download original file.

![image_2021-04-02_15-13-35](https://user-images.githubusercontent.com/70720738/113414969-df0e5c00-93c6-11eb-9e29-1dae7e9da018.png)

![image_2021-04-02_15-15-25](https://user-images.githubusercontent.com/70720738/113414968-df0e5c00-93c6-11eb-80fe-ee55374f58c1.png)

![image_2021-04-02_15-16-45](https://user-images.githubusercontent.com/70720738/113414964-dddd2f00-93c6-11eb-9312-ed782454f49b.png)

**Comment by derneuere** [comment]
This is correct and expected behavior. You only see a thumbnail of your image for compatibility reasons in the browser and not the file itself. The feature #198 is implemented, but I hadn't had the time to build a new frontend image and push it to docker hub.
