### ISSUE TITLE
Regenerate thumbnails for a photo

### ISSUE THREAD

**Issue by Pheggas** [LibrePhotos/librephotos#227]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.04 LTS

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false

    Container                     Repository                 Tag       Image Id       Size  
--------------------------------------------------------------------------------------------
pheggas_backend_1    reallibrephotos/librephotos            dev      35d02f0af826   4.252 GB
pheggas_db_1         postgres                               latest   88590756b124   314.3 MB
pheggas_frontend_1   reallibrephotos/librephotos-frontend   dev      03ff4507135c   1.32 GB 
pheggas_proxy_1      reallibrephotos/librephotos-proxy      dev      1a526b8f46c8   132.9 MB
pheggas_redis_1      redis                                  latest   7f33e76fcb56   105.3 MB

### Are you running LibrePhotos on a virtual machine if so please list:
yes, VMware.

### How is you picture library mounted on the host (or in the virtual machine):
Via Rclone - mounted GDrive.

### Description of issue:
So, i have bunch of photos in mounted folder from GDrive. Those photos are oriented in both directions, portrait and landscape. But as i started scan in Librephotos, after it finished, i found out it flipped most of the photos in wrong direction. Let's say portrait photos became landscape. Firstly i thought it supports only landscape photos so it flipped them but i wasn't right. One landscape photo has been flipped to be portrait photo. So i thought it wrongly generated only thumbnails but when i clicked on random photo, it showed in same way (flipped wrongly) even in "full screen mode".

### How can we reproduce it:
I think just freshly install latest build? I installed it via Docker after deleting old Ownphotos image from original project. You can maybe reproduce it this way.

#### Additional Information:

I didn't have this issue with that old Ownphotos image installed.

Due fact the logs include my personal information (where were photos taken etc.), i'll send those logs only to project contributors.

![unknown](https://user-images.githubusercontent.com/9994511/113854630-5f560800-979f-11eb-965b-33d18cae7b40.png)
![unknown1](https://user-images.githubusercontent.com/9994511/113854643-61b86200-979f-11eb-9ea5-2f4f00f14d80.png)

**Comment by derneuere** [comment]
We have to change how we rotate images. We have to use the function of wand / ImageMagick: https://docs.wand-py.org/en/0.5.7/wand/image.html#wand.image.BaseImage.auto_orient

**Comment by sysoppl** [comment]
Same for me, freshly added photos have random orientation sometimes
