### ISSUE TITLE
When viewing the Worker Status, the progress of scanning photos does not appear in the box

### ISSUE THREAD

**Issue by JoshLoecker** [LibrePhotos/librephotos#231]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [ ] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.04, Docker version 20.10.5

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker: 20.10.5
Docker compose: 1.28.2

### Are you running LibrePhotos on a virtual machine if so please list:
No

### How is you picture library mounted on the host (or in the virtual machine):
Local file system, ext4 format

### Description of issue:
When viewing the "Worker" status, in the top right of the web interface near the profile icon, the status of the photo scan does not fit properly into the box.
Example: [https://imgur.com/a/MsWcGFJ](https://imgur.com/a/MsWcGFJ)

### How can we reproduce it:
I am not sure. This has occurred since installation, and after a fresh install

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by tomamplius** [comment]
duplicate #149

**Comment by derneuere** [comment]
This is now fixed.
