### ISSUE TITLE
Worker process keeps being terminated due to signal 4

### ISSUE THREAD

**Issue by adan89lion** [LibrePhotos/librephotos#232]
# Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

When asking general "how to" questions:
- Please do not open an issue here join us on the Discord server  [LibrePhotos](https://discord.gg/xwRvtSDGWb)

**When Submitting please remove every thing above this line**

### What Operating system and version is LibrePhotos running on:
Synology DSM 7.0

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker 18.09.8

### If running via Docker or Kubernetes please list version including docker-compose:
Untouched from librephotos-docker repository:
```
# DO NOT EDIT
# The .env file has everything you need to edit.
# Run options:
# 1. Use prebuilt images (preferred method):
#   run cmd: docker-compose up -d
# 2. Build images on your own machine:
#   build cmd: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
#   run cmd: docker-compose up -d

version: '3'
services:
  proxy:
    image: reallibrephotos/librephotos-proxy:${tag}
    restart: always
    volumes:
      - ${myPhotos}:/data
      - ${proMedia}:/protected_media
    ports:
      - ${httpPort}:80
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${dbUser}
      - POSTGRES_PASSWORD=${dbPass}
      - POSTGRES_DB=${dbName}
    volumes:
      - ${dbLocation}:/var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0

  frontend:
    image: reallibrephotos/librephotos-frontend:${tag}
    restart: always
    depends_on:
      - backend

  backend:
    image: reallibrephotos/librephotos:${tag}
    restart: always
    volumes:
      - ${myPhotos}:/data
      - ${proMedia}:/protected_media
      - ${logLocation}:/logs
      - ${cachedir}:/root/.cache

    environment:
      - SECRET_KEY=${shhhhKey}
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${mapApiKey}
      - TIME_ZONE=${timeZone}
      - WEB_CONCURRENCY=${gunniWorkers}
      - SKIP_PATTERNS=${skipPatterns}
      - DEBUG=0

    # Wait for Postgres
    depends_on:
      - db

  redis:
    image: redis:6
    restart: always
```

### How is you picture library mounted on the host (or in the virtual machine):
Local system (via Docker bind)

### Description of issue:
After composing and getting the containers to run, I noticed that `librephotos_backend_1` container is constantly starting workers but keeps getting killed by signal 4 (SIGILL)
```
Running backend server...
production backend starting
[2021-04-09 18:46:47 +0000] [99] [INFO] Starting gunicorn 20.1.0
[2021-04-09 18:46:47 +0000] [99] [INFO] Listening at: http://172.27.0.6:8001 (99)
[2021-04-09 18:46:47 +0000] [99] [INFO] Using worker: gevent
[2021-04-09 18:46:47 +0000] [103] [INFO] Booting worker with pid: 103
[2021-04-09 18:46:59 +0000] [99] [WARNING] Worker with pid 103 was terminated due to signal 4
[2021-04-09 18:46:59 +0000] [124] [INFO] Booting worker with pid: 124
[2021-04-09 18:47:13 +0000] [99] [WARNING] Worker with pid 124 was terminated due to signal 4
[2021-04-09 18:47:13 +0000] [135] [INFO] Booting worker with pid: 135
[2021-04-09 18:47:23 +0000] [99] [WARNING] Worker with pid 135 was terminated due to signal 4
[2021-04-09 18:47:23 +0000] [146] [INFO] Booting worker with pid: 146
[2021-04-09 18:47:30 +0000] [99] [WARNING] Worker with pid 146 was terminated due to signal 4
[2021-04-09 18:47:30 +0000] [157] [INFO] Booting worker with pid: 157
```
Since the workers are being terminated after a few seconds, it is impossible to connect via the frontend and the proxy container.

### How can we reproduce it:
- Docker-compose the containers (after editing personal credentials and database settings)
- Load exposed port in browser
- Login page loads successfully but the login button isn't working (browser console indicates the requests are cancelled)
- Check Docker logs
- See an enormous log with `Booting worker with pid: n` and `Worker with pid n was terminated due to signal 4`

#### Additional Information:
The CPU and RAM usage of the backend was little, and no resource restrictions set for the containers.
I've reduced the Gunni Workers to 1 but no avail.

**Comment by deliantwo** [comment]
I think I have the same issue. It was really difficult to find more logs but I think I have found something about it in dmesg:
```
[1132542.797399] traps: gunicorn[30958] trap invalid opcode ip:7efc1604e9ba sp:7ffe58e21e60 error:0 in _dlib_pybind11.cpython-38-x86_64-linux-gnu.so[7efc16027000+86d000]
[1132544.051230] traps: gunicorn[30964] trap invalid opcode ip:7efc1604e9ba sp:7ffe58e21e60 error:0 in _dlib_pybind11.cpython-38-x86_64-linux-gnu.so[7efc16027000+86d000]
[1132546.120534] traps: gunicorn[30982] trap invalid opcode ip:7efc1604e9ba sp:7ffe58e21e60 error:0 in _dlib_pybind11.cpython-38-x86_64-linux-gnu.so[7efc16027000+86d000]
```
Is it related?

**Comment by derneuere** [comment]
The reason is, that you use pretty old CPUs or a Celeon /Pentium Gold J processor that don't support AVX. A user on discord was able to start the backend after he built the docker image himself.

**Comment by alexislefebvre** [comment]
Possible duplicate of #223

**Comment by adan89lion** [comment]
Yes, it's possible that the NAS's CPU is too underpowered to run photo / video conversion. I can confirm that LibrePhotos runs well on my PC.

It is not a problem of LibrePhotos anymore thus I'll close this issue.

@deliantwo I don't see these logs in the Docker logs section, maybe it's similar but not the exact same issue? Perhaps you can start a new issue.
