### ISSUE TITLE
Move window scrollbar only works for the first row

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#24]
This attempts to move the window scrollbar to the photo when clicking the arrow buttons in the photo viewer or keyboard keys and that is a good idea, however as implemented it only works correctly for the first row of photos in any day:
https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/layouts/%5C#L378-L391

**Comment by sysoppl** [comment]
What about replacing scrollbar with a timeline, something like in gphotos? Would be nice to scroll with visible year or month

**Comment by derneuere** [comment]
Seems to work now. Probably got fixed by reloading the picture to reframe it in the middle.
