### ISSUE TITLE
Refresh DB: Regenerate Thumbnails / Paths?

### ISSUE THREAD

**Issue by praul** [LibrePhotos/librephotos#241]
Hi, is there a possibility to regenerate thumbnails and update paths?
I have rotated some pictures and would like to update the thumbnails accordingly.

Also, I have moved some pictures around. Librephotos recognizes them from the hash, but does not update path accordingly

Any way to run these maintenance actions?

Thanks for your answer

**Comment by derneuere** [comment]
If you run a scan, the paths now get updated. It will also create the missing thumbnails.
