### ISSUE TITLE
Nginx rewrite to full resolution error

### ISSUE THREAD

**Issue by praul** [LibrePhotos/librephotos#242]
Hi, I'm running librephotos in docker, x64 on debian. 
When trying to view a full resolution image, I get an 403 error from nginx proxy

The log from the proxy indicates, there is an extra slash added that could cause this problem (/data//)?

`2021/05/01 06:22:10 [error] 29#29: *846 open() "/data//EingangPaul/IMG_20210424_153021.jpg" failed (13: Permission denied), client: 172.21.0.1, server: , request: "GET /media/photos/10727ab3958d92e57492ae8bd10278491.jpg HTTP/1.1", upstream: "http://172.21.0.4:8001/media/photos/10727ab3958d92e57492ae8bd10278491.jpg", host: "192.168.2.111:2344", referrer: "http://192.168.2.111:2344/"`

**Comment by derneuere** [comment]
I could not reproduce this error.
