### ISSUE TITLE
Only one of the scanning workers uses cpu

### ISSUE THREAD

**Issue by mvoggu** [LibrePhotos/librephotos#249]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Arch Linux

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
```
~ docker --version
Docker version 20.10.6, build 370c28948e
```
```
~ docker-compose --version
docker-compose version 1.29.2, build unknown
```

### Are you running LibrePhotos on a virtual machine if so please list:
No

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (ext4)

### Description of issue:
To reduce time taken for scanning newly added pictures, I set `HEAVYWEIGHT_PROCESS=8` in the .env file.
While scanning pictures, using _htop_ shows 8 processes running, but only one of the worker processes has a cpu usage of 100% and the other processes remain mostly idle(0% cpu usage).Also, only one of the cores is being used at 100%, while the other cores are kept idle. It doesn't seem like the best use of available processing power.
- Is this intended behaviour?
- How can I identify my bottleneck for scanning photos

### How can we reproduce it:
Run librephotos using Docker-compose method specified in README
But in .env, set `HEAVYWEIGHT_PROCESS=8` and `myPhotos` to path of directory containing pictures
Login as admin
In _Admin Area_, set _Scan Directory_ for admin as `/data`, 
In _Settings_ for the admin user, hit _Scan photos (file system)_
Using _htop_ or some other means, monitor the processes created, their cpu usage and the usage of each cpu core

#### Additional Information:

![Screenshot_20210513_183244](https://user-images.githubusercontent.com/50870617/118131626-61edf200-b41c-11eb-8ab1-5156bd047de1.png)

**Comment by derneuere** [comment]
It was apparently only ever tested with a local installation. I added the variable to the .yml file. It should now work.

**Comment by mvoggu** [comment]
Yes, seems to work correctly now. Thank you.

![Screenshot_20210519_150454](https://user-images.githubusercontent.com/50870617/118791150-13c16e80-b8b4-11eb-9b4c-64f4ee6ce085.png)
