### ISSUE TITLE
Auto scan for photos 

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#25]
Any chance to implement some kind of watcher that will watch for changes and start scanning for photos? Or just a script that can be executed in cron. Would be really nice feature.

**Comment by tintamarre** [comment]
I just found out that you actually can get a bear token:
`/api/auth/token/obtain/`
... and then launch scan workers:
`curl -H 'Accept: application/json' -H "Authorization: Bearer $YOURTOKEN" $YOURURL/api/scanphotos`

**Comment by tintamarre** [comment]
I wrote a small script to do it with cron.

```bash
#!/bin/bash
TOKEN=`curl -s -d "username=USERNAME&password=PASSWD" -X POST http://YOUR--URL/api/auth/token/obtain/ | jq '.access' | tr -d '"'`

curl -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" http://YOUR--URL/api/scanphotos
```

**Comment by sysoppl** [comment]
Great, thanks for advice

**Comment by tomamplius** [comment]
#204 Allow to create an other process in parallel of the backend process.

**Comment by sysoppl** [comment]
@tomamplius So, how I can do this when PR is already merged?

**Comment by derneuere** [comment]
Add this to you .env file: 

```
# Number of workers, when scanning pictures. This setting can dramatically affect the ram usage.
# Each worker needs 800MB of RAM. Change at your own will. Default is 1.
HEAVYWEIGHT_PROCESS=1
```

**Comment by tomamplius** [comment]
on docker in don't know if cron is install
after add on /etc/cron.d/librephotos-scan
with bellow content
~~~
0 0 * * * root cd /code && python3 manage.py scan
~~~
It will be scan at 00:00
~~~
# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,>
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
~~~

**Comment by sysoppl** [comment]
For docker it will be
`sudo docker exec --user root CONTAINER_NAME python3 manage.py scan`
after a while it reports warning:
```
System check identified some issues:

WARNINGS:
api.Face.person_label_is_inferred: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
```

**Also, in admin area it seems that scan start just for one user, rest is ignored**
![obraz](https://user-images.githubusercontent.com/30871217/114240805-73109280-9988-11eb-940f-fd1125cf2a11.png)

**Comment by sysoppl** [comment]
Good. Now it's working fine

@derneuere  maybe you should add to readme or somewhere information about how to exec auto scan?
```
sudo docker exec --user root CONTAINER_NAME python3 manage.py scan
```
example cron
```
# Every day at 3 AM
0 3 * * * sudo docker exec --user root CONTAINER_NAME python3 manage.py scan >/dev/null 2>&1
```

Thanks for implementation!

**Comment by mariomare22** [comment]
What about periodic scan of nextcloud folder? is there a way to implement it?

**Comment by tomamplius** [comment]
PR  #246 allow use the same command to scan local folder or nextcloud photos

**Comment by dashixdot** [comment]
> For docker it will be `sudo docker exec --user root CONTAINER_NAME python3 manage.py scan` after a while it reports warning:
> 
> ```
> System check identified some issues:
> 
> WARNINGS:
> api.Face.person_label_is_inferred: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
>         HINT: Use BooleanField(null=True) instead.
> ```
> 
> **Also, in admin area it seems that scan start just for one user, rest is ignored** ![obraz](https://user-images.githubusercontent.com/30871217/114240805-73109280-9988-11eb-940f-fd1125cf2a11.png)

直接运行`docker exec --user root CONTAINER_NAME python3 manage.py scan`会提示错误，查了发现是环境变量SECRET_KEY没有设置，不知道是不是我设置错误。
后来写了一个powershell脚本，成功运行了
`$secret_key=(docker exec CONTAINER_NAME bash -c "python3 manage.py shell -c $'from django.core.management.utils import get_random_secret_key\nprint(get_random_secret_key())'")`
`docker exec CONTAINER_NAME bash -c "export SECRET_KEY='$secret_key' && python3 manage.py scan && export SECRET_KEY=''"`

**Comment by derneuere** [comment]
@dashixdot It should just work. This sounds like a new error. I created an issue for it: #550

**Comment by huangda1982** [comment]
I think that if scan API could take a argument specifying which subdirectory to scan. So that people can combine this API with some filesystem changing monitor to do autoscan. A full scan takes a lot time.
