### ISSUE TITLE
semantic image search

### ISSUE THREAD

**Issue by flozi00** [LibrePhotos/librephotos#250]
**Describe the enhancement you'd like**
semantic image search

**Describe why this will benefit the LibrePhotos**
searching images by description

**Additional context**
openai published CLIP which is trained on Image and text, so it's possible to do zero shot classification or semantic search by vector similarity

**Comment by flozi00** [comment]
I took a look into the code and saw that you already do verctor search for similar images
J think it should be easy replacing the resnet model with clip model and adding text as search input too.
Where to do so ?

Furthermore I'd like to add tesseract ocr, but don't know where's the right place to do so too.

**Comment by derneuere** [comment]
You probably want to change this API Endpoint: https://github.com/LibrePhotos/librephotos/blob/e73c44cc118b3f61459700883d2d1b71308b8ea0/ownphotos/urls.py#L170-L173

Which would be this view: https://github.com/LibrePhotos/librephotos/blob/e73c44cc118b3f61459700883d2d1b71308b8ea0/api/views.py#L202-L223

You probably want to save the encoding / text once and the search of it on demand, right?
You would need to add a couple of new fields here: https://github.com/LibrePhotos/librephotos/blob/dev/api/models/photo.py

You can add it either to this function: https://github.com/LibrePhotos/librephotos/blob/e73c44cc118b3f61459700883d2d1b71308b8ea0/api/models/photo.py#L104-L128

Or you could write your own function and then call it in the scan process here: https://github.com/LibrePhotos/librephotos/blob/e73c44cc118b3f61459700883d2d1b71308b8ea0/api/directory_watcher.py#L95-L103

Do you know how much resources  this algorithm needs and how fast it is?
If it is to ressource heavy, you could also implement this object detection and classification: https://github.com/LibrePhotos/librephotos/issues/54

When we use mobilenet, it should work fast on any machine and we could take the labels to search semantically over it.

**Comment by flozi00** [comment]
https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/image-search/Image_Search.ipynb

Here is an easy to use example of clip
Locally its pretty fast with in memory search

**Comment by flozi00** [comment]
> You probably want to save the encoding / text once and the search of it on demand, right?

There is no text to save
The image gets encoded into vector / tensor, this gets stored in database

While searching the query / text get's encoded as vector too and the similar image vectors get searched

Would be adding tesseract OCR to photocaptions ok ?

**Comment by derneuere** [comment]
Alright, sounds similar to the image_similarity algorithm we use. I think you would then add the clip_encoding as field to photo and calculate them when scanning.

You would need to figure out how to display the result of the query. You have to merge the results of the search over captions with the clip results.

If you want to add Tesseract OCR, I think it would be better to use a new field for the results. For example you could name it tesseract_captions. We already have an issue for that here: https://github.com/LibrePhotos/librephotos/issues/228

**Comment by flozi00** [comment]
I would go by cosine similarity
If bigger than x display before caption results
locally with cosine similarity 0.27 was good score to match exactly the images I wanted to

It's hard for me to understand the structure of code at the moment
If I give you working functions you only have to call to receive OCR texts or vectors, could you add the feature then ?

**Comment by flozi00** [comment]
Wow 
I installed right now and it's pretty cool
With CLIP search + OCR I think it's competive to most proprioritary solutions
I like the face recognition solution, to train own modell

**Comment by flozi00** [comment]
You can play around with this demo
https://helios-rkouye.vercel.app/
Pretty cool, powered by CLIP and elasticsearch

**Comment by derneuere** [comment]
I don't have a lot of time at the moment, but you could start with the functions and then I could maybe add it in the future.

**Comment by derneuere** [comment]
We now have that feature :)
