### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by derritter88** [LibrePhotos/librephotos#251]
**Describe the enhancement you'd like**
Include GPU capabilities for faster progress - e.g. Nvidias docker support.

**Describe why this will benefit the LibrePhotos**
Image tagging, face recognition, etc. would work much faster if those process would be done via a GPU.

**Comment by guystreeter** [comment]
Accessing a GPU from within a container is quite complicated. Doing the recognition in a local install would simplify this.
I think it would be great to support a remote recognition server, or perhaps a way to put the backend on a more powerful system. The web server doesn't need as much processing power as recognition does.
It would keep costs down for people running `librephotos` on a cloud server, if they only had to spin up a recognition server when new photos are added.
The face recognition app for Nextcloud has some experimental support for this. See
[here](https://github.com/matiasdelellis/facerecognition-external-model)

**Comment by polaroidkidd** [comment]
Is it really that difficult? As far as I remember you can load the Nvidia docker container, check if GPU support is present and run the models on that if it is, otherwise continue with the CPU. I haven't looked at this in a long time so I might be completely off base here.

I can see how having an external recognition/training server would be a major refactoring. It would need its own APIs, you'd have to link the existing code bases to them.... And a lot more

**Comment by guystreeter** [comment]
Here's the latest user doc from NVIDIA:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/user-guide.html#user-guide
It seems not as complicated as it used to be, and supports more container types, but it still isn't simple.

**Comment by polaroidkidd** [comment]
well, since I just managed to install a GPU on my server I'm going to spend some time on this. I think it would greatly speed up some of the training tasks.

**Comment by derneuere** [comment]
Places365, clip and face_recognition will definitely benefit from this. Not sure about imagemagick and libvips. You usually just have to set a flag like this here:

https://stackoverflow.com/questions/63302534/how-to-write-torch-devicecuda-if-torch-cuda-is-available-else-cpu-as-a-f

Maybe you also have to recompile dlib for face_recognition. EDIT: Found the line, it's this here: https://github.com/LibrePhotos/librephotos-docker/blob/0a644863bc5b12edba66fcabd1185bccc24ef732/backend/base/Dockerfile#L100

Setting the flag in the correct place and creating a docker file for GPU should be all that is needed :)

**Comment by scepterus** [comment]
So will the docker file be updated?

**Comment by DigitalWarrior** [comment]
@scepterus soon, there probably would be an additional docker image one with GPU and one without. Docs will need to be updated also for that install. 
@polaroidkidd Would you like to take on this issue as you said you where going to be doing the testing? If so can you ping me on Discord .digital_warrior

**Comment by scepterus** [comment]
Why make 2 docker images if it's just a flag in the docker file?

**Comment by derneuere** [comment]
It's only a flag on the application level, but not on the deployment level. As stated before, you have to use an nvidia container, use the gpu version of pytorch and recompile dlib. 

If you feel like this is something you could do, feel free to work on it :)

**Comment by polaroidkidd** [comment]
@derneuere yeah, I'll get it sorted this weekend and will shoot you a MR. Ideally we could package the applications once and then throw it on two different images instead of building the whole thing twice, bit I'll start out with the "easy" way and see where that goes. I wonder if we require different settings in the admin panel... I guess I'll find out

**Comment by scepterus** [comment]
Would it not be easier to have the section in the dockerfile have an option to build this or this? So if you want GPU support remove this part, and if you don't have GPU remove the other part?

**Comment by derneuere** [comment]
There is now an image called librephotos-gpu, which provides cuda support :)

**Comment by guystreeter** [comment]
That's great, thanks for doing it. Does this replace the backend? Can we run it on a different server than the rest of librephotos? I still need a solution for the case where librephotos in on my externally-accessible server, which is under-powered for image recognition.

**Comment by derneuere** [comment]
The backend acts as a monolith and will probably stay like that. 

But you could try hosting two librephotos backends which are connected to the same db, but run on different machines. The lightweight one could handle api requests and the heavyweight one could handle the workers. Not sure, if that works, but it's an idea you could try.
