### ISSUE TITLE
Demo Server error

### ISSUE THREAD

**Issue by graemearthur** [LibrePhotos/librephotos#253]
Error when trying to login:

No connection to backend server, try again in a few minutes.

**Comment by MurrayGroves** [comment]
Same here

**Comment by Nerodacles** [comment]
It's for anyone, i think, it's the same thing that happened to me, delete the database, and re-install the db!

**Comment by DigitalWarrior** [comment]
Looking into the issue and will have resolved today.

**Comment by DigitalWarrior** [comment]
Updated to recent code base and made a change to the auto wipe and rebuild. Hopefully it does not hang any more during that process.
