### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by WesSec** [LibrePhotos/librephotos#254]
First of all, thank you for this software, you guys are doing a great job and we benefit a lot from your hard work!

**Describe the enhancement you'd like**

For all my selfhosted stuff, a mariaDB is already in use for the different applications, it would be awesome of librephotos was also capable of using the mysql backend. I know Django supports it, but it's not included in the package. Spinning up another database causes extra overhead.

**Describe why this will benefit the LibrePhotos**

More configuration options will please a lot of users who are in the same situation as me.

**Comment by derneuere** [comment]
At this point, I will not implement this. Maintaing two databases will cause extra development and debugging time, while only saving a negligible amount of RAM.

**Comment by yuduobing** [comment]
> At this point, I will not implement this. Maintaing two databases will cause extra development and debugging time, while only saving a negligible amount of RAM.

The most important thing is that MySQL is easy to backup, as data is priceless。hope LibrePhotos can use mysql

**Comment by avibrazil** [comment]
I would need MariaDB support too as I have limited compute resources and MariaDB is already in use.
