### ISSUE TITLE
DB error during API call on backend

### ISSUE THREAD

**Issue by sushshring** [LibrePhotos/librephotos#256]
## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Debian on WSL

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
3.8

### Are you running LibrePhotos on a virtual machine if so please list:
WSL

### How is you picture library mounted on the host (or in the virtual machine):
Windows FAT

### Description of issue:
API error during DB access from backend while loading after recent update

### How can we reproduce it:
I updated the Librephotos version to the latest using docker and restarted my containers. After the backend container came back up, any API call it it throws the error: 
```
django.db.utils.ProgrammingError: column api_photo.image_paths does not exist

LINE 1: SELECT "api_photo"."image_paths", "api_photo"."image_hash", ...

^

HINT: Perhaps you meant to reference the column "api_photo.image_path".
```
More information included in zipped log including stacks
[librephotos_error.log](https://github.com/LibrePhotos/librephotos/files/6549143/librephotos_error.log)

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by sushshring** [comment]
Adding docker compose file for reference. Is this due to a postgres update and Librephotos depends on a specific postgres version?

```
networks:
  public:
    external: true
  librephotos:
services:
  backend:
    restart: always
    depends_on:
    - db
    environment:
      ADMIN_EMAIL: ********
      ADMIN_PASSWORD: ********
      ADMIN_USERNAME: admin
      BACKEND_HOST: backend
      DB_BACKEND: postgresql
      DB_HOST: db
      DB_NAME: librephotos
      DB_PASS: ********
      DB_PORT: '5432'
      DB_USER: docker
      DEBUG: '0'
      MAPBOX_API_KEY: *******
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SECRET_KEY: *******
      SKIP_PATTERNS: ''
      TIME_ZONE: America/Los_Angeles
      WEB_CONCURRENCY: '2'
    image: reallibrephotos/librephotos:dev
    volumes:
    - /mnt/d/photos:/data:rw
    - /home/db/librephotos/media:/protected_media:rw
    - /home/db/librephotos/logs:/logs:rw
    - /home/db/librephotos/cache:/root/.cache:rw
    networks:
      librephotos:
        aliases:
        - backend
  db:
    restart: always
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
      -c random_page_cost=1.0
    environment:
      POSTGRES_DB: librephotos
      POSTGRES_PASSWORD: **************
      POSTGRES_USER: docker
    image: postgres
    volumes:
    - /home/db/librephotos/data:/var/lib/postgresql/data:rw
    networks:
      librephotos:
        aliases:
        - db

  frontend:
    depends_on:
    - backend
    image: reallibrephotos/librephotos-frontend:dev
    networks:
      librephotos:
        aliases:
        - frontend
  proxy:
    restart: always
    depends_on:
    depends_on:
    - backend
    - frontend
    image: reallibrephotos/librephotos-proxy:dev
    networks:
      public:
        aliases:
        - librephotos
      librephotos:
    volumes:
    - /mnt/d/photos:/data:rw
    - /home/db/librephotos/media:/protected_media:rw
  redis:
    restart: always
    image: redis
    networks:
    - librephotos
version: '3.8'
```

**Comment by derneuere** [comment]
I think the migration didn't finish. Are they any other errors in the command_migrate log? What happens if you do a complete stop and start again?

**Comment by derneuere** [comment]
Apparently calling models in migrations the usual way just doesn't work and django skips the migration without saying why. And it works when you use a new database.

Anyway I pushed a commit which should fix this. The build takes usually half an hour.

**Comment by derneuere** [comment]
Does it now work for you? 😅

**Comment by sushshring** [comment]
Yep its working!
