### ISSUE TITLE
Live demo not working

### ISSUE THREAD

**Issue by lselortondo** [LibrePhotos/librephotos#259]
Tried using the live demo with username "demo" and password "demo1234" but I get message saying "No connection to backend server, try again in a few minutes. 8:42:21 PM"

**Comment by DigitalWarrior** [comment]
Updated demo refresh script to match current configuration. 
Note: Changes to the .env or to the .yml are not automatically updated and will probably break the refresh script. 
Script is set to run ever two hrs. Will close after 24hr with no issue.

**Comment by david-pekrul** [comment]
I am still not able to open the demo site.
https://demo2.librephotos.com/login
```
No connection to backend server, try again in a few minutes.
10:23:24 PM (CST)
```

I am also having similar problems when I try and deploy this to my home server. 
I'm wondering if this problem is related to the DB errors on setup?
https://github.com/LibrePhotos/librephotos/issues/257#issuecomment-850606553

**Comment by derneuere** [comment]
@david-pekrul Did you configure your .env file? What CPU do you use? Can you post the log by starting just with docker-compose up?

**Comment by jakev383** [comment]
> I am still not able to open the demo site.
> https://demo2.librephotos.com/login
> 
> ```
> No connection to backend server, try again in a few minutes.
> 10:23:24 PM (CST)
> ```
> 
> I am also having similar problems when I try and deploy this to my home server.
> I'm wondering if this problem is related to the DB errors on setup?
> [#257 (comment)](https://github.com/LibrePhotos/librephotos/issues/257#issuecomment-850606553)

I had a similar problem when deploying the other day and ended up needing to add a couple of items for the postgres container in addition to those provided in the example compose YAML:
POSTGRES_USER
POSTGRES_PASSWORD
POSTGRES_DB

**Comment by DigitalWarrior** [comment]
Yay, added logging to the crontab, and it was having issues taking down the server. An update to the script has been made and should run in the next two hrs.

**Comment by DigitalWarrior** [comment]
Logs indicate refresh script is running correctly. Issue Closed.

**Comment by noriakisana** [comment]
demo currentyl down same error

**Comment by DigitalWarrior** [comment]
@JochenMehlich I was able to log into both demo servers. https://demo2.librephotos.com and https://demo1.librephotos.com
Can you verify you are not able to access either.

**Comment by Stifler6996** [comment]
Im getting same error with the Demo. no access to backend.
I also tried to deploy it locally (NOT Docker, Debian local install) and I get the same problem.
