### ISSUE TITLE
Frontend expects valid similar images when opening photo view

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#26]
This is not always the case because the image similarity index only gets build on startup and when it finished scanning. If you start with an empty database and start to scan 2000 images, than you can't while it still scan open pictures to look at them.

**Comment by atomicwrites** [comment]
At the very least a message that says you need to wait for the scan to complete would be nice, rather that an infinite loading spinner. I thought my installation wasn't working.

**Comment by robertcontois** [comment]
Do you have a screenshot of this or where you see the error/delay? Just trying to track down the path of the function calls.

**Comment by derneuere** [comment]
Start with a fresh database and initialize a long scan. While it is still scanning click on one of the photos. It will load forever and an error will be posted in the web console.
