### ISSUE TITLE
Add users in admin area

### ISSUE THREAD

**Issue by hwiorn** [LibrePhotos/librephotos#260]
**Describe the enhancement you'd like**
Currently, there is no option to add users in admin page. When I need to add a user in my LibrePhotos, I have to enable the sign-up feature and register the user, then disable the feature.

**Describe why this will benefit the LibrePhotos**
In a private LibrePhotos, Admin can add users without allowing user registration.

**Comment by jakekapellen** [comment]
I am actively working on this now. Feel free to "assign" me @derneuere.

My idea is to allow modifying, deleting, and adding users. I have the UI basically done on my local machine (the easiest part) and am working on the modal dialog to add/edit a user, likely a refactoring of the sign up page.

**Comment by derneuere** [comment]
I think you can probably just extend the view, that we currently use for changing paths. Sounds like a good idea to use the signup API for creating a new user 👍

**Comment by jakekapellen** [comment]
Update: I have the basics mostly working on the admin page (in my own fork). Adding new users, deleting users, and updating mostly works. There are some bugs to work out, but the UI is basically done.

I have the following work remaining:
- Fix a bug where you can't update users if they don't have a scan directory (I get a 400 error saying that the scan directory is required...)
- Try refactoring the password prompt into a new control so I can add it to the Settings page
- Update the non-admin update API so users can change their own password
- Test the initial setup page to verify that it works correctly
- Internationalize a bunch of new strings
- Loads of other testing and bug fixes, most likely

You are welcome to check out the progress if you would like. Either way, I'm hoping to open a pull request later this week.
