### ISSUE TITLE
Clicking on the scanning button twice "screws up" the library

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#266]
Report from this thread, that clicking twice breaks LibrePhotos: https://www.reddit.com/r/selfhosted/comments/npoxm4/librephotos_a_fork_of_ownphotos_with_video_support/h0712ot/

**Comment by DigitalWarrior** [comment]
I attempted this on the demo server last night and was unable to reproduce, can some one else verify that this is not an issue with the latest from docker-hub?

**Comment by josarsepi** [comment]
I can not reproduce this in the container I pulled down on Monday.

**Comment by derneuere** [comment]
Hmm. Maybe he opened two windows of LibrePhotos and clicked in each on scanning. Is this possible?

**Comment by DigitalWarrior** [comment]
It very well could be possiable. I will test later when I am back at a PC.
