### ISSUE TITLE
Reduce size of backend docker image

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#270]
The backend image has a size of 4.5GB and only 350MB are for the machine learning models. While all the dependencies will take up some space, it should be possible to reduce the size. The starting point would be to find a smaller base image.

This will make the first install faster and updating better.

**Comment by TripleEmcoder** [comment]
It's much worse: `reallibrephotos/librephotos            latest        e835971ab10d   2 weeks ago     8.4GB`
The reason must be bringing a very large base image: `FROM ubuntu:hirsute` and building stuff inside with `-dev packages`.

This should be fairly easy to fix for anyone aware of librephotos' dependencies and build process by bringing in a smaller base image (alpine?) and using [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) to only copy compiled binaries to the final image.

**Comment by derneuere** [comment]
Reduced it by half and I think this can be close now.
