### ISSUE TITLE
Add Directory View

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#271]
**Describe the enhancement you'd like**
At the moment the image path is saved, but there is not an easy way to look at all the images of a particular folder or path. We should implement a view that allows the selection of a directory, to then show all the images in the folder and subfolders.

**Comment by TheAnachronism** [comment]
Are there any news on this?

**Comment by jpslv** [comment]
I would love to see this feature implemented! I organize each album by folder, so it would be really useful to browse my folders.

**Comment by Typhonragewind** [comment]
This is the missing feature that would make me switch from PhotoPrism in a heartbeat

**Comment by davi024** [comment]
This is what I wanted to propose. Not only keeping the directory structure of my already created albums, but also being able to create new albums in this directory through LibrePhotos.

Summary:
- See the already created structure of my albums
- Save albums generated with LibrePhotos in my album directory

**Comment by jpslv** [comment]
Please! This is the only feature keeping me from using LibrePhotos!

**Comment by 5m4u66y** [comment]
Duplicate of issue #129

**Comment by derneuere** [comment]
True!
