### ISSUE TITLE
Worker-Status Window cut off

### ISSUE THREAD

**Issue by LLLOOOMMM** [LibrePhotos/librephotos#273]
## 🐛 Bug Report

* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.04.2 LTS

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker: 20.10.6
docker-compose: 1.29.2

### Are you running LibrePhotos on a virtual machine if so please list:
VM on vSphere 7

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB
Local (NTFS)

### Description of issue:
Worker-Status Window is cut off. See pictures below. Resizing the Browser-Window does not effect the issue. I found the issue in Firefox, Chrome and Edge.

### How can we reproduce it:
Log in to librephotos and hover over worker-status indicator

#### Additional Information:
![worker_window1](https://user-images.githubusercontent.com/37272717/121381498-0f81f180-c946-11eb-887c-141a227cbe81.JPG)
![worker_window2](https://user-images.githubusercontent.com/37272717/121381502-101a8800-c946-11eb-8c3f-45cf8c57ce06.JPG)

**Comment by derneuere** [comment]
This is now fixed.
