### ISSUE TITLE
Sharing with a normal user doesn't show user list

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#281]
When sharing a photo/album with a user thats not the default, it doesnt show the user list, it always shows a blank space.

![image](https://user-images.githubusercontent.com/29661633/122765459-85535a80-d26e-11eb-96cb-e659f0aeb6a2.png)
That screenshot is sharing with the default account, but if i try with one that isn't the default, i alway get this.

![image](https://user-images.githubusercontent.com/29661633/122765672-bfbcf780-d26e-11eb-84d0-61eac082c1de.png)

The "user list" never show a user.

**Comment by julien8765** [comment]
Same here, only the admin account can share an album with other users : non-admin users don't see the other users.

**Comment by derneuere** [comment]
This is now fixed.
