### ISSUE TITLE
Face labeling workflow: Retain "unknown" status for faces after face training

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#282]
Face training allocates *all* unknown faces to best guess candidates. 

Introducing a minimum confidence level would ensure that uncategorized faces could be selected

**Comment by jakekapellen** [comment]
Is this fixed by the migration to HDBSCAN? HDBSCAN relies on higher-density clustering, so it filters out noise points quite well.

**Comment by derneuere** [comment]
I think I will close these issue, as these should be fixed :)
