### ISSUE TITLE
Face Labeling workflow: Enable ability to click the "name" heading in Inferred view to confirm inferred face

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#283]
Enable ability to click the "name" heading in Inferred view to confirm inferred face

Current workflow to confirm inferred faces consists of:
1. select faces correctly inferred
2. click the plus button 
3. search or scroll to the SAME person that you're labeling faces for currently

improved workflow:
1. select faces correctly inferred
2. click "name" label at op right corner to confirm label

**Comment by stnokott** [comment]
Yes, one of the features I'm most interested in.
Small, but big impact, at least for me.

As an alternative to your suggestion to click the name to confirm, I'd also suggest simply adding a button next to the plus /delete buttons that assigns all currently selected faces to their inferred person.

**Comment by 5m4u66y** [comment]
Hi,
I just fixed issue #667 which addresses a similar user requirement. Please check if this can also be an accepted solution for this issue?

**Comment by ChrisFab16** [comment]
It seems like it would solve the issue, yes.
