### ISSUE TITLE
Library scan is very slow

### ISSUE THREAD

**Issue by SteveDevDev** [LibrePhotos/librephotos#288]
New Libre docker install.  I have about 30k photos on an NFSv4 mounted share.  I fed Libre a subset of these photos in the .env file (just 71 photos).  It has been running for 3 hours and has only gotten through 59 photos.  When I used a similar product someone suggested, Photoview, it was able to churn through the photos very rapidly.  Libre seems to have more features and better facial recognition features, so I'd like to use it.  I'm not sure what logs to provide.

**Comment by SteveDevDev** [comment]
Actually it seems to be hung.  I see this happening on #167 .

**Comment by derneuere** [comment]
Please provide the log files. You can find them under you specified folder for logs. I want the ownphotos.log file.

Could you also provide more information about your system? Which method did you use to install librephotos, which CPU are you using, which OS are you using etc.
