### ISSUE TITLE
librephotos-proxy has hard-coded hostnames for backend, frontend

### ISSUE THREAD

**Issue by ohthehugemanatee** [LibrePhotos/librephotos#290]
## 🐛 Bug Report

* [ N/A ] I am including my log files in zip format.
* [ x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:

 Ubuntu 20.04LTS node.

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Kubernetes

### If running via Docker or Kubernetes please list version including docker-compose:

k3s: 
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm"}
```
(k3s server is on arm, but the node that's running librephotos is x86 Ubuntu)

### Are you running LibrePhotos on a virtual machine if so please list:
No

### How is you picture library mounted on the host (or in the virtual machine):

NFS

### Description of issue:

If you are not using the precise`docker-compose` setup, the proxy will break. For example if you run your services under different names, or all accessible through localhost, or on kubernetes, the proxy breaks.

proxy log output:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/07/06 09:57:03 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:19
nginx: [emerg] host not found in upstream "frontend" in /etc/nginx/nginx.conf:19

```

### How can we reproduce it:

Change the hostname for the frontend in `docker-compose.yaml` to `frontend-foobar`.
OR
Run in kubernetes.
OR
Run the services all exposed on "localhost".

#### Additional Information:

proposed solution: populate the hostnames on the proxy with env vars.

related to #61

**Comment by ma-karai** [comment]
Proxy config needs to be added, in order to deal with this.

**Comment by derneuere** [comment]
You can change now your names with the make command.
