### ISSUE TITLE
Videos do not play

### ISSUE THREAD

**Issue by matteodelabre** [LibrePhotos/librephotos#292]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Debian 10.10

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Manually via instructions in <https://github.com/LibrePhotos/librephotos-linux>.

### How is you picture library mounted on the host (or in the virtual machine):
Local file system

### Description of issue:
Videos are properly indexed and appear in the pictures list, but when trying to play one I get an error. Specifically, the request for fetching the video returns a 400 HTTP error.

### How can we reproduce it:
Add a video in your data folder, run the scan, try to play it by clicking on it in the main page.

#### Additional Information:
I think this issue is caused by the fact that the `MediaAccessFullsizeOriginalView` view sends a response with a `X-Accel-Redirect` header that points directly to the absolute path of the video file. It should instead use the `/original` prefix so that the reverse proxy handles the request appropriately. Also, that header’s value needs to be URL-encoded, otherwise I get a 404 error with video files that contain non-ASCII characters. The following patch fixes the issue for me (but I’m not sending it as a pull request since I’m not sure it’s the proper way to fix the issue):

```diff
diff --git a/api/views.py b/api/views.py
index 8d7d5d9..a80e4e4 100644
--- a/api/views.py
+++ b/api/views.py
@@ -12,7 +12,7 @@ from constance import config as site_config
 from django.core.cache import cache
 from django.db.models import Count, F, Prefetch, Q
 from django.http import HttpResponse, HttpResponseForbidden
-from django.utils.encoding import force_text
+from django.utils.encoding import force_text, iri_to_uri
 from rest_framework import filters, viewsets
 from rest_framework.pagination import PageNumberPagination
 from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
@@ -1686,7 +1686,7 @@ class MediaAccessFullsizeOriginalView(APIView):
             filename = mime.from_file(photo.image_paths[0])
             response = HttpResponse()
             response['Content-Type'] = filename
-            response['X-Accel-Redirect'] = photo.image_paths[0]
+            response['X-Accel-Redirect'] = iri_to_uri(photo.image_paths[0].replace(ownphotos.settings.DATA_ROOT, "/original"))
             return response

     def get(self, request, path, fname, format=None):
```

**Comment by matteodelabre** [comment]
Note: I guess this error doesn’t happen with a Docker install, since the nginx route `/data` coincides with the data mount path.

**Comment by faizpuru** [comment]
I'm having the same issue with video (docker installation)

**Comment by derneuere** [comment]
@matteodelabre Thank you for debugging and fixing the problem. This solution also worked for the docker-compose setup :+1:
