### ISSUE TITLE
People album wrong photo and count

### ISSUE THREAD

**Issue by danielk117** [LibrePhotos/librephotos#30]
hi,

i have 459 photos scanned and 4 people with correct faces set.
the people-album shows me the following. all 4 images are false (like the car) and the photo count is wrong.

![grafik](https://user-images.githubusercontent.com/36566093/101977561-78660680-3c4e-11eb-8187-ab327a3f4091.png)

**Comment by derneuere** [comment]
LibrePhotos always tries to sort all faces to labels. Go to Dashboards -> Facerecogniton. At the top there is tab "inferred". There you can see what LibrePhotos thinks which face is who. If you don't have enough labels / unlabeled persons it will label persons wrong. Will fix the photo count. It is the actual count but squared...

**Comment by derneuere** [comment]
I created a new image. Please do a docker-compose pull and then a docker-compose up. It should work now. If it does close the issue :)

**Comment by danielk117** [comment]
> LibrePhotos always tries to sort all faces to labels. Go to Dashboards -> Facerecogniton. At the top there is tab "inferred". 

You're right. After "train faces", all photos was assign to one of my 4 people. But i deleted all wrong inferred photos. My screenshot was taken some time after the deletion.

Pulled your new build. The photo count is now correct. But the photos stays wrong.

**Comment by derneuere** [comment]
I can't seem to reproduce the error. Did you refresh the page after deleting the faces? LibrePhotos tends to cache a lot of data instead of loading it.

**Comment by danielk117** [comment]
yes, i think you're right. i checked the inferred photos again, restarted everything with compose and now the shown photos are right.
thank you!
