### ISSUE TITLE
Try additional fields for photo datetime

### ISSUE THREAD

**Issue by deviantintegral** [LibrePhotos/librephotos#300]
**Describe the enhancement you'd like**

Looking at: https://github.com/LibrePhotos/librephotos/blob/2963f447a3bdce978d5e5d0466e826176cd8abe0/api/models/photo.py#L225-L242

It appears that only the "Date/Time Original" is used when extracting the timestamp for a photo. So far, out of the 5000 photos I've indexed, it looks like 1/5th do not have that field, and only have the "GPS Date/Time" field. I'm not sure why this is - I've found photos from the same camera (a Nexus 6P) both having and missing the Original Date field.

Given that exiftool can extract many different date fields, including file creation or modification times, Librephotos should fall back to other available fields to ensure that photos have a reasonable date instead of "unknown".

**Describe why this will benefit the LibrePhotos**

If the above holds and we can assume that 10-20% of "real world" photos have incomplete data metadata, then improving this indexing will improve the experience for a significant number of users.

**Additional Information**

This may need to be a configuration option, especially if we fall back to filesystem timestamps.

**Comment by derneuere** [comment]
It's now implemented!
