### ISSUE TITLE
Public Link creates link to /media/photos/ instead of /media/thumbnails_big/ resulting in a 403

### ISSUE THREAD

**Issue by grasponcrypto** [LibrePhotos/librephotos#302]
## 🐛 Bug Report

* [NA] I am including my log files in zip format.
* [X] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.04  
Latest version of LibrePhotos  

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker-compose

### Description of issue:
Public image url generates incorrectly if created from the thumbnail as opposed to selecting the photo first, then creating the public url.  
incorrect: .example.com/media/photos/whatever.jpg
correct: example.com/media/thumbnails_big/whatever.jpg

### How can we reproduce it:
navigate to librephotos homepage, make any image public directly from there by hovering over the thumbnail, without first selecting the image.  The url generated will be incorrect and cause a 403.

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by derneuere** [comment]
This now works :)
