### ISSUE TITLE
Enable Redux DevTools

### ISSUE THREAD

**Issue by jmalm** [LibrePhotos/librephotos#303]
**Describe the enhancement you'd like**
I would like to be able to use Redux DevTools when developing librephotos-frontend, so that I can easily inspect the state and actions.

![image](https://user-images.githubusercontent.com/3975811/127279051-e0a26730-e9ac-4b78-93d4-590ebfc4ffd4.png)

It would require a small change to `store.js`:

```
@@ -20,12 +20,13 @@ const configureStore = (history) => {
         },
         rootReducer)
 
+    const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
     const store = createStore(
         reducer, {},
-        applyMiddleware(  
+        composeEnhancers(applyMiddleware(
             thunk,
-            routerMiddleware(history) )
-    )
+            routerMiddleware(history) ))
+    );
```

It would also be good to add information in the documentation on how to use this developer feature.

**Describe why this will benefit the LibrePhotos**
Being able to inspect the state really helps both new developers when trying to understand how the app is designed, and when making changes.

**Additional context**
I would be happy to create a pull request with these small changes (excluding documentation updates), but am unsure of what the process for that looks like. I assume that the PR should be connected to this issue in some way?

**Comment by derneuere** [comment]
Awesome, I didn't know that there were DevTools for Redux.

Either open up a pull request with a description on what the change does, or open up a separate issue with description of the problem and link it in the PR. When I understand what the change is supposed to do, I am able to review the change.

I merged your PR. Thanks for your pull request!
