### ISSUE TITLE
Add duration and a icon for videos in the bottom left corner

### ISSUE THREAD

**Issue by RandomHacks-Git** [LibrePhotos/librephotos#308]
I use librephotos mainly for videos and the previews are way too resource intensive to the point it's almost impossible to watch a video on firefox. Videos kinda play on chrome but the experience still isn't great with the computer fan going crazy.

I wish there was a setting to disable the previews or only play them on hover.
Not related to this issue but I would also like if the duration of the videos would be presented on the thumbnails.

Overall this is a nice alternative to google photos, just needs some polishing.
Keep up the good work!

**Comment by psydaddy** [comment]
It happens with me as well.
This new update make it almost impossible to use

**Comment by derneuere** [comment]
Play video previews only on hover is now implemented. I will rename the issue to better reflect the next step.

**Comment by RandomHacks-Git** [comment]
Beautiful! Massive performance increase for firefox users, the page is much more fluent now and videos play fine. Good job! 😉

**Comment by derneuere** [comment]
Video duration is now added together with an video icon
