### ISSUE TITLE
Preview/thumbnail size

### ISSUE THREAD

**Issue by trowj** [LibrePhotos/librephotos#309]
**Describe the enhancement you'd like**
Somewhere along the line, I suspect with the UI rework, the option to have BIG or SMALL thumbnails was lost. I know it's a personal choice, based on eyesight, monitor size, etc, but the current thumbnails are way too big. When before I could pick 'small' mode and see maybe 30 pictures on a page, I'm now stuck with 6 or 8.

**Describe why this will benefit the LibrePhotos**
More pictures on screen serves better the idea of a thumbnail, rather than a full-page review like the lightbox provides. 

**Additional context**
Screenshots attached, it's a big picture. I have a 22" monitor so you can see how big each preview is. For reference, I've also attached what Google photos looks like on my monitor - much smaller previews, personally of a size I find good but I could see being small for some people. It looks like Librephotos are roughly twice as tall as Gphotos, which means they take 4x screen real estate...

![Screenshot_BIG_thumbs](https://user-images.githubusercontent.com/7526864/128612494-c1765b60-3a70-4ebe-8435-bb3247b0e6ba.png)
![Screenshot_Gphotos](https://user-images.githubusercontent.com/7526864/128612497-8d674014-4c01-4722-8eb7-6cf0203370e1.png)

**Comment by derneuere** [comment]
If someone wants to implement it before me:
https://github.com/derneuere/react-pig/blob/8818ff625da16cade62733a4e9a3ad92ba0f3c16/src/utils/getMinAspectRatio.js#L15

You have to add a prop to react-pig for the setting "smaller thumbnails", and experiment with the minAspectRatio until you get a good-looking smaller setting.

**Comment by derneuere** [comment]
It's now implemented in react-pig. It now only has to be added as a field to the user model and to be exposed in the frontend as a slider.
