### ISSUE TITLE
Photos not centering when info panel is opened

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#31]
Horizontal photos are not centering when info panel is opened:
![image](https://user-images.githubusercontent.com/30871217/101989039-e5ed5380-3c9d-11eb-9302-c4b0bd377d3e.png)
![image](https://user-images.githubusercontent.com/30871217/101989042-eab20780-3c9d-11eb-98f9-3c7ffa4855ab.png)

It is working ok with vertical photos:
![image](https://user-images.githubusercontent.com/30871217/101989160-d0c4f480-3c9e-11eb-8e3b-6dfd11b27c95.png)

Also, after opening info panel and switching to next photo, there is a fragment of next photo visible at the left and sometimes right, this does not occur when I don't touch info panel.

**Comment by derneuere** [comment]
Which browser are you using?

**Comment by sysoppl** [comment]
Chrome  87.0.4280.88, without any adblockers

---
Same for Firefox 83.0

**Comment by sysoppl** [comment]
Similar problem on phone, this time photo is very small (white box) after closing info panel
![obraz](https://user-images.githubusercontent.com/30871217/102715040-db047580-42d2-11eb-9950-7ca647dd3db5.png)

**Comment by derneuere** [comment]
I pushed a new docker image. It should work now. Does it resolve your issue?

**Comment by sysoppl** [comment]
Yes 😀
