### ISSUE TITLE
Write favorited / rating to photo metadata

### ISSUE THREAD

**Issue by jmalm** [LibrePhotos/librephotos#310]
**Describe the enhancement you'd like**
When a user marks a photo as favorited (or, in the future, sets a -1 - 5 rating), write this metadata back to the original photo or to an XMP sidecar file so that the information can be used in other software.

**Describe why this will benefit the LibrePhotos**
Photographers often use several applications as part of their own photography workflow. This enhancement will make it easier to use LibrePhotos as part of different workflows. For example, by feeding back favorited photos, LibrePhotos could be used for picking favorites to process in a separate photo editing software that has functionality for filtering photos based on metadata. 

**Additional context**
I haven't found a good metadata tag for "favorited" photos that is supported by a wide range of photography software. In contrast, most have support for "rating". Because of this, LibrePhotos should base a "favorited" photo marking on "rating", with any photo with a rating greater than or equal to some user-defined minumum rating being regarded as "favorited". When a user marks a photo as "favorited", it should be given a rating equal to that user-defined minimum rating. (This will also make it possible to implement functionality for letting users set ratings, rather than just "favorited", in the future.)

Further, when the rating of a photo is changed, this should be written back as image metadata, either in the original image file, or as an XMP sidecar file. The reasoning for writing to an XMP sidecar file is that the user may not want LibrePhotos to modify the original file. Indeed, that file may even be read-only. Writing to the original image or an XMP sidecar file should be set by the user.

(Some of this work has already been started, but I wanted to create an issue to connect pull requests to, and also as a placeholder for discussions.)

**Comment by Michael2MacDonald** [comment]
It has been over a year, is there an update on this issue?
