### ISSUE TITLE
Frontend crashes after adding a favorite and switching to the favorite view

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#314]
If you add a photo to favorites within the "With Timestamps" view and then switch to the favorites view, then the site crashes. If you refresh the favorites view, everything works again. It looks like an issue with a redux store. The items are manipulated in a way that makes react-pig crash.

The bug was found #312 while testing the pull request.

```
TypeError: g.items is undefined
computeLayoutGroups/<
src/app/node_modules/react-pig/dist/index.es.js:5898

  5895 | // the working rowAspectRatio.
  5896 | 
  5897 | var tempImgData = [];
> 5898 | g.items.forEach(function (image, index) {
       | ^  5899 |   if (index === 0) {
  5900 |     groupTranslateY = translateY;
  5901 |   } 
```

**Comment by jmalm** [comment]
I found the issue, I think. When adding a photo as favorite, it's just added to store.photos.favoritePhotos directly, but the FavoritePhotos view expects store.photos.favoritePhotos to be a date-grouped list. This will definitely change in my current refactoring.

Relevant code from photoReducers.js:

```js
      if (valFavorite) {
        updatedPhotos.forEach(photo => {
          newFavoritePhotos.push(photo);
        });
      } else {
        newFavoritePhotos = newFavoritePhotos.filter(photo => {
          if (updatedPhotosImageHashes.includes(photo.image_hash)) {
            return false;
          } else {
            return true;
          }
        });
      }
```

**Comment by derneuere** [comment]
This is now resolved :tada:
