### ISSUE TITLE
new docker image for backend crashes

### ISSUE THREAD

**Issue by phynias** [LibrePhotos/librephotos#319]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
ubuntu

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### Description of issue:

> statd: unrecognized service
> Traceback (most recent call last):
>   File "/code/image_similarity/main.py", line 6, in <module>
>     from retrieval_index import RetrievalIndex
>   File "/code/image_similarity/retrieval_index.py", line 1, in <module>
>     import faiss
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/local/lib/python3.9/dist-packages/faiss-1.7.1-py3.9.egg/faiss/__init__.py", line 18, in <module>
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/local/lib/python3.9/dist-packages/faiss-1.7.1-py3.9.egg/faiss/loader.py", line 65, in <module>
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/local/lib/python3.9/dist-packages/faiss-1.7.1-py3.9.egg/faiss/swigfaiss.py", line 13, in <module>
> ImportError: cannot import name '_swigfaiss' from 'faiss' (/usr/local/lib/python3.9/dist-packages/faiss-1.7.1-py3.9.egg/faiss/__init__.py)
> Traceback (most recent call last):
>   File "/code/manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 377, in execute
>     django.setup()
>   File "/usr/local/lib/python3.9/dist-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python3.9/dist-packages/django/apps/registry.py", line 114, in populate
>     app_config.import_models()
>   File "/usr/local/lib/python3.9/dist-packages/django/apps/config.py", line 211, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/code/api/models/__init__.py", line 1, in <module>
>     from api.models.album_auto import AlbumAuto
>   File "/code/api/models/album_auto.py", line 4, in <module>
>     from api.models.photo import Photo
>   File "/code/api/models/photo.py", line 7, in <module>
>     from api.im2txt.sample import im2txt
>   File "/code/api/im2txt/sample.py", line 8, in <module>
>     import torch
>   File "/usr/local/lib/python3.9/dist-packages/torch/__init__.py", line 196, in <module>
>     from torch._C import *
> ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory

### How can we reproduce it:
latest docker image

**Comment by phynias** [comment]
on this note. is it possible to maybe start tagging the docker images? so we can roll back to an older version. currently there is just the dev tag.

**Comment by StarkZarn** [comment]
My updated container reproduces this behavior exactly as well.

**Comment by derneuere** [comment]
There is now a new build online 👍 
I agree, I should add tagging next.

**Comment by derneuere** [comment]
It now works on ARM and x64
