### ISSUE TITLE
Container ..... is restarting, wait until the container is running

### ISSUE THREAD

**Issue by idefy** [LibrePhotos/librephotos#326]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x ] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Raspberry PI 4, latest version of LibrePhotos

### What architecture is LibrePhotos running on:
ARM

### How is LibrePhotos installed:
Docker following steps here: https://docs.librephotos.com/1/arm_install/

### If running via Docker or Kubernetes please list version including docker-compose:
docker-compose 1.29.2

### Are you running LibrePhotos on a virtual machine if so please list:
No

### How is you picture library mounted on the host (or in the virtual machine):
external HDD with NTFS

### Description of issue:
The web site is never available: ERR_CONNECTION_REFUSED
It seems the docker container is in constant reboot
```
$ docker-compose top
ERROR: Container 4dfc7012a3d2be8ad3940cde420491a67ec57bfc00fb90ec221cc5806dcd053b is restarting, wait until the container is running
```

### How can we reproduce it:
Follow steps here: https://docs.librephotos.com/1/arm_install/

I've setup .env with correct path to my external HDD. I left the logs path untouched to make sure to capture something in case the HDD path was the issue, but no.

Sometimes you have to run docker up twice as there is a time out that can occur the first time:
```
 $ docker-compose -f docker-compose.arm.yml up -d
Creating network "librephotos-docker_default" with the default driver
Creating librephotos-docker_db_1    ... done
Creating librephotos-docker_redis_1   ... done
Creating librephotos-docker_backend_1 ... done
Creating librephotos-docker_frontend_1 ... done
Creating librephotos-docker_proxy_1    ... 

ERROR: for librephotos-docker_proxy_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for proxy  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

```
Running the second time it seems to be fine:
```
$ docker-compose -f docker-compose.arm.yml up -d
librephotos-docker_db_1 is up-to-date
librephotos-docker_redis_1 is up-to-date
librephotos-docker_backend_1 is up-to-date
librephotos-docker_frontend_1 is up-to-date
librephotos-docker_proxy_1 is up-to-date
```

#### Additional Information:

* Include a ZIP file containing your `log` files.
No logs to include, the directory is empty
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by derneuere** [comment]
We now also support up-to-date images with the tag reallibrephotos/librephotos:dev
I tried it out, and I could not reproduce the issue. I think that this is probably an error specific to the old image.
