### ISSUE TITLE
Document code format and code linting standards

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#334]
We should document for other developers who want to contribute which code format and code linting we prefer.
We use currently black, isort and flake8 #317  in the backend and prettier and es-lint #333 in the frontend. The documentation should explain how to install it, what the benefits are, and how to install the pre-commit hook on the local system.

**Comment by polaroidkidd** [comment]
wait, did you already do this? Otherwise i can take care of documenting the frontend part

**Comment by derneuere** [comment]
I only added the minimal documentation: https://docs.librephotos.com/5/dev_frontend/ This can still be improved easily :D
