### ISSUE TITLE
Only use one instance of scanning of exiftool

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#335]
We currently instantiate exiftool when a picture needs it while scanning. The current release seems to have a higher memory footprint which leads to a significant increase in memory usage.

We should load/unload the exiftool instance like we do it for semantic_search and places_365.

**Comment by jmalm** [comment]
Fixing this.

**Comment by jmalm** [comment]
Fixed in https://github.com/LibrePhotos/librephotos/pull/342.
