### ISSUE TITLE
Databasequeries slow

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#34]
I have around 10000 photos in my database. All the queries take multiple seconds to execute. It is probably a regression introduced by #7.

**Comment by sysoppl** [comment]
Same for me, ~11 000 photos load about 20 seconds, also cpu usage is high
![obraz](https://user-images.githubusercontent.com/30871217/102393120-3fc08700-3fd8-11eb-869f-e92a168e054a.png)

**Comment by derneuere** [comment]
@sysoppl I created a new image. Please do a docker-compose pull and then a docker-compose up. It should work now better. If it does close the issue :)

**Comment by sysoppl** [comment]
Same as before, ~20 seconds of loading and then I see photos. 
CPU usage is lower
![obraz](https://user-images.githubusercontent.com/30871217/102510010-786b6980-4087-11eb-88fc-7d44b7b3669a.png)


BTW, I cannot close this issue, it is yours ;)

**Comment by derneuere** [comment]
True 😅

We added new parameter to the docker-compose file:
The number of Gunicorn worker processes; SET to (2*cpu cores);
      - WEB_CONCURRENCY=2 # CHANGEME

Maybe that's the reason why it is still slow for you. Could you try that out?

**Comment by sysoppl** [comment]
Yes, this reduced time to ~2sec. It is fixed
