### ISSUE TITLE
EXTRA string=is not a valid Windows path

### ISSUE THREAD

**Issue by MatthK** [LibrePhotos/librephotos#347]
# Before you create an issue make sure that:
I have installed Librephotos on a Raspberry Pi and it worked fine, although very very slow in scanning the photos.
As I do have a Windows PC around, I thought I migrate the Docker Compose to this machine, let it do the scanning more quickly, and then migrate it back.
After copying the whole librephotos-docker directory to a network drive, next to the photos, I tried to fire up the `docker-compose up` on the Windows machine in that network drive. When I try to run that, it errors out with the following message:

```
PS P:\Drive\librephotos-docker> docker-compose up
[+] Running 1/2
 - Container librephotos-docker_redis_1                         Created                                                                                                                        0.0s
 - Container 71954bd9119b_71954bd9119b_librephotos-docker_db_1  Recreate                                                                                                                       0.7s
Error response from daemon: \\prometheus\home\Drive\librephotos-docker\librephotos\data%!(EXTRA string=is not a valid Windows path)
```

In the .env file I have tried various options to define the paths.

```
./librephotos/Photo
librephotos/Photo
//prometheus/home/Drive/librephotos-docker/librephotos/Photo
```
All give me the same error message as above.
When I finally tried `/librephotos/Photo` it did start up, but then it did not recognize my previously defined user. I could login with the admin user, but it seems the previous data was lost.

How do I have to define the path on the Windows machine, so that I keep the existing data?

**Comment by derneuere** [comment]
We do not support windows explicitly at the moment. If you find a workaround, add it to this issue :)
