### ISSUE TITLE
Non-admin user can't change settings

### ISSUE THREAD

**Issue by jmalm** [LibrePhotos/librephotos#348]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [ ] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Docker on linux

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB

### Description of issue:

It seems like no users other than admin are allowed to change their user settings. After changing scan options or favorite options and hitting Update, I get 403 back on the following:

Request URL: http://localhost:3000/api/manage/user/2/
Request Method: PATCH
Status Code: 403 Forbidden

This is when user with ID=2 is doing the call.

### How can we reproduce it:

Using a user other than admin:
1. Change a value under Scan options or Favorite options
2. Hit Update
-> No toaster is shown about successfully changing settings
-> In DevTools, HTTP status code of the request is 403 Forbidden
3. Refresh page
-> old values are shown

**Comment by derneuere** [comment]
This is now fixed :D
