### ISSUE TITLE
Minimum confidence for person albums

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#354]
As a user, I want that high confidence inferred faces are added to the person albums.

This should be configurable and should be by default higher than the minimum confidence for the face recognition (#60). The default should be high enough to get no false positives.

We should add new field "confidence_person" within the user model and add it in the frontend within the settings tab.

**Comment by nagarrido** [comment]
Any update on this?

**Comment by jakekapellen** [comment]
Feel free to assign this to me.
