### ISSUE TITLE
Docker librephotos_backend_1 always consuming 7-10% CPU

### ISSUE THREAD

**Issue by clubhousekey** [LibrePhotos/librephotos#369]
With ~70,000 photos I am seeing consistent 7-10% CPU usage for librephotos_backend_1 from `docker stats`. Occurs with 2021w35, 2021w36, 2021w37, and the latest dev image.

**Comment by clubhousekey** [comment]
This appears to be related to the value of gunniWorkers.

gunniWorkers=4 idles at 7-10% CPU
gunniWorkers=2 idles at 3-5% CPU
gunniWorkers=1 idles at 1-2% CPU

I am mainly wondering why idle without any active connections or scans is producing any regular CPU usage.

**Comment by derneuere** [comment]
This does not happen in production anymore. If in debug mode, the cpu usage will be higher as python is looking constantly for file changes to hot reload if necessary.
