### ISSUE TITLE
Calculate Clip Embeddings stuck

### ISSUE THREAD

**Issue by kenzot11** [LibrePhotos/librephotos#381]
## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [X] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Docker Pulls

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker version: 20.10.6
Docker compose version: 1.27.4

### Are you running LibrePhotos on a virtual machine if so please list:
virtual Docker host running on Ubuntu 20.04.2 LTS (using Portainer)

### How is you picture library mounted on the host (or in the virtual machine):
NFS mounted in Linux Host.

### Description of issue:
Earlier i added about 2.500 Photos without any issue. Scan worked fine and "Calculate Clip Embeddings" also went smoothly.
Later a added about 13.500 more photos, scan took longer (as expected) but "Calculate Clip Embeddings" got stuck at 5%.
When scanning the photos again it got stuck at 2%.
Suspecting a bad photo or something.

### How can we reproduce it:
Not sure as it worked before with less pictures. maybe the 
[librephotologs.zip](https://github.com/LibrePhotos/librephotos/files/7449712/librephotologs.zip)
amount of photos?

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
![image](https://user-images.githubusercontent.com/25793634/139599813-2c957b21-61fa-4dc6-86d1-897280fdbb4c.png)

**Comment by derneuere** [comment]
It can't find a thumbnail for a picture:
[Errno 2] No such file or directory: '/protected_media/thumbnails_big/6741f97f96262ec20751041715f8016e2.webp'

I also can't find any reference in your log files. That's kind of weird. I will implement some error handling in the next couple of days.

This only impacts finding of similar images and the semantic search, if you activated that. You can also delete the log entry as it's no longer running.

**Comment by kenzot11** [comment]
Hi derneuere

yeah was also looking for the culprit but can't find the photo in the logs.
Looking forward to the improved error handling!

**Comment by derneuere** [comment]
It will now check if the thumbnail exists. However, this issue isn't completely solved yet, as it skips way too many images. Something seems to be broken when saving the location after generating the thumbnails.

**Comment by kenzot11** [comment]
I found the file which was causing problems by looking for the link between the file and thumbnail in the database. Looks to be a corrupted .mp4 file. Deleted the file, rescan, added a copy of the file which wasn't corrupt, rescan => OK
Maybe some sort of error log if a file can't be read properly?

**Comment by ippocratis** [comment]
> I found the file which was causing problems by looking for the link between the file and thumbnail in the database. Looks to be a corrupted .mp4 file. Deleted the file, rescan, added a copy of the file which wasn't corrupt, rescan => OK Maybe some sort of error log if a file can't be read properly?

Can you elaborate please?
I have a similar issue
Calculate clip embeding is stucked at xx%
In the own photos.log I see that it throws an error 
`ERROR : Error in batch_calculate_clip_embedding: cannot identify image file '/protected_media/thumbnails_big/35e425cb8849d26baa3744d90b11495b1.webp`
I ssh'd to the backed container and deleted the file inside the container but ig it get recreated on every lib scan
how can I see the file association in the dB ?

**Comment by ippocratis** [comment]
@derneuere 
@kenzot11 

From  .env

dbName=librephotos
dbUser=docker
dbPass=pass

From docker-compose.yml

volumes:
      - ${dbLocation}:/var/lib/postgresql/data

From docker ps
Container name = 69f3a19600bf

So I run
`docker exec -tiu docker 69f3a19600bf psql`

But returns
unable to find user docker: no matching entries in passwd file


Also
if I
`sudo docker exec -it  d000272b4bd9 bash`

I see that there is no postgresql entry in /var/lib

Did I got something wrong?

**Comment by derneuere** [comment]
I am not sure, what you are trying to do. I pushed a fix for your issue. The process should now skip the faulty image. It's available on the dev tag for now.

**Comment by ippocratis** [comment]
> I am not sure, what you are trying to do. I pushed a fix for your issue. The process should now skip the faulty image. It's available on the dev tag for now.

Thanks
I'll switch to dev

I was trying to open the postgres dB and see the associated assert in my library to the one that threw errorus thumbnail

**Comment by ippocratis** [comment]
@derneuere 

nano .env

tag=dev

docker-compose down

docker-compose pull

docker-compose up -d

?

**Comment by ippocratis** [comment]
@derneuere 
Calculate clip embedding indeed is fixed in dev tag
thanks
