### ISSUE TITLE
Scan only photos extentions

### ISSUE THREAD

**Issue by yodatak** [LibrePhotos/librephotos#386]
Hi on  the librephotos_backend
it show it try to make thumbernails from WAV files or hprj files i could be cool for people that have a big library of photos to only scan know extentions for photo

INFO:ownphotos:Could not handle /data/Sons/f0590656_ZOOM0006/ZOOM0014/ZOOM0014_LR.WAV, because unable to call thumbnail
  magickload: Magick: no decode delegate for this image format `VIDEO' @ error/constitute.c/ReadImage/572 (null)
  ������uINFO:ownphotos:Could not handle /data/Sons/f0590656_ZOOM0006/ZOOM0014/ZOOM0014.hprj, because unable to call thumbnail
  VipsForeignLoad: "/data/Sons/f0590656_ZOOM0006/ZOOM0014/ZOOM0014.hprj" is not a known file format
  ������nINFO:ownphotos:Could not handle /data/1ermai2/DCIM/100CANON/IMG_9235.CR2.xmp, because unable to call thumbnail
  magickload: Magick: must specify image size `/tmp/magick-nIUbLhhaQ_LZ1XFxZgEqr_Gv10uhGyID' @ error/mvg.c/ReadMVGImage/186 (null)
  ������nINFO:ownphotos:Could not handle /data/1ermai2/DCIM/100CANON/IMG_9189.CR2.xmp, because unable to call thumbnail
  VipsForeignLoad: "/data/1ermai2/DCIM/100CANON/IMG_9189.CR2.xmp" is not a known file format

**Comment by yodatak** [comment]
I think we  have to modify this part to make them seek only for videos extentions and photos extensions right ?
https://github.com/LibrePhotos/librephotos/blob/dev/api/directory_watcher.py#L30

**Comment by derneuere** [comment]
We could do that, but we would have to list every file format, which we support, which is a long list, that needs to be maintained.

We currently just try to parse the files as images / videos and if that fails we skip it. That way it's more manageable. That's also the reason why we treat this event an info log and not an error.
