### ISSUE TITLE
Question-Documentation Lacking

### ISSUE THREAD

**Issue by brink668** [LibrePhotos/librephotos#387]
I could not find the answers to these questions in the support documentation.  Hoping someone can answer this.

What does Train Faces do you? When should you run this?
What does ReScan Faces do? When you should you run this?

**Comment by derneuere** [comment]
Hey, thanks for your questions. I added a bit of documentation. Does this answer all of your questions?https://docs.librephotos.com/2/face_recognition/

**Comment by brink668** [comment]
Thank you so much for updating and adding this information. This is even better than what I was expecting.
