### ISSUE TITLE
Timestamp - Use "Date Created" if "Date Taken" isn't available

### ISSUE THREAD

**Issue by kenzot11** [LibrePhotos/librephotos#388]
**Describe the enhancement you'd like**
A lot of my photos don't have a date in the field "Date Taken", 99% of these have the correct date in the field "Date Created".
This is especially true for Photos shared to me via Whatsapp or other messaging apps.
If the field "Date Created" isn't filled in, the field "Date Created" could be used instead as a fallback.

**Describe why this will benefit the LibrePhotos**
When Photos are marked without timestamp you can't really sort them and they won't be added to Albums.
When the alterative field "Date Created" is used these should be accounted for during automatic album creations.

**Additional context**
![image](https://user-images.githubusercontent.com/25793634/140643165-1219bead-e6b5-412b-9950-b9a5e3ea66ff.png)
![image](https://user-images.githubusercontent.com/25793634/140643182-86f92d2f-366d-4914-9eac-28bff86af66e.png)

**Comment by derneuere** [comment]
As mention in #436 we have to switch from default rules to predefined rules in the add rules dialog. That should be everything that has to be added in order to implement this.

**Comment by derneuere** [comment]
You can now add this rule in the settings page.
