### ISSUE TITLE
Improve InfinteScrolling

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#39]
Currently, 50k-100k images are loaded as hashes at once. This is not very efficient and leads to problems if the number of pictures is high enough. 

Instead, we should load fewer images like 250 image hashes at once and load the next 250 image hashes if we are at the bottom of the page.

**Comment by darrepac** [comment]
https://medium.com/google-design/google-photos-45b714dfbed1

**Comment by alexislefebvre** [comment]
Similar problem, with a solution: https://github.com/photoprism/photoprism/pull/1089

**Comment by derneuere** [comment]
It should scale now easily to higher numbers than that :)
