### ISSUE TITLE
How to setup Mapbox

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#392]
It is currently not clear on how to get places to show up on the map. We should document the current way on how to get a Mapbox API key and then apply it to LibrePhotos in order to get places.

**Comment by Puttt** [comment]
I've done it recently:
- create an account on Mapbox
- after login go to 'Tokens' on the main menu
- click on 'Create Token'
- fill out the name (for example 'LibrePhotos')
- leave the public scopes as there are
- check following secret scopes:
   - STYLES:TILES
   - STYLES:READ
   - FONTS:READ
   - DATASETS:READ
   - VISION:READ
   - STYLES:LIST

I don't know if this is the correct way, but it works for me.

**Comment by Seneliux** [comment]
I can´t remember, but I think that my default public token, generated automaticlly by the account creation, works. It is without secret scopes.

**Comment by iandonnelly** [comment]
And then take that key and paste it into your .env file on the line: `mapApiKey=`

**Comment by erikmakela** [comment]
@derneuere What was the reason for implementing Mapbox? Especially with the API cap couldn't code such as Digikam be re-written? Too time costly?

https://www.digikam.org/about/features/
https://stackoverflow.com/questions/1153577/integrate-python-and-c

**Comment by derneuere** [comment]
The original implementation in ownphotos used Mapbox. So it's historical baggage. We currently only use it for reverse geocoding. I also want to move to a more open implementation, see #150

I would prefer geopy as it is smaller, and it uses python :)

**Comment by redwood996** [comment]
Would love to see other alternatives than Mapbox, since it requires credit card during the sign up.

**Comment by sickelap** [comment]
What alternatives you have in mind?

**Comment by derneuere** [comment]
https://photon.komoot.io/ would be an alternative that is open

**Comment by ThatCoffeeGuy** [comment]
Would love to see this happen.

**Comment by sickelap** [comment]
I am currently trying to make [geopy](https://pypi.org/project/geopy/) to work. Thing is that reverse geocoding works just fine. Problem is with auto albums. Currently, albums place uses mapbox extensively. I.e., when adding albums places, it depends heavily on the API response format. I'll try to do my best not to break albums places, but it looks that's not an easy feat.

**Comment by ThatCoffeeGuy** [comment]
> 

Really appreciate it.

**Comment by ThatCoffeeGuy** [comment]
BTW some good news: Mapbox raised their previously 50k limit to 100k / mo. I still would very much love to see it gone due to their predatory, no way to limit usage pricing model, but it's good to know that it's twice as much as it is mentioned on the front page.

![image](https://user-images.githubusercontent.com/24213618/235288056-ca241ff9-bf3e-43d2-96f5-618ea468ae4a.png)
