### ISSUE TITLE
Issue in Pulling Backend during install

### ISSUE THREAD

**Issue by gk1089** [LibrePhotos/librephotos#412]
I am trying to set librephotos on a Ubuntu 20.04 VM (2 cores, 8GB RAM) using the procedure at: https://docs.librephotos.com/1/standard_install/. The VM is behind a proxy and I was able to make the corresponding changes in docker proxy configuration to get it working.

Docker version 20.10.12, build e91ed57
Docker Compose version v2.2.2

I am stuck at the 'docker-compose up -d' step. The other sections like the db, frontend etc seemed to get downloaded easily in the first go, but the 'backend Pulling' is failing for me repeatedly. 
sudo docker-compose up -d
[+] Running 2/21
 ⠴ backend Pulling                              395.8s
   ⠿ 9e6a0d5477cf Pull complete        57.6s
   ⠿ 488d22dd410d Pull complete      227.5s
   ⠧ f3da551cb53e Extracting [=>                                                 ]  10.58MB/298.8MB                     390.8s
   ⠧ f7c7f6ed5e3a Downloading [=======>                                           ]  272.6MB/1.858GB        390.8s
   ⠧ 773050c9bf97 Download complete                                                                                             390.8s
   ⠧ fa5ae7cd0fb8 Download complete                                                                                              390.8s
   ⠧ c05ad4bb676c Download complete                                                                                            390.8s
   ⠧ 0cab1eba9b45 Downloading [=============================>                     ]  55.32MB/92.82MB   390.8s
   ⠧ ada4b4ac8da5 Downloading                                                                                                        390.8s
   ⠧ 4d02b54f1670 Waiting                                                                                                                 390.8s
   ⠧ c3ea95ec824b Waiting                                                                                                                 390.8s
   ⠧ 734522b45a01 Waiting                                                                                                                390.8s
   ⠧ 5adb853b81b4 Waiting                                                                                                               390.8s
   ⠧ caae76624139 Waiting                                                                                                                390.8s
   ⠧ f2ace73c66c4 Waiting                                                                                                                 390.8s
   ⠧ 06d59f654e6d Waiting                                                                                                                390.8s
   ⠧ 8a8e1b0012d0 Waiting                                                                                                               390.8s
   ⠧ d73a56a8abc1 Waiting                                                                                                               390.8s
   ⠧ 9faf8c9762e8 Waiting                                                                                                                  390.8s
   ⠧ 548ac91a1bd0 Waiting                                                                                                                390.8s
unauthorized: authentication required

My internet is fairly stable and I have tried running the step multiple times. I tried searching based on 'unauthorized : authentication required' for docker/docker-compose but could not find any relevant results.

This is my first time playing with docker so please be gentle and explain how to generate/access logs to find the root cause of the issue.

Cheers!

**Comment by derneuere** [comment]
It could be this issue here: https://github.com/docker/hub-feedback/issues/645

If your vm has a clock-drift, then it will cause this error.

**Comment by gk1089** [comment]
You were right! This was happening because of the time drift. However, since I am behind a proxy, I was not able to update the time on my server using ntp and had to update it using the http headers using the information available at: https://superuser.com/questions/307158/how-to-use-ntpdate-behind-a-proxy

Maybe this will help someone else too in the future.

Thanks!
> It could be this issue here: [docker/hub-feedback#645](https://github.com/docker/hub-feedback/issues/645)
> 
> If your vm has a clock-drift, then it will cause this error.
