### ISSUE TITLE
All photos from WhatsApp are marked with "Invalid date"

### ISSUE THREAD

**Issue by kuzmos** [LibrePhotos/librephotos#416]
Latest (`docker pull` at least once a week) docker image on Ubuntu, 100k+ library. All whatsapp photos get marked with invalid date and don't show up in the "With timestamp" feed, nor are correctly sorted in the "Without timestamp" one. The root cause is obvious - no timestamp in EXIF. However, it is annoying. 

**Describe the enhancement you'd like**
WhatsApp images have date in their file name, could that be heuristically parsed to put the image at least in the correct ballpark of the feed? Example: `IMG-20220103-WA0007.jpg`

**Describe why this will benefit the LibrePhotos**
On big collections, this would significantly improve the user experience. A lot of people tend to take photos by WhatsApp only, not by their native phone app.

**Comment by sefininio** [comment]
@pivis please also consider adding the option to re-scan current library for photos like this and run the `configurable date time extractor` during the scan

**Comment by pivis** [comment]
I really like your idea, but I think it should be a separate issue (since it is orthogonal to WhatsApp) - so I created https://github.com/LibrePhotos/librephotos/issues/437 just for that.

**Comment by derneuere** [comment]
It's now implemented!

**Comment by sefininio** [comment]
Awesome!
So now a rescan will add timestamp to whatsapp images? Or is there something that the user needs to do?

**Comment by derneuere** [comment]
To apply these rules to all your photos, do a "Rescan all photos".

**Comment by sefininio** [comment]
No additional config required?

**Comment by derneuere** [comment]
No, the WhatsApp rule is a default 👍

**Comment by kuzmos** [comment]
Updated the docker, rescanned photos, and the WhatsApp pictures appeared in the feed. Beautiful. Thanks for this! Default rules do the job.
