### ISSUE TITLE
No photos before refreshing

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#43]
This occur when I'm not accessing librephotos for a while (few minutes or so). Refreshing page helps. 
![bug1](https://user-images.githubusercontent.com/30871217/102715102-46e6de00-42d3-11eb-8982-89f14e764497.gif)

Tested on chrome and firefox

**Comment by derneuere** [comment]
Seems to be resolved in my browser. Could you test if the bug still occurs for you?

**Comment by sysoppl** [comment]
It works in chromium as well as in firefox mobile, so probably fixed
