### ISSUE TITLE
Version information in the frontend

### ISSUE THREAD

**Issue by Seneliux** [LibrePhotos/librephotos#433]
It is good to add some version information to the frontend. Including backend / frontend version.

Now it is hard to track updates, versions, etc.

**Comment by MatthewBraun** [comment]
It would be great if there was an "About" page under the menu that contains "logout" "settings" "admin area" On that page it would include the versions along with a link to the Github and possibly a list of the most recent versions. Maybe even have a "bug report" instruction page for ease of reporting issues.

**Comment by 5m4u66y** [comment]
Duplicate of issue #575
