### ISSUE TITLE
Pictures imported from WhatsApp have no date taken information

### ISSUE THREAD

**Issue by sefininio** [LibrePhotos/librephotos#435]
**Describe the enhancement you'd like**
When importing new photos, one of the sources is WhatsApp. However, photos from WhatsApp lack `date taken` information and as a result, get added to the `without timestamp` feed way down on the bottom (by order of adding) and even if they are tagged with people - they appear in the person album way down on the bottom.

However,  WhatsApp image files usually have the following name pattern: 
`IMG-20220121-WA0004.jpg` which means that we can deduce the date taken (2022/01/21 in this case). Maybe we can leverage this when scanning photos?

**Describe why this will benefit the LibrePhotos**
This will allow photos from WhatsApp to be imported into the library and placed chronologically instead of dumped in the "no timestamp" zone.

**Additional context**
One thing important to note here - if/when this is implemented, we should also provide the means to re-scan the entire library for photos that currently don't have a timestamp and process them in bulk and use the filename to create a timestamp for them .

**Comment by pivis** [comment]
Seems to be the duplicate of https://github.com/LibrePhotos/librephotos/issues/416 - I'm working on this now. Should be ready soon.

**Comment by sefininio** [comment]
Yup you are right, ill close this one and comment there. Thanks,
