### ISSUE TITLE
Add the size of LibrePhotos and compatibility in ReadMe

### ISSUE THREAD

**Issue by darrepac** [LibrePhotos/librephotos#44]
Hi

Trying to install in my Pi... The install is still running (dev: Pulling from reallibrephotos/librephotos) and already more than 3-4gig of data has been downloaded (!!). Is this normal???
I am afraid that I run out of size...and did not expect that librephotos would take such amount of space.

**Comment by sysoppl** [comment]
It is hungry for space, for me it is taking ~6gb of space (just backend!). 
![obraz](https://user-images.githubusercontent.com/30871217/102719009-abae3280-42eb-11eb-9f12-3876a6d4f68b.png)

**Comment by darrepac** [comment]
ok! so at least it is not something bad on my side...at a moment I thought it was download my 120GB photos...
6GB...hope it will fit!

**Comment by sysoppl** [comment]
Well, if you choose to connect with nextcloud it will copy your photos to your /data folder, so if you don't have enough space be careful ;)

**Comment by darrepac** [comment]
well no, I am not connecting with nextcloud.
And I am df -h every 5min ;)

**Comment by sysoppl** [comment]
I just realized that I only gave you the size of one container. as I remember, size of them all was something over 10GB (front, back, redis and db).

**Comment by darrepac** [comment]
ok so I am stopping everything now... Should put a warning in the readme!
10GB!!

**Comment by derneuere** [comment]
It currently does not work anyway on arm processors. Some people are on it, but we don't have a working build for raspberry pis. If you want to help out with the development, come to the discord 👍

**Comment by darrepac** [comment]
ah ok!
I am not enough skilled for that! Shame LibrePhotos, as a rework of ownphotos, sounds promising!
Raspberry Pi sounds to me the best platform to host such service (price/consumption/power ratio)
I am sure it will come soon or later

**Comment by darrepac** [comment]
you can also add the status about Raspberry Pi in the readme (stating that it doesn't work for the moment and the call for volunteers)

**Comment by darrepac** [comment]
Just for my understandings, what is the recommended platform for the backend right now?

**Comment by dakshsingh** [comment]
Regarding the size of the docker images I was quite surprised by the size as well. I set up Librephotos a few days back on an Unraid NAS so didn't really run into any problems but compared to other Docker applications it's an order of magnitude larger.

I wonder what causes the large size.
