### ISSUE TITLE
Watermark on video thumbnails

### ISSUE THREAD

**Issue by mariusg0000** [LibrePhotos/librephotos#444]
**Describe the enhancement you'd like**
Add a watermark on video thumbnails.

**Describe why this will benefit the LibrePhotos**
To differentiate more easily between video and photo files.

**Additional context**

**Comment by pivis** [comment]
I like this idea - maybe something like a partially transparent small triangle looking to the right (like a play button) in one of the corners of the thumbnail.

**Comment by derneuere** [comment]
It's now implemented on dev.
