### ISSUE TITLE
Issues with the (mobile) toast notifications in a photos quick actions

### ISSUE THREAD

**Issue by EXOgreen** [LibrePhotos/librephotos#446]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [ x ] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:

This is from the demo site

### Description of issue:

When loaded up on mobile (Firefox) the options in the top right of a selected photo (hidden/favorited/etc) can only be selected once before  the pop up notification that confirms the action shows up. This notification never self-hides itself (which I also take issue with) and after tapping it I cannot select any options until I close and reopen the photo. 

Bonus points 
Please see if there is a way to make the notification no longer hide the options
The notification clears itself after a few seconds
The toasts.addPublicPhoto and toasts.removePublicPhoto get descriptive text instead of their function name

### How can we reproduce it:

What I did
1. Opened the demo site on mobile
2. Open any photo
3. Select any quick options in the top right
4. Tap on notification to hide it
5. Try to select another option, which fails

**Comment by derneuere** [comment]
This is now all implemented in dev :)
