### ISSUE TITLE
Clarification on datetime parsing rules usage

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#451]
"datetime" parsing rules have been recently added to user settings page. This addition make sense in particular to cover specific behavior as Whatsapp photos which have no valuable dates except in their filename. Thanks to Pivis and DerNeuere for this implementation.
Nice capabilities have been provided to add, remove, sort parsing rules.
The main drawback is that (according to a basic user as me...) it is very difficult to clearly understand these rules and which tag will be used if I compare to tags available in Windows file explorer as an example.
In addition, no documentation is provided on that matter.

As a minimum, I would recommend some cosmetic adjustments:
- Number each existing rule so that everyone can designate a rule without any ambiguity (it can be done in the title of the rule then updated in the translation)
- Indicate somewhere the ordered list of rules by default (to be able to come back to default setting in case of testing or whatever)
and possibly:
- add a button to come back to default set of rules
An other point : It may be useful to be able to manually set the datetime (without modifying the photo) as it is proposed in Google Photos to cover unsolvable cases?

Of course a bit of documentation would be valuable... in particular, **what happen when a user change the rules, has he to perform a scan, a rescan or something other**?

**Comment by loulou91** [comment]
Apparently, first bullet of this enhancement request has been implemented and that's a good point ;-)
Thanks to @sickelap !

- Number each existing rule so that everyone can designate a rule without any ambiguity (it can be done in the title of the rule then updated in the translation)

**Comment by loulou91** [comment]
I also answer to the second bullet << - Indicate somewhere the ordered list of rules by default>>
That's what I saw starting a new base from scratch.
![image](https://user-images.githubusercontent.com/51127123/208707234-7cdc5b8b-8310-4bc5-8c99-dd578cfbbe26.png)

**Comment by sickelap** [comment]
I like the “Reset” feature for date time rules. I will try to come up with something. Perhaps tonight.

**Comment by loulou91** [comment]
Well done @sickelap, I close this subject.
