### ISSUE TITLE
View Auto Album fails to load images

### ISSUE THREAD

**Issue by WoollyMammal** [LibrePhotos/librephotos#452]
## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
``` sh
                   -`                    user@domain
                  .o+`                   -----------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Kernel: 5.16.10-arch1-1
               `+oooooo:                 Uptime: 7 days, 7 hours, 25 mins
               -+oooooo+:                Packages: 1430 (pacman), 9 (flatpak)
             `/:-:++oooo+:               Shell: bash 5.1.16
            `/++++/+++++++:              Resolution: 3440x1440
           `/++++++++++++++:             WM: i3
          `/+++ooooooooooooo/`           Theme: Adwaita [GTK2]
         ./ooosssso++osssssso+`          Icons: Adwaita [GTK2]
        .oossssso-````/ossssss+`         Terminal: alacritty
       -osssssso.      :ssssssso.        CPU: AMD Ryzen 5 2600X (12) @ 3.600GHz
      :osssssss/        osssso+++.       GPU: NVIDIA GeForce RTX 2070
     /ossssssss/        +ssssooo/-       Memory: 23344MiB / 32071MiB
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```

### What architecture is LibrePhotos running on:
x86_64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
I'm running docker as an alias of [Podman](https://docs.podman.io/en/latest/index.html), but that doesn't seem like that should be the issue here.
* Podman version 3.3.1
* Docker Compose version 2.2.3
There is a newer version of podman, but there is [a bug](https://github.com/containers/podman/issues/12003) I'm avoiding by staying on this version.

### Are you running LibrePhotos on a virtual machine if so please list:
No.

### How is you picture library mounted on the host (or in the virtual machine):
Local file system volume mount into the containers.
The local filesystem is an unencrypted, multi-device [BTRFS](https://btrfs.wiki.kernel.org/index.php/Main_Page) pool.

### Description of issue:
When trying to access the images grouped into an auto-album, the auto-album appears to have nothing in it.
This seems to happen for auto-albums. Manual albums, people albums, things albums and places albums are not affected.

### How can we reproduce it:
1. Create a new librephotos instance (via docker-compose)
2. Scan in some photos that would be grouped into an auto-album
3. Run the "generate auto albums" command and wait for it to complete
4. Try to access one of the generated auto-albums

#### Additional Information:
[backend.log](https://github.com/LibrePhotos/librephotos/files/8147702/backend.log) is a copy of the `docker logs backend` command's output.
[logs.zip](https://github.com/LibrePhotos/librephotos/files/8147707/logs.zip) is the zipped up version of all the files in the `logs` folder.

**Comment by derneuere** [comment]
I have fixed this bug. This will be in the next weekly release :)
