### ISSUE TITLE
images leak between users

### ISSUE THREAD

**Issue by guystreeter** [LibrePhotos/librephotos#453]
# Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

When asking general "how to" questions:
- Please do not open an issue here join us on the Discord server  [LibrePhotos](https://discord.gg/xwRvtSDGWb)

**When Submitting please remove every thing above this line**

## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Fedora 35

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Current "dev" image from docker hub

### Are you running LibrePhotos on a virtual machine if so please list:
no

### How is you picture library mounted on the host (or in the virtual machine):
Local file system ext4

### Description of issue:
When I log out from one user and log in as another, the previous user's photos are displayed until I refresh the browser

### How can we reproduce it:
Create 2 users and give them different photos. Log in as on user, then log out and log in as the other user.

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by derneuere** [comment]
For somebody who wants to fix this: This happens because the Redux store does not get cleared out correctly when logging out.

**Comment by varet80** [comment]
> For somebody who wants to fix this: This happens because the Redux store does not get cleared out correctly when logging out.

Backend has to clean this up?

**Comment by sickelap** [comment]
I will take a look into this
