### ISSUE TITLE
Button train classifier in faces does not work

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#454]
### How is LibrePhotos installed:
Docker 

### Version:
dev:latest

### Description of issue:
Button to train faces in faces does not work.

Button in question: 
![image](https://user-images.githubusercontent.com/29661633/156099693-c7d67286-b344-4d70-a4a5-125b61bb462d.png)

### How can we reproduce it:
Just click it, does not work.

**Comment by derneuere** [comment]
Thanks for testing. Fixed 👍
