### ISSUE TITLE
date info is missing in the autocreated album

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#463]
I appreciate very much the capability to automatically group pictures according date criteria. It allows not to systematically have to create manual albums to group photos and ease photos searching.
But, there are no indication about the date in the album name except the day of the week !

I think that "Monday Morning with X and Y in this place and that place" should be improved with at least the date of the first picture and duration (for instance). Intuitively, the use can deduce many things looking at album cover but not the capture date !

**Comment by 5m4u66y** [comment]
LibrePhotos/librephotos-frontend#135 is the easiest fix for this. Just display the date below album title.
The display is already a mess on mobile, so by adding this, I make it even more messy :(

**Comment by loulou91** [comment]
Thanks! To ease things everywhere, replacing long title which takes place (often 3 or 4 lines) is often confusing (with names) and is not really useful (at least for me...) with date (or min/max) and keeping number of photos would be enough!!!

**Comment by derneuere** [comment]
I think removing the date from the function https://github.com/LibrePhotos/librephotos/blob/d2e1a6f9983e940122f699a163066848e38c0592/api/models/album_auto.py#L28
 here would be the next step :)

**Comment by loulou91** [comment]
I insist but there is a problem with the place taken by the title on the screen! On my tablet or my phone (chrome android, but ios should be the same ;-) ) it is sometime so large that date and number of pictures is not visible!
According to me, only date and number of pictures should be displayed, additional information (if needed) being displayed by an other way (mouseover for instance).
Remark about the names displayed: It's funny when the photos of a wedding are commented with the name of 2 guests or the name of the 2 mothers-in-law ;-)
