### ISSUE TITLE
cannot execute on Raspberry Pi -- all components exit, and loop restart with status code 159

### ISSUE THREAD

**Issue by aldobranti** [LibrePhotos/librephotos#466]
all components freshly downloaded on RPI with Debian10

$docker-compose up -d
$docker ps -a
8d777536b6df   reallibrephotos/librephotos-proxy:latest      "/docker-entrypoint.…"   2 hours ago    Restarting (159) **6 seconds ago**                                                librephotos-docker_proxy_1
a5434c282daf   reallibrephotos/librephotos-frontend:latest   "/serve"                 2 hours ago    Restarting (159) **34 seconds ago**                                               librephotos-docker_frontend_1
5715aa9e900e   reallibrephotos/librephotos:latest            "/entrypoint.sh"         2 hours ago    **Restarting (159) **36 seconds ago****                                               librephotos-docker_backend_1
d8c1064f9268   postgres:13                                   "docker-entrypoint.s…"   2 hours ago    Up 56 minutes                     5432/tcp                                    librephotos-docker_db_1
509837c7fec6   redis:6                                       "docker-entrypoint.s…"   2 hours ago    **Restarting (159) 37 seconds ago**                                               librephotos-docker_redis_1

**Comment by derneuere** [comment]
Could you start it without the -d and paste the console output here. There should be an actual error below that.

**Comment by aldobranti** [comment]
My apologies for the incompleteness

$ docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting librephotos-docker_db_1    ... done
Starting librephotos-docker_redis_1 ... done
Starting librephotos-docker_backend_1 ... done
Starting librephotos-docker_frontend_1 ... done
Starting librephotos-docker_proxy_1    ... done
Attaching to librephotos-docker_redis_1, librephotos-docker_db_1, librephotos-docker_backend_1, librephotos-docker_frontend_1, librephotos-docker_proxy_1
db_1        | 
db_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1        | 
db_1        | 1970-01-01 00:00:00.000 UTC [1] LOG:  starting PostgreSQL 13.6 (Debian 13.6-1.pgdg110+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 32-bit
db_1        | 1970-01-01 00:00:00.000 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 1970-01-01 00:00:00.000 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 1970-01-01 00:00:00.000 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 1970-01-01 00:00:00.000 UTC [25] LOG:  database system was shut down at 1970-05-18 02:15:00 UTC
db_1        | 1970-01-01 00:00:00.000 UTC [1] LOG:  database system is ready to accept connections
db_1        | 1970-01-01 00:00:00.000 UTC [29] LOG:  stats collector's time 1970-06-30 23:03:27.634968+00 is later than backend local time 1970-01-01 00:00:00+00
db_1        | 1970-01-01 00:00:00.000 UTC [29] LOG:  stats collector's time 1970-06-30 23:03:27.634968+00 is later than backend local time 1970-01-01 00:00:00+00
librephotos-docker_frontend_1 exited with code 159
librephotos-docker_redis_1 exited with code 159
librephotos-docker_backend_1 exited with code 159
librephotos-docker_redis_1 exited with code 159
^CGracefully stopping... (press Ctrl+C again to force)
Killing librephotos-docker_proxy_1     ... done
Killing librephotos-docker_frontend_1  ... done
Killing librephotos-docker_backend_1   ... done
Killing librephotos-docker_db_1        ... done
Killing librephotos-docker_redis_1     ... done
ERROR: 2

the principal complaint seems to be about this time mismatch between the stats collector and the backend
I did _try_ searching for this error before posting

**Comment by derneuere** [comment]
When googling the error code 159, it returns Raspberry Pi issues with 64 bit docker images. It looks to me like your system does not use 64 bit, but 32 bit. We do not support 32 bit.

**Comment by aldobranti** [comment]
this is a 64-bit RPi and runs the 64-b kernel
(setting **arm_64bit=1** in /boot/config,txt)
I had to assert the env variable **DOCKER_DEFAULT_PLATFORM=linux/arm64** to get this far
AFAIK Raspberry docker-land is 32b
But looking at the reviews on this seems like you're not supporting RPi at any bit count

Thanks for your assistance

**Comment by aldobranti** [comment]
Setting 'privileged:true' in docker-compose.yml allowed this to run on so the diagnosis that this was a 32b/64b issue was a false lead,
I then began to experience lots of OOM kills , so I will back off on using librephotos until I can afford an 8Gb Pi
