### ISSUE TITLE
Number of photos in Librephotos doesn't match what's in Nextcloud

### ISSUE THREAD

**Issue by meichthys** [LibrePhotos/librephotos#469]
* [ ] I am including my log files in zip format.
* [X] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 21.04

### What architecture is LibrePhotos running on:
x64 or ARM
X64

### How is LibrePhotos installed:
Docker, Kubernetes, or .deb
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Latest tag

### Are you running LibrePhotos on a virtual machine if so please list:
Docker is a VM in Proxmox

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB
Local file system (mounted via davfs from nextcloud)

### Description of issue:
The total number of items in librephotos does not match the total number of items in Nextcloud.

### How can we reproduce it:
Sync Nextcloud with Librephotos and compare item totals.

#### Additional Information:
![image](https://user-images.githubusercontent.com/10717998/157658131-6ea18f83-301d-47f6-8a61-5cef3c918f65.png)

![image](https://user-images.githubusercontent.com/10717998/157658145-7d228da8-8dc3-47d3-97ae-25d69cc7e0a9.png)

**Comment by derneuere** [comment]
This can have a number of reasons:
1. You have duplicated files in your folder
2. You have files in the folder, that are not images or videos
3. You have a lot of photos marked as hidden

Are there any specific files missing?

**Comment by meichthys** [comment]
Thanks. I'll investigate these potential reasons and look for specific files that are missing. 
Currently:
1. I don't see any duplicate files
2. This could be the case. I'll investigate further
3. I don't currently have any hidden files in Librephotos or Nextcloud.

**Comment by meichthys** [comment]
Closing in favor of waiting for #55
