### ISSUE TITLE
Make "Similar Photos" clicklable

### ISSUE THREAD

**Issue by imwhocodes** [LibrePhotos/librephotos#474]
On the **Details _Tab_** photo similar to the one opened are shown, make this photo clickable so you can jump to the similar photo

**Similar Photos** is a pretty cool feature, but it is useless if you can not got to that photo

The behaviour should be similar to **Attributes** and **Categories** list on the same  **Details _Tab_**

Thanks

**Comment by cunicode** [comment]
[related](https://github.com/LibrePhotos/librephotos/issues/265 )
 @scottg88 [is giving it a go](https://github.com/LibrePhotos/librephotos/issues/265#issuecomment-1024749248)

**Comment by derneuere** [comment]
I will close this as it is a duplicate :)
