### ISSUE TITLE
Refresh takes user back to login screen every time

### ISSUE THREAD

**Issue by dm7500** [LibrePhotos/librephotos#478]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [ ] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Debian 10

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
docker-compose version 1.28.5, build c4eb3a1f

### How is you picture library mounted on the host (or in the virtual machine):
SMB

### Description of issue:
When any page in LibrePhotos is refreshed, it will throw the user back to the login page, even right after proper authentication.

### How can we reproduce it:
Authenticate into LP, navigate to a page, and refresh

#### Additional Information:
Ideally, this would save my session between refreshes to the page.

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by polaroidkidd** [comment]
oh.. I thought I fixed this. This one's on me. I think it's got something to do with an incorrect redux-freeze config in the frontend module.

**Comment by polaroidkidd** [comment]
confirmed, I'm working on a fix.

**Comment by polaroidkidd** [comment]
should be fixed with this PR https://github.com/LibrePhotos/librephotos-frontend/pull/65

**Comment by derneuere** [comment]
@dm7500 Did updating the docker images fixed your issue?
