### ISSUE TITLE
Explain directory structure

### ISSUE THREAD

**Issue by luckydonald** [LibrePhotos/librephotos#48]
So looking through the docker-compose file there are 4 folders the backend needs:
- data
- protected_media
- logs
- cache

Those are no where described.

1. It is not clear to me if my photos go into data or protected_media.
I sure want my media to be secure and protected?
2. Is the logs folder really needed? Shouldn't that end up in the docker stdout already?
3. Is the cache really needed in case of a container restart?

**Comment by atomicwrites** [comment]
I actually had the same question, it looks like data is the path to where you keep your photos and cache/log are obvious but i don't understand what is stored in protected_media.

EDIT: Now that I have my instance running and finished scanning I can see that `protected_media` is thumbnails. I just wonder if anything else could go there based on the super vague name.

**Comment by spex66** [comment]
Same here. wonder how to add more volumes to the list "Choose a directory from below"
Only "/data" shows up here atm.

**Comment by pathetic-lynx** [comment]
The [docker compose template](https://raw.githubusercontent.com/hooram/ownphotos/dev/docker-compose.yml.template) of ownphotos suggests it only contains thumbnails:

```
    volumes:
      - /photos/on/host:/data # CHANGE ME
      - /path/to/store/thumbnails/on/host:/code/protected_media # CHANGE ME
      - /path/to/store/logs/on/host:/code/logs # CHANGE ME
```

**Comment by derneuere** [comment]
This is now documented, because it's part of the docker setup.
