### ISSUE TITLE
Scanned Photos count larger than photos With Timestamped count

### ISSUE THREAD

**Issue by masterkrieger** [LibrePhotos/librephotos#482]
## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.04.4 LTS

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker version 20.10.14, build a224086
docker-compose version 1.25.0

### Are you running LibrePhotos on a virtual machine if so please list:
Proxmox VM of Ubuntu 20.04.4 LTS

### How is you picture library mounted on the host (or in the virtual machine):
NFS

### Description of issue:
Ran the Scan photos (Nextcloud) and shows that 2354 photos have been scanned. If I goto ` Photos -> With Timestamp`, then it only shows me 277 images. I can't find the rest of the images in `Without Timestamp`, `Recently Added`, `Hidden`, `Favorites`, or `My Public Photos`. I don't see any errors 
These are all images taken from my phone uploaded to Nextcloud with timestamps. 

### How can we reproduce it:
Install Docker images from Docker-compose method instructions on docs (https://docs.librephotos.com/1/standard_install/). Updated admin password, `httpPort=3002`, and `timeZone=America/New_York` in ".env" file. Then ran `docker-compose up -d` After logging into LibrePhotos, I entered the Nextcloud credentials with a new Nextcloud App Password and the Nextcloud Scan Directory status turned green. In the Admin Area, I added the scan directory and only option is `/InstantUpload`. Then I click the `Scan photos (nextcloud)` button and finishes the scan after a few hours.

#### Additional Information:

* Include a ZIP file containing your `log` files.
[librephotos_docker_logs.zip](https://github.com/LibrePhotos/librephotos/files/8445675/librephotos_docker_logs.zip)

* Provide pictures or links to videos that clearly demonstrate the issue.
![2022-04-07 14_41_05-LibrePhotos - Opera](https://user-images.githubusercontent.com/1848365/162277119-ac048fb8-1733-4307-9199-dfa2c2a0a4d3.png)
![2022-04-07 14_59_34-LibrePhotos - Opera](https://user-images.githubusercontent.com/1848365/162277120-be6eafc1-f177-47d0-8c51-78754f67c495.png)

**Comment by derneuere** [comment]
In the newest release, I tried to make the counting more consistent.

It could also be another issue. Please look into your data/logs folder. There should be a ownphotos.log file. Maybe another issue got logged there, which could explain the difference.
