### ISSUE TITLE
Delete doesn't delete large selections

### ISSUE THREAD

**Issue by fcimeson** [LibrePhotos/librephotos#484]
## 🐛 Bug Report
- Sorry, no log files as I I deleted them

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.04.1 LTS (server)

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
latest

### Are you running LibrePhotos on a virtual machine if so please list:
No

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (zfs)

### Description of issue:
When selecting a large number of photos for deletion, the action of deletion only deletes 50 or so but reports deleting the full amount.

### How can we reproduce it:
Do what I did.

#### Additional Information:
* No logs sorry

**Comment by loulou91** [comment]
I confirm this annoying bug. I wanted to delete 1700 photos included in a folder. After removing the 1700 photos from /data/xxx folder, I had to perform 6 cycles (rescan xxx folder, calculate clip embeddings, delete missing pictures) before having all photos completely deleted!!!

**Comment by meichthys** [comment]
I can also confirm that I've noticed the same issue. Smaller chunks of photos seem to delete ok.
