### ISSUE TITLE
Disable background timeline scrolling when using mouse scroll to zoom photo

### ISSUE THREAD

**Issue by AndrejErjavec** [LibrePhotos/librephotos#486]
In the web interface, when the mouse scroll is used to zoom in and out of the photo, the timeline scrolls as well. 
I would suggest fixing this issue by disabling timeline scrolling when a user is in photo viewing mode.

**Comment by polaroidkidd** [comment]
This one shouldn't be too difficult to fix and it seems super annoying UX. I'll look into it.
