### ISSUE TITLE
Getting logged out after five minutes

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#490]
### What Operating system and version is LibrePhotos running on:
It's dependent on the docker image for now.

### What architecture is LibrePhotos running on:
x64 and ARM

### How is LibrePhotos installed:
Docker dev image

### Description of issue:
As a user, I want to stay logged in while sorting my images. Currently, I will get logged out after five minutes and have to log in again.

### How can we reproduce it:
Login, wait for five minutes, do an action, get logged out

#### Additional Information:
We currently use [Simple JWT](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html) for handling auth. Each user has an access token, which has a very limited timespan and a refresh token which has a longer time span. The program should, when the access token is expired, get a new access token with the refresh token. I think the refreshing part broke while refactoring it.

**Comment by polaroidkidd** [comment]
I introduced the code that created this error, I'll fix it.

**Comment by derneuere** [comment]
Fixed :+1:
