### ISSUE TITLE
Please set the language Settings of some obviously, I can't find it

### ISSUE THREAD

**Issue by snailrend** [LibrePhotos/librephotos#496]
I passed the docker installation librephotos.
But I didn't found in any place where can set the language ([document](https://docs.librephotos.com/) or .env file but could not find),
Please help me, let me know where is it

**Comment by derneuere** [comment]
Each user can decide that for himself under the settings tab :)

**Comment by snailrend** [comment]
Ask questions after a minute, I find it.
Then I have another question, can the default setting the language of the new user?

**Comment by derneuere** [comment]
No not yet. Right now, the default language is the language of the browser of the new user, I think.

**Comment by snailrend** [comment]
> No not yet. Right now, the default language is the language of the browser of the new user, I think.

This seems to be enough, thank you for your reply actively

**Comment by derneuere** [comment]
No problem! I will close this issue then :)
