### ISSUE TITLE
Unauthorized: /api/rqavailable/

### ISSUE THREAD

**Issue by raphaelporsche** [LibrePhotos/librephotos#497]
Hi,
I wanted to install librephotos on my Odroid HC4 (arm64) for testing using docker-compose.

I followed the instuctions (cloned librephotos-docker, copied librephotos.env to .env, adjusted myPhotos and data nothing else) and started up librephotos.
The login screen turned into a create user screen, but the confirm button is greyed out:
![grafik](https://user-images.githubusercontent.com/70773164/168490822-6105a9bc-be42-4575-9a5d-be5571087029.png)
The logs are showing a lot of `Unauthorized: /api/rqavailable/` errors
```
backend     | Unauthorized: /api/rqavailable/
proxy       | 192.168.0.11 - - [15/May/2022:19:23:02 +0000] "GET /api/rqavailable/ HTTP/1.1" 401 89 "http://192.168.0.2:3000/login" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
```

Is there something I am not seeing here? What is it, I am doing wrong?
Thanks for your help!

**Edit 1**: I changed `latest` to `dev` but it's the same here.
**Edit 2**: Same behavior when I run libreoffice on my laptop (Intel i5-7200U).

**Comment by wdckwrth** [comment]
+1

Followed docker install instructions. No changes. The login screen comes up, I put in the default user and password, and get this pop-up.

<img width="485" alt="Screen Shot 2022-05-16 at 12 37 58 PM" src="https://user-images.githubusercontent.com/8429466/168641650-4b2e7795-93f1-4990-b0a3-7653eba4228c.png">

**Comment by derneuere** [comment]
I pushed a fix to dev :sweat_smile: It should be available in 20 minutes. Would be great if you can test it.

**Comment by raphaelporsche** [comment]
The behavior now changed:
![Screenshot_20220516_204843](https://user-images.githubusercontent.com/70773164/168661929-8c41c97d-95a4-438a-b823-599b783283e4.png)

The error message also changed to `Not Found: /api/user/undefined/`
```
backend   | Not Found: /api/user/undefined/
proxy     | 172.19.0.1 - - [16/May/2022:18:45:49 +0000] "GET /api/user/undefined/ HTTP/1.1" 404 54 "http://localhost:3000/login" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
proxy     | 172.19.0.1 - - [16/May/2022:18:45:49 +0000] "GET /api/user/ HTTP/1.1" 200 52 "http://localhost:3000/login" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
proxy     | 172.19.0.1 - - [16/May/2022:18:45:49 +0000] "GET /api/sitesettings/ HTTP/1.1" 200 108 "http://localhost:3000/login" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
proxy     | 172.19.0.1 - - [16/May/2022:18:46:38 +0000] "POST /api/user/ HTTP/1.1" 201 1924 "http://localhost:3000/login" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
proxy     | 2022/05/16 18:46:38 [info] 31#31: *3 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.19.0.1, server: , request: "GET /logo-white.png HTTP/1.1", upstream: "http://172.19.0.5:3000/logo-white.png", host: "localhost:3000", referrer: "http://localhost:3000/"
proxy     | 172.19.0.1 - - [16/May/2022:18:46:38 +0000] "GET /logo-white.png HTTP/1.1" 499 0 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
backend   | Not Found: /api/user/undefined/
proxy     | 172.19.0.1 - - [16/May/2022:18:46:38 +0000] "GET /api/user/undefined/ HTTP/1.1" 404 54 "http://localhost:3000/login" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
```

**Comment by raphaelporsche** [comment]
Now I was able to create a new user and log in, thank you very much!
Problem seems to be fixed :-)

**Comment by derneuere** [comment]
I am in the middle of a refactor to a new UI framework. If you find any issues, please let me know :)

**Comment by raphaelporsche** [comment]
Nice, I definitely will!
P.s. Greetings from Freiburg to Berlin.

**Comment by wdckwrth** [comment]
dev works here as well. Thanks!

**Comment by raphaelporsche** [comment]
@derneuere If I try to log in with UhuruPhotos I get the following error message in librephotos
```
backend     | Unauthorized: /api/auth/token/obtain/
proxy       | 192.168.0.122 - - [17/May/2022:15:41:51 +0000] "POST /api/auth/token/obtain/ HTTP/1.1" 401 94 "-" "UhuruPhotos/0.0.24 Dalvik/2.1.0 (Linux; U; Android 11; Mi Note 10 Lite Build/RKQ1.200826.002)"
```
Could it be, that this unauthorized error is related to this issue?

Edit: Turns out this was the problem https://github.com/LibrePhotos/librephotos/issues/487
