### ISSUE TITLE
Import photos from nextcloud into data folder

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#5]
Hey, I saw that there is some development in here, so I have some question / idea.

I noticed that when I imported photos from nextcloud, space on ssd drive where I keep my docker images and configs significantly increased, and when I checked what it was I saw that all data from nextcloud was copied into ownphotos image/container (not sure, I'm not an expert with docker). Is it possible to copy it to data folder instead? I'd prefer to keep photos on hdd with a lot of space.

**Comment by derneuere** [comment]
That sounds definitely like a more sane default. I changed it in the latest docker build. Could you test it and confirm that everything works?

**Comment by sysoppl** [comment]
Tested and working good
