### ISSUE TITLE
Separate "Unknown" faces section

### ISSUE THREAD

**Issue by AzAel76** [LibrePhotos/librephotos#501]
**Describe the enhancement you'd like**
A separate page where the unknown faces are listed rather than down in the Alphabetically sorted "U" section.

**Describe why this will benefit the LibrePhotos**
Manual face tagging and identification is a separate workflow and I believe deserves is own page.

**Comment by luk6173** [comment]
This would be a very useful enhancement, I have many Photos which are tagged as "Unknown - other"...

**Comment by kuzmos** [comment]
Support this. Scrolling to the middle of the faces to find Unknown - other takes a lot of lazy loading (roughly 130k photos in total).

**Comment by nagarrido** [comment]
I'm also up for this

**Comment by derneuere** [comment]
This is now implemented :)
