### ISSUE TITLE
Counter is not resetting on the face dashboard after doing an action

### ISSUE THREAD

**Issue by varet80** [LibrePhotos/librephotos#504]
# Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

When asking general "how to" questions:
- Please do not open an issue here join us on the Discord server  [LibrePhotos](https://discord.gg/xwRvtSDGWb)

**When Submitting please remove every thing above this line**

## 🐛 Bug Report

* [x] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Kubernetes

### If running via Docker or Kubernetes please list version including docker-compose:
Running images from 2022w21

### Description of issue:
I noticed that Selecting images is not working as before. What I mean by that is that frontend introduced a bug on image selection.

1. Selected counter goes only up
2. Images not clearly showing/stating which is selected and which not
3. Delete on face recognition/Infered page is not working  at all

### How can we reproduce it:
- Open Face recognition
- Open Inferred page
- Select an image
- hover out of the image, the image has no special background to show it is selected

Additionally:
- Select more images with Shift and or separate.
- they also get no backgroun

Counter:
Counter increases but do not decrease! Ever! 
When you deselect an image (even though is not visible) counter is not changing. But if you select it again it increases.

Delete is nto workign on Inferred images. did not try it in other

No special logs are.

Tested on:
Chrome, Firefox and Edge (mac and windows systems)

**Comment by edsonsbj** [comment]
I'm also having this problem and the counter gets more annoying when I'm grouping faces

**Comment by derneuere** [comment]
This issue should be resolved by this week's release. Would be great, if you could confirm that.

**Comment by varet80** [comment]
seems by 99% fixed.

I noticed:
Goto Infered tab:
Check many images
delete them
counter is not reseting (little bug)
