### ISSUE TITLE
search is not possible

### ISSUE THREAD

**Issue by edsonsbj** [LibrePhotos/librephotos#506]
### What Operating system and version is LibrePhotos running on:
Zorin OS 16

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
latest

### Are you running LibrePhotos on a virtual machine if so please list:
N/D

### How is you picture library mounted on the host (or in the virtual machine):
Native Docker volume and Nextcloud

### Description of issue:
After updating the search bar is not working properly

For example, if I search for 2015 and press enter as before, nothing appears and if I go to the suggestions, 2019 appears. Before it was possible to even search for the name of the directory where a particular photo was.

### How can we reproduce it:
do a search

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by derneuere** [comment]
This issue should be resolved by this week's release. Would be great, if you could confirm that.

**Comment by edsonsbj** [comment]
thanks friend i just updated and this problem was solved
