### ISSUE TITLE
autoalbum ; photo not classified in a very simple context

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#511]
Version dated 2022-06-01

In my base I included today (from empty base) 2 videos dated 1st of June, and one picture dated 19 of May. Result is ok ;-)
I requested auto-album generation, but I got only one album including only the 2 videos. Log is there:
[log.txt](https://github.com/LibrePhotos/librephotos/files/8815786/log.txt)
![image](https://user-images.githubusercontent.com/51127123/171447848-c44679e4-8470-4ce9-80e6-e6ef52c7b681.png)
![image](https://user-images.githubusercontent.com/51127123/171448148-8ae2befa-cb39-4545-bd9e-201e281f52f5.png)

**Comment by 5m4u66y** [comment]
I see nothing buggy in the result you obtained.
Currently, autoalbum algorithm groups photos if they were taken in a 36 hours time period. 2 photos taken in this time delta is enough to create an autoalbum. I don't expect LibrePhoto to create one autoalbum for each individual photo in my library.
I personally think that the system is already making way too many autoalbums. I have 939 autoalbums in my library, only 100 or so make sense to me. Most of the time I don't want an autoalbum for only 2 photos taken in a 36 hours period. I would like to increase the minimum number of photos. Maybe it would be could to make the number of photos and time period settings that can be changed by the user.

**Comment by loulou91** [comment]
The problem was (at that time) 3 photos but 1 album containing only 2 photos? Where is the 3rd one?
I will try to test it again.

**Comment by 5m4u66y** [comment]
> Where is the 3rd one?

The 2 videos (dated 1st of June) makes an autoalbum, this is OK with the algorithm. The 3rd media, a photo dated 19 of May is not within a 36 hours period with any other media, so it is normal there is no autoalbum for this one.

**Comment by loulou91** [comment]
Looks logical! I thought ALL photos would be included in an album...
I close the issue!

ps: could you have a look to improvement #463?

**Comment by loulou91** [comment]
closed.
