### ISSUE TITLE
Request: Face Label Removal

### ISSUE THREAD

**Issue by flaurafauna** [LibrePhotos/librephotos#514]
**Describe the enhancement you'd like**
Be able to remove a face from a person without deleting the face and thumbnail.

**Describe why this will benefit the LibrePhotos**
It'll make it easier to correct mistakes made when identifying faces without prompting a full rescan.

**Additional context**
I'm training faces and occasionally you add a face to a person that it doesn't belong to. No big deal, unfortunaely, there's no way to just remove the face label. My options are move it to another person (which I don't want to do, since it's a random face that got mixed in) or delete the face altogether, which makes the system no longer recognize it as a face (this is not super helpful if I then want to go search for faces or if I find out the name of the individual later and then want to add them). To get that face back I have to rescan the entire database for faces which is inredibly annoying as I have tens of thousands of photos.

**Comment by RubenKelevra** [comment]
Actually I see this *a lot*. Faces are very often attributed to the wrong people in my test so far with 4000 pictures, while it found around 250 faces.

@derneuere 

How about restructuring this two pages below face recognition:

- Persons
- Unknown

### Persons

Contains a short list of some pictures of the person and all non-approved recommendations for this person.

### Unknown

Contains a list of faces grouped together like in the face cloud view (but as a normal picture list), to make it easier to select all pictures of the same person.

---

Additionally a threshold for "auto confirm" could be set, something like 98% or similar.

**Comment by derneuere** [comment]
I think it will get better once #284 is implemented. We even found somebody who is currently working on it! We will then have only clusters of images, which should be a unique person.

In general this should not be hard to implement as you can already do that. Change it to the Person "Unknown" in order to have the functionality described here.

**Comment by derneuere** [comment]
This will be in the next release :)
