### ISSUE TITLE
HMI crash when "small thumbnails" is set to "on" in profile page

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#519]
When "small thumbnails" is set to "on" in profile page, HMI crashes time to time with such screens:
![image](https://user-images.githubusercontent.com/51127123/173224982-3624c42c-2e60-41f4-9082-209fcb3a7e20.png)

Moreover display of pictures in "photos" page is much slower than when "small thumbnails" is set to "off".

At least an other user encountered same types of behavior.

**Comment by derneuere** [comment]
Should be fixed now. Would be great if you could test it again :)
