### ISSUE TITLE
Scan percentage not rounding correctly.

### ISSUE THREAD

**Issue by DigitalWarrior** [LibrePhotos/librephotos#52]
Should be either a xx% or xx.xx%
![image](https://user-images.githubusercontent.com/802654/103251684-fdcc0500-4936-11eb-889d-de47f694a086.png)

**Comment by el-tiuri** [comment]
As far as I've seen, this occurs at every multiple of 7, and in no other case.

**Comment by alexislefebvre** [comment]
It looks like a floating number error, this number should be rounded to something like 2 decimals. See https://0.30000000000000004.com/

**Comment by tomamplius** [comment]
reproduce and solved 
![image](https://user-images.githubusercontent.com/6951820/110866777-f4133600-82c5-11eb-8628-a7a2434bdff0.png)

**Comment by tomamplius** [comment]
fix with merge
