### ISSUE TITLE
Frontend: Placeholder strings in set-public toast notification

### ISSUE THREAD

**Issue by stnokott** [LibrePhotos/librephotos#521]
The toast notification(s) for setting/unsetting a photo as public, a placeholder value (probably the i18n key) is displayed for the notification description.
Assuming, it is indeed the key, it is also not present in the Weblate project.

Steps to reproduce:
1. Open photo from "Photos" sidebar menu
2. Click button to set/unset public
![image](https://user-images.githubusercontent.com/30934296/173346143-d154d88a-386e-4352-a893-b63b16f48707.png)
3. See notification with placeholder value
![image](https://user-images.githubusercontent.com/30934296/173346066-3e60fafb-6c44-4508-9fb8-7cec5ff1de9a.png)
4. Press button to set/unset again
5. See different placeholder
![image](https://user-images.githubusercontent.com/30934296/173346033-43d8edae-0435-425d-baec-9059787c4021.png)

Running in latest non-singleton Docker containers (`2022w22`).

**Comment by derneuere** [comment]
Thanks for reporting the issue. It should be now fixed in 2022w24 :)
