### ISSUE TITLE
Issues with photos selection in face recognition page

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#523]
Win11 Chrome HMI
1/ multiple faces selection using click and shift click: It works well if selection is done top-down, but if selection is done down-top, the first selected photo (the one which is down) is unselected after shift click.

2/ switch selection top left: when we enter the page, it is grey (0 selected). If I select at least one photo, it becomes blue with the number of selected faces. Now if I click on the switch it goes back to grey but the number of selected photos is unchanged! Moreover, despite the fact that previously selected photos look unselected (no more blue frame) it is possible to delete them or associate them to a person.  The inconsistency of the display is confusing and may lead to mistakes.
According to me the best would be to really unselect all photos when clicking on the switch.

3/ the blue frame around a selected photo is too light (for my eyes ;-)). A more contrasting blue would better to immediately see what is selected or ot.

**Comment by jorgecorrea** [comment]
I agree with third point, and it's very easy to solve, putting a darker colour

**Comment by loulou91** [comment]
Today, 2/ looks closed 3/ better but I would appreciate more contrast!

**Comment by derneuere** [comment]
Deselecting of the first faces is no longer happening on dev :)
