### ISSUE TITLE
Keep existing directory structure of media.

### ISSUE THREAD

**Issue by TheAnachronism** [LibrePhotos/librephotos#526]
**Describe the enhancement you'd like**
This is something that I see many photo library tools don't do, and I still don't understand why. Why isn't it possible to be able to traverse the entire library the same way as it is organized in the filesystem? If all the grouping and organizing of the entire library as already been done on filesystem level, shouldn't it be possible to just have this exact view in the web interface?  I have a considerable collection of photos/videos that are already organized in their subdirectories, so it would be extremely helpful if that exact structure could be imported into LibrePhotos without having to build it again by manually creating these albums.

**Describe why this will benefit the LibrePhotos**
For people who have all their media in just one directory as it might come out of a phone or so this won't help much. But people who have organized their collections in to separate directories wouldn't have to redo it inside LibrePhotos.

**Comment by derneuere** [comment]
This sounds like you want something like this: #271 I closed this issue as this seems to be a duplicate :)
