### ISSUE TITLE
Support for Video

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#53]
A missing feature is support for video files.

We would need to change the data model to add video.
https://github.com/LibrePhotos/librephotos/blob/289f413c303bc06e04de2c8c8decb764ba86481c/api/models.py#L107

We would also need to change the scanning mechanism.
https://github.com/LibrePhotos/librephotos/blob/289f413c303bc06e04de2c8c8decb764ba86481c/api/directory_watcher.py#L110

Not only that, but we would need to implement #10.

Likewise, we have to implement the thumbnail creation function. We should probably use FFmpeg with a python wrapper for that. Do we want a single thumbnail or a sprite preview? 
We need to implement the calls for face classification, scene detection and object detection. We also need to decide if we only analyze the thumbnail/sprite preview or the whole video file (needs GPU support)

Then we have to change and create the API calls to display videos together with pictures and allow to open a picture. Do we need to implement transcoding?

The last step would be to refactor the light box, so that it can display videos.

**Comment by mprajescu** [comment]
It is a feature that many are looking for and I think the easiest way to have it is with a thumbnail but a sprite that would “play” when you hover it would be amazing. 

I don’t think transcoding would be on the top of the list, but decoding/encoding with GPU would be a must for self hosting at home.

for example, you shoot your videos with iPhone in 4K, you upload it to your home server, it converts the video into a web friendly full HD MP4.

I can help with testing, because I’m waiting for a feature like this plus have it setup with  SSO with keycloak and then this will be my family’s cloud photos and video repository.

The most important feature would be to use ffmpeg with GPU or Intel quick sync.  

I’m still struggling to understand how to pass through an Nvidia p400 to a docker container, but hopefully it is something that can be clearly documented somewhere.

**Comment by thelittlefireman** [comment]
Hi,
Great idea. If you need to add hardware encode decode with gpu on a container you just need to mont a device with
 ```
--device /dev/dri/renderD128:/dev/dri/renderD128 \ --device /dev/dri/card0:/dev/dri/card0
```

See jellyfin github for more informations.

About enabling hardware acceleration with ffmpeg you just need to add ` -hwaccel` as ffmpeg option. See [https://trac.ffmpeg.org/wiki/HWAccelIntro](https://trac.ffmpeg.org/wiki/HWAccelIntro)

**Comment by samster395** [comment]
How soon is this feature likely to be added?

Just asking because i'm thinking of switching and video support is important to me.

**Comment by derneuere** [comment]
It is now added :)

**Comment by aryaniyaps** [comment]
@derneuere I am curious how this has been implemented. I can still see that the data model
has an "ImageField" and no fields for storing videos separately.

Thanks!

**Comment by derneuere** [comment]
@aryan340
The ImageField "image" isn't used I think, but I have to test that before removing it. 

We basically only save paths in the thumbnails ImageFields and redirect the requests accordingly. For videos, we use the actual file path.

I added a "BooleanField" called video to the photo entity. https://github.com/LibrePhotos/librephotos/blob/bd4fabf104ea818a4b8fae61e6e41c08ad89ba16/api/models/photo.py#L61 

This will get set when scanning, when it is an video. I figure that out with magic: 
https://github.com/LibrePhotos/librephotos/blob/bd4fabf104ea818a4b8fae61e6e41c08ad89ba16/api/directory_watcher.py#L19-L22 

Then I added that field to the Serializers here:
https://github.com/LibrePhotos/librephotos/blob/bd4fabf104ea818a4b8fae61e6e41c08ad89ba16/api/serializers.py#L95-L106

I added a new API Endpoint that resolves /api/media/<hash>. I will check if the user has a valid jwt token, look for that hash in the database and then create a response with a X-Accel-Redirect to the actual file. You can see that part here: https://github.com/LibrePhotos/librephotos/blob/bd4fabf104ea818a4b8fae61e6e41c08ad89ba16/api/views.py#L1678-L1690

Then I had to change the nginx config to resolve the new file paths:
https://github.com/LibrePhotos/librephotos-docker/blob/7713e6ffecddb5542c7b8cc767a32703887b0b85/proxy/nginx.conf#L38-L41

The last step was adding a ReactPlayer component and checking if the photo is actually a video here:
https://github.com/LibrePhotos/librephotos-frontend/blob/86b2bb61b4a3e43e200d3fe22766b92c73c30e74/src/components/lightBox.js#L140

**Comment by aryaniyaps** [comment]
thanks for the detailed explanation!
