### ISSUE TITLE
Scan finished messages

### ISSUE THREAD

**Issue by darrepac** [LibrePhotos/librephotos#536]
Hi,

After several days running the scan, everything is now finished.
I got now, tens of messages "scan finished" and "calculate clip embeddings"... One should be enough

Running LP on docker (pulled June 21)
![image](https://user-images.githubusercontent.com/7128994/176831987-a26dc90c-e4d6-475f-9f3f-e701e47e9e34.png)

**Comment by derneuere** [comment]
@polaroidkidd This should be fixed now with the new RTK queries, right?

**Comment by polaroidkidd** [comment]
Oh ~~shit~~ poop, no I forgot that one. I'll do it in the few days
