### ISSUE TITLE
2 scolling bars on "faces recognition" page

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#537]
In bug report #517 I noted that there was some problem to see scrolling bar with dark mode in faces recognition page. I understand a bit more now.
On that picture (standard mode) you can see that 2 scrolling bars are present on the right of the screen. A thin one and a large one. And only the thin one is usable.
![image](https://user-images.githubusercontent.com/51127123/176991934-4e2679ff-c637-49c6-9cbd-854df0d04f42.png)

I also noted that the design of the scrolling bar is not the same for "photos" page (large scrolling bar) than for "things" and "album" pages (thin one). Personally I prefer "photos" scrolling bar than others.
![Capture d’écran 2022-07-02 095702](https://user-images.githubusercontent.com/51127123/176992457-cabbdbb0-b2cb-4516-a896-dfe1cf62bed1.jpg) ![Capture d’écran 2022-07-02 095613](https://user-images.githubusercontent.com/51127123/176992458-206cceb3-495a-4333-83a8-d497f2ef07d9.jpg) ![Capture d’écran 2022-07-02 095431](https://user-images.githubusercontent.com/51127123/176992459-9ad98daf-81cf-41b8-9f52-c2b28097b727.jpg)

**Comment by derneuere** [comment]
Fixed the bug! The thin scrollbar will look like the one in photos, once we migrated away from the old framework :)
