### ISSUE TITLE
Sidebar UI not shown fully when OS scaled up

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#538]
## 🐛 Bug Report

* [] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:

Ubuntu linux using the dev docker tag. Web UI viewed on Windows 11 with 300% scaling

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:

:dev

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type)

### Description of issue:

The side bar on the main ui is cut off when the windows scaling is set to 300% (notice the trash icon is not visible)

![image](https://user-images.githubusercontent.com/873077/177200270-5162ed72-e65e-42fa-ac9f-27a8c011f6be.png)

### How can we reproduce it:

Set window scaling to 300% and notice the sidebar

**Comment by derneuere** [comment]
I think this is now solved with the new sidebar :)
