### ISSUE TITLE
Video Thumbnails broken when adding videos to album

### ISSUE THREAD

**Issue by meichthys** [LibrePhotos/librephotos#541]
![image](https://user-images.githubusercontent.com/10717998/178057589-7091adfc-aa08-4f07-be78-c9a04796a062.png)

## 🐛 Bug Report

* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Docker image

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### Description of issue:
When adding videos to an album, the video thumbnails are broken.

**Comment by meichthys** [comment]
This may only be an issue in Firefox (v102). 
I can not reproduce the issue in Safari.

**Comment by derneuere** [comment]
The relevant code is here: https://github.com/LibrePhotos/librephotos-frontend/blob/e148728758d6f649492dc710a17588b9c02fff83/src/components/album/ModalAlbumEdit.tsx#L61

**Comment by stbkde** [comment]
Same issue in Google Chrome.

**Comment by derneuere** [comment]
This should be fixed now :)
