### ISSUE TITLE
Uploading multiple pictures fails 

### ISSUE THREAD

**Issue by RubenKelevra** [LibrePhotos/librephotos#542]
**When Submitting, please remove every thing above this line**

## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
ArchLinux

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker version 20.10.17, build 100c70180f

### Are you running LibrePhotos on a virtual machine if so please list:
no

### How is you picture library mounted on the host (or in the virtual machine):

Local file system (ZFS)

### Description of issue:

When selecting more than one file the progress bar jumps a bit around and then stops to show completion of one picture upload. When refreshing the first picture of the selection will be added, but the rest not - regardless how long I wait for the progress to be completed.

I've tested this via http to localhost in Firefox 102.0.1 and Chromium 103.0.5060.53. Exactly same behaivor.

What's really weird is that the browser will consume a lot of CPU power to do basically nothing. (Chromium 60% of one core / Firefox a bit more). 

### How can we reproduce it:

Not sure, it's 100% reproduceable for me. So not sure why this wasn't seen before by other users.

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by RubenKelevra** [comment]
This may be related to KDE or Linux. Somehow I think librephotos is getting one file twice and thus refuses to continue:

```
rerendering [PhotoListView.tsx:85:10](http://localhost:3000/static/js/components/photolist/PhotoListView.tsx)
rerendering [PhotoListView.tsx:85:10](http://localhost:3000/static/js/components/photolist/PhotoListView.tsx)
Array [ {…} ]
[computeLayoutGroups.js:17:10](http://localhost:3000/static/node_modules/react-pig/src/computeLayoutGroups.js)
rerendering [PhotoListView.tsx:85:10](http://localhost:3000/static/js/components/photolist/PhotoListView.tsx)
Array [ {…} ]
[computeLayoutGroups.js:17:10](http://localhost:3000/static/node_modules/react-pig/src/computeLayoutGroups.js)
total size: 1202445 [ChunkedUploadButton.tsx:159:12](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
528857 [ChunkedUploadButton.tsx:37:18](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
current size: 528857 [ChunkedUploadButton.tsx:163:12](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
305879 [ChunkedUploadButton.tsx:37:18](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
528857 [ChunkedUploadButton.tsx:37:18](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
File already uploaded [ChunkedUploadButton.tsx:150:18](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
current size: 834736 [ChunkedUploadButton.tsx:163:12](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
367709 [ChunkedUploadButton.tsx:37:18](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
current size: 367709 [ChunkedUploadButton.tsx:163:12](http://localhost:3000/static/js/components/ChunkedUploadButton.tsx)
```

Money quote: "File already uploaded"

**Comment by spencerlundgren** [comment]
I am experiencing the same behavior 100% of the time when uploading more than one photo.

Running through docker on Debian 11

**Comment by RubenKelevra** [comment]
@spencerlundgren is this a regression for you? Or has this never worked before?

**Comment by spencerlundgren** [comment]
@RubenKelevra I just barely installed librephotos for the first time this week, and it has not worked the whole time.

**Comment by RubenKelevra** [comment]
@spencerlundgren wrote:

> @RubenKelevra I just barely installed librephotos for the first time this week, and it has not worked the whole time.

Gotcha, can you share specifics, like platform browser, docker version etc to narrow it down?

Thanks

**Comment by meichthys** [comment]
It looks like it probably never worked for multiple images. I could be wrong, but the code in 'api/views/upload.py' seems to indicate that it expects only a single image.

I can reproduce this by trying to upload two images. An exception happens [here](https://github.com/LibrePhotos/librephotos/blob/5aa5e5a7bd0b07f7a3846a4c9d34a5844bcba9da/api/views/upload.py#L74) which indicates that the `uplaods` directory didn't exist, however when i check, it does actually exist.

**Comment by meichthys** [comment]
To follow up on this, the dependency we rely on for uploads ([Django-chunked-upload](https://pypi.org/project/django-chunked-upload/#data)) doesn't currently support multiple files. 

For reference, the Django docs have a sample setup for multiple file uploads: https://docs.djangoproject.com/en/dev/topics/http/file-uploads/#uploading-multiple-files

**Comment by derneuere** [comment]
We upload the images/videos sequentially, so that should not be the issue. This is relevant code in the frontend: https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/components/ChunkedUploadButton.tsx

I can upload multiple files on the demo server. I think that not uploading at all could be a file permission issue.

I did however notice, that the upload progress bar, jumps around, and then gets locked up, even though the images did get uploaded.

**Comment by spencerlundgren** [comment]
> I can upload multiple files on the demo server. I think that not uploading at all could be a file permission issue.

I think that the OP mentioned that the first file selected does get uploaded, but not the others. That is the same behavior that I am seeing as well.

**Comment by derneuere** [comment]
I fixed the fault progress bar. The images also get uploaded and are in the upload folder, but do not show up as python rq and django rq do not enqueue more then job for some reason.

This is the relevant part, if somebody wants to look into it:
https://github.com/LibrePhotos/librephotos/blob/ee8660d76b8e559f819785dfffb0e94076185d3f/api/views/upload.py#L100-L101

**Comment by derneuere** [comment]
We now start a new scan job that only scans the upload directory instead. This should fix it. It is currently available on the dev tag and will be available in a week in latest.

**Comment by RubenKelevra** [comment]
Ah cool, thanks for the fix!

@derneuere Is the upload currently limited by the processing speed? I mean can the browser continue to upload the second file as soon as the first one has been completed, or does it need to wait for the analysis to take place?

**Comment by derneuere** [comment]
We calculate a md5 hash to look if the file is already uploaded. This calculation should be fast, but can take a second for large files, I think. The other processing like face recognition happens independently of uploading.
