### ISSUE TITLE
Aborting a job leads to an unlimited amount of toast-popups about its completion

### ISSUE THREAD

**Issue by RubenKelevra** [LibrePhotos/librephotos#547]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Arch Linux 

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
2.6.1

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (ZFS) 

### Description of issue:
I started a scan of newly added pictures. While it was undergoing I've added additional pictures, that's why I wanted to restart the task. 

So I went to the admin panel and stopped it. 

Then there's a toast popup like once a second about completion of this task (which sounds more like a success message btw) repeatedly, until I reload the page. 

### How can we reproduce it:
See above 

---

I've seen the help text stating that the "remove" isn't going to stop the task - but the task gets shown as aborted in the view afterwards... mh.

![Screenshot_20220715_130913-1](https://user-images.githubusercontent.com/614929/179212265-e241418d-82b7-4868-8cd5-2e39d9e573cc.png)

**Comment by meichthys** [comment]
This is also applicable to scans that finish successfully: #536

**Comment by polaroidkidd** [comment]
whoops, yes. That probably has something to do with this line here [/src/hooks/useWorkerStatus.ts#L28](https://github.com/polaroidkidd/librephotos-frontend/blob/b9fce8714d6d834c1f8e6df2433045827e36a651/src/hooks/useWorkerStatus.ts#L28)

I think I'll have to add a case where it handles canceled jobs there.

**Comment by derneuere** [comment]
@polaroidkidd This should be fixed now with the new RTK queries, right?

**Comment by polaroidkidd** [comment]
no. I actually just found out that the "finished" notifications are a bit broken. Are jobs asynchronous in the backend? is there a que they enter? do they exit FIFO wise or "which ever job finnishes first" and a round-robbin of sorts jumps back and forth between jobs?
