### ISSUE TITLE
URLs to photos other than jpg format will get ".jpg" ending, which is confusing

### ISSUE THREAD

**Issue by RubenKelevra** [LibrePhotos/librephotos#552]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Arch Linux

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
2.6.1

### Are you running LibrePhotos on a virtual machine if so please list:
no

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (ZFS)

### Description of issue:
If a PNG is stored in LibrePhotos and selected for a large preview the original file name will be displayed on the right, like "/data/imported/IMG_20220615_122657_2.png". But the link generated to access the file will not end in `.png` but `.jpg`:

```
http://localhost:3000/media/photos/6f933986222c8b32a548ab128812cde71.jpg
```

### How can we reproduce it:
- Add a png file
- Click on it on the overview
- Click on the encircled I-Icon
- Click on the Link which shows the path
- The browser will load a png with `.jpg` ending in the URL.

**Comment by derneuere** [comment]
This is now fixed :)
