### ISSUE TITLE
Can't see the customized albums after creating the second album

### ISSUE THREAD

**Issue by pegasusknightyf** [LibrePhotos/librephotos#554]
When I create my first album, everything goes OK.

After I create the second album, I go back to "My albums" page. Then I can't see all of my albums...  

I tried restarting the docker container, but it still not work.

The backend log says:
Unauthorized: /api/user/1/
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/albums/user/list/ 

![chrome_j9k0FhCoeR](https://user-images.githubusercontent.com/50168059/180040249-48482b65-f666-4955-b4c0-bc1fd62be26b.png)
![chrome_JxiCqUpMse](https://user-images.githubusercontent.com/50168059/180040264-e29d7adb-1e16-45c6-8d21-5c32076c59be.png)

**Comment by stbkde** [comment]
Same issue here. I don't see any of the created albums.

> LibrePhotosOS

> Browser:
Firefox: 103.0 (64bit)
Chrome: 103.0.5060.134 (Official Build) (64-Bit)
Chromium: 103.0.5060.134 (Official Build) Arch Linux (64-Bit)

**Comment by derneuere** [comment]
@pegasusknightyf  It would be great, If you could add some information, because I can't recreate the issue. How did you install LibrePhotos?

**Comment by lephuochung18** [comment]
I've the same issue fresh install after create 2nd album it disappear.

**Comment by pegasusknightyf** [comment]
@derneuere, I installed it in docker

**Comment by pegasusknightyf** [comment]
OH, I find that if I  access to the database manaully, delete all the old album data, then go back to the frontend and create new albums, the issue disappear...

**Comment by dotanm** [comment]
@pegasusknightyf , can you please write here which tables did you clear?

In my case I'm not seeing any albums to begin with, but I thought maybe purging the personal albums may solve the issue.

**Comment by pegasusknightyf** [comment]
> @pegasusknightyf , can you please write here which tables did you clear?
> 
> In my case I'm not seeing any albums to begin with, but I thought maybe purging the personal albums may solve the issue.

I clear the following two tables:
api_albumuser, api_albumuser_photos

**Comment by derneuere** [comment]
This was probably a csrftoken auth issue, which should be fixed in the next release :)
