### ISSUE TITLE
New user "deleted" is in the database 

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#557]
An unknown user "deleted" started to appear after #553. This could also be related to the scanning no longer working.

**Comment by derneuere** [comment]
@jakekapellen

**Comment by jakekapellen** [comment]
This appears to be an existing issue that is only made apparent with the new functionality. I don't think there was previously a workflow to delete a user, so I don't know if get_deleted_user was ever called before. Let me know if that assumption is wrong.

I can set the user to inactive when it gets created, then filter inactive users from the views. That will take some regression testing, so expect a pull request when I'm done.

**Comment by derneuere** [comment]
No, we do not use get_deleted_user yet, as you can only add new users, but can't delete any. I think your suggestion should work 👍
