### ISSUE TITLE
Show years in the scrollbar when scrolling through pictures

### ISSUE THREAD

**Issue by jakekapellen** [LibrePhotos/librephotos#562]
**Describe the enhancement you'd like**
When scrolling through large libraries with multiple years of data, it isn't easy to find an approximate point in time without guessing how far down to jump. It would be nice to be able to see the years next to the scrollbar when scrolling to make it easier to jump.

Alternatively, a "jump to" option at the top would be okay, but significantly less usable.

**Describe why this will benefit the LibrePhotos**
When looking through large amounts of photos, it takes trial and error to find what you are looking for.

**Additional context**
Other programs (e.g. Google Photos) have something like this.

**Comment by ChrisFab16** [comment]
Similarly, this would be great in the "Faces" view to get a highlight of which name you got to when using the scrollbar

**Comment by wjbeckett** [comment]
Absolutely would love to see this implemented.

**Comment by lilfade** [comment]
Here to vote on this feature as well, would help me with my medium-sized library.

**Comment by 5m4u66y** [comment]
Implemented in LibrePhotos/librephotos-frontend#133
This issue can be closed.
