### ISSUE TITLE
"My albums" page blank

### ISSUE THREAD

**Issue by RandomHacks-Git** [LibrePhotos/librephotos#564]
I run librephotos on docker and have the latest pull.

When I go to "my albums" I'm redirected to a completely white page and get this on the backend log:

![imagem](https://user-images.githubusercontent.com/22402348/180558618-9fa04c55-ac6a-4ef6-8fa3-97e35f666576.png)

If I go to /shared/fromme/photos/ I don't see my shared album and get this on the backend log:

![imagem](https://user-images.githubusercontent.com/22402348/180561931-2c961b32-be61-4432-8cac-979ab357e52a.png)

I am able to access my album directly by going to /useralbum/1

**Comment by derneuere** [comment]
The bug should now be fixed in dev :) Thank you for reporting the bug!
