### ISSUE TITLE
Significant Client Performance Issue in FaceDashboard With Large Databases

### ISSUE THREAD

**Issue by jakekapellen** [LibrePhotos/librephotos#565]
I noticed that the FaceDashboard page slows to a crawl when you have large databases (like the faces dataset you sent me with 13K faces). In particular, I noticed that clicking any face takes longer than expected for a simple selection action, and multi-select seems even slower, where there is a noticeable pause.

I dug more into this with React Profiler. It turns out that React is entirely refreshing the FaceDashboard component every 200-400ms, and the refresh itself takes about 200-300ms, leaving little time for much else. It isn't noticeable with smaller datasets, but at scale the page really crawls. I dug into the hooks that are triggering (React Profiler has a nice option where it can record the renders and explain why things are re-rendering), and a vague "Reducer" property that simply is an integer seems to increment during that time, but nothing else changes.

I tried running the same workflow on earlier versions of the client, and the degradation is still there. It definitely occurred after the original migration of FaceDashboard to tsx (commit ab86fe708a3e43ec431d9a77578a42a3ad93a072 on May 18); this weird constant rerender doesn't occur before that, but it is present later on (at least by commit cd22272c21d1c11bcf6c5fc568139d2737c39b54 on May 24).

**Comment by derneuere** [comment]
I wrapped the Dashboard in a React.Memo and I think it is now faster. Can you confirm that, or is it still too slow?

**Comment by jakekapellen** [comment]
This helped a bit (perf hit gone from 250ms to 150ms), but rerenders are still happening regularly when you aren't interacting with the form. One of the triggering hooks has gone away, but it is still responding to another subscription, somehow. The React Profiler label for it is "SyncExternalStore" which clearly is a reference to the store, but I can't tell which specific selector is being referenced.

**Comment by jakekapellen** [comment]
With further testing, I rescind my previous comment; I don't think the performance hit decreased (about 250ms again in another test run). That said, I did notice a pattern. The refreshes come in pairs spaced .2s around every 2 seconds (so at 0s, 0.2s, 2s, 2.2s, 4s, 4.2s, etc.). This makes me think that it is indirectly caused by the worker polling (which happens every 2 seconds, right?).

**Comment by derneuere** [comment]
@polaroidkidd was working on a similar issue that affected the whole app. Maybe he has an idea why that's happening. I also can't find the reference for the polling of the worker status, but it looks like it 😅 

We could narrow the memo down even further, so that it only re-renders if inferredFaceList or labeledFaceList gets changed, similar to how we did it in PhotoListView: https://github.com/LibrePhotos/librephotos-frontend/blob/2c4182138beb03704b24cd6f2c81392ed17d0871/src/components/photolist/PhotoListView.tsx#L379-L382

**Comment by polaroidkidd** [comment]
This sounds like one the time timeout requests we have somewhere in the codebase. I previously refactored the workerindicator into it's own hook (which introduced a notification bug when you delete jobs). Previously this resulted in the entire app rerendering every 2000ms. There are two more (one in the AdminPage, which I'm currently rewriting  [here](https://github.com/polaroidkidd/librephotos-frontend/blob/bff5fc149633d4e2c261377a2481b027224a9af9/src/layouts/settings/AdminPage.tsx#L156), and there's another one in here [/src/components/CustomSearch.tsx#L48](https://github.com/polaroidkidd/librephotos-frontend/blob/bff5fc149633d4e2c261377a2481b027224a9af9/src/components/CustomSearch.tsx#L48).

I have a sneaking suspicion that this is what might be causing re renders, but I haven't tested it yet.

I'm just throwing it out there that I'm an _occasional_  contributer.  If you see a quick and easy fix to sort this out (and maybe possibly migrate more stuff to RTK query/api), be my guest.
