### ISSUE TITLE
On the demo server, the UI is very choppy/messy, is this the expected experience?

### ISSUE THREAD

**Issue by ioogithub** [LibrePhotos/librephotos#566]
Before committing many hours to learning and implementing a gallery I am trying demos.

When I try the demo at https://demo2.librephotos.com I see several issues:

1. When I scroll up and down the header bar "Photos 25 days, 229 photos" flickers. When every scroll it disappears 75% of the way up the screen then redraws itself. The effect looks awful, almost like the bar is dancing around the screen.

2; If I click on the three dots menu then scroll up or down, the effect is even worse than the header bar. I can see the menu redrawing itself a different percentage of the screen every time. Sometimes I can see the photos behind the bar.

These effects looks very messy and unresponsive.

3. Several times I pressed one of the buttons at the bottom and it took me to a black page. When I tried to navigate back I also got a blank page that never recovered. I had to reload manually.

Are these normal and expected behavior from librephotos? I know that pwa can apps suffer from lag and are generally not as responsive as native apps but this is a whole other level of low performance.

I wanted to get other users feedback before committing time and energy to learning and implementing this project.

**Comment by meichthys** [comment]
Welcome to the community,

I have not noticed these exact same issues, but there are definitely a lot of touchups needed to the UI to make it more responsive and consistent. I am also looking at getting involved to help out but will probably be contributing to the backend since I am more familiar with python than react.

**Comment by derneuere** [comment]
Hey @ioogithub, we provide a bug template for a reason. I need to know which Browser you used and if you installed any plugins, that could result in this issue. I also need reproducible steps. 

LibrePhotos does currently not "flicker" in Chrome or Firefox and has a couple of minor issues in Safari. It also doesn't lag in the demo instance, and there are no blank pages when clicking buttons.

Also change your tone. Otherwise, I will give no further free support.

**Comment by ioogithub** [comment]
> Also change your tone. Otherwise, I will give no further free support.

This sounds like a command. How much do you usually charge for your support at trying the demo? I'm not even a user yet, I tried to run the demo and reported first impressions and performance issues. None of my feedback referenced you personally. Your point on using the template is valid however if genuinely intended feedback results in hostility and threats go ahead and close the ticket. I was looking for a non-toxic, photo gallery project.

Below this post GitHub has posted a Community Guidelines link, perhaps you could review the parts on respect and empathy.

**Comment by meichthys** [comment]
> a whole other level of low performance.
> 

You may not have meant it to sound derogatory, but this doesn't come across as "genuinely intended feedback".
Perhaps you can resubmit a new issue with some extra information using the bug template so we can investigate specific issues with specific details.

**Comment by ioogithub** [comment]
I guess it is challenging to provide non-positive feedback. My comment was not meant to be hurtful but to express my astonishment at what I was seeing. The demo site UI is breaking up, jumping around, the side menu is redrawing itself 70% on a jagged diagonal at every scroll tick for a fraction of a second then disappearing and the top menu is flickering and jumping around.

It looks so awful that I had to ask if this is the expected performance because I have never seen this before.

Thank you [meichthys](https://github.com/meichthys) for answering my question.

Anyway I won't pursue the issue further as I can infer the answer from @derneuere the response.
