### ISSUE TITLE
train_faces job failing, even with multiple people created

### ISSUE THREAD

**Issue by tr1plus** [LibrePhotos/librephotos#568]
**When Submitting please remove every thing above this line**

## 🐛 Bug Report

* [ x ] I am including my log files in the issue.
* [ x ] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Debian/Docker

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker - using **dev** tag

### If running via Docker or Kubernetes please list version including docker-compose:
```
version: '3.8'
services:
  proxy:
    image: reallibrephotos/librephotos-proxy:${tag}
    restart: always
    volumes:
    # - /home/docker/librephotos/photos:/data
      - nas-images:/data
      - librephotos-protected:/protected_media
    ports:
      - ${httpPort}:80
    depends_on:
      - backend
      - frontend

  frontend:
    image: reallibrephotos/librephotos-frontend:${tag}
    restart: always
    depends_on:
      - backend

  backend:
    image: reallibrephotos/librephotos:${tag}
    restart: always
    volumes:
      - nas-images:/data
      - librephotos-protected:/protected_media
      - ${logLocation}:/logs
      - ${cachedir}:/root/.cache

    environment:
      - SECRET_KEY=${shhhhKey}
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=database.triplusnet.home
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${mapApiKey}
      - TIME_ZONE=${timeZone}
      - WEB_CONCURRENCY=${gunniWorkers}
      #- SKIP_PATTERNS=${skipPatterns}
      - DEBUG=0
      - HEAVYWEIGHT_PROCESS=${HEAVYWEIGHT_PROCESS}

  redis:
    image: redis:6
    restart: always
    
volumes:
  nas-images:
    driver: local
    driver_opts:
      type: cifs
      o: "username=librepho,password=xxx,rw"
      device: "//192.168.1.10/Photos"
  librephotos-protected:
    driver: local
    driver_opts:
      type: cifs
      o: "username=librepho,password=xxx,rw"
      device: "//192.168.1.10/librephotos-work"
```

### Are you running LibrePhotos on a virtual machine if so please list:
Proxmox VM running docker

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB
SMB

### Description of issue:
After running a scan, the train_faces job triggers and fails with below error message.
Looking into issue https://github.com/LibrePhotos/librephotos/issues/29, however I have multiple faces/people labeled
![image](https://user-images.githubusercontent.com/7044850/181201920-723e06e4-0191-4455-95ff-93fbd4befb4d.png)

```
06:47:02 default: api.face_classify.train_faces(<User: triplus>, UUID('55894a1b-c1ab-474a-ae49-f3296c7d213c')) (ee757aef-3e58-406f-bef2-f46563e29387)
[ERR] Expected 2D array, got 1D array instead:

.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

```
2022-07-27 08:23:49,914 : face_classify.py : train_faces : 286 : ERROR : An error occurred
Traceback (most recent call last):
  File "/code/api/face_classify.py", line 245, in train_faces
    probs = clf.predict_proba(face_encodings_unknown_np)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1252, in predict_proba
    y_pred = self._forward_pass_fast(X)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 160, in _forward_pass_fast
    X = self._validate_data(X, accept_sparse=["csr", "csc"], reset=False)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py", line 879, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

### How can we reproduce it:
Run 'scan photos'

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by tr1plus** [comment]
Maybe an open question

Could it be that this error is happening because I have 2 users: admin & my own?
admin user has no photos/faces, but my own user does.

In that case, it seems that triggering the "scan photos" will run the "train faces" for all users, which is/could be also not intended.

**Comment by derneuere** [comment]
@jakekapellen I think this should be an easy fix. You only have to run on only one account and return early if there are no faces 👍

**Comment by jakekapellen** [comment]
Based on the code, I don't think you have NO faces, I'm guessing you don't have any UNLABELED faces, is that correct, @tr1plus? There is already handling to quit out early if there are no labeled faces, and I could reproduce the crash when everything is labeled.

Can you confirm if your own user has everything labeled already?

**Comment by tr1plus** [comment]
> Based on the code, I don't think you have NO faces, I'm guessing you don't have any UNLABELED faces, is that correct, @tr1plus? There is already handling to quit out early if there are no labeled faces, and I could reproduce the crash when everything is labeled.
> 
> Can you confirm if your own user has everything labeled already?

Correct, all my faces are labelled.

stupid question - if I re-pull the dev image, do I already get your changes, or how does the development process happen? :)

**Comment by derneuere** [comment]
Yes, it usually takes an hour for the dev image to build. When it's done just shut down your container, pull them and start up again :)

You can check here how far the building is: https://github.com/LibrePhotos/librephotos-docker/actions

**Comment by tr1plus** [comment]
![image](https://user-images.githubusercontent.com/7044850/181444350-106eda03-d03f-4da5-837a-f793e6ddc839.png)
Confirmed - train faces succeeds now after pulling the new dev image

thanks guys!
