### ISSUE TITLE
Logout does not properly end the session

### ISSUE THREAD

**Issue by tr1plus** [LibrePhotos/librephotos#569]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Debian/Docker

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker - using **dev** tag

### If running via Docker or Kubernetes please list version including docker-compose:
```
version: '3.8'
services:
  proxy:
    image: reallibrephotos/librephotos-proxy:${tag}
    restart: always
    volumes:
    # - /home/docker/librephotos/photos:/data
      - nas-images:/data
      - librephotos-protected:/protected_media
    ports:
      - ${httpPort}:80
    depends_on:
      - backend
      - frontend

  frontend:
    image: reallibrephotos/librephotos-frontend:${tag}
    restart: always
    depends_on:
      - backend

  backend:
    image: reallibrephotos/librephotos:${tag}
    restart: always
    volumes:
      - nas-images:/data
      - librephotos-protected:/protected_media
      - ${logLocation}:/logs
      - ${cachedir}:/root/.cache

    environment:
      - SECRET_KEY=${shhhhKey}
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=database.triplusnet.home
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${mapApiKey}
      - TIME_ZONE=${timeZone}
      - WEB_CONCURRENCY=${gunniWorkers}
      #- SKIP_PATTERNS=${skipPatterns}
      - DEBUG=0
      - HEAVYWEIGHT_PROCESS=${HEAVYWEIGHT_PROCESS}

  redis:
    image: redis:6
    restart: always
    
volumes:
  nas-images:
    driver: local
    driver_opts:
      type: cifs
      o: "username=librepho,password=xxx,rw"
      device: "//192.168.1.10/Photos"
  librephotos-protected:
    driver: local
    driver_opts:
      type: cifs
      o: "username=librepho,password=xxx,rw"
      device: "//192.168.1.10/librephotos-work"
```

### Are you running LibrePhotos on a virtual machine if so please list:
Proxmox VM running docker

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB
SMB

### Description of issue:
When logging out of one user and logging in on another user, the photos of the first user are still shown.
In my example:

1. Login with admin user (for me, this one has no pictures ect.)
2. Logout on admin user
3. Login with a different user
4. Observe that there are no photos displayed (so the admin photos probably)
5. Press crtl+f5 and the correct photos are visible.

### How can we reproduce it:
see above

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by meichthys** [comment]
Duplicate of #453

**Comment by tr1plus** [comment]
You are correct - I will close this so it can be tracked in the original ticket.
"logout" & "session" were not the correct search terms it seems ;)

**Comment by meichthys** [comment]
Thanks for checking out Librephotos!
