### ISSUE TITLE
Missing photos counter wrong

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#571]
### What Operating system and version is LibrePhotos running on:
unknown

### What architecture is LibrePhotos running on:
x64 

### How is LibrePhotos installed:
Docker

### Description of issue:
[u/nagarrido_96](https://old.reddit.com/user/nagarrido_96) on [reddit reports](https://old.reddit.com/r/librephotos/comments/w240mi/missing_photos_counter_wrong/): I have a test instance for librephotos, and recently I deleted all photos but one (directly from the source folder). When I click "remove missing photos" the missing photos get deleted, but the counter for total photos and missing photos does not reset. Has this happened to anyone?

### How can we reproduce it:
- Delete images from folder
- Run "Delete Missing" job
- Counter does not change

**Comment by meichthys** [comment]
Does it update eventually? I think i remember seeing this before, but after a certain amount of time it did update to match the actual number of photos.

**Comment by derneuere** [comment]
This is fixed, I think
