### ISSUE TITLE
Add Librephotos version number to GUI

### ISSUE THREAD

**Issue by meichthys** [LibrePhotos/librephotos#575]
**Describe the enhancement you'd like**
I may be missing it, but I don't see anywhere in the GUI where I can see the version of Librephotos that I'm running.
It would be nice to display this either on the bottom of the sidebar, or perhaps in the settings.

**Describe why this will benefit the LibrePhotos**
This would help when troubleshooting with a user.

**Additional context**
Some examples of how other software displays the version:
Gitea (In Footer):
![image](https://user-images.githubusercontent.com/10717998/181503693-ee50e766-4e85-4448-a695-c43f301d21e9.png)

Nextcloud (In settings):
![image](https://user-images.githubusercontent.com/10717998/181503815-9e59fd95-02c0-4431-befe-82e67065d00d.png)

Portainer (bottom of sidebar):
![image](https://user-images.githubusercontent.com/10717998/181503920-2a3c9fa5-9ce2-408e-b1ed-b28b2d1ed9ae.png)

Bitwarden (On Login screen):
![image](https://user-images.githubusercontent.com/10717998/181504255-1bc3ad41-294b-472a-942e-917a5b200114.png)

**Comment by sickelap** [comment]
At the moment there's no versioning in any of the components. It's very much a work-in-progress. 
If that would help we could use the commit hash (full/shortened) as version representation but I don't see it as being informative enough. Perhaps we should wait for this feature until there will be proper versioning in all components we need to think about which version to show... frontend, backend and proxy.

**Comment by meichthys** [comment]
I didn't even realize we aren't using version numbers yet lol. In this case, we can probably just wait until proper versioning is implemented.
Once implemented, we should probably include versions for the frontend, backend, and proxy all in the admin panel.

**Comment by sickelap** [comment]
We could have an "About" page where we could have not only version numbers (when they will be available) but also mission statement, licences and so on...

**Comment by meichthys** [comment]
Sounds like a good idea to me 👍

**Comment by PiotrEsse** [comment]
+1 for commit hash or even "build" date (ie for docker image). I understand that versioning is a whole concept had to be introduced to development workflow and its timeconsuming but hash commit or date would be great.

**Comment by derneuere** [comment]
It will now be visible in the sidebar :)
