### ISSUE TITLE
Migrate react-scripts to vite

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#577]
**Describe the enhancement you'd like**
Right now, the dev experience isn't great, because HMR is very slow. We can improve the experience by switching to vite instead.

**Comment by polaroidkidd** [comment]
do you have the `FAST_REFRESH` flag in the `.env.development` file set to true? 
I'm working on a pretty strong machine, so I maybe that's why I don't really notice slow HMR. Could it maybe have something to do with the linting during the dev process?

**Comment by sickelap** [comment]
I am using .env.development as follows and I don't have any issues with HMR. Reload works "blazingly fast"<sup>tm</sup>

```bash
TSC_COMPILE_ON_ERROR=true
BROWSER=none
FAST_REFRESH=true
ESLINT_NO_DEV_ERRORS=true
HTTPS=false
REACT_EDITOR=vim
DISABLE_ESLINT_PLUGIN=true
DISABLE_NEW_JSX_TRANSFORM=false
# custom env vars
REACT_APP_PROXY_IP="localhost"
REACT_APP_PROXY_PORT="3000"
REACT_APP_WDYR=false
```

**Comment by polaroidkidd** [comment]
@derneuere  seems to think the dev experience isn't that great and there is an [issue in the create-react-app repo](https://github.com/facebook/create-react-app/issues/9886), which matches this description. I've created [a mr](https://github.com/LibrePhotos/librephotos-frontend/pull/100) to disable es-lint during dev mode as that is one of the [suggested fixes](https://github.com/facebook/create-react-app/issues/9886#issuecomment-1122007649) in the create-react-app repository.

@derneuere , does this improve performance for you or does it remain the same? Is the variable `DISABLE_ESLINT_PLUGIN=true` set in your `.env` file?

**Comment by derneuere** [comment]
I tried both changes. It looks like it now only need 2s instead of 8-10s on the first compile, but any following compile seems to be just as fast with or without linting. 

From my understanding, everything is way faster in vite. This would also cut down on build times, start up times etc.
