### ISSUE TITLE
Add videos to Demo

### ISSUE THREAD

**Issue by meichthys** [LibrePhotos/librephotos#578]
**Describe the enhancement you'd like**
It would be nice to have some videos in the demo to be able to quickly test video related issues/features.

**Describe why this will benefit the LibrePhotos**
It would make it easier to quickly test video issues that new users are experiencing.

**Comment by derneuere** [comment]
![image](https://user-images.githubusercontent.com/6658807/182038501-8d531c11-a176-41fd-850c-c76fa6e02ce0.png)

We have videos on the demo instance, but the first user set's the path and can choose one without videos.

**Comment by meichthys** [comment]
Ok thanks. How often does the demo reset?

**Comment by derneuere** [comment]
I think once per hour or so. I have to ask Digital_Warrior to get the exact time.
