### ISSUE TITLE
look & feel of photo + details. Detail part is a bit truncated

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#579]
This issue is reported using Web UI, browser Chrome, OS Win11.
Here is the default reported:
![image](https://user-images.githubusercontent.com/51127123/182081248-e89f3075-d8d7-45b3-9412-485f249bc9b8.png)

**Comment by loulou91** [comment]
I noted a different (strange) behavior of the WEB UI on my smartphone Xiaomi rednote 7 using chrome as browser in landscape position. Here is the result with and without picture details.
![Screenshot_2022-08-06-08-06-19-810_com android chrome](https://user-images.githubusercontent.com/51127123/183236850-a9a566aa-627e-4d91-8ab5-1d6849a8ad3b.jpg)
![Screenshot_2022-08-06-08-06-04-598_com android chrome](https://user-images.githubusercontent.com/51127123/183236851-c2709eb9-c222-4f47-a637-249735d8d1dc.jpg)
.

**Comment by derneuere** [comment]
Should be fixed now :)
