### ISSUE TITLE
No more able to open an auto-album

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#580]
Since yesterday I got an empty blank page when I want to open an auto-album.
![image](https://user-images.githubusercontent.com/51127123/182082609-d29978b1-486b-4882-af62-4242a879ae65.png)

**Comment by derneuere** [comment]
This should be fixed now!

**Comment by loulou91** [comment]
Unfortunately not really ;-)

**Comment by derneuere** [comment]
I think now it should work! :D Added another fix!

**Comment by loulou91** [comment]
That will be the last fix for the time being ;-) Thanks a lot, it works.

Just missing issue #463 resolution "date info is missing in the auto-created album name" ;-) ;-)

**Comment by derneuere** [comment]
One thing at a time 😄
