### ISSUE TITLE
Migration to Matine v5

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#583]
**Describe the enhancement you'd like**
Mantine v5 has a lot of new features, but also introduces a lot of breaking changes. We are tracking all of the dependencies here, that still need to be migrated:

- [x] @matine/modals
- [ ] @matine/core
- [ ] @matine/forms
- [ ] @matine/dates
- [ ] @matine/hooks
- [ ] @matine/notifications

**Comment by 5m4u66y** [comment]
I think that this issue can be closed.
LibrePhotos/librephotos-frontend#125
