### ISSUE TITLE
Page "Data - Timeline" looks corrupted

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#594]
Web UI Chrome, Win11
Page looks corrupted 
![image](https://user-images.githubusercontent.com/51127123/183361462-58501d96-c8a8-455d-8c93-59baad526e0b.png)

**Comment by derneuere** [comment]
The upper graph should be fixed now. Not sure about the one at the bottom.

**Comment by loulou91** [comment]
Much better, but:
- Date a bit truncated on upper graph
- second looks not so bad, but I don't know the spec ;-) Some text appears but not really readable...

**Comment by derneuere** [comment]
Fixed!
