### ISSUE TITLE
Manual album page : number of photos truncated

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#595]
Web UI, chrome, win11
Manual album design looks to work only for "short" album name. For longer names (on 2 lines) the number of photos is truncated.
![image](https://user-images.githubusercontent.com/51127123/183369350-a8d66c8b-5caa-444f-b67a-af9b4953a830.png)

**Comment by derneuere** [comment]
I clamped the title of the album to improve the situation. It that how you would expect it or how do you think it should look like?

**Comment by loulou91** [comment]
I think your solution is clean and enough even if long names are a bit truncated. Thanks
