### ISSUE TITLE
docker install error

### ISSUE THREAD

**Issue by lslvxy** [LibrePhotos/librephotos#597]
# Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

When asking general "how to" questions:
- Please do not open an issue here join us on the Discord server  [LibrePhotos](https://discord.gg/xwRvtSDGWb)

**When Submitting please remove every thing above this line**

## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [ ] I have looked for similar issues among all the former issues including closed ones.

### What architecture is LibrePhotos running on:
x64 

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
docker version
Client: Docker Engine - Community
 Version:           20.10.17

docker compose version
Docker Compose version v2.6.0
### Are you running LibrePhotos on a virtual machine if so please list:
install in pve LXC

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type), NFS, or SMB

Local file system

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
[log.txt](https://github.com/LibrePhotos/librephotos/files/9299222/log.txt)

**Comment by derneuere** [comment]
You somehow installed an old version. Please change the tag to: 2022w29
