### ISSUE TITLE
Minimum confidence for face recognition

### ISSUE THREAD

**Issue by tknobi** [LibrePhotos/librephotos#60]
First of all, thank you for reviving and continuing this great project!

Now to my question, is it possible to set up a minimum confidence for face recognition? 
There are more faces in my photos than I want to create albums. So there are many people who are allowed to stay on "unkown" or "unlabeled". Is it necessary that all faces found are always assigned to a known face?

Sheers
tknobi

**Comment by guystreeter** [comment]
Yes, please. Right now, it appears that every face gets inferred to one of the labeled faces, even if they are nowhere close. My mother didn't like having the dog labeled as her :)

**Comment by derneuere** [comment]
Make it configurable by creating a new CONSTANCE_CONFIG field [here](https://github.com/LibrePhotos/librephotos/blob/dev/ownphotos/settings.py)

**Comment by bmabir17** [comment]
@derneuere okey thanks

**Comment by derneuere** [comment]
I think I will close these issue, as these should be fixed :)
