### ISSUE TITLE
Faces Navigation: Multiple suggestions

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#600]
When you have a lot of pictures and a lot of faces, it is tedious to manually scroll downwards, as there can be hundred of pages of faces.

Suggestions for faster Navigation in Faces views:

1. A-Z tabs by the scroll bar to jump to a start letter
2. Have a highlight by the mouse indicating which face the scrollbar currently will bring you to (when holding down mouse button on scroll bar)
3. Collapse all thumbnails to a "single Thumbnail per face" view

similar to 1. this would also be useful in the photos view

**Comment by EricInBj** [comment]
+1

about point 3 , maybe Collapse all thumbnails to a "single LINE per face"  is better

4. Add exif time column to api_face table, and sort faces by this column in Labeled view.

**Comment by huangda1982** [comment]
+1
I have tens of thousands faces in "Unknown - Other" tag and my name is 黄达, sorted after any alphabet.

**Comment by PiotrEsse** [comment]
+1 - at least pagination would be beneficial.

**Comment by korikori** [comment]
+1, and a separate tab for Unknown is much better than having it on the same page as faces you've already identified.

**Comment by 5m4u66y** [comment]
Regarding the problem of having labeled persons after a huge "Unknown - Other" group, I propose to move this group at the end of the list.
But I don't really understand why we have an "Unknown - Other" group in the labelled list. @derneuere could you please clarify this?

**Comment by derneuere** [comment]
We are trying to cluster all faces into distinct groups. When that's done, we calculate how high the confidence is. If a face does not match any group, it gets put into "Unknown - Other".

It's kind of important that you match the faces from "Unknown - Other" before doing another run, to get better results. Putting this group at the end will make it harder for people to understand how to improve the grouping of faces.

**Comment by 5m4u66y** [comment]
Ok, but having a big group with more than 21 thousands faces in the middle of my labeled persons is not a good point.
I already spent many hours tagging faces, trying to reduce this group, but it is not reducing that fast. There are many faces from the same person in this group. And in the inferred faces, I have around 2,500 clusters, most of them are between 2 and 6 faces. And there, I have an "unknown - other" group with 1112 faces. The clustering needs a big improvement.

In my opinion this is really confusing to have two groups named "unknown - other" in each of the lists, with different faces.
Moving this group at the end of the list is an easy modification in the code and I still thing it should be done, at least until there is another way to display this group (maybe a dedicated tab is the best way to go), or a scroller with an easy view of current position.

**Comment by derneuere** [comment]
Classification and the new unknown section should improve this :)
