### ISSUE TITLE
Multi-face selection in inferred tab does not render until page is scrolled

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#605]
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:

Multi docker container setup on Ubuntu Linux x64

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
latest

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (Type)

### Description of issue:

On the faces page, if I click to select a face (which works as expected) and then Shirt Click on another face further down, the multi selection ui change doesn't actually show up unless I scroll the page to cause an update.

### How can we reproduce it:

Should be reproducible if it happens on all setups and not just mine. If that's the case I can provide more info if needed.

#### Additional Information:

https://user-images.githubusercontent.com/873077/184516814-90ada26e-23e5-46e7-84f1-8d238ad422d1.mp4

**Comment by savvasdalkitsis** [comment]
I forgot to mention that I'm using Opera (latest version) on Windows 11

**Comment by loulou91** [comment]
The same with Chrome and for all faces (inferred and labeled). In addition the number of selected faces is incorrect after scroll. An additional selection (or deselection) makes the number to be correct.
An other case is: I click on a ace, then shift click on other face. Nothing happen in terms of selection except if I click on another face.

**Comment by derneuere** [comment]
I pushed a fix on dev :)
