### ISSUE TITLE
Photo folders path contain Chinese ，the photos can not be find

### ISSUE THREAD

**Issue by stellar-mini** [LibrePhotos/librephotos#606]
Iibrephotos is installed in the docker in unraid, if the folder under the photo path contains Chinese, the photos under this folder can not be recognized, change the folder name to English can be perfectly recognized

librephotos安装在unraid中的docker中，photo路径下的文件夹含有中文，该文件夹下的照片无法识别，文件夹名称更改为英文可以完美识别

**Comment by derneuere** [comment]
This should be fixed in the latest release. Your database was initialized with the wrong charset. Start fresh and then it should work :)
