### ISSUE TITLE
Faces UX - open origin photo in context

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#611]
Currently, if you need to establish context for a face, it is possible to hover over the thumbnail and click the icon in the lower left corner.

I find that sometimes, I would like to open the picture to full screen to have access to metadata, location etc. 

The suggestion is to provide another hover icon on the full picture, once that is opened in preview to open the full picture in a new window/tab, in context of the timestamp (i.e. next/previous picture would be next/previous in relation to timeline)

**Comment by derneuere** [comment]
We now use the LightBox instead, which should give you all the information you need.
