### ISSUE TITLE
Weird logo placement while using Safari

### ISSUE THREAD

**Issue by mikkelnl** [LibrePhotos/librephotos#613]
When using MacOS: in Safari, the logo is displaced, and shown like this:

<img width="502" alt="Schermafbeelding 2022-08-17 om 17 02 21" src="https://user-images.githubusercontent.com/1759050/185174275-52436404-8370-4dd8-bfa9-cf5b98c0781f.png">

Using Google Chrome, it works fine.

**Comment by sickelap** [comment]
Yep, can confirm that there's an issue with WebKit browsers. Tested on macOS and Linux (Epiphany)

**Comment by meichthys** [comment]
Seems to be ok on iOS webkit.

**Comment by ark-** [comment]
I'm still getting this in the singleton docker container. When are these containers updated with the latest?

**Comment by derneuere** [comment]
Probably on tuesday :)
