### ISSUE TITLE
Facial Recognition "Context" image preview does not work for video

### ISSUE THREAD

**Issue by tanpro260196** [LibrePhotos/librephotos#615]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files: [librephotos_logs.zip](https://github.com/LibrePhotos/librephotos/files/9366396/librephotos_logs.zip)
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
In the Faces section, the preview image for a video's faces show up broken.
![image](https://user-images.githubusercontent.com/12226439/185253119-7eaeeb36-7af9-47c2-85ec-fff3fca72897.png)

## 🔁 How can we reproduce it:
As above.

## Please provide additional information:
- 💻 Operating system: Ubuntu 22.04
- ⚙ Architecture (x86 or ARM): x64
- 🔢 Librephotos version: 
- 📸 Librephotos installation method: Docker - Lastest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local file system (mergefs)

**Comment by derneuere** [comment]
We now use the LightBox instead, which can display videos
