### ISSUE TITLE
Not able to open "large" things album

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#617]
22-08-19 version, WEB UI, Chrome, Win11.
I'm not able to open things album larger than ~3000 photos. report says "no image found" after about 30s.
To be noted that some things albums are very large, more than 40K pictures, with my base containing 53k pictures.

This issue maybe looks like #580

**Comment by derneuere** [comment]
I pushed a fix :) Should work now!

**Comment by loulou91** [comment]
Well done! efficient fix :-)
