### ISSUE TITLE
Support for alternative storage options?  S3 or Google Cloud Storage

### ISSUE THREAD

**Issue by jonathanclarke** [LibrePhotos/librephotos#62]
Is there any roadmap for alternative storage options of the images such as within a users private S3 bucket or Google Cloud storage?

**Comment by kyprifog** [comment]
Has anyone explored an s3 bucket?  Is there a WIP branch?

**Comment by luckcolors** [comment]
I would like to work on this but i would need some help as python is not my first language.

My idea would be to use this: https://django-storages.readthedocs.io/en/latest/

The problem at the moment is that all storage related interactions are done directly without using Django's storage API.
This means that all the app needs to be patched accordilingly.

I think it would also be possible if we migrate to django apis to "drop in" different kinds of drivers, so not just s3.

**Comment by derneuere** [comment]
I do not think that this is in scope. We are trying to manage personal photo collections saved on a regular file system. While importing from S3 or Google Cloud Storage would be an interesting feature, using S3 and Google Cloud Storage isn't something a regular user would use.
