### ISSUE TITLE
Support XMP face metadata

### ISSUE THREAD

**Issue by andrewshadura** [LibrePhotos/librephotos#629]
**Describe the enhancement you'd like**
For example, in my personal photo collection, a lot of pictures have faces in them already tagged (e.g. by Picasa or DigiKam).
LibrePhotos ignores that metadata and does face recognition from scratch.

**Describe why this will benefit the LibrePhotos**
This will save users time, especially to those who already took care of their photo collection.

**Additional context**
See e.g. https://github.com/photoview/photoview/issues/401

**Comment by fcimeson** [comment]
I would also request that LibrePhotos can save the face tag to the metadata (the media file or a sidecar).

**Comment by Michael2MacDonald** [comment]
Look at issue #130
Maybe we should move to that issue and close this one?

**Comment by derneuere** [comment]
It would be great if somebody could provide more files for testing. The Ryan Gosling File has an incorrect face tag, which is not that useful for testing.

**Comment by derneuere** [comment]
Oh, should have read it correctly. X and Y are the center of the rect, which changed the calculation by alot. Should work now :)
