### ISSUE TITLE
Demo page is not showing any existing albums or photos. 

### ISSUE THREAD

**Issue by jonathanclarke** [LibrePhotos/librephotos#63]
The demo server is not showing any existing content?  https://demo2.librephotos.com/

Logged in, couldn't figure out how to upload any new picture to the demo. Was a blank page almost apart from the header and sidebar; screenshot below. 

![image](https://user-images.githubusercontent.com/11335/103409256-0d915680-4b8e-11eb-843d-8f98112c3357.png)

**Comment by derneuere** [comment]
None of the photos have timestamps. Click on photos and then "Without Timestamp" and then you should see pictures.
