### ISSUE TITLE
404 error when click on filepath

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#639]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
When i click on the file path of a photo, or a video, it always get me a 404 not found error.

`172.22.0.2 - - [12/Sep/2022:<t:1662963257:t> PM:05 +0000] "GET /api/rqavailable/ HTTP/1.1" 200 61 "https://" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
2022/09/12 <t:1662963257:t> PM:06 [error] 33#33: *10 open() "/data//neroData/Screenshots/2022/09/Screenshot_2022-09-09-20-30-45-023_com.disney.disneyplus.jpg" failed (2: No such file or directory), client: 172.22.0.2, server: , request: "GET /media/photos/b47bce479c8e604847b7c384b868ce1f1 HTTP/1.1", upstream: "http://172.27.0.4:8001/media/photos/b47bce479c8e604847b7c384b868ce1f1", host: "myhost", referrer: ""`

dont know really why the path is with 2 "//", this is my docker-compose config:

`volumes:
      - ${myPhotos}:/data
      - ${data}/protected_media:/protected_media
      - ${data}/logs:/logs
      - ${data}/cache:/root/.cache
      - NX-Nero:/data/neroData

volumes:
  NX-Nero:
    external: true`

`NX-Nero` is the NFS share of nextcloud.

![image](https://user-images.githubusercontent.com/29661633/190697513-ead4589c-11ac-4d2c-acd5-527b7a1b1b53.png)

## 🔁 How can we reproduce it:
Click a file path of a photo or a video.

## Please provide additional information:
- 💻 Operating system: Ubuntu 20.04 LTS
- ⚙ Architecture (x86 or ARM): x64
- 🔢 Librephotos version: dev - latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.):  docker
```
Container           Repository                             Tag                 Image Id            Size
lb_backend          reallibrephotos/librephotos            dev                 77f2547c7489        6.26GB
lb_db               postgres                               13                  e30fb19f297b        373MB
lb_frontend         reallibrephotos/librephotos-frontend   dev                 f809549e4bc2        26.2MB
lb_proxy            reallibrephotos/librephotos-proxy      dev                 4f90ef8b65fa        142MB
lb_redis            redis                                  6                   94cfe49e6758        113MB
```
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): NFS
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): HyperV

**Comment by sickelap** [comment]
Could you please check permissions for the file, the immediate folder or its parent folders are correct

**Comment by Nerodacles** [comment]
Sorry for the late reply, but, at least it create the thumbs image, and i can see it on LB, but i will check it.

![image](https://user-images.githubusercontent.com/29661633/190820621-fee44b7b-2a02-45b5-b657-60c853b17400.png)

**Comment by Nerodacles** [comment]
```root@d174f089a8a6:/data/neroData/Screenshots/2022/09# ls -l
-rw-r--r-- 1 www-data www-data 486249 Sep 10 00:30 Screenshot_2022-09-09-20-30-45-023_com.disney.disneyplus.jpg
```
are this fine?

**Comment by Nerodacles** [comment]
Are this fine?

**Comment by sickelap** [comment]
The permission on the file looks fine. how about the permissions on the folder containing this file and all parent folders going up?

**Comment by Nerodacles** [comment]
> The permission on the file looks fine. how about the permissions on the folder containing this file and all parent folders going up?

`drwxrwxrwx 18 www-data www-data    19 Aug  5 03:20 neroData`
`drwxrwxrwx  3 www-data www-data  127 Aug 12 05:26  Screenshots`
`drwxrwxrwx 11 www-data www-data       11 Sep  8 22:03 2022`
`drwxr-xr-x 2 www-data www-data  6 Sep 12 02:38 09`

**Comment by sickelap** [comment]
This should not affect the access. But in any case, I would try to make folder permissions the same as all others.
Another thing you could try is to load the file directly (view in the viewer or try to download via browser) and monitor proxy logs to see what's going on there.

**Comment by Nerodacles** [comment]
> Another thing you could try is to load the file directly (view in the viewer or try to download via browser)

How can i do that?

**Comment by Nerodacles** [comment]
Ok, i did managed to fix it, by disconnecting the nfs share that i created using portainer and the docker nfs volumes.

I just connected the nfs share directly to the folder on linux, and it just works now!
