### ISSUE TITLE
Exclude photos/folders by their name

### ISSUE THREAD

**Issue by adan89lion** [LibrePhotos/librephotos#64]
Hi,
I'm having issues with LibrePhotos to coexist with Synology Photos (a.k.a Synology Moments). Synology NAS generates `@eaDir` folders to save metadata of media files (such as thumbnails and EXIF data). Is there anyway to batch exclude photos based on their file name? Like `@eaDir/*` to exclude all the files under the `@eaDir` folder.

It is already implemented in PhotoPrism and I found it very handy to use.

**Comment by derneuere** [comment]
You can set the skip patterns in the admin panel.
