### ISSUE TITLE
Place Tree is bugged

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#645]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
When viewing the place tree is displayed wrong.

![image](https://user-images.githubusercontent.com/29661633/191407377-7f43a17e-446c-4e1c-b883-72b694212681.png)

![image](https://user-images.githubusercontent.com/29661633/191407414-eeff3da5-3b78-4427-a591-9f7143de61f0.png)

## 🔁 How can we reproduce it:
Just click it!

## Please provide additional information:
- 💻 Operating system: Ubuntu 20.04
- ⚙ Architecture (x86 or ARM): x64
- 🔢 Librephotos version: dev - latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
```
    Container           Repository                             Tag                 Image Id            Size
lb_backend          reallibrephotos/librephotos            dev                 375a85684562        6.26GB
lb_db               postgres                               13                  e30fb19f297b        373MB
lb_frontend         reallibrephotos/librephotos-frontend   dev                 f809549e4bc2        26.2MB
lb_proxy            reallibrephotos/librephotos-proxy      dev                 4f90ef8b65fa        142MB
lb_redis            redis                                  6                   94cfe49e6758        113MB
```
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): NFS
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): HyperV

**Comment by derneuere** [comment]
Fixed it :)
