### ISSUE TITLE
Extend "Scan Photos (filesystem)" to also include new photos

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#646]
Extend the scope of "Scan Photos" under "Library" to also look for newly added files to the monitored folders.

Currently, in order to add newly added files, I need to run "Rescan all Photos", which on my collection takes several days to run. It would be more intuitive and effective to simply look for new files as an incremental update.

**Comment by derneuere** [comment]
"Scan Photos (filesystem)" should only add new photos, while skipping old ones. I think that is the behavior you want, right? Do you have an idea, how I can recreate your issue?

**Comment by ChrisFab16** [comment]
1. initial scan of folders and files
2. add new files in the filesystem (my organisation is YYYY/MM/DD so typically there will be new MM/DD folders created)
3. click "Scan Photos" - and observe that not all new files are showing up in "photos"

**Comment by PiotrEsse** [comment]
Does "scan photos" skip already scanned ones? 
In my case next run of "scan photos" last much, much shorter. Initial scan took 2 days, next run took 2-3h. It shows a count of all pictures indexing (lets say 50000 pictures but I only add 200 new pictures) but it does it much faster so I think its really skipping already indexed ones.

**Comment by stnokott** [comment]
Having a similar issue, while the scan is running, it shows the correct number of images to be scanned.
![image](https://user-images.githubusercontent.com/30934296/196969083-84cb66b3-2744-4d51-b6ee-3735946d5ba1.png)

But in the end, only 1-10 images are available as actually scanned.
![image](https://user-images.githubusercontent.com/30934296/196969164-a620e34d-1ffc-4711-834e-a0370dcddde0.png)

**Comment by ChrisFab16** [comment]
From recent testing this seems to be fixed.
