### ISSUE TITLE
Can't upload video .mp4

### ISSUE THREAD

**Issue by ajcarrascod** [LibrePhotos/librephotos#648]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X ] ❌ I have looked for similar issues (including closed ones)
* [X ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
When I try to upload a video, there is an error and the log shows:

2022-09-25 19:21:40,330 : directory_watcher.py : is_valid_media : 46 : INFO : Could not handle /data/uploads/web/VID-20210209-WA0036.mp4, because unable to call thumbnail
  magickload: Magick: improper image header `/data/uploads/web/VID-20210209-WA0036.mp4' @ error/tga.c/ReadTGAImage/215 (null)

## 🔁 How can we reproduce it:
Try to upload the file I have attached.

## Please provide additional information:
- 💻 Operating system: Linux
- ⚙ Architecture (x86 or ARM): 
- 🔢 Librephotos version: docker
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): 

Video:
https://user-images.githubusercontent.com/16685137/192164765-fa13e6a7-a89c-47d6-a444-0dccf78d61f6.mp4

**Comment by derneuere** [comment]
The file is broken, because it has the wrong mime type. It has a application/octet-stream mime type and not a video mime type.
