### ISSUE TITLE
RAW-Image support

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#65]
To support RAW-Images we have to convert them to jpegs via [darktable-cli](https://www.darktable.org/2012/07/exporting-images-on-the-command-line/). This should allow us to support a wide array of raw image types.

**Comment by SolAstrius** [comment]
Should we keep .jpegs right in the directory with raws? And how can we implement raw downloading?

**Comment by derneuere** [comment]
No, the program will take care of creating the .jpegs in the form of thumbnails. All the images you see in the program are conformed to .jpegs to allow for optimal file size and compatibility with browsers. I could add a file download button where you would get the actual file :)

**Comment by SolAstrius** [comment]
So where will LibrePhotos instance save the thumbnails?)

**Comment by derneuere** [comment]
There are saved at /code/protected_media

**Comment by derneuere** [comment]
This works now!

**Comment by jalada** [comment]
Amazing! Thanks @derneuere, will be sure to give it a try.

Don't forget to update the README; it still says this is an upcoming feature.
