### ISSUE TITLE
Captions are locked after generating

### ISSUE THREAD

**Issue by danglingptr0x0** [LibrePhotos/librephotos#650]
**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Generating a caption from the frontend using the button generates it, but the field locks itself afterward. Can't make edits to it on any platform. Pressing `Submit` doesn't help.

## 🔁 How can we reproduce it:
Open any photo and use the `Generate` button to generate a caption. Then, try editing the field (even removing all text in case the algorithm misclassified).

## Please provide additional information:
- 💻 Operating system: tested this on win64 (Firefox) and iPadOS 16 (Safari)
- ⚙ Architecture (x86 or ARM): amd64 and arm64, respectively
- 🔢 Librephotos version: as of [69b11e481c0fd093738553d43116d482e2eaceb8](https://github.com/LibrePhotos/librephotos-docker/commit/69b11e481c0fd093738553d43116d482e2eaceb8)
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker-compose
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: N/A
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): NFS
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): N/A

**Comment by derneuere** [comment]
This is related to #551 and #159 and a duplicate :)

**Comment by danglingptr0x0** [comment]
@derneuere sorry, man, I initially did search but couldn't find a duplicate
