### ISSUE TITLE
Faces Workflow: Add a sort option by date of the photo per face in "inferred" view

### ISSUE THREAD

**Issue by huangda1982** [LibrePhotos/librephotos#655]
**Describe the enhancement you'd like**
Show taken date (year) of the photo per face in "inferred" view.

**Describe why this will benefit the LibrePhotos**
Brothers and sisters are very similar at same age.
This feature can help to tell photos of different childern (babies) at same age.

**Additional context**
Don't know if many people need this feature.

**Comment by derneuere** [comment]
I think #457 should fix this as you can then see all the info about the image instead :)

**Comment by huangda1982** [comment]
I still think this is useful. Filtering by date is much faster than seeing every image. I understand this is not a MUST feature. People don't do this all the time :)

**Comment by derneuere** [comment]
I think a sort option for the dates would make sense!

**Comment by PiotrEsse** [comment]
This would be very welcome feature as in fact its problem with proper image classification for babies. All look quite the same ;-D but they are separated by a time.

**Comment by 5m4u66y** [comment]
I started to work on this, but my code is not working as expected, and I don't understand why right now.
The faces don't get refreshed when switching sort option.

**Comment by 5m4u66y** [comment]
While I couldn't understand why LibrePhotos/librephotos-frontend#122 was not working as expected, I decided to try a different approach. The result is LibrePhotos/librephotos-frontend#124 with sorting done on client side only.
I don't know which one would be more effective. But for now only the second one works (even thought it needs more testing).

**Comment by derneuere** [comment]
You have to do it like you did in https://github.com/LibrePhotos/librephotos-frontend/pull/122 

If a user has more than 100 faces per person the sorting will be wrong, if you only do it on the client side, because the timestamps of the faces only get fetched if the section is visible.

**Comment by 5m4u66y** [comment]
Can we close this issue?

**Comment by derneuere** [comment]
Yes!
