### ISSUE TITLE
WebLate translation is closed - please update files and/or make it active

### ISSUE THREAD

**Issue by PiotrEsse** [LibrePhotos/librephotos#656]
Id like to help with translation into Polish. Can You please make it available ;-)
![image](https://user-images.githubusercontent.com/42764623/193988449-f978d999-9899-4b2d-8885-e7a77ed27278.png)

**Comment by derneuere** [comment]
It should be possible to commit new translations again.

**Comment by PiotrEsse** [comment]
Sorry, still closed ;-(
![image](https://user-images.githubusercontent.com/42764623/196053825-946974a1-e5d0-4ad2-a742-a7cd8ebb37fc.png)

**Comment by derneuere** [comment]
I should have read the error message 😅 Should be fixed now.

**Comment by PiotrEsse** [comment]
Now its working. Now I can translate LP to polish.
