### ISSUE TITLE
Similar Faces stacked by 3 but images are almost the same

### ISSUE THREAD

**Issue by PiotrEsse** [LibrePhotos/librephotos#657]
Its not a bug but rather a question.
why LP cluster/stack photos which are very similar, by 3 in the row. Those pictures are almost the same - shouldn't they be stacked all in one 

![image](https://user-images.githubusercontent.com/42764623/194137456-6aa2b675-528b-4a25-954a-ee6b4abf23e6.png)

**Comment by 5m4u66y** [comment]
This bug is due to the following line of code in face_classify.py :
```python
clt = HDBSCAN(min_cluster_size=2, metric="euclidean")
```
Any good reason to set min_cluster_size to 2? Like @PiotrEsse I had only clusters of a few faces (between 2 and 6 faces). Changing min_cluster_size to 20 (only tried this value, just an arbitrary choice), I now get clusters of hundreds, sometime more than one thousand faces. And all those faces are mainly clustered correctly (less than 10 wrongly inferred faces in a cluster of 1754 faces I looked at).
Could we just hard code min_cluster_size to a higher value, or ask for it in a popup when running the process, or should we add a customizable parameter for this setting?

**Comment by 5m4u66y** [comment]
That is doing a really great job. I can't believe I have spent so many hours classifying faces, while this little "2" could have changed everything :(

**Comment by derneuere** [comment]
Make it a customizable parameter until we figure out how it behaves in different photo collections. It could be that on small collections, 2 performs better than a higher number. It should be configurable in the user settings.

@jakekapellen Do you remember why we chose 2?

**Comment by 5m4u66y** [comment]
@derneuere an additional information, I wanted to test with other values (3 ...), but after doing a clustering with min_cluster_size set to 20, if I set it back to 2, and run clustering again, I still get good clusters with hundred faces (tried on my test instance, redeploying the backend container so I am sure this setting is back to a value 2). Maybe this is normal, I didn't look deep into this code and don't know if there are persistent data saved to the database.

**Comment by atlas-shrugged08** [comment]
@derneuere I have 4000+ such clusters where most images are of the same face (this is after I resolved about a 1000 clusters and did training several times). I have about 78k faces/100k files.

Is there something i can do to alleviate the pain of going through 4000+ more clusters manually? any db hack or hidden setting or anything?
Would a full rescan of faces help or likely not?

**Comment by derneuere** [comment]
Well, the hack for now is starting the backend with the env DEBUG=1, going into the container and change this line in the file face_classify here: https://github.com/LibrePhotos/librephotos/blob/b632864b3e5b28301b9e00f92c4ecd8aa6f5ffd6/api/face_classify.py#L128

It probably should be configurable in the settings instead.

A full rescan of faces just adds the deleted faces back.

**Comment by atlas-shrugged08** [comment]
Thank you so much for the quick response, I will try that. I assume I will need to run train faces after I change that line.

**Comment by atlas-shrugged08** [comment]
@derneuere unfortunately that did not help much so I thought I'd at least report back the results.
After changing the above line to 20, I ran train faces again and it resulted in moving a lot of faces to unknown but the 4k odd clusters are still there. (with varying sizes of about 5 to 13 faces each and most of those faces are in the labeled faces list. Its also now reporting the labeled number as 171 on one page and 145 on another. attaching screenshots).

Edit: adding another screenshot in the end. It seems it runs find similar faces on all 78k but train faces only on about 13k. the 54k unknown faces in labeled section are not being used in train faces?

![image](https://user-images.githubusercontent.com/123214845/231323565-2083f317-e999-43f1-927c-ca7f2e0e27d5.png)

![image](https://user-images.githubusercontent.com/123214845/231323618-0e7ba7bb-d253-4c89-85f7-baabdf0da713.png)

![image](https://user-images.githubusercontent.com/123214845/231324301-9980b76b-459e-421a-8180-08c9b81c715b.png)

![image](https://user-images.githubusercontent.com/123214845/231479007-708f7b26-25f1-413d-a9a7-b328c0912b22.png)


Edit 3: oh well, at least i solved the mystery of 171 vs 145. It seems to be a bug (and a privacy concern i guess) - it is bringing in labels from the second user I have. It shows those labels with zero photos (so at least its not creeping into the other user's photos but the labels are there).

**Comment by derneuere** [comment]
Added a rule where the cluster size doubles every 10x increase in faces. Should be a good compromise for now.
