### ISSUE TITLE
Scan 4 photos and stops

### ISSUE THREAD

**Issue by Littlemanjr2** [LibrePhotos/librephotos#660]
Running on unraid docker. I have all my photos in the /var/lib/librephotos/photos directory. When I run a scan it's scans 4 pictures then stalls. Takes a docker restart and it will scan another 4 photos and stalls. I've seen the few other issues related to this but their issues seem to be connected to using some kind of network share. That's not my case.

**Comment by derneuere** [comment]
We have the bug template for a reason. Please fill it out, otherwise I can't help you.
