### ISSUE TITLE
Scans 4 files then stalls

### ISSUE THREAD

**Issue by Littlemanjr2** [LibrePhotos/librephotos#661]
# 🐛 Bug Report

* [ X] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ X] ❌ I have looked for similar issues (including closed ones)
* [ X] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I have all my photos in the /var/lib/librephotos/photos directory. When I run a scan it's scans 4 pictures then stalls. Takes a docker restart and it will scan another 4 photos and stalls. I've seen the few other issues related to this but their issues seem to be connected to using some kind of network share. I've tried several fresh docker pulls and installs with no success. 

## 🔁 How can we reproduce it:
I dont know

## Please provide additional information:
- 💻 Operating system: Unraid Docker
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: 
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: 
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): Unraid
[New folder.zip](https://github.com/LibrePhotos/librephotos/files/9746843/New.folder.zip)

**Comment by Littlemanjr2** [comment]
Anyone?

**Comment by Littlemanjr2** [comment]
There's bug reports open on here from 2 months ago with no comment or help at all that are probably just easy support questions. Owner was real quick to tell me I submitted my bug wrong but not to help anyone.

**Comment by derneuere** [comment]
Not sure why you are thinking, that I can help you, if you a) didn't have an error, b) didn't explain how this bug works. Again, I don't have an unraid system, that I can test. This is an open source project, so feel free to open a pull request, where you fix the bug.

I will close this issue, because I am annoyed by your spamming.

**Comment by flippedcracker** [comment]
I have this same issue. It scans just 4 photos and then stalls. I'm guessing it has to do with the configuration with using the Community Apps template vs using the docker compose
