### ISSUE TITLE
100Gb?

### ISSUE THREAD

**Issue by MRobi1** [LibrePhotos/librephotos#67]
I figured I'd spin this up to give this a try. I saw in the docs it requires at least 10Gb of space which is fine.
When starting I had 361Gb of 503 used. It took about a half hour to deplay the container, and without even logging in I now have 458.4Gb used. So just shy of 100Gb??
Is the 10Gb a type-o in the docks or did something weird happen on my deployment?

**Comment by derneuere** [comment]
No it should not be that big. How many pictures did you scan?
Did you scan photos via nextcloud? It will then download all pictures to its own directory.

**Comment by MRobi1** [comment]
> No it should not be that big. How many pictures did you scan?
> Did you scan photos via nextcloud? It will then download all pictures to its own directory.

I couldn't even log in to start scanning anything.
Got an error message about logging into the back-end. Checking the logs from the back-end gave a fatal error about invalid password (they match in the config file). Tried changing the password from default and rebuilding but it was spitting out an error about librephotos-data needing to be rebuilt. Figured I'd start from scratch, do I've just finished deleting the containers, I removed the directories and deleted the image files and I'm down to 358Gb free. 

I'm headed out the door right now but I'll try building it again when I get back later to see if it comes out any smaller.

**Comment by DigitalWarrior** [comment]
@MRobi1 is this issue still ongoing?

**Comment by MRobi1** [comment]
@DigitalWarrior I had actually kind of forgotten about it.
I noticed the portainer template was updated the day after I opened this, so I copied it, made the changes for directories and passwords and just deployed it. This time it used 9.55Gb and I can successfully log in 👍
