### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by Roebie** [LibrePhotos/librephotos#670]
How can I change the date format librephotos uses?

When I set the website's profile language to English I get dates formatted like **MMMM DD YYYY, DDDD** which is pretty acceptable as far as I know.
When I set the language to Dutch however that same format is used (with day and month names in Dutch). In Dutch this looks completely ridiculous. No one uses that format in Dutch. We would use **DDDD DD MMM YYYY**. 

I haven't found a way to change the date format however, but that doesn't mean there isn't one... I hope...

If this can't be changed yet, please consider this a feature request. Personally, I'd prefer to set the date format right next to the language dropdown in the profile settings.

Thanks!

**Comment by 5m4u66y** [comment]
Yesterday my pull request to replace moment.js by luxon was merged into dev branch. See issue #385. 
With luxon, all date fields should have better translation. Leave comments here, if there are still some date formats to adjust.

**Comment by 5m4u66y** [comment]
Can we close this issue?

**Comment by derneuere** [comment]
Yeah, I think we can do that :)
