### ISSUE TITLE
User's settings can't load to web

### ISSUE THREAD

**Issue by CrazyShipOne** [LibrePhotos/librephotos#673]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
After modify and update confidence, semantic search topK options, favorite min rating on the setting page, reload the page, those select components are left black whereas returned json contains those value.

## 🔁 How can we reproduce it:
As same as description above.

## Please provide additional information:
- 💻 Operating system: 
docker
- ⚙ Architecture (x86 or ARM): 
amd64
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
2022w41

### Setting page:
![setting](https://user-images.githubusercontent.com/19662816/198876382-92343c0f-696a-47c9-8691-c9c7459b0552.png)

### Returned data:
![api](https://user-images.githubusercontent.com/19662816/198876386-91659d1d-9db1-4dec-a1c8-fc8c0c256a43.jpg)

**Comment by Nerodacles** [comment]
Still not loading and saving anything.

**Comment by Nerodacles** [comment]
Now it works in the dev branch, wait for the latest branch to be updated!
