### ISSUE TITLE
Scan Photos task resulted with 0 Item(s) processed after rescan non-zero directory

### ISSUE THREAD

**Issue by CrazyShipOne** [LibrePhotos/librephotos#674]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I have around 30k photos in the /data directory, after I clicked 'rescan all photo' and waited for 4 hours, changed photos (mostly exif changed since I run a script to correct them) are loaded perfectly but there is '0 Item(s) processed' under the job. Shouldn't the number be actual photos number it dealt with?

## 🔁 How can we reproduce it:
Do a 'rescan all photo' job on non-zero directories, see result of this job.

## Please provide additional information:
- 💻 Operating system: 
Debian
- ⚙ Architecture (x86 or ARM): 
x86

- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
2022w41
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
Local file system

**Comment by derneuere** [comment]
Changed it to "added new Assets(s)" to make it more clear and added a follow up ticket to add processed Assets to the repsonse :)
