### ISSUE TITLE
[Q]Should I put those "Unknown ####" faces back to "Unknown - Others" to let them to be infferred to another named person?

### ISSUE THREAD

**Issue by huangda1982** [LibrePhotos/librephotos#675]
Will faces in those "Unknown ####" be inferred to another named person ?

**Comment by 5m4u66y** [comment]
Hi,
Each time you run the train faces job, all existing inferred clusters are first deleted. Then the clustering is done again, taking into account all faces that are not already associated by the user to an existing person.
