### ISSUE TITLE
[Q] Wrong detected Faces?

### ISSUE THREAD

**Issue by luk6173** [LibrePhotos/librephotos#676]
Hi all,

I'm on the way to recognize all faces on my photos, but I have some issues. Some faces were wrong inferred so I deleted them and run the face trainig again. Again same faces were wrong inferred so I deleted them.

What is the right way to remove / exclude the wrong detected faces ?

Thank you and regards!

**Comment by loulou91** [comment]
About your wrong inferred, if you apply the same process it looks normal to get the same result ;-)

If the result is wrong you have the capability to manually affect the face to the right person or to delete it.

Hope this helps.

**Comment by luk6173** [comment]
ok, yes this helped! Thank you, my misstake :)
