### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by ippocratis** [LibrePhotos/librephotos#679]
I have "maped" my postgres database on an external drive
 `volumes:
      - ${data}/protected_media/db:/var/lib/postgresql/data`

{data} is `data=/run/media/ippo/TOSHIBA/`

In the .env

The db got corrupted somehow
The postgres container was in restarting loop

I recomposed the container and recreated the database but even if I had the thumbnails folder intact it was time consuming on a limited resources raspberry pi.

So,
What would be a proper way to take database backups?

I guess pg_dump and pg_dump_all? 

But then another concern is, do I have to handle missmaches in missing photos in the db emtries as   the backup most likely be a few days old?

Thanks and keep up

**Comment by ippocratis** [comment]
To answer my own question

I made some testing on a live test instance

Docker ps
Grab postgres container id

Backup

docker exec -t your-db-container pg_dumpall -c -U your-db-user > dump_$(date +%Y-%m-%d_%H_%M_%S).sql

Restore

cat your_dump.sql | docker exec -i your-db-container psql -U your-db-user -d your-db-name

*Note the -U dbuser (default is docker on. env)
and the -d bdname (default librephotos on. env)

I could also put that on a crontab and have periodic db snapshots

The above seems to work fine even if i took a db backup
copying some photos to the photos source folder 
Scaning
Deleting the db files so it got corrupted
Sertoring db
The ui returns to the prev version with the copied photos missing
run a scan and the missing photos return

**Comment by derneuere** [comment]
Thanks for figuring this out. It would be great, if you could also trigger this via the UI.
