### ISSUE TITLE
6gb+ docker image

### ISSUE THREAD

**Issue by techie2000** [LibrePhotos/librephotos#680]
**Describe the enhancement you'd like**
All ofmy many docker images combines are <15gb.... one layer alone (00856e006cf8) on the librephotos images is 6gb !!

**Describe why this will benefit the LibrePhotos**
On a slow connection, 6gb takes 'forever' to download, and excess/unused 'stuff' must be being retained on that layer (given that apps way more complex in nature that librephotos take up way less)

**Additional context**
```
Pulling image: reallibrephotos/singleton:latest
IMAGE ID [1965417284]: Pulling from reallibrephotos/singleton.
IMAGE ID [e96e057aae67]: Pulling fs layer. Downloading 100% of 29 MB. Verifying Checksum. Download complete. Extracting. Pull complete.
IMAGE ID [01eca18ab462]: Pulling fs layer. Downloading 100% of 60 MB. Verifying Checksum. Download complete. Extracting. Pull complete.
IMAGE ID [9207938ee730]: Pulling fs layer. Downloading 100% of 983 KB. Verifying Checksum. Download complete. Extracting. Pull complete.
IMAGE ID [ee2b68d68fec]: Pulling fs layer. Downloading 100% of 53 KB. Verifying Checksum. Download complete. Extracting. Pull complete.
IMAGE ID [b164cc3bd207]: Pulling fs layer. Downloading 100% of 106 KB. Download complete. Extracting. Pull complete.
IMAGE ID [dc5062a40050]: Pulling fs layer. Downloading 100% of 67 KB. Verifying Checksum. Download complete. Extracting. Pull complete.
IMAGE ID [4f4fb700ef54]: Pulling fs layer. Downloading 100% of 32 B. Verifying Checksum. Download complete. Extracting. Pull complete.
IMAGE ID [00856e006cf8]: Pulling fs layer. Downloading 13% of 6 GB.
IMAGE ID [17ec9298135e]: Pulling fs layer. Downloading 100% of 845 KB. Verifying Checksum. Download complete.
IMAGE ID [9b9b1629d62f]: Pulling fs layer. Downloading 100% of 1 MB. Verifying Checksum. Download complete.
IMAGE ID [4ceafbd41d85]: Pulling fs layer. Downloading 100% of 122 B.
IMAGE ID [570003f2242e]: Pulling fs layer. Downloading 100% of 5 KB. Verifying Checksum. Download complete.
IMAGE ID [504f653315c2]: Pulling fs layer. Downloading 100% of 530 B. Verifying Checksum. Download complete.
IMAGE ID [8bd51bdb2792]: Pulling fs layer. Downloading 100% of 5 KB. Verifying Checksum. Download complete.
IMAGE ID [84af761819c0]: Pulling fs layer. Downloading 100% of 174 B. Verifying Checksum. Download complete
```

**Comment by techie2000** [comment]
eeek... 2.5gb of cache, 4.3gb of python packages
```
drwxr-x---     999:999     7.5 GB  │   │   ├── librephotos

drwxrwxr-x     999:999     2.5 GB  │   │   │   ├─⊕ .cache
drwx------     999:999     4.3 GB  │   │   │   ├── .local
drwxrwxr-x     999:999     7.6 kB  │   │   │   │   ├─⊕ bin

drwxrwxr-x     999:999     4.3 GB  │   │   │   │   ├── lib
drwxrwxr-x     999:999     4.3 GB  │   │   │   │   │   └── python3.10
drwx------     999:999     4.3 GB  │   │   │   │   │       └── site-packages

```

**Comment by reivilibre** [comment]
(how much of this is the machine learning models?)

**Comment by 5m4u66y** [comment]
> (how much of this is the machine learning models?)

A bit less than 1 GB.
\+ 126 MB for faces recognition models
\+ 1.6 GB just for torch module

**Comment by firecat53** [comment]
I haven't played with it yet, but a casual glance through the Dockerfiles looks like all of the build-essential and make dependencies are retained. Those typically can be removed after build, but I'm not very familiar with this application. Also, there's probably some combining of layers during the build that could occur instead of having multiple RUN commands. Easier to debug that way, but definitely adds to the final size.

**Comment by rafalkrupinski** [comment]
Typically running all build commands and then removing all temporary files and build-related packages **in one command** using `&&` helps.

Wanted to have a look, but the only mention of Dockerfile is in .gitignore
(I haven't used LibrePhotos yet, but I'm planning to)

**Comment by derneuere** [comment]
We now use pytorch in cpu mode only. This should reduced the image size a bit. I think these issue are in general more fitting in the librephotos-docker repository.
