### ISSUE TITLE
When searching a person it does not appears

### ISSUE THREAD

**Issue by Nerodacles** [LibrePhotos/librephotos#686]
# 🐛 Bug Report

* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
When im searching a person in the demo2 and in my personal lb instance, the person face and name never appears.
I add a person and try to search it.
![image](https://user-images.githubusercontent.com/29661633/204623197-3ba312fc-60dc-4eb8-bf43-ee72b544d1d7.png)

Then if i search it in the search bar, the person never appears.
![image](https://user-images.githubusercontent.com/29661633/204623281-268371c3-be34-41a0-a64a-2a8ebbdd5613.png)

## 🔁 How can we reproduce it:
Just add a person in demo2, and try to search it.

## Please provide additional information:
- 💻 Operating system: ubuntu 20.04
- ⚙ Architecture (x86 or ARM): x64
- 🔢 Librephotos version: dev - latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
![image](https://user-images.githubusercontent.com/29661633/204623645-bd7f2cf6-82cc-4faa-a139-0b9c302321eb.png)

- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.):  NFS Share
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): Hyper-V

**Comment by DigitalWarrior** [comment]
Demo 1 allows searching by person.

**Comment by derneuere** [comment]
This is now implemented thanks to @Nerodacles
