### ISSUE TITLE
email is not accepted

### ISSUE THREAD

**Issue by vulubalulu** [LibrePhotos/librephotos#689]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
During the registering process my email format of aaa.**b**.cccc@xxx is not accepted as a valid email address.
Through trial and error I have found out that aaa.**bb**.cccc@xxx is accepted as a valid email address

Probably related to this closed issue 
https://github.com/LibrePhotos/librephotos/issues/637

**Comment by AudreyBeard** [comment]
Looks like this is an issue with https://github.com/LibrePhotos/librephotos-frontend, though it looks like issues are deactivated there

**Comment by AudreyBeard** [comment]
Proposed a quick solution (in above PR), but I think it's worth considering an overhaul on email verification because the regex seems quite brittle
