### ISSUE TITLE
Volumes defined in docker-compose.yaml but unused

### ISSUE THREAD

**Issue by craumix** [LibrePhotos/librephotos#69]
The section
`volumes:
  librephotos-data:
  media:`
at the end of the compose file defines two volumes. Though they are never used.

The postgres has a bind-mount with a similar name.
`$HOME/librephotos_data:/var/lib/postgresql/data`

It would probably be a good idea to use the volumes in appropriate mounts or remove the from the compose file.

**Comment by derneuere** [comment]
Thanks, I removed the unused volumes! :+1:
