### ISSUE TITLE
Base URL functionality

### ISSUE THREAD

**Issue by rutj87** [LibrePhotos/librephotos#694]
Hi, 

Love this!

I am trying to get librephotos working behind my Nginx Proxy Manager within a custom location but can't see that Librephotos has the option to set base url anywhere for reverse proxy. Is there a way to do this?

Thanks in advance!

**Comment by sickelap** [comment]
Could you provide more details?

**Comment by derneuere** [comment]
Seems like the same issue as this one here #757
