### ISSUE TITLE
Server app for on android

### ISSUE THREAD

**Issue by abdulhakam** [LibrePhotos/librephotos#698]
Is there a server app for android, or a wrapper app like docker in apk to run on older android phones. or maybe run it on QPython/QPython3

this will allow anyone who has an old android phone turn it into a NAS device and the phones will still be in use for longer periods of time,

Its like this: I have 6 or 7 old but perfectly working android phones (oldest one has android 4.4KitKat), I am currently using them as FTP servers on my home wifi, since they had large enough memory cards in them, now I thought "it would be better if I could run librephotos on them" so I wont have to search thousands of files on ftp network to find one particular file, BUT  the problem is my phones all those phones except ONE (the oldest one) are unable to run docker on either terminal emulator or termux, nor am I able to  root them, so I think the server packaged as an app could be the only thing that would work, BTW QPython is working on all phones,

**Comment by ippocratis** [comment]
> Is there a server app for android, or a wrapper app like docker in apk to run on older android phones. or maybe run it on QPython/QPython3

No

Well there is docker in termux and and python in termux and there are linux chroot apps and there are phones capable running droidian/ubuntu touch

> this will allow anyone who has an old android phone turn it into a NAS device and the phones will still be in use for longer periods of time,

True but android even though is based on linux,  linux for arm package wont work for android and they have to be compiled spesifictly for android

So 

It would be great to see that happen but development is already crazy on the software and I think it will be quite hard work to port the packages to android

**Comment by abdulhakam** [comment]
Thanks, I guess the last option would be to get pure python server app and run it using QPython. It wont have any advanced features but at least I would be able to search, view and download files through it via browser. Much better than FTP I think.
