### ISSUE TITLE
Regression : scrolling issue in faces screen

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#699]
With version dated 18/12/2022 : I got a new strange issue on Chrome browser HMI (pc win11 and tablet android) : on faces screen (labelled and inferred) when I scroll down, the screen goes up and down several times...
I've been able to reproduce it with a small test base !

**Comment by guystreeter** [comment]
Happens for me as well. Extremely annoying

**Comment by Nerodacles** [comment]
I think it was after this commit of the [librephotos-frontend](https://github.com/LibrePhotos/librephotos-frontend/commit/cecaa29d00a8513a257fb09234d4393da525660c).

Its happening in the demo2 lb server too.

https://user-images.githubusercontent.com/29661633/208511221-a99c80d9-1eba-493d-a9f7-97bf88c4dec8.mp4

I'm just scrolling up and down, and it keeps regressing itself to the "middle" of the person.

**Comment by derneuere** [comment]
It was probably this commit here: https://github.com/LibrePhotos/librephotos-frontend/commit/83c8c717d7368dbbfd186bc5cf5a2ada315b3a3f#diff-dc7f1f3734828052777186915da0b6f0a32bb7a991cfd6dd334a2a89d6f7aa54R96

@sickelap Could you revert the changes you made to the useEffect Hooks?

**Comment by Nerodacles** [comment]
> It was probably this commit here: [LibrePhotos/librephotos-frontend@83c8c71#diff-dc7f1f3734828052777186915da0b6f0a32bb7a991cfd6dd334a2a89d6f7aa54R96](https://github.com/LibrePhotos/librephotos-frontend/commit/83c8c717d7368dbbfd186bc5cf5a2ada315b3a3f#diff-dc7f1f3734828052777186915da0b6f0a32bb7a991cfd6dd334a2a89d6f7aa54R96)
> 
> @sickelap Could you revert the changes you made to the useEffect Hooks?

Yea,it's that commit!

**Comment by sickelap** [comment]
I'll look into it
