### ISSUE TITLE
Standard local install, cannot connect to BE

### ISSUE THREAD

**Issue by githlp** [LibrePhotos/librephotos#700]
**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
gunicorn_django.log says:
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password-authentification for user »docker« failed

maybe it's a problem that gitea-server is listening already on that port ?

netstat -plant | grep 5432
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1206/postgres
tcp        0      0 127.0.0.1:52128         127.0.0.1:5432          TIME_WAIT   -
...
tcp        0      0 127.0.0.1:5432          127.0.0.1:44132         ESTABLISHED 1395/postgres: 13/m
tcp        0      0 127.0.0.1:5432          127.0.0.1:44182         ESTABLISHED 1438/postgres: 13/m
tcp        0      0 127.0.0.1:52176         127.0.0.1:5432          TIME_WAIT   -
...
tcp        0      0 127.0.0.1:44132         127.0.0.1:5432          ESTABLISHED 1345/gitea
tcp        0      0 127.0.0.1:52040         127.0.0.1:5432          TIME_WAIT   -
tcp        0      0 127.0.0.1:44182         127.0.0.1:5432          ESTABLISHED 1345/gitea
...

Maybe i need to change that listening port for librephotos, just how?

## 🔁 How can we reproduce it:
install on server where another psql dependent service is already running

## Please provide additional information:
ubuntu server 22.04 x86_64

- 🔢 Librephotos version: latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): deb lobal install

**Comment by githlp** [comment]
After running ./install-librephotos.sh also my nextcloud cannot reach the psql-db anymore.. What could be the reason ?

**Comment by sickelap** [comment]
Not related to the issue, but netstat flags made me laugh :rofl:

**Comment by githlp** [comment]
there is no initial account after setup, or what should that be?
so i added in librephotos-backend.env
```
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin1235
```

but the FE raises error message:
```
"Detail
No active account found with the given credentials"
```

Where or how can i setup an active account for starting with librephotos ?

**Comment by githlp** [comment]
solved with
`sudo librephotos-cli changepassword admin`

Entered, finally :-)
