### ISSUE TITLE
Initial setup not running

### ISSUE THREAD

**Issue by DigitalWarrior** [LibrePhotos/librephotos#702]
# 🐛 Bug Report

* [ X] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ X] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Setup does not run on fresh install. No questions to set up admin user ect. 

## 🔁 How can we reproduce it:
Clean install

## Please provide additional information:
- 💻 Operating system: Red Hat Stream 9
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker (other users report issues with pi and unraid
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): n/a
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):  n/a
[lplog.zip](https://github.com/LibrePhotos/librephotos/files/10273332/lplog.zip)

**Comment by DigitalWarrior** [comment]
I think I have tracked down the issue. the docker-compose.yml was changed. 
https://github.com/LibrePhotos/librephotos-docker/commit/f12a321008dd175b115da98f980ce9c3f01e5b79
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - ADMIN_EMAIL=${adminEmail:-admin@localhost}
      - ADMIN_USERNAME=${userName:-admin}
      - ADMIN_PASSWORD=${userPass:-admin}
     Pinged the author of the change. Awaiting response.

**Comment by Nerodacles** [comment]
@DigitalWarrior remember to close this!

**Comment by DigitalWarrior** [comment]
nope leaving it open. 😂
