### ISSUE TITLE
Library Scans 

### ISSUE THREAD

**Issue by nikhilhurule** [LibrePhotos/librephotos#704]
**Describe the enhancement you'd like**
Once the whole library is scanned  you should be able to just add library path to another user and the user should be able to see the library without Scanning it again
**Describe why this will benefit the LibrePhotos**
now you have to scan library for every user and if you have like huge library and 10-20 users it takes a lot of time .

**Additional context**
it will save alot of time and processing power and time and help to easly add new user and instant access to the library

**Comment by DigitalWarrior** [comment]
I am currently sharing Albums with other users. This way they can not delete photos ect.

**Comment by Nerodacles** [comment]
> I am currently sharing Albums with other users. This way they can not delete photos ect.

This is 100% better!

**Comment by derneuere** [comment]
This seems similar to #395
