### ISSUE TITLE
Newbie basics: how to share

### ISSUE THREAD

**Issue by rfortier** [LibrePhotos/librephotos#705]
Brand new to librephotos, can't figure out how to share photos to another (non-admin) account.

If the answer is RTFM, I'm fine with that, I just need a pointer to a non-developer manual. Everything I find is install notes or bugs or enhancement requests on Github. 

Is there a forum somewhere that's not Github issues and enhancement requests? If there is, it does not fall over easily to Google searches.

If the answer is it's early, go read the code, I'm fine with that too, just don't want to put in that work if there is an obvious simpler answer. 

Details:

Installed Librephotos on my QNAP NAS using docker-compose 'latest' path. Created admin account, set up an originals directory, scanned some stuff and everything worked beautifully. Especially facial recognition. Great work, folks. 

Created a second, non-admin account with the same originals directory. Zero photos. Scanned the directory, went fast because sidecars are configured, but still zero photos. 

Went back and made all Admin's photos public. No change.

Went back and tried to share all Admin's photos to 2nd account (maybe sharing originals directories isn't supported?). Still no change, but the sharing interface is non-intuitive (asks me about unsharing when I'm trying to share), maybe I'm not doing it right. 

So, I'm stumped. This is so basic it seems it can't be a bug (or I'd provide more details and follow the bug report process). Can someone point me in the right direction?

**Comment by derneuere** [comment]
Only one user at a time owns a directory and it's child folders. If you want to share photos between users, use the share function of LibrePhotos instead.

**Comment by rfortier** [comment]
Thanks. Knew it had to be something simple. Happy New Year!
