### ISSUE TITLE
Album site disappears when entering a char into Album share dialog 

### ISSUE THREAD

**Issue by githlp** [LibrePhotos/librephotos#706]
I have two more users in librephotos and when i want to share my first Album the Share dialog appears.

The two other users are listed with correct "Joined" time but i cannot set slider (it's inactive).

As soon as i enter first char of a username the whole page turns white.

A page reload brings back the Album overview site. So sharing does not work - maybe there are insufficient rights ?

**Comment by derneuere** [comment]
I could set the sharing slider, but I could recreate your issue when searching for people and fixed it :)
