### ISSUE TITLE
regression in "label faces" feature

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#707]
With pull dated 2022-12-26

I want to associate a face to a known person. When I type the first letter all already known names disappear from the list. I have to type the full name to see it reappear. Easy to reproduce as well as with a brand new data base...

**Comment by loulou91** [comment]
Doe's anyone share my concern? I tested it on demo base and it's the same...

**Comment by Nerodacles** [comment]
> Doe's anyone share my concern? I tested it on demo base and it's the same...

With demo1, or 2?

**Comment by Nerodacles** [comment]
But yea, i think i know what you mean, the method that i always used, is to do a ctrl + f, to find the name of the person.

Because when you add it in the input, that input always stays, and it doesnt resets itself after searching for a person.

**Comment by loulou91** [comment]
With demo2. My method was working before and I would appreciate to see it working again ;-)

**Comment by sickelap** [comment]
I found what the issue is. will fix that.
