### ISSUE TITLE
New Librephoto Docker setup -- unable to scan photo when login as User (admin sees photos)

### ISSUE THREAD

**Issue by adangster1** [LibrePhotos/librephotos#708]
I am using Docker compose via Windows to start Librephoto
- Admin assigned to **/data** and able to see all the pictures stored in this directory (as expected)
- I created  _"user1"_ and only assigned access to **/data/user1** folder 

>>> Logged in Admin --> I can see all the photos in /data/user1/photos_dir
>>> Logged in as User1 --> No photo detected in  /data/user1
----What did I do wrong here ? User1 is unable to see/access subfolder? Or user function does not actually work?
I am considering moving from Synology Photos --> librephoto .. but unable to support users is no go for me.

Folder structure:
# Location of your photos.
scanDirectory="C:/LibrePhoto_Folder"

# Internal data of LibrePhotos
data=./librephotos/data

----------------
Windows Folders structure
"C:/LibrePhoto_Folder"     --> /data
"C:/LibrePhoto_Folder/user1"  --> data/user1
"C:/LibrePhoto_Folder/user1/photos_dir"

**Comment by derneuere** [comment]
Only one user at a time owns a directory and it's child folders. If you want to share photos between users, use the share function of LibrePhotos instead.
