### ISSUE TITLE
faces rescan uses all memory

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#718]
With pull dated 04/01/2023 chrome WEB UI, 53K pictures.
After rescan request memory is almost fully used included swap as shown on screen capture. If I stop LP, swap memory is not freed.
Normal scan works without any problem.
![image](https://user-images.githubusercontent.com/51127123/210623453-da41c9db-e92d-4f2c-8297-012be93a1cda.png)

**Comment by loulou91** [comment]
It's probably more complicated that what I said...
I relaunched rescan yesterday and this morning I got thiese screens 
![image](https://user-images.githubusercontent.com/51127123/210741032-aa6800ad-d775-49e7-b0e0-fbbc328fc34e.png)
![image](https://user-images.githubusercontent.com/51127123/210741189-1476624d-0ea7-456b-a017-1edd40efe05d.png)
The CPU looks no more used but the job is still running and here is the own log.
[ownphotos-s.log](https://github.com/LibrePhotos/librephotos/files/10350789/ownphotos-s.log)
What can I do more to track the issue?

**Comment by loulou91** [comment]
I got also this in rqworker log
`16:17:20 default: api.autoalbum.generate_event_albums(<User: admin>, UUID('d51b60e8-10c1-4e42-a443-adfb30fbfcd1')) (c18fe917-dee9-4e58-b68f-272d4cb2e04a)
16:32:18 default: Job OK (c18fe917-dee9-4e58-b68f-272d4cb2e04a)
16:32:18 Result is kept for 60 seconds
16:32:18 Cleaning registries for queue: default
16:33:06 default: api.directory_watcher.scan_faces(<User: admin>, UUID('0e3bf903-b546-4adf-8a33-8f475a044be5')) (ba5c1d80-3c92-4d28-a511-3c6bb978d2ea)
Exception in thread Thread-2 (_handle_workers):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 516, in _handle_workers
    cls._maintain_pool(ctx, Process, processes, pool, inqueue,
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 340, in _maintain_pool
    Pool._repopulate_pool_static(ctx, Process, processes, pool,
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
`

**Comment by Nerodacles** [comment]
> It's probably more complicated that what I said... I relaunched rescan yesterday and this morning I got thiese screens ![image](https://user-images.githubusercontent.com/51127123/210741032-aa6800ad-d775-49e7-b0e0-fbbc328fc34e.png) ![image](https://user-images.githubusercontent.com/51127123/210741189-1476624d-0ea7-456b-a017-1edd40efe05d.png) The CPU looks no more used but the job is still running and here is the own log. [ownphotos-s.log](https://github.com/LibrePhotos/librephotos/files/10350789/ownphotos-s.log) What can I do more to track the issue?

On my end, it uses 100% all the cpu, and the memory i think it frees the memory when the scan finishes, bc, it went from consuming 3.3gb -> 5gb -> 3.3gb.

**Comment by derneuere** [comment]
Does not happen on my system. Please reopen, when it's still an issue with amount of workers / Heavyweight Processes
