### ISSUE TITLE
Fix the public user list

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#724]
Right now we have the problem, that the public list no longer loads for regular users. The reasons are twofold:
1. The previous used "api/user" endpoint shared too much information for a regular user
2. The public user list was not opt in

To fix this, we have to implement:
- [x] a user list view with less information (public name, number of public photos), where only user who opted in are shown
- [x] a new boolean in user to allow public sharing
- [x] add the boolean to the sign-up and to the settings page

**Comment by sickelap** [comment]
I will look into this

**Comment by derneuere** [comment]
Thanks for implementing this :)
