### ISSUE TITLE
recurring worker timeout 

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#725]
Running Librephotos in docker

After running without problems for a while, UI is not being populated and tmy logs are full of messages like the following:
backend_1   | use SECRET_KEY from env
backend_1   | [2023-01-12 11:47:02 +0000] [168] [CRITICAL] WORKER TIMEOUT (pid:547)
backend_1   | [2023-01-12 11:47:02 +0000] [547] [INFO] Worker exiting (pid: 547)
backend_1   | [2023-01-12 11:47:03 +0000] [168] [WARNING] Worker with pid 547 was terminated due to signal 9
backend_1   | [2023-01-12 11:47:06 +0000] [558] [INFO] Booting worker with pid: 558
backend_1   | use SECRET_KEY from env
backend_1   | [2023-01-12 11:47:21 +0000] [168] [CRITICAL] WORKER TIMEOUT (pid:557)
backend_1   | [2023-01-12 11:47:22 +0000] [168] [WARNING] Worker with pid 557 was terminated due to signal 9
backend_1   | [2023-01-12 11:47:22 +0000] [565] [INFO] Booting worker with pid: 565
backend_1   | use SECRET_KEY from env
backend_1   | [2023-01-12 11:47:36 +0000] [168] [CRITICAL] WORKER TIMEOUT (pid:558)
backend_1   | [2023-01-12 11:47:36 +0000] [558] [INFO] Worker exiting (pid: 558)
backend_1   | [2023-01-12 11:47:37 +0000] [168] [WARNING] Worker with pid 558 was terminated due to signal 9
backend_1   | [2023-01-12 11:47:37 +0000] [569] [INFO] Booting worker with pid: 569

This is correlating with other jobs on the machine driving high disk I/O activity, so presumably it could be partially remedied by adjusting the worker timeout setting, but I don't see where to set that option.

Regardless, it would be a more resilient approach to keep track of recurring worker death and maybe gradually increasing timeouts before killing/relaunching the worker process

**Comment by derneuere** [comment]
Probably same issue as #755
