### ISSUE TITLE
Loosing unknown faces when requesting successive train faces

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#729]
Hereafter you can see the scenario I run to highlight the issue. I reported the various number of faces we can see on Library tab and faces tab (labelled and inferred popup).
It looks coherent when I remove some faces and associate cluster with a name. At one moment I launched successive faces train without any additional actions. And I noted figures continue to evolve and apparently some unknown faces disappear.
If necessary, I will try to prepare a smaller base to simply reproduce the problem.
![image](https://user-images.githubusercontent.com/51127123/212881727-f0c1643d-d264-46e9-bb8c-65aedca9b0a1.png)

**Comment by loulou91** [comment]
I made some progress to reproduce the issue with only 2 pictures! Hope a dev will accept to take a look ;-)
![image](https://user-images.githubusercontent.com/51127123/212967982-a230883c-dbb1-4344-ac12-ad38fcdaa122.png)
As shown on the attached capture, I run the following scenario:
1/Launch LP and request scanning of 2 pictures containing 155 faces
2/ creation of 2 persons from labelled unknown-other set of faces, pers1 with 10 faces pers2 also with 10 faces. For the time being all is correct
3/ start train faces ; then a 3rd not visible person appears in the count but not on faces tab
4/ after that, if I delete all present faces, one unknown person and one unknown face still exists. If I look to the detail of one of the 2 picture, I see ONE unknown-other face.
I repeated this scenario several time with the same result. I guess that if someone follows strictly the scenario he should get the same result! That's it ;-)
I join a zip file containing LP directory including the 2 pictures.
[LP issue 729.zip](https://github.com/LibrePhotos/librephotos/files/10437924/LP.issue.729.zip)

Notes,
1/ generally speaking inconsistencies look to start when the number of persons in Library tab is different that the one in Faces tab.
2/ the third person look to be in fact "Unknown - Other" to which a face is now associated, seen with the command:

librephotos=# select * from api_person;
| id |      name              |  kind              | cover_photo_id | cluster_owner_id |
|---|---|---|---|---|
|  1 | Unknown - Other | UNKNOWN||

(1 row) After db creation

| id |      name              |  kind              | cover_photo_id | cluster_owner_id |
|---|---|---|---|---|
|  1 | Unknown - Other | UNKNOWN||
|  2| Unknown - Other | UNKNOWN||1|
|  3 | Unknown 1          | CLUSTER      |                           |                1
|  4 | Unknown 2          | CLUSTER      |                           |                1

(4 rows) After 1st scan		

 id |      name              |  kind              | cover_photo_id | cluster_owner_id 
|---|---|---|---|---|
|  1 | Unknown - Other | UNKNOWN |                           |                 
|  2 | Unknown - Other | UNKNOWN |                           |                1
|  3 | Unknown 1          | CLUSTER      |                           |                1
|  4 | Unknown 2          | CLUSTER      |                           |                1
|  5 | pers1                    |                     |                           |                1
|  6 | pers2                    |                     |                           |                1

(6 rows) After creation of pers1 & pers2	Library tab says 2 people

 id |      name              |  kind              | cover_photo_id | cluster_owner_id 
|---|---|---|---|---|
|  1 | Unknown - Other | UNKNOWN |                           |                 
|  2 | Unknown - Other | UNKNOWN |                           |                1
|  5 |pers1                    |                      |                           |                1
|  6 | pers2                   |                      |                           |                1
|  7 | Unknown 1          | CLUSTER      |                           |                1
|  8 | Unknown 2          | CLUSTER      |                           |                1

(6 rows) After train faces    Library tab says 3 people

**Comment by loulou91** [comment]
As far as demo2 server is functioning again, I've been able to reproduce the issue while uploading the 2 pictures with numerous persons.
Hope this helps!
![gettyimages-200244581-003-1024x1024](https://user-images.githubusercontent.com/51127123/214506077-9d180a2a-b448-4bc9-8a9d-5564fd3855f0.jpg)
![gettyimages-1291584234-1024x1024](https://user-images.githubusercontent.com/51127123/214506082-1c3406ae-fbda-4fbb-b2b4-f6fc106df7b0.jpg)

**Comment by derneuere** [comment]
Should be fixed now :)
