### ISSUE TITLE
Inconsistent pan and zoom, unable to access image right click menu

### ISSUE THREAD

**Issue by Janhouse** [LibrePhotos/librephotos#731]
For some images zoom and pan using scrollbar, and image right click menu works, while for others it doesn't. It appears to happen because some `<div>` element is put on top of the image.

I have attached a video showing this behavior.

Using librephotos docker containers, dev version (pulled a few days ago). Frontend container ID: 3d78745d18ec

Not sure if relevant, but all the original images are in HEIC format.

[Screencast from 2023-01-17 16-23-27.webm](https://user-images.githubusercontent.com/1036439/212924938-38024f41-62a2-4ad8-8c39-95b67cede6b6.webm)

**Comment by derneuere** [comment]
Similar to this issue here: https://github.com/LibrePhotos/librephotos/issues/486

Mantine has a function for that https://mantine.dev/hooks/use-scroll-lock/

**Comment by Janhouse** [comment]
> Similar to this issue here: #486
> 
> Mantine has a function for that https://mantine.dev/hooks/use-scroll-lock/

That one is just an issue that can also be seen in the attached video, but it is a different issue. :slightly_smiling_face:
