### ISSUE TITLE
Demo site has no photos and/or doesn't allow uploads

### ISSUE THREAD

**Issue by gene1wood** [LibrePhotos/librephotos#733]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

When visiting the demo site and logging in as `demo / demo1234` the site has no photos. Additionally when I upload a test photo to see how librephotos works when there's actual content there, nothing happens. I've tried changing the demo user's base directory around but haven't had luck.

Is this intentional (that there are no photos, and that uploads don't work)?

## 🔁 How can we reproduce it:

Visit the demo site and you'll find no photos. Try to upload a photo. It says it's successful but there remain 0 photos on the site.

**Comment by derneuere** [comment]
Found the issue. The demo instance should refresh with the new image in the next 12 hours or so :)
