### ISSUE TITLE
Blank white screen after navigating to two photos with info pane open

### ISSUE THREAD

**Issue by pseudo64** [LibrePhotos/librephotos#743]
I installed LibrePhotos last night and scanned a local dir with jpg/mp4 files across a few scan sessions.  Things were OK at first, but currently there are two photos that I cannot select the info button to bring up the detail pane - when that is attempted, the entire screen just renders white and I have to refresh the page to return to the home screen.  This is across browsers and docker restarts.

**Comment by sickelap** [comment]
The issue does not contain enough information for developers to reproduce.
Please update the issue by using issue template. Otherwise, it likely will be closed without even looking at it.

**Comment by derneuere** [comment]
More specifically, the logs from your browser would be helpful :) It sounds like a frontend issue

**Comment by derneuere** [comment]
I will reopen this issue once we have more details.
