### ISSUE TITLE
Import already tagged faces with 3rd party software

### ISSUE THREAD

**Issue by ippocratis** [LibrePhotos/librephotos#746]
**Describe the enhancement you'd like**
An option to add people faces already tagged with another software.Popular options are Google photos and photoprism

**Describe why this will benefit the LibrePhotos**
Resource economy:i'm running librephotos on a low power raspberry pi 400 and face classification is resource intensive 
Time econony:face clustering/grouping is mostly inaccurate (in my experience) with librephotos and I have to manually tag almost each face .it will save me huge amount of time to add already tagged faces 

**Additional context**
Thanks and keep up

**Comment by webysther** [comment]
A great example is using the industry standard for face tagging and this [plugin](https://github.com/colin0brass/FaceLabellingExportLrPlugin) make possible to collect this information.

**Comment by derneuere** [comment]
I added reading of faces a release back :)
