### ISSUE TITLE
Manually add people to a photo

### ISSUE THREAD

**Issue by z-designs** [LibrePhotos/librephotos#748]
**Describe the enhancement you'd like**
I would like to option to add a person to a photo, when a face is not detected.

**Describe why this will benefit the LibrePhotos**
It would make it possible to find photos of people, even if their back was turned or their face cannot be detected.

**Comment by andras-tim** [comment]
E.g. this image contains multiple people, but the LibrePhotos recognizes only one:
![image](https://user-images.githubusercontent.com/619016/225694310-2f2613ec-cec1-4b6b-a3c8-db41c627bbeb.png)

![image](https://user-images.githubusercontent.com/619016/225694471-5a4dbf9b-fab9-4aa7-bc4d-1acb6e1bc463.png)

**Comment by andras-tim** [comment]
Same here:
https://github.com/LibrePhotos/librephotos/issues/431
