### ISSUE TITLE
Video library filter

### ISSUE THREAD

**Issue by z-designs** [LibrePhotos/librephotos#750]
**Describe the enhancement you'd like**
The option to look only at videos and only at photos.

**Describe why this will benefit the LibrePhotos**
Currently when you go to the library photos and videos are mixed together and there is no easy way to filter/sort them.

**Comment by dotanm** [comment]
Good idea! Perhaps there can be 2 new options in the Photos drop-down:
Photos only
Videos only

Here:
![image](https://user-images.githubusercontent.com/2696449/219044788-0b96e621-6a1a-4610-bfd0-18edc358177e.png)

**Comment by AnkurPrabhu** [comment]
would love to work on this can this be assigned to me ?

**Comment by derneuere** [comment]
@AnkurPrabhu Assigned it :)

**Comment by AnkurPrabhu** [comment]
have created the backend pr once my front-end is setup will create the front end pr
