### ISSUE TITLE
LibrePhotos keeps restarting and cannot access pages

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#755]
# 🐛 Bug Report

* [X] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X] ❌ I have looked for similar issues (including closed ones)
* [X] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

My setup keeps restarting it seems (cannot access pages most of the time) 

I get this in the logs, not sure if this is an error or not (it is labeled as a warning but who knows):

## Please provide additional information:
- 💻 Operating system: Ubuntu
- ⚙ Architecture (x86 or ARM): x86 
- 🔢 Librephotos version: Docker latest version
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: 
    reallibrephotos/librephotos:dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
   local filesystem (ext4)
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): 
- 
[logs.txt](https://github.com/LibrePhotos/librephotos/files/10725565/logs.txt)

**Comment by derneuere** [comment]
Does this still happen for you?

**Comment by savvasdalkitsis** [comment]
it does unfortunately. i've been running latest and updating the image quite frequently. the server works fine (accessing from UhuruPhotos) but when i load the web ui it seems to fall over

**Comment by derneuere** [comment]
Similar error to #799

**Comment by atlas-shrugged08** [comment]
I am experiencing the same issue. Crashes every minute or so and unusable as of now. Also tried with the latest dev build.

fwiw, I created a new instance and did a quick scan of about 300 pics/videos and left it overnight, there are no crashes. 
So the crashes start to occur only on large data. (a.k.a realistic data).

**Comment by derneuere** [comment]
Also improved api/albums/thing/list query. This should now be faster, which should fix this error.
