### ISSUE TITLE
Update people thumbnails

### ISSUE THREAD

**Issue by nagarrido** [LibrePhotos/librephotos#759]
**Describe the enhancement you'd like**

At the moment, when adding faces to a person, the displayed thumbnail is always the same and does not change despite changing that person's album cover.

**Describe why this will benefit the LibrePhotos**

In the android client uhuru photos, people are shown with the thumbnail which is not updated, instead of the selected album cover for the person. It would be nice to have my current face and not my 1-year-old face in the people section of the app :)

**Comment by derneuere** [comment]
It should now pick the face from the cover image.
