### ISSUE TITLE
In face tab when typing the name it say personn already exist and can't se to this

### ISSUE THREAD

**Issue by yodatak** [LibrePhotos/librephotos#765]
With latest for docker, i got a huege amount of face to sort and photos to sort 63952 photos
70448 faces,51 personns 
 
It don't work when i click on "Moi" , and i got also no feedback that the action is ok or not

![image](https://user-images.githubusercontent.com/704477/221955154-e8b6fca3-59b8-43d6-87eb-0beec4c99613.png)

**Comment by derneuere** [comment]
Cant reproduce.
