### ISSUE TITLE
Display more image metadata

### ISSUE THREAD

**Issue by craumix** [LibrePhotos/librephotos#77]
From what I can make out, currently only geolocation and the timestamp are exported from the imported images. (Please feel free to close this if I'm wrong)

I think it would be important to import all of an images metadata, especially for RAW images.

**Comment by derneuere** [comment]
This is related to #10 

All the exif data is saved as a json here: https://github.com/LibrePhotos/librephotos/blob/7f3d17538e03d022aceb18143f22acb95c2239ca/api/models.py#L132

And set here:
https://github.com/LibrePhotos/librephotos/blob/7f3d17538e03d022aceb18143f22acb95c2239ca/api/models.py#L305-L312

And here:
https://github.com/LibrePhotos/librephotos/blob/7f3d17538e03d022aceb18143f22acb95c2239ca/api/models.py#L342-L348

But yeah, we should import all the metadata as own fields and display it in the frontend. Do you have a list of what fields we should add?

**Comment by craumix** [comment]
I'm not sure if exporting all the metadata as own fields is necessary since it only needs to be displayed...
But if you want to go that route I would probably choose something similar to what Photoprism shows so:

- Altitude
- Camera
- ISO
- Exposure
- Lens
- F Number
- Focal Length

**Comment by wahlis** [comment]
I would recommend to also read the IPTC info like keywords, caption etc. See https://www.carlseibert.com/guide-iptc-photo-metadata-fields/ for a photographers idea about what to use

**Comment by robertcontois** [comment]
I've rewritten most of the EXIF read portion of the code to be more efficient and updated the module that reads the EXIF data to support any file format supported by exiftool (https://exiftool.org/#supported). Other code needs to be changed for those new files types to be imported, but when that happens we'll be able to read the EXIF data.

We're still working on an efficient way to store the information and display it but it's not trivial.

**Comment by totti4ever** [comment]
Great you are working on this, just want to second that request. Extended request would be to search for it :-)

**Comment by tbrtje** [comment]
+1, that would be awesome. If it is possible to implement after this is done, editing things like keywords or other metadata from the webif would be neat too

**Comment by derneuere** [comment]
More exif data fields are now in the backend. It now just has to be implemented in the web view.

**Comment by wjbeckett** [comment]
This is amazing. 
Definitely looking forward to more exif data being visible. Would this also make it easier to search and show images based on similar EXIF data? For example, all photos taken with that camera?

Will there need to be a rescan of the photos to have this data viewed in the frontend?
