### ISSUE TITLE
I cannot install Librephotos with Docker.

### ISSUE THREAD

**Issue by eleven05** [LibrePhotos/librephotos#776]
# 🐛 Bug Report
## 📝 Description of issue:
When running "docker-compose up -d"in CMD on windows 11 I get these errors.

time="2023-03-06T18:40:51-08:00" level=warning msg="The \"scanDirectory\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"data\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"httpPort\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"tag\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbUser\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbName\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbUser\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbPass\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbName\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"data\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"tag\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"tag\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"scanDirectory\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"data\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"data\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"data\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbName\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbUser\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbPass\" variable is not set. Defaulting to a blank string."
time="2023-03-06T18:40:51-08:00" level=warning msg="The \"dbHost\" variable is not set. Defaulting to a blank string."
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid spec: :/data: empty section between colons

In the ENV file I only changed my location of photos and internal data to...
# Start of mandatory changes. 

# Location of your photos.
scanDirectory=E:AZ

# Internal data of LibrePhotos
data=D:/Self Hosted/LibrePhotos/data

## 🔁 How can we reproduce it:
https://docs.librephotos.com/1/standard_install/ goes to a broken page so i used https://docs.librephotos.com/docs/installation/standard-install.

## Please provide additional information:
- 💻 Operating system:  windows 11
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker compose
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): external drive
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
You probably forgot to rename the librephotos.env to .env

**Comment by eleven05** [comment]
Yup, I did not do that, Thanks for helping.

**Comment by sanxi33** [comment]
after this，I get another problem：
PS D:\librephoto\librephotos-docker> docker-compose up -d
[+] Running 5/6
 - Network librephotos-docker_default  Created                                                                                                          0.0s
 - Container frontend                  Started                                                                                                          1.2s
 - Container redis                     Healthy                                                                                                          6.2s
 - Container db                        Error                                                                                                            3.2s
 - Container backend                   Created                                                                                                          0.1s
 - Container proxy                     Created                                                                                                          0.1s
dependency failed to start: container for service "db" is unhealthy

I fixed it by change the docker-compose.yml :
    volumes:
      - ${data}/db:/var/lib/postgresql/data
to
    volumes:
      - ${data}/db:/var/lib/postgresql/data 777
