### ISSUE TITLE
Install for windows 10 exe?

### ISSUE THREAD

**Issue by ghost** [LibrePhotos/librephotos#777]
aa

**Comment by derneuere** [comment]
This is a duplicate and part of #57. Currently, nobody is working on it and there are still a lot of steps to take. If you want to work on it, I can give you an outline of the steps needed.

**Comment by gabryk91** [comment]
@derneuere I'm interested in helping with deploy a windows install solution without docker. Count me in if you want to share infos to work in that direction. Thanks
