### ISSUE TITLE
Dedicated place for documentation

### ISSUE THREAD

**Issue by strugee** [LibrePhotos/librephotos#78]
@foobazbar123 and I have been chatting on IRC and we think it would be great if LibrePhotos had a dedicated place for documentation - ReadTheDocs seems like an obvious choice. Honestly it doesn't really matter (we could even just use a `docs/` folder) though, as long as there's some way to separate multiple pages. The project README is just going to get ridiculously long otherwise.

**Comment by derneuere** [comment]
Hey @strugee , we started using the [wiki](https://github.com/LibrePhotos/librephotos/wiki). Do you think that this would fit?

**Comment by strugee** [comment]
Sounds great :+1:

**Comment by strugee** [comment]
I can set up a basic home page on the wiki, copy some of the README into the wiki, and then send a PR removing what I copied and pointing at the wiki if that works for you?

**Comment by mgrove36** [comment]
It's been decided that we'll be using GitHub pages for a documentation site. There's a repo for it [here](https://github.com/LibrePhotos/librephotos-docs)

**Comment by derneuere** [comment]
http://docs.librephotos.com/ is online!
