### ISSUE TITLE
can't login using the pre-release apk

### ISSUE THREAD

**Issue by ippocratis** [LibrePhotos/librephotos#786]
# 🛑 Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.
- You have asked for help on our Discord server [LibrePhotos](https://discord.gg/xwRvtSDGWb) if your issue involves general "how to" questions

**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [ x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ x] ❌ I have looked for similar issues (including closed ones)
* [ x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I can't log in to my librephotos instance using the pre-release
If I install a release > login > update >then it works bit with some bugs I will dercribe below
## 🔁 How can we reproduce it:
Uninstall if installed
Install the pre-release
You can't login

## Please provide additional information:
- 💻 Operating system: amdroid 13 but tested on various devices with android 11 and 12 also
- ⚙ Architecture (x86 or ARM): arm
- 🔢 Librephotos version: not sure image is 2 months old
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local file system from am external hatdbdrive
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): 

Eventually if I manage to login local photos are not shown but thats another issue in I manage to login straight from the pre-release

**Comment by ippocratis** [comment]
[logcat_03-12-2023_17-09-21.txt](https://github.com/LibrePhotos/librephotos/files/10951287/logcat_03-12-2023_17-09-21.txt)


Logcat is from a logcat reader with root as the /storage/emulated/0/Android/data/com.librephotosmobile/cache/logs/com.librephotosmobile-latest.log only contains state changes

**Comment by derneuere** [comment]
Uploaded a bug fix :)

**Comment by ippocratis** [comment]
Log in resolved with the fix
Thanks
