### ISSUE TITLE
Settings tab elements not ready yet?

### ISSUE THREAD

**Issue by ippocratis** [LibrePhotos/librephotos#789]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Tapping on "sync all images", "remove backed up images",  "reset local images" does nothing

Tapping on  "server" pops up an "not implemented" message

Tapping on "debug logging" toggle does nothing 

Tapping on "log out" and "dark mode" works fine

## 🔁 How can we reproduce it:
Head to settings tab and try the options there

## Please provide additional information:
- 💻 Operating system: 
Android 13,12,11

**Comment by derneuere** [comment]
"sync all images", "remove backed up images", "reset local images" only work if you can see local images. Changing the baseurl for the server is not yet implemented For debugging logging, see https://github.com/LibrePhotos/librephotos-mobile#enable-file-logging
