### ISSUE TITLE
Bridge Discord to #librephotos on IRC

### ISSUE THREAD

**Issue by strugee** [LibrePhotos/librephotos#79]
Oh, I forgot there was a Discord server... we could do that too although honestly because Discord does not respect my privacy or [freedom](https://www.fsf.org/about/what-is-free-software) it would be great to avoid it. I wonder how difficult it is to bridge Discord and IRC - I'll file a separate GitHub issue for that so we don't clutter this one up.

_Originally posted by @strugee in https://github.com/LibrePhotos/librephotos/issues/57#issuecomment-753384023_

**Comment by derneuere** [comment]
We found two possible tools to do that
https://github.com/reactiflux/discord-irc
https://github.com/qaisjp/go-discord-irc

@DigitalWarrior Could you try these tools and connect the irc with discord?

**Comment by DigitalWarrior** [comment]
@derneuere on it.

**Comment by DigitalWarrior** [comment]
We are now on Freenode. We have 3 channels on Freenode that map back to discord. 

| Discord            | Freenode IRC          |
|--------------------|-----------------------|
| #chit-chat         | #Libre-Photos         |
| #community-support | #Libre-Photos-Support |
| #dev               | #Libre-Photos-dev     |
___________________________________________
Freenode server address is chat.freenode.net
