### ISSUE TITLE
Add JXL file support

### ISSUE THREAD

**Issue by scepterus** [LibrePhotos/librephotos#794]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I’ve setup Librephotos in a docker, and it sees my photos folder. However, .JXL are not being added to the library even after the scan  has finished.

## 🔁 How can we reproduce it:
Add JXL to scan folder

## Please provide additional information:
- 💻 Operating system: Docker
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: Latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: [73ae16b](https://github.com/LibrePhotos/librephotos-docker/commit/73ae16bddbe4a0e6cc2bd207bb097dd386466470)
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Bind
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
This is correct, as libjxl is not available on Ubuntu 22.04. Marked it as an enhancement instead.

**Comment by scepterus** [comment]
Is there a way for me to add that support to the docker? On Manjaro and Windows it was a very simple thing to do, can it be done here as well?

**Comment by derneuere** [comment]
Sure, change this [dockerfile](https://github.com/LibrePhotos/librephotos-docker/blob/main/backend/base/Dockerfile), figure out how to add the dependency libjxl in the Ubuntu 22.04 and open up a pull request :)

**Comment by derneuere** [comment]
We upgraded to lunar lobster and I added the package. This is now available in dev and will be in the next release.
