### ISSUE TITLE
Support for google motion photos

### ISSUE THREAD

**Issue by Rihcus** [LibrePhotos/librephotos#797]
**Describe the enhancement you'd like**

Add google motion photo support in libre photos

**Describe why this will benefit the LibrePhotos**
A clear and concise explanation on why this will make LibrePhotos better.

Its an android equivalent to live photos

**Additional context**
Add any other context or screenshots about the enhancement request here.

Sample motion photo in zip (unzip to view the jpeg)
[motion photo sample.zip](https://github.com/LibrePhotos/librephotos/files/11009629/motion.photo.sample.zip)

Viewable using:
https://dj0001.github.io/Motion-Photo-Viewer/
or photos.google.com/ 

Background context
https://medium.com/android-news/working-with-motion-photos-da0aa49b50c

**Comment by derneuere** [comment]
To identify it, use exiftool. There should be an attribute for it. 

Extracting seems to be possible, but it's not supported by ffmpeg, imagemagick, libvips or exiftool. 
We probably have to write a function for it. Here is some example code: https://github.com/ViRb3/google-camera-motion-photo-splitter/blob/master/splitter.py

The big thumbnail should be an image, which is the image we view in the light box. The two smaller thumbnails should be a video. The photo should be marked as a live photo, and we probably have to add a type for live photos to the serializer.

**Comment by derneuere** [comment]
Similar to #287
