### ISSUE TITLE
tap on any thumbnail crashes the app

### ISSUE THREAD

**Issue by ippocratis** [LibrePhotos/librephotos#798]
#mobile
  I'm on 4be44fd librephotos-mobile version updated over the previus Verizon where tapping on thumbnails returnel a white screen
now the app crashes when I tap on thumbnails
not sure if it is related with the clossed
 https://github.com/LibrePhotos/librephotos/issues/796

Logs from logcat reader

[logcat_03-19-2023_11-54-25.txt](https://github.com/LibrePhotos/librephotos/files/11010643/logcat_03-19-2023_11-54-25.txt)

Logs from /storage/emulated/0/Android/data/com.librephotosmobile/cache/logs/com.librephotosmobile-latest.log

[latest.log](https://github.com/LibrePhotos/librephotos/files/11010647/latest.log)

**Comment by derneuere** [comment]
Should be fixed in https://github.com/LibrePhotos/librephotos-mobile/commit/8311e9b6451bc38e0ebbdc071b1d6adcad1b06bb
