### ISSUE TITLE
Can share picture but not albums

### ISSUE THREAD

**Issue by Chacsam** [LibrePhotos/librephotos#800]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x ] ❌ I have looked for similar issues (including closed ones)
* [x ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

When I try to share an album, I cannot select any user. They are all there, but "anonymous" and greyd out.

![album](https://user-images.githubusercontent.com/28670803/227705167-7108af2d-7427-4364-9450-eda49f28b789.jpg)

On the same setup, the sharing of individual pictures seems to work perfectly: users are displayed, I can activate/deactivate sharing.

## 🔁 How can we reproduce it:

Create an Album, try to share

## Please provide additional information:
- 💻 Operating system: Synology DSM 7.1
- ⚙ Architecture (x86 or ARM): 
- 🔢 Librephotos version: latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:  reallibrephotos/librephotos:latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by ludoctl** [comment]
Hi there,
_First draft:_
Exact same issue here, and I can add that I could actually use the toggle when there was still only 1 other user to share to, but I can't anymore now that I have two other users.
_Then:_
I added an avatar and switched the theme to dark mode in my profile as well as the intended user to share to, and I could toggle! Though I could see the avatar display and the display was still quite buggy.
Cheers

**Comment by Chacsam** [comment]
Hi,
Thanks for the suggestion, but that didn't help. :-(
But I confirm, the display of the Avatar is shaky as well. Just a different kind of icon.
![image](https://user-images.githubusercontent.com/28670803/230145461-b4d5fbc1-9004-410c-9603-c38d0dbdf8b8.png)

**Comment by derneuere** [comment]
Fixed now in dev, will be in next release :)
