### ISSUE TITLE
Latest dev build crashes the backend server

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#808]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

[log.txt](https://github.com/LibrePhotos/librephotos/files/11121479/log.txt) with the attached logs

**Comment by derneuere** [comment]
Thanks for the report! Should be fixed now, as the demo server also works again.

I upgraded to Django 4.2, a new database driver and a new python version. That was probably too much to do all at once 😅
