### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by strugee** [LibrePhotos/librephotos#81]
It would be super useful if there was some sort of CI set up that could run unit tests and a Docker image build smoketest on PRs and commits.

**Comment by derneuere** [comment]
Well we would need some unit tests first 🤔
But I agree that we should do that. I think GitHub Actions should be the way forward.  I opened up a pull request with a basic docker-publish.yml file. Could you look over it and give some feedback?

**Comment by polaroidkidd** [comment]
I've noticed recently that prettier doesn't actually format the files anymore within the lint-staged command for some reason. As a work-around I'm thinking to let prettier simply format everything in a separate pre-commit hook. I haven't tried it out yet.

**Comment by derneuere** [comment]
Yeah, that makes sense too!
