### ISSUE TITLE
Unable to display picture / run video from detail tab (original file) if accentuated : error 404

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#810]
hereafter is a zip file containing a set of files (picture & video) with and without accents to reproduce the issue.
Without accent of course no problem.

I tested with é but it's probably the same with other special characters.
![image](https://user-images.githubusercontent.com/51127123/229817574-cbd4b10f-bd5f-4e1d-9308-3d75a6d2575c.png)

[gteste.zip](https://github.com/LibrePhotos/librephotos/files/11149271/gteste.zip)

**Comment by loulou91** [comment]
Thanks! looks correct for filenames but still not for path containing special characters!

**Comment by loulou91** [comment]
They are even not "seen" in scan dir.

**Comment by sickelap** [comment]
Do you mean photos in the folder name with ligatures are not being scanned? I can look into that this evening.

**Comment by loulou91** [comment]
Well, I'm not so sure... sometimes it works sometimes not, then it may be linked to other issues... as #822 for instance that I encounter always.
For these test I used to change the name of /data subfolder and then to see if it was possible to see it "Set the scan directory" screen... starting from a new base containing 1 picture.
For the time being I've not been able to define a reproducible scenario!

**Comment by derneuere** [comment]
Pushed a fix to always quote the internal path. That should fix it, I think.
