### ISSUE TITLE
Calculate Clip Embeddings stuck (like #758?)

### ISSUE THREAD

**Issue by loulou91** [LibrePhotos/librephotos#822]
Calculate Clip Embeddings stuck with a very simple environment (2023/04/14 dev docker pull).
Brand new base, no photos, start scan and task "Calculate Clip Embeddings" never ends.

![image](https://user-images.githubusercontent.com/51127123/232202910-b4a3adb8-0de2-48cf-b6df-51022dd48253.png)

[rqworker.log](https://github.com/LibrePhotos/librephotos/files/11238922/rqworker.log)
[ownphotos.log](https://github.com/LibrePhotos/librephotos/files/11238924/ownphotos.log)

**Comment by loulou91** [comment]
Now if I add a photo, scan terminates ok (picture looks well scanned) but I got the following error in ownphoto.log.
2023-04-15 09:05:49,947 : batch_jobs.py : batch_calculate_clip_embedding : 81 : ERROR : Error calculating clip embeddings: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /data_models/clip-embeddings/0_CLIPModel.

[ownphotos.log](https://github.com/LibrePhotos/librephotos/files/11238939/ownphotos.log)
[rqworker.log](https://github.com/LibrePhotos/librephotos/files/11238940/rqworker.log)

**Comment by hieronymousch** [comment]
Same here when trying to do a fuzzy search (last week in NY)

**Comment by derneuere** [comment]
I have added the updated clip embeddings, should work now again :)

**Comment by yaroslav-serhiichuk** [comment]
The issue still exists for me.

**Comment by derneuere** [comment]
@yaroslav-serhiichuk When a job gets stuck, that usually means, that it crashed, and we could not catch the error correctly. I fixed an error for loulou, but your issue could be different. Please open up a new issue and file out the template :)
