### ISSUE TITLE
Face dashboard displays a totally empty page on the latest dev

### ISSUE THREAD

**Issue by kuzmos** [LibrePhotos/librephotos#829]
**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [x ] 📁 I've Included a ZIP file containing my librephotos `log` files - inline
* [x ] ❌ I have looked for similar issues (including closed ones)
* [x ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
http://librephotoshost/faces displays an empty white page, after blicking a usual page layout for a second. Also http://librephotoshost/people displays 0 albums. All other pages work, and the Train faces is launched and returns results. It was working before. Logs of backend contain this:

`/usr/local/lib/python3.11/dist-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.person.Person'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/albums/place/list/
Unauthorized: /api/stats/
Unauthorized: /api/stats/
Unauthorized: /api/albums/user/list/
Unauthorized: /api/albums/thing/list/
Unauthorized: /api/persons/
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/albums/place/list/
Unauthorized: /api/albums/thing/list/
Unauthorized: /api/albums/user/list/
Unauthorized: /api/persons/
/usr/local/lib/python3.11/dist-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.person.Person'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
20:48:37 Cleaning registries for queue: default
Unauthorized: /api/persons/
Unauthorized: /api/sitesettings
Unauthorized: /api/persons/
Unauthorized: /api/albums/date/4558/
Unauthorized: /api/albums/user/list/
Unauthorized: /api/albums/place/list/
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/albums/thing/list/
Unauthorized: /api/persons/
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/albums/place/list/
Unauthorized: /api/albums/thing/list/
Unauthorized: /api/persons/
Unauthorized: /api/albums/user/list/
Unauthorized: /api/albums/date/list/
`

## 🔁 How can we reproduce it:

Source of faces page, as opened in Firefox:

`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="stylesheet" href="[https://unpkg.com/leaflet@1.7.1/dist/leaflet.css](view-source:https://unpkg.com/leaflet@1.7.1/dist/leaflet.css)" integrity="xxxxxx" crossorigin=""/><style>.leaflet-container{height:250px;width:100%;z-index:2;position:relative}</style><link rel="manifest" href="[/manifest.json](view-source:http://librephotos/manifest.json)"><link rel="shortcut icon" href="[/favicon.ico](view-source:http://librephotos/favicon.ico)"><title>LibrePhotos</title><script defer="defer" src="[/static/js/main.380c0a64.js](view-source:http://librephotos/static/js/main.380c0a64.js)"></script><link href="[/static/css/main.51e61a9b.css](view-source:http://librephotos/static/css/main.51e61a9b.css)" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>`

Source of people page, as opened in Firefox:

`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="stylesheet" href="[https://unpkg.com/leaflet@1.7.1/dist/leaflet.css](view-source:https://unpkg.com/leaflet@1.7.1/dist/leaflet.css)" integrity="xxx" crossorigin=""/><style>.leaflet-container{height:250px;width:100%;z-index:2;position:relative}</style><link rel="manifest" href="[/manifest.json](view-source:http://librephotos/manifest.json)"><link rel="shortcut icon" href="[/favicon.ico](view-source:http://librephotos/favicon.ico)"><title>LibrePhotos</title><script defer="defer" src="[/static/js/main.380c0a64.js](view-source:http://librephotos/static/js/main.380c0a64.js)"></script><link href="[/static/css/main.51e61a9b.css](view-source:http://librephotos/static/css/main.51e61a9b.css)" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>`

**Comment by derneuere** [comment]
Would be great if you could post the logs from the console of the browser too :)

**Comment by kuzmos** [comment]
`Some cookies are misusing the recommended “SameSite“ attribute 20`

`TypeError: r.image is undefined`
`    are FaceComponent.tsx:32`
`    React 7`
`    x scheduler.production.min.js:13`
`    T scheduler.production.min.js:14`
`react-dom.production.min.js:189:29`

`Uncaught TypeError: r.image is undefined`
`    are FaceComponent.tsx:32`
`    React 7`
`    x scheduler.production.min.js:13`
`    T scheduler.production.min.js:14`

`FaceComponent.tsx:32:55`
`    are FaceComponent.tsx:32`
`    React 7`
`    ou self-hosted:1409`
`    x scheduler.production.min.js:13`
`    T scheduler.production.min.js:14`

`TypeError: e.response is undefined`
`    <anonymous> apiClient.js:30`
`peopleActions.js:26:14`

**Comment by derneuere** [comment]
The query was slow, which lead to a timeout. Should be fixed now in dev and in the next release :)
