### ISSUE TITLE
Problem with Nextcloud import

### ISSUE THREAD

**Issue by rn232** [LibrePhotos/librephotos#834]
Hello,

I have a problem when I try to import my files from Nextcloud.
In the progress bar, it says 0/0 photos imported, even after several hours. Moreover, the task never stops running, even if all the photos are imported. I have to go to the Librephotos directory to check if my photos are there, I have no other way to check. 
And finally I have to cancel this task manually, then import my photos so that they appear. Is this a known bug? Is it a bad use on my part?

I also had a question about how it works. Are the photos imported or synchronized to Nextcloud? In case of date change for example, will the pictures be updated to Nextcloud ?

My NC instance is self-hosted. The picture directory is mounted using CIFS on a remote NAS, owned by me too.

Librephotos is installed via Portainer. I've already my HA postgresql database, so i removed the db container. I connected my Nextcloud by creating one application password. I can browse my NC folders.

My docker run in a qemu virtual machine on Proxmox.

I thank you in advance for your help.

![image](https://user-images.githubusercontent.com/26837968/233847219-6f850cc7-3006-435e-912c-9c4579af719d.png)
![image](https://user-images.githubusercontent.com/26837968/233847240-78fa0122-4394-4309-8b4a-b966da6f6279.png)

**Comment by marcus-k** [comment]
I have the same problem. I just tested with the normal docker installation following the docker-compose instructions and I could not import any photos from Nextcloud. The issues I have are exactly the screenshots OP posted.

**Comment by sickelap** [comment]
I did a test on my Nextcloud instance, and it seems that it is working just fine. It stuck at the very beginning, though. Same way as it was shown in screenshots. This is because backend downloads all the images from the specified folder.
Although we have log statements to indicate the progress in the console, for whatever reason they are not being printed. Could be something to do long-running jobs are implemented with RQ.

For the time being, try selecting a Nextcloud folder with a few photos in it and see how it goes.

**Comment by rn232** [comment]
I have configured my instance with a WebDAV mount for now so I think if I make a date change for example it will sync with my Nextcloud.
I'll set up a test environment to try what you told me and I'll keep you posted.

**Comment by sickelap** [comment]
No, it's not syncing back anything to Nextcloud. Would be nice feature though.

**Comment by derneuere** [comment]
We switch to django q2. Should start now all the jobs in the correct way.
