### ISSUE TITLE
Ditch the predatory Mapbox for something that actually has a free tier

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [LibrePhotos/librephotos#837]
**Describe the enhancement you'd like**
I want a reverse geocoding solution where I have the option to lock my account to free-tier only. Currently mapbox only allows you to register using a credit card and you can not setup a usage limit in your account. Meaning, I am subject to surprise charges by them, any time they want and I can't really do anything about it. 

According to their support: 

"There is no easy way to cap your monthly billing at this time. For now, the best way to create predictable monthly API usage is by monitoring your [account statistics](https://account.mapbox.com/statistics/) and your [invoices](https://account.mapbox.com/invoices/)." Funny, I really wonder how is there no easy way. 

After sending them a message: 

"We are experiencing a high volume of tickets coming in. If you haven't purchased one of our [support plans](https://www.mapbox.com/support#support-plans), we may not be able to respond to your question."

**Describe why this will benefit the LibrePhotos**
More people would use the reverse geocoding feature, I'd sleep better. :) 

**Additional context**
There could be a hard-limit built in librephotos that'd protect you from going above the mapbox free tier.

**Comment by ThatCoffeeGuy** [comment]
https://github.com/LibrePhotos/librephotos/issues/150

**Comment by sickelap** [comment]
I will take a look at more generic reverse geocoding.

**Comment by derneuere** [comment]
This is now implemented, thanks to @sickelap :)
