### ISSUE TITLE
Crash on Create Embed Clip

### ISSUE THREAD

**Issue by scepterus** [LibrePhotos/librephotos#845]
# 🐛 Bug Report

* [X] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
As discussed on the discord support channel, when I run rescan for faces it fails, I was told to run a rescan for the entire library, and it hangs then crashes with the errors in the log file attached.
This could be related to another issue where faces that were found in videos don't show a preview.

Also, would like to point out, we talked about try catching known failures and giving users useful feedback from crashes with actionable items, either only in the logs, or if possible in the web interface as well.

## 🔁 How can we reproduce it:
I don't know what is special about my case, could be the language of the folders for some of them, could be the format.
Sorry.

## Please provide additional information:
- 💻 Operating system:  TrueNAS Scale (Debian)
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: Latest stable as of this ticket
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: Latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): mounted directly to the docker
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): 
[ownphotos.log](https://github.com/LibrePhotos/librephotos/files/11415325/ownphotos.log)

**Comment by derneuere** [comment]
For some reason, your jxl files do not have a height value in the EXIF data. I pushed a fix in dev tag, which should fix your issue. It would be great if you could provide a jxl file without height info, so that we can test it through the whole chain.

**Comment by scepterus** [comment]
How would I know which file it failed on? Does it print the file it crashed on? I didn't see it in the logs.

**Comment by derneuere** [comment]
It prints out the path it errors on. You can see it pretty easily in the log file :)

**Comment by scepterus** [comment]
![image](https://github.com/LibrePhotos/librephotos/assets/56637330/496c349f-3ece-4a24-985e-f5b989165911)
This clearly has height in the picture, anyway I can extract the metadata or something to share with you?

**Comment by scepterus** [comment]
@derneuere  Should I open a different issue for the known issues try catch thing?

**Comment by derneuere** [comment]
@scepterus Yes that would be ideal, so that I can track that individually. At the end of the month, I look at all the closed issues to create the changelogs and without the issue I could forget, that I implemented that.

**Comment by scepterus** [comment]
You got it, opening now.
