### ISSUE TITLE
Open original photo from faces tab

### ISSUE THREAD

**Issue by scepterus** [LibrePhotos/librephotos#846]
**Describe the enhancement you'd like**
We would benefit from the ability to go to the photo a face was taken from because sometimes the face is unclear or is very small.

**Describe why this will benefit the LibrePhotos**
being able to open the photo (or video), and see which album it is, and zoom in on the face in question would help a lot in categorizing faces better.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by scepterus** [comment]
Just noticed this is a duplicate of:
https://github.com/LibrePhotos/librephotos/issues/611
I did not find it before.

**Comment by derneuere** [comment]
We now use the LightBox instead, which should give you all the information you need.

**Comment by scepterus** [comment]
Cool is it in the demo?

**Comment by derneuere** [comment]
Yes!
