### ISSUE TITLE
Scan will not add jpg photos when set to readonly

### ISSUE THREAD

**Issue by TechieDylan** [LibrePhotos/librephotos#849]
# 🐛 Bug Report

* [X] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I just set up a docker container for librephotos, upon first scan I found .jpg were not being added it appears its because I have the volumes set to be readonly but videos are being added without issues. Out of 4000 photos none were added but all 100 videos were, tested with another folder that had .tif photos and they work so seems isolated to .jpg

## 🔁 How can we reproduce it:
set a volume readonly and do a scan on the most recent docker release

## Please provide additional information:
- 💻 Operating system: Ubuntu 22.04 
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: latest tag docker release ([2023w18])
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): SMB to Ubuntu and then volume in docker that is readonly
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): N/A

[backend-2023-05-08T17-04-16.log.gz](https://github.com/LibrePhotos/librephotos/files/11423548/backend-2023-05-08T17-04-16.log.gz)

**Comment by Amzamiviram** [comment]
I'm having the same/similar issue.  I've done a local install on Ubuntu 22.04 instead of Docker.  Librephoto has full access to my photo directory which is mounted from a cifs share.  No jpg files get imported into my library after a scan but I do get .png and videos.  The rqworker.log has these errors for all of the jpg photos scanned.
```During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/librephotos/backend/api/directory_watcher.py", line 215, in rescan_image
    photo._generate_thumbnail(True)
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 311, in _generate_thumbnail
    "could not generate thumbnail for image %s" % self.main_file.path
AttributeError: 'NoneType' object has no attribute 'path'
    ERROR:ownphotos:job f9f86a35-d85f-441a-bace-d1424ff86549: could not load image /var/lib/librephotos/photos/parents-photos/2011-08-23 Pinecrest/Pinecrest 003.JPG. reason: 'NoneType' object has no attribute 'path'
Traceback (most recent call last):
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 240, in _generate_thumbnail
    inputPath=self.main_file.path,
AttributeError: 'NoneType' object has no attribute 'path'```


    💻 Operating system: Ubuntu 22.04
    ⚙ Architecture (x86 or ARM): x86
    🔢 Librephotos version: latest release ([2023w18])
    📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Local Debian Install
        🐋 If Docker or Kubernets, provide docker-compose image tag: latest
    📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): CIFS Mount to windows file share, full permissions.
    ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): Proxmox

**Comment by TechieDylan** [comment]
I believe I found the issue related to my errors. this line has `open(path, "rb+")` and should be `open(path, "rb")` as the + signifies update causing my error of the file system being read only. 

https://github.com/LibrePhotos/librephotos/blob/dc6e4e89188f4a8acd15b900d06cc7da89f9f804/api/models/file.py#L185

Not sure if its rb+ for a reason but when I change it to rb everything works as expected for me now.

**Comment by derneuere** [comment]
@sickelap Is that a change that would make sense and doesn't break embedded media?

**Comment by sickelap** [comment]
Yes, that will be fine. Here we open the file for reading only, no need to have `+`. I'll update it.

**Comment by derneuere** [comment]
Should be fixed now.
