### ISSUE TITLE
The automatically created photo albums do not open

### ISSUE THREAD

**Issue by aadegtyarev** [LibrePhotos/librephotos#852]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files: [LibrePhoto-logs.zip](https://github.com/LibrePhotos/librephotos/files/11471340/LibrePhoto-logs.zip), [Log: Error-Automatic-Albums.txt](https://github.com/LibrePhotos/librephotos/files/11471312/Error-Automatic-Albums.txt)
* [x] ❌ I have looked for similar issues (including closed ones)
* [] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

I have generated automatic albums and they are displayed when I go to their section. But when I want to view them, the page "Images not found" opens

## 🔁 How can we reproduce it:

1. Put some photos in the photo folder and scan them for adding to the library.
2. Tag people in some of them.
3. Generate automatic albums.
4. Try to view them.

## Please provide additional information:
- 💻 Operating system: Ubuntu Linux 22.04
- ⚙ Architecture (x86 or ARM): x86_64
- 🔢 Librephotos version: I couldn't find where to check the version. I installed it on May 13th from the latest trusted image.
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest

- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): The folder with photos is mounted via binding.
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): NO

![ksnip_20230514-104253](https://github.com/LibrePhotos/librephotos/assets/77433258/356d75a7-b828-45a2-bced-1ab2ed7a4497)

**Comment by loulou91** [comment]
Is it the case for all albums whatever are their size ?
In my case limit is about 6k photos. Above it's timeout...

**Comment by aadegtyarev** [comment]
> Is it the case for all albums whatever are their size ?

This is my test server, so there are only 1k photos on it. The problem occurs in albums with any number of photos, whether it's 40 or 488.

**Comment by Nerodacles** [comment]
Same in my TestLB (only with 300 photos + vids) and the prod one! (40k+)

**Comment by loulou91** [comment]
Indeed it's a bit weird... for me, with my prod LP and last dev pull, it works with some albums only and number of included photos is not a criteria. I tried to remove and to recreate auto-albums but it's the same.

**Comment by loulou91** [comment]
After more investigation, albums which can be open have no persons referred in.

**Comment by loulou91** [comment]
Error in gunicorn_django.log:
> /usr/local/lib/python3.11/dist-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.person.Person'> QuerySet.
>   paginator = self.django_paginator_class(queryset, page_size)
> Internal Server Error: /api/albums/auto/4122/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
>     return view_func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/viewsets.py", line 125, in view
>     return self.dispatch(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/code/api/views/album_auto.py", line 46, in retrieve
>     return super(AlbumAutoViewSet, self).retrieve(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/mixins.py", line 56, in retrieve
>     return Response(serializer.data)
>                     ^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 555, in data
>     ret = super().data
>           ^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 253, in data
>     self._data = self.to_representation(self.instance)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 522, in to_representation
>     ret[field.field_name] = field.to_representation(attribute)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/fields.py", line 1838, in to_representation
>     return method(value)
>            ^^^^^^^^^^^^^
>   File "/code/api/serializers/album_auto.py", line 32, in get_people
>     serialized_person = PersonSerializer(face.person).data
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 555, in data
>     ret = super().data
>           ^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 253, in data
>     self._data = self.to_representation(self.instance)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 522, in to_representation
>     ret[field.field_name] = field.to_representation(attribute)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/rest_framework/fields.py", line 1838, in to_representation
>     return method(value)
>            ^^^^^^^^^^^^^
>   File "/code/api/serializers/person.py", line 61, in get_face_url
>     return "/media/" + obj.face_url
>                        ^^^^^^^^^^^^
> AttributeError: 'Person' object has no attribute 'face_url'

**Comment by derneuere** [comment]
Fixed the bug by adding the new subquerys to the view :)
