### ISSUE TITLE
Photos are not uploading through the web interface

### ISSUE THREAD

**Issue by aadegtyarev** [LibrePhotos/librephotos#853]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files: [LibrePhoto-logs.zip](https://github.com/LibrePhotos/librephotos/files/11471353/LibrePhoto-logs.zip), [Error-Upload-Photo.txt](https://github.com/LibrePhotos/librephotos/files/11471354/Error-Upload-Photo.txt)
* [x] ❌ I have looked for similar issues (including closed ones)

## 📝 Description of issue:
I can't upload photos using the upload function in the web interface.

## 🔁 How can we reproduce it:
1. Enable photo uploading in the settings.
2. Click on the upload button and select a single photo.
3. Errors will appear in the logs and the photo itself will not be uploaded.

## Please provide additional information:
- 💻 Operating system: Ubuntu Linux 22.04
- ⚙ Architecture (x86 or ARM): x86_64
- 🔢 Librephotos version: I couldn't find where to check the version. I installed it on May 13th from the latest trusted image.
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): The folder with photos is mounted via binding.
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): NO

**Comment by derneuere** [comment]
Removed the need to set up CSRF_TRUSTED_ORIGINS for uploading images as users found it confusing
