### ISSUE TITLE
Failure reading exif tags: Multiple tag issues returned, invalid use case

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#855]
# 🛑 Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.
- You have asked for help on our Discord server [LibrePhotos](https://discord.gg/xwRvtSDGWb) if your issue involves general "how to" questions

**When Submitting please remove every thing above this line**

# 🐛 Bug Report
2023-05-15 09:15:38,944 : directory_watcher.py : rescan_image : 259 : ERROR : job 00d29b43-5e22-48c0-bd9a-49305358e798: could not load image /data/2015/09/06/IMG_20150906_123904.jpg. reason: multiple tag values returned, invalid use case
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 248, in rescan_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 362, in _calculate_aspect_ratio
    raise e
  File "/code/api/models/photo.py", line 348, in _calculate_aspect_ratio
    height, width = get_metadata(
                    ^^^^^^^^^^^^^
  File "/code/api/util.py", line 126, in get_metadata
    retrieved_value = et.get_tag(file, tag)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/exiftool/experimental.py", line 243, in get_tag
    raise RuntimeError("multiple tag values returned, invalid use case")
RuntimeError: multiple tag values returned, invalid use case

## 📝 Description of issue:
on a rescan on the latest dev release I am getting the below error in  ownphotos.log 

## 🔁 How can we reproduce it:
not sure as this is not happening for all files
the exiftool dump (redacted) is below:

`ExifTool Version Number         : 12.56
File Name                       : IMG_20150906_123904.jpg
Directory                       : /data/2015/09/06
File Size                       : 1731 kB
File Modification Date/Time     : 2015:09:06 10:39:05+00:00
File Access Date/Time           : 2023:05:15 09:15:38+00:00
File Inode Change Date/Time     : 2021:07:09 08:02:58+00:00
File Permissions                : -rwxrwxr-x
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Modify Date                     : 2015:09:06 12:39:05
GPS Latitude Ref                : North
GPS Date Stamp                  : 2015:09:06
GPS Time Stamp                  : 10:38:57
GPS Longitude Ref               : East
Camera Model Name               : <<redacted>>
Y Cb Cr Positioning             : Centered
Resolution Unit                 : inches
Y Resolution                    : 72
Orientation                     : Horizontal (normal)
Color Space                     : sRGB
Create Date                     : 2015:09:06 12:39:05
F Number                        : 2.4
Focal Length                    : 4.0 mm
Aperture Value                  : 2.4
White Balance                   : Auto
Exif Image Width                : 3264
Sub Sec Time                    : 209
Shutter Speed Value             : 1/121
Date/Time Original              : 2015:09:06 12:39:05
Sub Sec Time Digitized          : 209
Components Configuration        : Y, Cb, Cr, -
Exif Image Height               : 2448
Flash                           : No Flash
Exif Version                    : 0220
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
ISO                             : 167
Flashpix Version                : 0100
Sub Sec Time Original           : 209
Exposure Time                   : 1/121
X Resolution                    : 72
Make                            : LGE
Image Width                     : 3264
Image Height                    : 2448
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.4
Image Size                      : 3264x2448
Megapixels                      : 8.0
Shutter Speed                   : 1/121
Create Date                     : 2015:09:06 12:39:05.209
Date/Time Original              : 2015:09:06 12:39:05.209
Modify Date                     : 2015:09:06 12:39:05.209
GPS Date/Time                   : 2015:09:06 10:38:57Z
GPS Latitude                    : <<redacted>>
GPS Longitude                   :<<redacted>>
Focal Length                    : 4.0 mm
GPS Position                    : <<redacted>>
Light Value                     : 8.7
`

**Comment by derneuere** [comment]
Reverted the bump of PyExifTool. Should works as exspected now.
