### ISSUE TITLE
Calculating clip embeddings stuck without start. No thumbnail.

### ISSUE THREAD

**Issue by wji9na** [LibrePhotos/librephotos#857]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
![screen](https://github.com/LibrePhotos/librephotos/assets/5336656/2045f3c2-5170-4521-a18c-0843097f0f72)

Calculating clip embeddings just stuck every time without actually starting process. I've been waiting for a few days with this state of this task, but nothing happens. Few minutes state is just for screenshot.

[ownphotos.log](https://github.com/LibrePhotos/librephotos/files/11496502/ownphotos.log)
[rqworker.log](https://github.com/LibrePhotos/librephotos/files/11496503/rqworker.log)

## Please provide additional information:
- 💻 Operating system: Debian 11
- ⚙ Architecture (x86 or ARM): 64
- 🔢 Librephotos version: 
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: ca2a37dabe35
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): CIFS
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): proxmox

**Comment by derneuere** [comment]
Switched to a new queuing solution. Should not happen anymore now.

**Comment by wji9na** [comment]
Have I wait for a new latest release to get a new queuing solution or can I safely pull dev build?

**Comment by derneuere** [comment]
Wait for the next release, should be available next week :)

**Comment by wji9na** [comment]
Alright! Thank you for you job!
