### ISSUE TITLE
Startup warnings

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#858]
LibrePhotos is installed in a docker (Tsshtvshtsy) environment. When running docker-compos, warnings appear in the log -
backend   | WARNINGS:
backend   | api.AlbumAuto: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.AlbumDate: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.AlbumPlace: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.AlbumThing: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.AlbumUser: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.Cluster: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.Face: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.LongRunningJob: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.Person: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | api.User: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | chunked_upload.ChunkedUpload: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
backend   | django_rq.Queue: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
backend   |  HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

Can it be fixed, or are these non-critical warnings?

**Comment by luzfcb** [comment]
This is a non-critical issue. Django changed the default type of the `id` field of the models to use big integers. It means that the old behavior is perfectly safe until you have 2,147,483,647 rows in the same table in the database.

**Comment by mxm199** [comment]
Thank you, I understand)
