### ISSUE TITLE
Difference in total number of photos/videos

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#859]
Good day everyone

Tell me how to find the difference in imported photos? Let me explain, 
In total in the attached folder with jpg/mp4 - 7682
In the user settings shows the number - 7674
In the main window "Photo" shows - 7671

How to find photos/videos that are not included in the processed list?

**Comment by derneuere** [comment]
Usually any file that could not get scanned will be logged in ownphotos.log

I also made the number more similar between both view :)
