### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by earthly-alien** [LibrePhotos/librephotos#868]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

I've recently done a clean install of reallibrephotos/singletonon docker image on unRAID. I don't know if this issue was present before, as I didn't test it, but right now on the latest image (2023w20) I cannot access the original files through the Web interface as I get Server Error (500) . I cannot reproduce the issue on the demo website, so I'm inclined to think it's something on my side, just don't know what exactly. The only errors relating to this issue I found in gunicorn_django.log, which I attached here.

[gunicorn_django.log](https://github.com/LibrePhotos/librephotos/files/11532397/gunicorn_django.log)

## 🔁 How can we reproduce it:

1. Open any image or video in the WebUI.
2. Click on Details.
3. Click on the filename.
4. Get Server Error (500).

## Please provide additional information:
- 💻 Operating system: Linux (unRAID v6.11.5) 
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: 2023w20
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker (unRAID community app)
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: reallibrephotos/singleton:2023w20
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local xfs
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): /

**Comment by derneuere** [comment]
Pushed a fix for unraid, when viewing the original file. Should be in the next release :)
