### ISSUE TITLE
Adding a new user

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#869]
Tell me how to add a second user, but so that he does not need to re-index the image library.
For example, there is an admin user who has a library added and indexed. If I add a new user and point him to the same image folder as the admin user, then I need to re-index the folder. Is it possible to avoid this so that the new user immediately displays the indexed images of the admin user? (I know about the share function, but this is not the same, since these images go to another menu, and not to the Photo section)

**Comment by derneuere** [comment]
Right now, you should only use the sharing feature. The system expects that one folder is only owned by one person.

This seems similar to #395
