### ISSUE TITLE
Logo linking to home

### ISSUE THREAD

**Issue by spcx86** [LibrePhotos/librephotos#877]
**Describe the enhancement you'd like**
Clicking on the logo currently does nothing, while it is widely a "convention" at this point that clicking the logo should redirect to the home page. 

**Describe why this will benefit the LibrePhotos**
Give a better user experience consistent with current UX practices.

**Comment by spcx86** [comment]
I want to pick this up if this is picked up.

**Comment by derneuere** [comment]
Sounds like a good idea! You can pick it up :)

**Comment by spcx86** [comment]
have created [PR](https://github.com/LibrePhotos/librephotos-frontend/pull/198)
