### ISSUE TITLE
Faces are identified, but "people" objects come out empty. 

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#882]
# 🐛 Bug Report
I have 300+ people identified in a collection of 100k+ photos.
I had a reboot where the pictures folder was not mounted and re-ran the photos scan.

Something broke, and now "People Albums" is empty and when I am tagging a new face, the name list comes up empty.

I've re-run the face tagging and library scans but the problem persists.

There seems to be no errors in the logs triggered by going to the people or face tagging views.

Running in docker
on x86
files are local

**Comment by ChrisFab16** [comment]
I managed to capture an error in the javascript console.
Steps to reproduce:

1. Click a face tile
2. Click "+"
3. Error appears in console

log below:

--
TypeError: e.response is undefined
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2
    promise callback*81985/d.prototype.request https://my.hostname/static/js/main.3f5354b3.js:2
    exports https://my.hostname/static/js/main.3f5354b3.js:2
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2
    promise callback* https://my.hostname/static/js/main.3f5354b3.js:2
    promise callback*81985/d.prototype.request https://my.hostname/static/js/main.3f5354b3.js:2
    e https://my.hostname/static/js/main.3f5354b3.js:2
    exports https://my.hostname/static/js/main.3f5354b3.js:2
    WH https://my.hostname/static/js/main.3f5354b3.js:2
    M0 https://my.hostname/static/js/main.3f5354b3.js:2
    rl https://my.hostname/static/js/main.3f5354b3.js:2
    xu https://my.hostname/static/js/main.3f5354b3.js:2
    wu https://my.hostname/static/js/main.3f5354b3.js:2
    wu https://my.hostname/static/js/main.3f5354b3.js:2
    lu https://my.hostname/static/js/main.3f5354b3.js:2
    Ho https://my.hostname/static/js/main.3f5354b3.js:2
    ru https://my.hostname/static/js/main.3f5354b3.js:2
    ru https://my.hostname/static/js/main.3f5354b3.js:2
    nu https://my.hostname/static/js/main.3f5354b3.js:2
    ns https://my.hostname/static/js/main.3f5354b3.js:2
    addFaces https://my.hostname/static/js/main.3f5354b3.js:2
    Vu/</</e[n]/< https://my.hostname/static/js/main.3f5354b3.js:2
    n https://my.hostname/static/js/main.3f5354b3.js:2
    Le https://my.hostname/static/js/main.3f5354b3.js:2
    Be https://my.hostname/static/js/main.3f5354b3.js:2
    Nr https://my.hostname/static/js/main.3f5354b3.js:2
    Nr https://my.hostname/static/js/main.3f5354b3.js:2
    Rr https://my.hostname/static/js/main.3f5354b3.js:2
    Wr https://my.hostname/static/js/main.3f5354b3.js:2
    uu https://my.hostname/static/js/main.3f5354b3.js:2
    ze https://my.hostname/static/js/main.3f5354b3.js:2
    Wr https://my.hostname/static/js/main.3f5354b3.js:2
    qt https://my.hostname/static/js/main.3f5354b3.js:2
    Vt https://my.hostname/static/js/main.3f5354b3.js:2
    Hr https://my.hostname/static/js/main.3f5354b3.js:2
    Fr https://my.hostname/static/js/main.3f5354b3.js:2
    Ur https://my.hostname/static/js/main.3f5354b3.js:2
    Ur https://my.hostname/static/js/main.3f5354b3.js:2
    createRoot https://my.hostname/static/js/main.3f5354b3.js:2
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2
main.3f5354b3.js:2:2767379
    WH https://my.hostname/static/js/main.3f5354b3.js:2
    (Async: promise callback)
    WH https://my.hostname/static/js/main.3f5354b3.js:2
    M0 https://my.hostname/static/js/main.3f5354b3.js:2
    rl https://my.hostname/static/js/main.3f5354b3.js:2
    xu https://my.hostname/static/js/main.3f5354b3.js:2
    wu https://my.hostname/static/js/main.3f5354b3.js:2
    wu https://my.hostname/static/js/main.3f5354b3.js:2
    lu https://my.hostname/static/js/main.3f5354b3.js:2
    Ho https://my.hostname/static/js/main.3f5354b3.js:2
    ru https://my.hostname/static/js/main.3f5354b3.js:2
    (Async: VoidFunction)
    ru https://my.hostname/static/js/main.3f5354b3.js:2
    nu https://my.hostname/static/js/main.3f5354b3.js:2
    ns https://my.hostname/static/js/main.3f5354b3.js:2
    addFaces https://my.hostname/static/js/main.3f5354b3.js:2
    Vu/</</e[n]/< https://my.hostname/static/js/main.3f5354b3.js:2
    n https://my.hostname/static/js/main.3f5354b3.js:2
    Le https://my.hostname/static/js/main.3f5354b3.js:2
    Be https://my.hostname/static/js/main.3f5354b3.js:2
    Nr https://my.hostname/static/js/main.3f5354b3.js:2
    Nr https://my.hostname/static/js/main.3f5354b3.js:2
    Rr https://my.hostname/static/js/main.3f5354b3.js:2
    Wr https://my.hostname/static/js/main.3f5354b3.js:2
    uu https://my.hostname/static/js/main.3f5354b3.js:2
    ze https://my.hostname/static/js/main.3f5354b3.js:2
    Wr https://my.hostname/static/js/main.3f5354b3.js:2
    qt https://my.hostname/static/js/main.3f5354b3.js:2
    Vt https://my.hostname/static/js/main.3f5354b3.js:2
    (Async: EventListener.handleEvent)
    Hr https://my.hostname/static/js/main.3f5354b3.js:2
    Fr https://my.hostname/static/js/main.3f5354b3.js:2
    Ur https://my.hostname/static/js/main.3f5354b3.js:2
    Ur https://my.hostname/static/js/main.3f5354b3.js:2
    createRoot https://my.hostname/static/js/main.3f5354b3.js:2
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2
    <anonymous> https://my.hostname/static/js/main.3f5354b3.js:2

**Comment by derneuere** [comment]
The query was slow, which lead to a timeout. Should be fixed now in dev and in the next release :)
