### ISSUE TITLE
Unable to browse and scan Nextcloud Directories

### ISSUE THREAD

**Issue by JulianOestreich90** [LibrePhotos/librephotos#888]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

The Login to Nextcloud under `/library` works and i get a 200 Response with a json of the nextcloud directories also. The `Scan` and `Browse` Button are staying grey though and therefore i can't scan folders in my nextcloud. I tried different Browsers (Chromium and Firefox) and different Nextcloud Users. 

![image](https://github.com/LibrePhotos/librephotos/assets/19915127/30a49ef6-be5d-4670-be36-5a27ace095b3)
![image](https://github.com/LibrePhotos/librephotos/assets/19915127/a78891f1-6564-46dd-b2e1-db3e37decb6a)

I also read Issue #522 but this is not my problem. The internal scan directory was set and i was already able to scan internally stored pictures.

## Please provide additional information:
- 💻 Operating system:  Linux
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: I used the Main Branch of librephotos-docker
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.):  docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
Fixed in the next release.
