### ISSUE TITLE
Videos don't show the player and left/right arrows are missing

### ISSUE THREAD

**Issue by RandomHacks-Git** [LibrePhotos/librephotos#891]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Videos no longer show the player controls as well as the left/right arrows to navigate to the previous or next picture/video.

![imagem](https://github.com/LibrePhotos/librephotos/assets/22402348/7295c1d0-4a74-4654-b35c-b5c852eb5614)

## 🔁 How can we reproduce it:
Click on a video from your library.

## Please provide additional information:
- 💻 Operating system: synology
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: last dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker

**Comment by derneuere** [comment]
Fixed :)
