### ISSUE TITLE
Docs on memory requirements

### ISSUE THREAD

**Issue by madimadi** [LibrePhotos/librephotos#892]
**Describe the enhancement you'd like**
Some hints on physical memory requirements in documentation would be really nice to have. Also minimal swap settings and rough expectation on performance.
Ex: 2GB RAM + 4GB swap is absolute minimum for installation.

**Comment by derneuere** [comment]
You can find that here. Anything else you would want from the docs? https://docs.librephotos.com/docs/installation/standard-install/#compatibility
