### ISSUE TITLE
Add "move face to unknown - other" and "delete face" options to image browser

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#896]
When I browse a person album I sometimes discover a mis-tagged face in the album.
In addition to the current options, I would like to be able to simply remove a face tag for a pictire with a mislabeled face

I suggest re-using the same icons used in the "faces" view

Sometimes, a face will be labeled wrongly, and the current workflow only allows to tag as someone else. 

Adding this feature will improve usability.

**Comment by derneuere** [comment]
This is now implemented :)
