### ISSUE TITLE
Managed to break faces section

### ISSUE THREAD

**Issue by mramirkhan** [LibrePhotos/librephotos#901]
I've managed to create a "face" with no name (null?) and i think that's breaking the faces feature. Not sure how i did this and clearly it's a bug.  When broken clicking on faces teachers a white page as it errors.

![image](https://github.com/LibrePhotos/librephotos/assets/19846862/e51127ed-fa57-465f-8344-2cbb4056e23a)

I fixed it by changing blank/empty title to a string of my choosing e.g

"update api_person set name='BUSTED' where id = 5870;"

This is how faces looked, notice the top one had no label. I had the blur somethings for privacy reasons. 

![image](https://github.com/LibrePhotos/librephotos/assets/19846862/bce90537-c375-4b90-8451-9335e8eaae60)

Now I can enter the faces page

If table schema didn't allow non null values then it could have saved me.

# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## Please provide additional information:
- 💻 Operating system: 
- ⚙ Architecture (x86 or ARM): 
- 🔢 Librephotos version: 
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by mramirkhan** [comment]
One simple quick fix is change the table schema  so that that field is "NOT NULL".

This will ensure table will never be in a state that breaks the front end. I had to get into the DB to fix but not everyone will feel comfortable doing this.

**Comment by derneuere** [comment]
Done :)
