### ISSUE TITLE
Opening shared album results in a blank page

### ISSUE THREAD

**Issue by RandomHacks-Git** [LibrePhotos/librephotos#902]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

When a user tries to open an album I shared, the page turns blank with a 404 error in the browser network tab and unauthorized entries on the backend log

![imagem](https://github.com/LibrePhotos/librephotos/assets/22402348/ec0deb4b-5ecb-4d7d-9054-ac3f80c6dde2)

## 🔁 How can we reproduce it:
I tried this on the demo server:
Create user, share album with said user, logout and login with the newly created user, navigate to the shared albums and try to open the shared album

To test directly I guess you can login to the demo server with test/thisisatest and navigate to https://demo2.librephotos.com/useralbum/1/

**Comment by RandomHacks-Git** [comment]
I just noticed I reported a similar bug before, same symptoms but it was for the "My albums" page: https://github.com/LibrePhotos/librephotos/issues/564

**Comment by derneuere** [comment]
Should be fixed now on dev :)

**Comment by RandomHacks-Git** [comment]
> Should be fixed now on dev :)

Hi, it seems somewhat fixed but if I navigate to "Sharing" -> "Shared with you" -> "Albums" (album covers don't load here) and click an album, while I can see all the thumbnails, if I click a video it does not play but if I log out and log back in or access the album link directly things work as expected, the same thing happens if I'm the owner of the album and navigate to "You shared". I tested this on the demo server with the same results.

A bit unrelated to this, when I use the search bar I also only get a blank page, I can't replicate this issue on the demo server so maybe it only happens on big libraries.

Keep up the good work 👍
