### ISSUE TITLE
Album characters always display '0 people'

### ISSUE THREAD

**Issue by husthyx** [LibrePhotos/librephotos#903]
# 🐛 Bug Report

* [* ] 📁 I've Included a ZIP file containing my librephotos `log` files: [ownphotos.log](https://github.com/LibrePhotos/librephotos/files/11918123/ownphotos.log)

## 📝 Description of issue:
I have confirmed over 100 people through facial recognition, and over 100 people in the photo album can be correctly classified. Recently, I have added more photos and rescanned them. However, the characters in the photo album cannot be correctly classified and are displayed as "0 people". I will continue to train facial recognition and still display as "0 people". What should I do?

 

## Please provide additional information:
- 💻 Operating system: unraid 6.11.5
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: [2023w20]
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: [2023w20]
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local file system
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
Just released a new version, where this bug should be fixed :)
