### ISSUE TITLE
Increase max number of heavyweight workers

### ISSUE THREAD

**Issue by RandomHacks-Git** [LibrePhotos/librephotos#904]
**Describe the enhancement you'd like**
Right now the number of heavyweight workers can only be set to a maximum of 3 through the frontend and setting it on the .env file seems to have no effect, it would be nice if this number could be increased beyond 3.

**Describe why this will benefit the LibrePhotos**
Increase scan speed.

**Comment by hardwareadictos** [comment]
Same behaviour here

**Comment by Atinoda** [comment]
I ran into this issue, but if you check the source code it seems that the environment variable is honoured.
![image](https://github.com/LibrePhotos/librephotos/assets/61033436/f5ecb946-48f7-4a71-837f-e9d99fcc323a)


I'm running using the docker image, set `HEAVYWEIGHT_PROCESS=15` in the backend environment variables, and inspected the container. The increased number is not shown in the GUI, but the specified number of workers are being spawned during the execution - and my initial photo ingress is flying in now!

![image](https://github.com/LibrePhotos/librephotos/assets/61033436/600d4eb7-fe23-4f34-94c7-d2c3ff93c518)

**Comment by scepterus** [comment]
This is great news. So all we need to do is enable more numbers in the gui?

**Comment by Atinoda** [comment]
Yes, I expect that would be fine. I don't do much front-end work, but I don't see why it would cause any issues!

There may be a motivation from the developers to limit that worker number - I set my compute workhorse to 30 workers and it managed to eat over 100GB of RAM and max out a 5950x. I could imagine that less technical users might go *"big number is more better"* and totally cripple their machines. For now, I'm happy to continue setting the env variable. I only need the huge number of workers for initial set-up, then I'm going to move the entire installation to a different server (thanks to docker for easy migration) where 3 workers is more than enough.

**Comment by Atinoda** [comment]
~~On closer inspection, seems that it is still stuck at three simultaneous independent operations, but that it spawns the specified number of threads to do the work. Not sure if that's the intended behaviour or not - regardless, it is still able to max out the CPU so it's probably irrelevant unless the instance serves a ton of simultaneous users.~~
I think it does work OK, confusion arose because it keeps kicking off duplicate Scan Photos jobs and things... I'll stick with my first impressions that the env variable is honoured - mainly because at 15 workers I saw about half the CPU usage than when I set it to 30 workers. So the proof is in the system monitor!

**Comment by scepterus** [comment]
> I could imagine that less technical users might go "big number is more better" and totally cripple their machines

This could be easily solved by calculating the amount of RAM the machine has  (if that's visible to the docker) and dividing it by 800 MB. And then displaying that number -1 as the most workers that can be set up.

**Comment by Atinoda** [comment]
That's assuming the devs even have the motivation of protecting users from themselves - maybe it's just a legacy default that hasn't been looked at in a while. Regardless, the file to edit in [LibrePhotos/librephotos-frontend](https://github.com/LibrePhotos/librephotos-frontend) is probably [src/layouts/settings/SiteSettings.tsx](https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/layouts/settings/SiteSettings.tsx) You could have a go at making the change, and submit it as a PR!

**Comment by scepterus** [comment]
So basically something like this:
```
import os from 'os';

const availableMemory = os.freemem() / (1024 * 1024);
const MAX_HEAVYWEIGHT_PROCESSES = Math.floor((availableMemory * 0.9) / 800);

```

**Comment by Atinoda** [comment]
It is probably more appropriate to query the installed memory with `os.totalmem()` - however a simple PR raising the hardcoded limit itself may be all that is required. Considering the specs of modern hardware, I'd suggest that 8 is a reasonable default ceiling.

If the devs are worried about the issue we're discussing, you could suggest your solution to them, then extend your PR to include it. Another option would be to base `MAX_HEAVYWEIGHT_PROCESSES` on the number of available CPU threads.

**Comment by derneuere** [comment]
We could do a server side check, but a message in the frontend with "Total ram usage will be approximately x GB of RAM when scanning. Are you sure, you want to set this?" is fine too.

The ceiling is 3, because in the past the backend used a lot more RAM.

**Comment by derneuere** [comment]
I added this now. You can set it up to 10 workers, but you will get a warning if you set it higher than three. It is now available in dev or in the next latest release in january.
