### ISSUE TITLE
TypeError with last version, can't use backend

### ISSUE THREAD

**Issue by nagarrido** [LibrePhotos/librephotos#906]
# 🐛 Bug Report

## 📝 Description of issue:
With the last update, I can't login to the app as the backend docker container is getting a TypeError. I tried reverting back to the last version of backend, and it is working. I'll Upload the logs in the following minutes.

Log: https://uccl0-my.sharepoint.com/:t:/g/personal/nagarrido_uc_cl/EWlcuk4APZpMva6e9Ol9148B69THdJKWmC8Rqr1oqWrP7g

## 🔁 How can we reproduce it:
Just update the app to the latest version

**Comment by scepterus** [comment]
same here:
`192.168.1.1 - - [02/Jul/2023:02:41:30 +0000] "GET /login HTTP/1.1" 404 830 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
2023/07/02 02:41:34 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.1, server: , request: "POST /api/auth/token/obtain/ HTTP/1.1", upstream: "http://172.22.0.5:8001/api/auth/token/obtain/", host: "192.168.1.1:65001", referrer: "http://192.168.1.1:65001/login"`

**Comment by hardwareadictos** [comment]
Same here, my service is totally broken on Production environment. Deployed dev branch (something not advisable on production) and it's working now.

I had to deploy it to maintain the service working and online, would be nice to know if a comeback to latest branch would be regressive on the DB with a futurable fix.

I'm open to provide any log (but on mines there is the same info attatched on the first post).

For the incoming releases, please take alook at the issue i opened a week ago: https://github.com/LibrePhotos/librephotos/issues/894

Than could prevent this type of issues making a rollback on production environments safe

**Comment by hardwareadictos** [comment]
> Same here, my service is totally broken on Production environment. Deployed dev branch (something not advisable on production) and it's working now.
> 
> I had to deploy it to maintain the service working and online, would be nice to know if a comeback to latest branch would be regressive on the DB with a futurable fix.
> 
> I'm open to provide any log (but on mines there is the same info attatched on the first post).
> 
> For the incoming releases, please take alook at the issue i opened a week ago: #894
> 
> Than could prevent this type of issues making a rollback on production environments safe

Update: Just pulled today's weekly latest version and all working fine now :)

**Comment by derneuere** [comment]
I pushed a bug fix to latest. Repull the container and then it should work :)

**Comment by scepterus** [comment]
Can confirm this works.

**Comment by dotter-ak** [comment]
Bug still present in reallibrephotos/singleton image
