### ISSUE TITLE
Nextcloud integration not working

### ISSUE THREAD

**Issue by hardwareadictos** [LibrePhotos/librephotos#908]
# 🛑 Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.
- You have asked for help on our Discord server [LibrePhotos](https://discord.gg/xwRvtSDGWb) if your issue involves general "how to" questions

**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

Once i try to enable Nextcloud interaction on Librephotos, it connects but Browse and Scan buttons are greyed out.

![image](https://github.com/LibrePhotos/librephotos/assets/20403906/a9c4a15f-af06-4604-ac28-745afb04cb94)

## 🔁 How can we reproduce it:

Trying to connect a Librephotos instance to Nextcloud instance,

## Please provide additional information:
- 💻 Operating system: Debian 11
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: "latest"
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): NFS
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): 
Nextcloud version: 26.0.3

**Comment by derneuere** [comment]
Fixed in the next release.
