### ISSUE TITLE
Unable to get past the first install sign on screen

### ISSUE THREAD

**Issue by Silicon-Falcon** [LibrePhotos/librephotos#909]
I just installed the app and it is asking me for a username and password that has never been set up, and the initial is not documented and I am not going to do research to find it! 
There isn't even a link to create a new account. You just leave me hangin.

If you want to reproduce this, simple. Install the package for the first time.

# 🛑 Before you create an issue make sure that:
- Your issue is **strictly related to LibrePhotos** itself. Questions about setting up a reverse proxy belong in what ever reverse proxy you are using. 
- You have read the [documentation](https://docs.librephotos.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.
- You have asked for help on our Discord server [LibrePhotos](https://discord.gg/xwRvtSDGWb) if your issue involves general "how to" questions

**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## Please provide additional information:
- 💻 Operating system: 
- ⚙ Architecture (x86 or ARM): 
- 🔢 Librephotos version: 
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
Closed, because it's not clear how you installed it.

**Comment by enrique-lozano** [comment]
@derneuere Same problem here. The docs are really poor in this aspect. I install the app via docker following the instructions in the docs and everything goes fine, but I got a login screen that I don't know how to pass. Where should I set my username and my password to login? I suppose this params are not the same as dbUser and dbPass in the `.env` file

**Comment by derneuere** [comment]
It's a generic error and usually means that either your backend did not start up or that it crashed during boot. You will get a first time setup when you use LibrePhotos for the first time, where you create your admin account.

**Comment by mkono87** [comment]
Same problem here using docker on unraid. Docs dont explain it well.
