### ISSUE TITLE
Change admin password

### ISSUE THREAD

**Issue by ghost** [LibrePhotos/librephotos#91]
Is there any way to change the admin password from GUI or from the database?

**Comment by cardboarddude** [comment]
Would love this feature. Also would like a work around. How can this be done from the backend?

**Comment by iwanzarembo** [comment]
It depends if you are using the manual install then you could use the [librephotos-cli](https://docs.librephotos.com/1/manual_debian_install/#librephotos-cli) in docker you need to go to the backend container and use the command:
`./manager.py changepassword yourname`

**Comment by Dreadlocke12** [comment]
Where is the backend container stored under linux (Ubuntu). I did find a few files called manager.py and as well some who are called manage.py. I am not sure which one should I use then.

**Comment by iwanzarembo** [comment]
@Dreadlocke12 If you are not using Docker Container, then you should use the [librephotos-cli](https://docs.librephotos.com/1/manual_debian_install/#librephotos-cli). 
Would you mind trying:
`/usr/lib/librephotos/bin/librephotos-cli changepassword admin_username`

**Comment by Dreadlocke12** [comment]
I use a docker container. Can you tell me where the mentioned manager.py is stored.

**Comment by iwanzarembo** [comment]
@Dreadlocke12 The file path in the backend container is `/code/manage.py`

**Comment by derneuere** [comment]
You can now change your password on the profile page.

**Comment by galinowski** [comment]
Thanks for the info above, just for future reference, this is what worked for me on Docker:

1. docker container ls
2. docker exec -it ID /bin/bash (where ID is the id of reallibrephotos/librephotos:latest in the previous command)
3. python manage.py changepassword USERNAME

**Comment by sickelap** [comment]
To add to this, because the backend container is called `backend` you can simplify this to one command:

```
docker exec -ti backend python manage.py changepassword USERNAME
```
