### ISSUE TITLE
Wrong thumbnails for people in faces 

### ISSUE THREAD

**Issue by nagarrido** [LibrePhotos/librephotos#910]
# 🐛 Bug Report

## 📝 Description of issue:

It seems that in the faces section the thumbnails for persons are not always correct. If I select a cover picture for a person, instead of having the correct thumbnail, another person from that cover picture is set as the thumbnail. This is specially important for users who are using the uhuru photos android client, as these thumbnails are used in this app in the people section. 

## 🔁 How can we reproduce it:

Select an album cover with several people for a specific person. Go to faces, and from inferred try to assign a face to the person. The thumbnail shown for said person will probably be incorrect, and another person from the cover photo will be shown in their place.

**Comment by scepterus** [comment]
Same here, ever since the last update it gives the wrong photo to a face, sometimes I even saw it use the same face for 2 people.

**Comment by derneuere** [comment]
Pushed a fix for it :)
