### ISSUE TITLE
Videos don't play when navigating to "Sharing" - "Shared with you" (...)

### ISSUE THREAD

**Issue by RandomHacks-Git** [LibrePhotos/librephotos#914]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

If I navigate to "Sharing" -> "Shared with you" -> "Albums" (album covers don't load here) and click an album, while I can see all the thumbnails, if I click a video it does not play but if I log out and log back in or access the album link directly things work as expected, the same thing happens if I'm the owner of the album and navigate to "You shared". 

I tested this on the demo server with the same results:
![imagem](https://github.com/LibrePhotos/librephotos/assets/22402348/82af8c49-83b8-4f0b-bb2f-50dfe7e217e5)

## 🔁 How can we reproduce it:

Add video to an album, share album with another user, navigate to "Sharing" -> "You shared" -> "Albums" open album and click on video. You can also log in with the user you shared the album with and navigate to "Shared with you" with the same results.

**Comment by derneuere** [comment]
Fixed it, will be in the next release :)
