### ISSUE TITLE
Filter by Video/Photos on main screen

### ISSUE THREAD

**Issue by hardwareadictos** [LibrePhotos/librephotos#918]
**Describe the enhancement you'd like**

Add the hability to display only videos/photos (filtering).

**Describe why this will benefit the LibrePhotos**
A clear and concise explanation on why this will make LibrePhotos better.

Better organisation.
**Additional context**
Add any other context or screenshots about the enhancement request here.

![Screenshot_20230712-121954](https://github.com/LibrePhotos/librephotos/assets/20403906/7b193656-be62-4342-9de0-72c63ef06838)

**Comment by AnkurPrabhu** [comment]
#1051
