### ISSUE TITLE
Remove face when looking at a photo if wrongfully assigned

### ISSUE THREAD

**Issue by scepterus** [LibrePhotos/librephotos#919]
**Describe the enhancement you'd like**
When looking at a photo and the detected face have the option to remove a wrong assignment, we can do this by choosing unknown other, but a quick button would be nice.

**Describe why this will benefit the LibrePhotos**
In cases of background strangers being detected as a known person wrongfully, it would help a lot.

**Comment by derneuere** [comment]
Added the button :)
