### ISSUE TITLE
[FRONTEND] Bad album alignment on mobile view

### ISSUE THREAD

**Issue by hardwareadictos** [LibrePhotos/librephotos#923]
On the album page, album lists seems to not respect the margins/alignments.

![Screenshot_20230714-120557](https://github.com/LibrePhotos/librephotos/assets/20403906/fd29f29d-9b88-4fa1-9cb6-8cf82e1f33ea)

Using latest docker image on frontend and whole stack.

**Comment by loulou91** [comment]
I would say I get similar behaviour of WEB UI on my smartphone but only some. I looks to be link to text size when it exeeds one line.... (I would say text size is too large... but it's linked to my eyesight ;-) )
Moreover, when I open "things" with portait mode I get 2 columns, if I go to landscape mode, I get 3 colomns and if I switch back to portrait mode I still get 3 columns.

**Comment by derneuere** [comment]
Fixed, will be available in next release :)
