### ISSUE TITLE
ERROR: for backend Container is unhealthy.

### ISSUE THREAD

**Issue by fungos** [LibrePhotos/librephotos#94]
I've been trying ownphotos before the fork and now librephotos, but I just can't get the scan photos to find all my photos.
I'm using https://github.com/photoprism/photoprism for now and with the same d ata configuration, it is able to scan all 76871 photos, but librephotos says there is only 133. Why is that?

![image](https://user-images.githubusercontent.com/151544/103484194-ccca5500-4dba-11eb-9b00-6cd008d02db5.png)

Also, when the scan starts, if says there is 465 items being processed and the progress seems to get stuck and broken:

![image](https://user-images.githubusercontent.com/151544/103484213-ee2b4100-4dba-11eb-993f-a8a9580ea645.png)

Is there anything else I can do to find the issue?

Note that I tried this a few times, and I even let the scan to "run" for 48h without any kind of progress last week.

**Comment by derneuere** [comment]
LongRunningJobs do not check if the rq worker is still working: #42 
Check ownphotos.log where the job crashed. Pictures are sorted by filepath + filename and it logs after processing a picture which image was processed. So it should be the next one in line that would cause the issue. Try with a new account maybe if it is reproducible.
Also it would be great if you could tell me what OS you are using and which CPU.

**Comment by fungos** [comment]
```
2021-01-03 04:02:26,074 : directory_watcher.py : handle_new_image : 90 : ERROR : job c0546358-0c20-4cfd-bce3-99d14c3eaf7b: could not load image /data/Dedup/Camera S7-2/.stversions/.thumbnails/1504473491666~20200304-192856.jpg. reason: duplicate key value violates unique constraint "api_photo_pkey"
DETAIL:  Key (image_hash)=(cf76931301dd2d9cd7863a064c453a2d1) already exists.
Traceback (most recent call last):
  File "/miniconda/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "api_photo_pkey"
DETAIL:  Key (image_hash)=(cf76931301dd2d9cd7863a064c453a2d1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 60, in handle_new_image
    photo = Photo.objects.create(
  File "/miniconda/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/miniconda/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/miniconda/lib/python3.8/site-packages/django/db/models/base.py", line 748, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/miniconda/lib/python3.8/site-packages/django/db/models/base.py", line 785, in save_base
    updated = self._save_table(
  File "/miniconda/lib/python3.8/site-packages/django/db/models/base.py", line 890, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/miniconda/lib/python3.8/site-packages/django/db/models/base.py", line 927, in _do_insert
    return manager._insert(
  File "/miniconda/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/miniconda/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/miniconda/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1394, in execute_sql
    cursor.execute(sql, params)
  File "/miniconda/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/miniconda/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/miniconda/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/miniconda/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/miniconda/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/miniconda/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "api_photo_pkey"
DETAIL:  Key (image_hash)=(cf76931301dd2d9cd7863a064c453a2d1) already exists.
```
I have a bunch of these and after these, it could finally continue. The progress bar is still broken without advancing, but in the dashboard I can see 1165 photos processed until now. I'll give more time to see it gets stuck again, but these stacks made me wonder if there shouldn't be a kind of blacklist somewhere to avoid indexing these artifacts like the hidden folders for thumbnails on the source data. I can see here the `.stversions` and `.thumbnails` folders generated by other softwares (syncthing and image viewers) which would be nice ignore.

**Comment by derneuere** [comment]
I ignore now hidden folders and elements when scanning. Could you maybe try it again with a fresh database? Please do a docker-compose down, docker-compose pull and a docker-compose up -d

**Comment by fungos** [comment]
Is there a way to do this in another container without scraping my actual DB? I got up to 50k/75k images right now, it can take ~2 days to finish this.

**Comment by fungos** [comment]
I know this may have nothing to do with the update, but I can't get it to start anymore, any ideas on how to fix this?

```
Creating network "librephotos_default" with the default driver
Creating librephotos-db       ... done
Creating librephotos-proxy    ... done
Creating librephotos-redis    ... done
Creating librephotos-frontend ... done

ERROR: for backend  Container "f3bdd7d6c183" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by andrewrohde** [comment]
I'm having the same exact issue. db and proxy both stop and restart.

> I know this may have nothing to do with the update, but I can't get it to start anymore, any ideas on how to fix this?
> 
> ```
> Creating network "librephotos_default" with the default driver
> Creating librephotos-db       ... done
> Creating librephotos-proxy    ... done
> Creating librephotos-redis    ... done
> Creating librephotos-frontend ... done
> 
> ERROR: for backend  Container "f3bdd7d6c183" is unhealthy.
> ERROR: Encountered errors while bringing up the project.
> ```

I'm having the same exact issue. db and proxy both stop and restart.

**Comment by oliveox** [comment]
Same issue with the backend container.

```
user@terminal$ docker stop $(docker ps -q) && docker rm $(docker ps -aq)
user@terminal$ docker-compose up -d
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating librephotos-proxy    ... done
Creating librephotos-redis    ... done
Creating librephotos-db       ... done
Creating librephotos-frontend ... done

ERROR: for backend  Container "d5a8a8207858" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by derneuere** [comment]
I cannot recreate the issue. Does it work if you remove the health check in docker-compose.yml?
https://github.com/LibrePhotos/librephotos/blob/92393367028ce10d92f68617547adab517c1fc5d/docker-compose.yml#L31-L35
https://github.com/LibrePhotos/librephotos/blob/92393367028ce10d92f68617547adab517c1fc5d/docker-compose.yml#L74-L77

**Comment by derneuere** [comment]
Also: Do you have free hard drive space? That could be a reason why starting the db is failing.

**Comment by oliveox** [comment]
> Also: Do you have free hard drive space? That could be a reason why starting the db is failing.

Stats with the docker images downloaded.

Available: 1.9T  
Use 1.5T
Free: 379G
Occupied: 80%

**Comment by oliveox** [comment]
> I cannot recreate the issue. Does it work if you remove the health check in docker-compose.yml?
> 
> https://github.com/LibrePhotos/librephotos/blob/92393367028ce10d92f68617547adab517c1fc5d/docker-compose.yml#L31-L35
> 
> https://github.com/LibrePhotos/librephotos/blob/92393367028ce10d92f68617547adab517c1fc5d/docker-compose.yml#L74-L77

Removed the healthcheck. The postgres container restart continuously after ~30 secs.

```
user@terminal:/$ docker ps 
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                          PORTS                  NAMES
8e631cab91a4        reallibrephotos/librephotos-proxy:dev      "/docker-entrypoint.…"   2 minutes ago       Up 2 minutes                    0.0.0.0:3000->80/tcp   librephotos-proxy
3ca2651d017b        redis:alpine                               "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes                    6379/tcp               librephotos-redis
87ab5e5a0eae        reallibrephotos/librephotos-frontend:dev   "/bin/sh -c ./run.sh"    2 minutes ago       Up 2 minutes                    3000/tcp               librephotos-frontend
b64f42558325        postgres                                   "docker-entrypoint.s…"   2 minutes ago       Restarting (1) 58 seconds ago                          librephotos-db
8c786f557ae3        reallibrephotos/librephotos:dev            "/bin/sh -c ./entryp…"   2 minutes ago       Up 2 minutes                    80/tcp                 librephotos-backend
```

Which container logs you suggest looking at?

**Comment by derneuere** [comment]
Look into the postgres container.

**Comment by oliveox** [comment]
> Look into the postgres container.

Not possible considering the container is continuously restarting

`Error response from daemon: Container b64f42558325f17ab6c7dbb7fa07e9cf2d7d0081fbd7c5326f94f052f6b3edc9 is restarting, wait until the container is running
`

**Comment by derneuere** [comment]
Delete this line: https://github.com/LibrePhotos/librephotos/blob/92393367028ce10d92f68617547adab517c1fc5d/docker-compose.yml#L23

Maybe then we can look into the logs.

**Comment by oliveox** [comment]
> Delete this line:
> 
> https://github.com/LibrePhotos/librephotos/blob/92393367028ce10d92f68617547adab517c1fc5d/docker-compose.yml#L23
> 
> Maybe then we can look into the logs.

My bad, first I've tried to 'docker exec' in it. Here is the container logs.

```
user@terminal:/$ docker logs b64

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
2021-01-29 12:41:11.106 UTC [82] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
2021-01-29 12:41:11.106 UTC [82] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
```

**Comment by derneuere** [comment]
Did you use a different user for your db directory? Where did you try to save your db?
I think this here is the issue:
2021-01-29 12:41:11.106 UTC [82] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
2021-01-29 12:41:11.106 UTC [82] HINT:  The server must be started by the user that owns the data directory.

**Comment by andrewrohde** [comment]
> I'm having the same exact issue. db and proxy both stop and restart.
> 
> > I know this may have nothing to do with the update, but I can't get it to start anymore, any ideas on how to fix this?
> > ```
> > Creating network "librephotos_default" with the default driver
> > Creating librephotos-db       ... done
> > Creating librephotos-proxy    ... done
> > Creating librephotos-redis    ... done
> > Creating librephotos-frontend ... done
> > 
> > ERROR: for backend  Container "f3bdd7d6c183" is unhealthy.
> > ERROR: Encountered errors while bringing up the project.
> > ```
> 
> I'm having the same exact issue. db and proxy both stop and restart.

My issue had to do with the inability of MySQL to set file permissions. MySQL requires the ability to set file permissions/ownership. I was mounting an SMB directory as the MySQL data directory which does not support linux file ownership/permissions. This was fixed once I used nfs to mount the data directory.

**Comment by riki137** [comment]
@fungos This was happening to me too, however i set `workerTimeOut=0` in `.env` file, and now it keeps indexing without getting stuck.
From logs i see that the image processing was getting aborted (by System.exit()) and not restarted. Not sure why.

Here's the crash from the log file when i had timeout set to 120:
```
2021-02-15 13:32:21,756 : photo.py : _im2vec : 325 : ERROR : something went wrong with im2vec
Traceback (most recent call last):
  File "/code/api/models/photo.py", line 319, in _im2vec
    im2vec = Im2Vec(cuda=False)
  File "/code/api/im2vec.py", line 20, in __init__
    self.model, self.extraction_layer = self._get_model_and_layer(model, layer)
  File "/code/api/im2vec.py", line 66, in _get_model_and_layer
    model = models.resnet152(pretrained=True)
  File "/miniconda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 288, in resnet152
    return _resnet('resnet152', Bottleneck, [3, 8, 36, 3], pretrained, progress,
  File "/miniconda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 228, in _resnet
    model.load_state_dict(state_dict)
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1037, in load_state_dict
    load(self)
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1035, in load
    load(child, prefix + name + '.')
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1035, in load
    load(child, prefix + name + '.')
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1035, in load
    load(child, prefix + name + '.')
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1031, in load
    module._load_from_state_dict(
  File "/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 994, in _load_from_state_dict
    if key.startswith(prefix):
  File "/miniconda/lib/python3.8/site-packages/gunicorn/workers/base.py", line 201, in handle_abort
    sys.exit(1)
SystemExit: 1
```

Not sure if this is a separate problem?

**Comment by derneuere** [comment]
@riki137 Which CPU are you using. Somebody in #167 has the same issue and I can't seem to recreate it.

**Comment by ma-karai** [comment]
I posted my CPU details in the other issue, I quickly setup photoprism and it indexed and "tensorflowed" all of my images in seconds (the 19 that is haha) 
Some great results there 
![image](https://user-images.githubusercontent.com/17119942/108032364-a727a100-7032-11eb-9154-7bedafb5417a.png)
