### ISSUE TITLE
LibrePhotos Android/iOS mobile application 

### ISSUE THREAD

**Issue by code-vibes** [LibrePhotos/librephotos#967]
A mobile application which can help view the not synced photos/folders or view the offline available photos without internet connection as well.

A mobile app will attract more users as it would be more user friendly compared to a web access. And to be able to use it even without internet for the offline available photos will be a the basic requirement expected by the genral masses/users.

**Comment by derneuere** [comment]
We already have that: 
https://play.google.com/store/apps/details?id=com.savvasdalkitsis.uhuruphotos&hl=en-US&ah=pXaNcptFquuJHGj4q3LDvXfw8RY
https://github.com/LibrePhotos/librephotos-mobile
