### ISSUE TITLE
Uploading media on dev fails

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos#975]
# 🐛 Bug Report

* [x] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

On latest dev, when uploading a photo, the upload calls themselves work fine but the `complete` call at the end fails with a 403:

![image](https://github.com/LibrePhotos/librephotos/assets/873077/60544ba4-519f-4be1-88ee-ed8493e9a826)

## Please provide additional information:
- 💻 Operating system: Docker on ubuntu host
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: dev
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: dev
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local file system
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by savvasdalkitsis** [comment]
logs:

backend            | Unauthorized: /api/user/
backend            | Unauthorized: /api/albums/date/list/
backend            | [2023-07-30 09:36:14 +0000] [74] [CRITICAL] WORKER TIMEOUT (pid:133)
backend            | [2023-07-30 09:36:15 +0000] [133] [INFO] Worker exiting (pid: 133)
backend            | Forbidden: /api/upload/complete/
backend            | [2023-07-30 09:36:33 +0000] [188] [INFO] Booting worker with pid: 188
backend            | use SECRET_KEY from env
backend            | Forbidden: /api/upload/complete/
backend            | Unauthorized: /api/albums/date/list/
backend            | [2023-07-30 09:37:47 +0000] [74] [CRITICAL] WORKER TIMEOUT (pid:188)
backend            | [2023-07-30 09:37:48 +0000] [188] [INFO] Worker exiting (pid: 188)
backend            | [2023-07-30 09:37:52 +0000] [193] [INFO] Booting worker with pid: 193
backend            | use SECRET_KEY from env
backend            | Unauthorized: /api/albums/date/list/
backend            | [2023-07-30 09:38:42 +0000] [74] [CRITICAL] WORKER TIMEOUT (pid:193)
backend            | /usr/local/lib/python3.11/dist-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.person.Person'> QuerySet.
backend            |   paginator = self.django_paginator_class(queryset, page_size)
backend            | [2023-07-30 09:38:45 +0000] [193] [INFO] Worker exiting (pid: 193)
backend            | [2023-07-30 09:38:47 +0000] [198] [INFO] Booting worker with pid: 198
backend            | use SECRET_KEY from env
backend            | Unauthorized: /api/albums/date/676/
backend            | Forbidden: /api/upload/complete/

**Comment by derneuere** [comment]
I pushed an update yesterday, which should fix that. The issue was that rtk did not send the form data in a valid way.

Edit: Oh, the build broke, will push a fix for that too.

**Comment by derneuere** [comment]
Works again :)
