### ISSUE TITLE
Documentation Website Update

### ISSUE THREAD

**Issue by AcidBurn18** [LibrePhotos/librephotos#976]
On you Website Hosting the Documentation [https://docs.librephotos.com/docs/installation/standard-install/](url).

link [https://docs.librephotos.com/docs/user-guide/first-steps](url) is broken.

Sccrenshot Attached Below

![Screenshot (57)](https://github.com/LibrePhotos/librephotos/assets/22994877/ba89cf23-d8e9-46e5-9dc8-db92c8aa98a6)

**Comment by DigitalWarrior** [comment]
Issue resolved.
