### ISSUE TITLE
Backend is failing on album request from UhuruPhotos

### ISSUE THREAD

**Issue by mramirkhan** [LibrePhotos/librephotos#981]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

Uhuru Photos is unable to refresh photos for a certain date range (21st July -> 10th inclusive)

## 🔁 How can we reproduce it:

Not sure?  All I do is do a full refresh in Uhuru and it doesn't "see" pictures in the range above. The react native app appears unaffected strangely. Web site version unaffected too and functions as expected.

## Please provide additional information:
- 💻 Operating system: 
Android client Uhuru causing exceptions on backend

- ⚙ Architecture (x86 or ARM): 
Arm

- 🔢 Librephotos version: 
latest

- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
dev

- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
local HDD

- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): 
N/A

![backend](https://github.com/LibrePhotos/librephotos/assets/19846862/a7eb306b-9b7c-4904-a631-0b85542fb510)
![proxy](https://github.com/LibrePhotos/librephotos/assets/19846862/7d1ab3b1-5760-4352-b58f-9521213a8d41)

**Comment by mramirkhan** [comment]
This is version i am running, commit 48284324122aa512ae287371f51f0fe25aef3060

**Comment by derneuere** [comment]
Could you check out, what the AlbumDate 1791 is actually containing? To do that, navigate to <youradress>/api/django-admin and look for the correct entity.

If you cannot access it, you have to add your adress to csrfTrustedOrigins
