### ISSUE TITLE
[error] 23#23: *6 open() "/protected_media/thumbnails_big/<long strin>.webp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by Keirriek** [LibrePhotos/librephotos#983]
**When Submitting please remove every thing above this line**

# 🐛 Bug Report

* [x ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x ] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Hello,
Installation Docker.
The pictures appear just as colored squares, with different colors.
See picture in screenshot file.
I got the hint that it looks like a permissions error.
The  Proxy reports errors, I didn't find errors in the other logs (all included):
When I click on a picture, these error occur:
10.8.0.6 - - [06/Aug/2023:08:51:34 +0200] "GET /media/thumbnails_big/852ea07c82fa0481bf8f260967f8d62d2 HTTP/1.1" 403 153 "http://192.168.1.31:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

2023/08/06 08:51:34 [error] 23#23: *438 open() "/protected_media/thumbnails_big/223698ee5c041c1faf30ada8a6803e592.webp" failed (13: Permission denied), client: 10.8.0.6, server: , request: "GET /media/thumbnails_big/223698ee5c041c1faf30ada8a6803e592 HTTP/1.1", upstream: "http://172.29.64.4:8001/media/thumbnails_big/223698ee5c041c1faf30ada8a6803e592", host: "192.168.1.31:3000", referrer: "http://192.168.1.31:3000/"

10.8.0.6 - - [06/Aug/2023:08:51:34 +0200] "GET /media/thumbnails_big/223698ee5c041c1faf30ada8a6803e592 HTTP/1.1" 403 153 "http://192.168.1.31:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

10.8.0.6 - - [06/Aug/2023:08:51:35 +0200] "GET /api/rqavailable/ HTTP/1.1" 200 61 "http://192.168.1.31:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

10.8.0.6 - - [06/Aug/2023:08:51:37 +0200] "GET /api/rqavailable/ HTTP/1.1" 200 61 "http://192.168.1.31:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

10.8.0.6 - - [06/Aug/2023:08:51:40 +0200] "GET /api/rqavailable/ HTTP/1.1" 200 61 "http://192.168.1.31:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

10.8.0.6 - - [06/Aug/2023:08:51:43 +0200] "GET /api/rqavailable/ HTTP/1.1" 200 61 "http://192.168.1.31:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

I tried it also with:
- changing the rights of the dir an files to admin:admin  and also with  john:everyone (1000:100) in combination with PIUD/PGID as below
 PUID and PGID for all services.
    environment:
      - PUID=000  also with 1000
      - PGID=00    also with 100
      - TZ=Europe/Amsterdam
yaml and env are attached.

Please could anyone give a solution or some hints to try.
I an quite a newby.

Regards, John

## Please provide additional information:
- 💻 Operating system: NAS QNAP TVS-671
- ⚙ Architecture (x86 or ARM): X86
- 🔢 Librephotos version: all
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag:
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): local shares
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): --

[librephotos-yaml.txt](https://github.com/LibrePhotos/librephotos/files/12268847/librephotos-yaml.txt)
[librephotos-env.txt](https://github.com/LibrePhotos/librephotos/files/12268848/librephotos-env.txt)
![Screenshot 2023-08-06 at 09-03-52 LibrePhotos](https://github.com/LibrePhotos/librephotos/assets/120742178/c7497ace-ed6a-4e7c-a5be-1303b6902b51)
[_proxy_logs.txt](https://github.com/LibrePhotos/librephotos/files/12268851/_proxy_logs.txt)
[_frontend_logs.txt](https://github.com/LibrePhotos/librephotos/files/12268853/_frontend_logs.txt)
[_db_logs.txt](https://github.com/LibrePhotos/librephotos/files/12268854/_db_logs.txt)
[_backend_logs.txt](https://github.com/LibrePhotos/librephotos/files/12268855/_backend_logs.txt)

**Comment by derneuere** [comment]
This looks like a file permission issue of the thumbnails. The thumbnails are located in /data/protected_media. PUID and PGID are not really a thing in LibrePhotos. Just make the thumbnails accessible to all users on your system.
