### ISSUE TITLE
Showing public photos

### ISSUE THREAD

**Issue by Kolatzek** [LibrePhotos/librephotos#990]
# 🐛 Bug Report

* [x ] 📁 I've Included a  file containing my librephotos-backend `log` file:  [log-backend-librephotos.txt](https://github.com/LibrePhotos/librephotos/files/12307293/log-backend-librephotos.txt)
* [x ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

As an anonymous user public photos will not be shown but only an "waiting" circle. The XHR comes with an HTTP 500 error which is coming from backend.

"TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?"

/user/username should show public photos to everyone or not?

## 🔁 How can we reproduce it:

It's hard to say. I think it will happen in every docker container.

## Please provide additional information:
- 💻 Operating system: Linux, Docker
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: latest docker image
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
    * 🐋 Docker  image tag: latest
- 📁 How is you picture library mounted:  docker volume (exactly a local path)
- ☁ If you are virtualizing librephotos, Virtualization platform: Proxmox 7.4

**Comment by derneuere** [comment]
Pushed a fix :)

**Comment by Kolatzek** [comment]
Issue fixed (but I had to switch from latest image to dev image in docker to check it).
