### ISSUE TITLE
No "Sign up"-Button with "allow user registration"

### ISSUE THREAD

**Issue by JanHanckel** [LibrePhotos/librephotos#991]
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ x ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I installed librephotos via docker on my qnap nas. Imported a bunch of files. In Admin panel I activated "allow user registration", but on Login page there is no sign up button, just login.

## 🔁 How can we reproduce it:
Activate "allow user registration" in Admin Panel and look for an "sign up" button on login page.

## Please provide additional information:
- 💻 Operating system: 
- ⚙ Architecture (x86 or ARM): 
- 🔢 Librephotos version:
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by derneuere** [comment]
Pushed a fix :)
