### ISSUE TITLE
Social graph navigation broken. "Cannot read properties of undefined" in Graph.js

### ISSUE THREAD

**Issue by ghost** [LibrePhotos/librephotos#992]
Graph is placed weirdly:
![image](https://github.com/LibrePhotos/librephotos/assets/136166458/ae6d1fd5-6938-47d6-a561-7d803edce437)
Trying to zoom/pan the graph results in the following errors
![image](https://github.com/LibrePhotos/librephotos/assets/136166458/227f3950-c31a-4e9c-adea-d3d1f5ca7930)

## Please provide additional information:
- 💻 Operating system: 
Ubuntu server, latest LTS
- ⚙ Architecture (x86 or ARM): 
x86
- 🔢 Librephotos version: 
Very recent (cloned the repo like yesterday)
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
Git clone -> docker-compose
- 📁 How is your picture library mounted (Local file system (Type), NFS, SMB, etc.): 
At /mnt/data0/blah/blah/blah/blah/Photos with only read permissions

**Comment by derneuere** [comment]
I probably have to fork or migrate the dependency react-d3-graph. https://github.com/d3/d3-selection/issues/191 removed the event type and the dependency react-d3-graph is not maintained. Will take a bit longer then expected.

**Comment by derneuere** [comment]
Pushed a fix on dev :)
