### ISSUE TITLE
Rescan exceptions

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#994]
Good day. 
Tell me if my photos are arranged in unique folders and the previous folders remain unchanged by year. The content changes (photos are added) only to folders in 2023. Is it possible to exclude already processed folders from the re-scan, because a lot of time is spent on a second full scan, especially when CNN mode is enabled?

**Comment by derneuere** [comment]
If you only want to scan the 2023 folder for a user, set it as a scanDirectory. Previously scanned images, should still be visible, however it could lead to incorrect numbers of missing photos.

If you do a normal scan, already scanned images will be skipped, which is probably the way you want it to act.
